### ISSUE TITLE
重启某一实例后重复重启该实例

### ISSUE THREAD

**Issue by EndMoyu** [MCSManager/MCSManager#1000]
**MCSManager Version**
9.9.0
**System Info/Version**
#1 SMP PREEMPT_DYNAMIC Debian 6.1.37-1 (2023-07-03) 6.1.0-10-amd64
**Node Version**
v14.19.1
**Step**
在重启某一实例之后该实例被面板重复启动好几次。
本人担任过多个服务器管理，架构几乎与这一致，只有放在家里的服务器出现了这个问题。
没有头绪，有时候使用过程中有时候daemon会报timeout，个人感觉是硬盘或者系统什么被我折腾出问题了orz。。。
(后去掉Docker后没问题了，但是Docker得挂啊orz)

![QQ截图20230831210242](https://github.com/MCSManager/MCSManager/assets/85435560/679876a6-e9b1-4fdd-8ded-9106ee5b6ba5)

**Comment by Bluemangoo** [comment]
你的图没有传上来。

**Comment by YukiEnd233** [comment]
> 你的图没有传上来。

我这边看没问题，退出账号之后也一样，可能大佬得检查一下环境吧（笑
图里主要是表达自动重启时会反复开启这个实例，我自己手动点重启实例也一样会反复开启...
