### ISSUE TITLE
由主服务器代理其他物理主机（子服务器）的API是否更合理

### ISSUE THREAD

**Issue by HisAtri** [MCSManager/MCSManager#1018]
一是由于存在协议约束，面板使用https后，若想要从web连接到子服务器，其必须启用wss加密，有不必要的麻烦；
二是如果通过web直接连接Minecraft服务器，子服务器的API端口必须开放，不便在子服务器上限制访问，有可能导致安全问题；

**Comment by Bluemangoo** [comment]
nginx请。

**Comment by unitwk** [comment]
感谢你提出建议。

首先所有与「子服务器」通信的连接，均由「主服务器」授权后才能生效，否则将会自动断开，不存在你所说的安全问题。

其次如果所有 API 均通过主服务器代理，你想象一下如果有 10 名用户上传 10GB 的文件，你需要一个服务器接受这些文件并且转发给其他子服务器，你可以想象到，你的主服务器将承担多大的流量与IO读写。

所以，大量数据流程直接连接子服务器，恰恰是一个正确的解决方案，因为你的子服务器一定存在公开的服务（Minecraft等）。

**Comment by huangsijun17** [comment]
而且，前端服务器是可以存放在VPN等隔离网内的。若数据走前端代理，流量还会走一次跳板机。
