### ISSUE TITLE
windows端 关闭浏览器自启动

### ISSUE THREAD

**Issue by HeleJia84deSp** [MCSManager/MCSManager#1033]
增加配置条目,使用户可以关闭浏览器自启动

**Comment by HeleJia84deSp** [comment]
虽说可以去格式化完的源码里自己删
但是还是希望能出一个配置条目

**Comment by huangsijun17** [comment]
浏览器自启动？什么意思？

**Comment by Bluemangoo** [comment]
源码里面找得到，编译后难找了。

**Comment by Bluemangoo** [comment]
https://github.com/MCSManager/MCSManager/blob/d16145396a0d49b421bccea22e08c74bd3df6847/src/app.ts#L57
怼着字符串去编译后找吧。

**Comment by HeleJia84deSp** [comment]
> https://github.com/MCSManager/MCSManager/blob/d16145396a0d49b421bccea22e08c74bd3df6847/src/app.ts#L57
> 
> 
> 怼着字符串去编译后找吧。

-在发的时候就解决了 但还是希望能出一个~

**Comment by Bluemangoo** [comment]
加个设置项好了。
