### ISSUE TITLE
希望可以在daemon配置文件中增加"允许WebShell”/“允许管理服务器文件”之类的选项

### ISSUE THREAD

**Issue by ItsukaRilu** [MCSManager/MCSManager#1040]
如题，因为不需要在mcsm中维护服务器，再加上mcsm的管理员登录并没有2FA之类的加强安全措施，个人认为存在一定的安全风险（即使已经使用强密码）。
查阅了文档，发现并没有提及相关的东西，所以提了这个issue。
当然如果已经有关闭的方式的话烦请告诉我，感谢各位maintainer的辛勤付出。

**Comment by unitwk** [comment]
只要能在 Daemon 上新建实例，就一定存在绕过各种限制的方式，比如实例的启动命令是 sh xxxx.sh，又或者是 cmd.exe /c xxx 等。

所以你所说的禁止 WebShell 的情况根本无法完美实现。

**Comment by huangsijun17** [comment]
MCSM本身就是一个web shell。甚至有某些MC的插件内置shell功能呢。

**Comment by ItsukaRilu** [comment]
好吧，感谢各位解答
