### ISSUE TITLE
希望增加*.ts文件的语法高亮

### ISSUE THREAD

**Issue by DanielToyama** [MCSManager/MCSManager#1041]
如题

**Comment by huangsijun17** [comment]
`.ts`是`TypeScript`？还是`Transport Stream`？为什么会有在线编辑的需求？场景在哪里？

**Comment by DanielToyama** [comment]
> `.ts`是`TypeScript`？还是`Transport Stream`？为什么会有在线编辑的需求？场景在哪里？

typescrpt,偶尔稍微编辑代码的时候会用
