### ISSUE TITLE
使用Docker的实例在使用更新功能时无法使用镜像中包含的curl

### ISSUE THREAD

**Issue by NyankoSong** [MCSManager/MCSManager#1046]
当我在【启动实例】这一选项进入实例时，我在镜像中安装的curl是可以正常被调用的，但是在【更新】功能中，就会提示找不到命令。按理说我应该放一些log，但是确实只有一句“curl: command not found”，也没什么可放的。。。

系统环境：Ubuntu 22.04
镜像：Ubuntu 22.04，预安装curl
调用方法：sh脚本调用

**Comment by huangsijun17** [comment]
镜像内环境变量PATH的问题？

**Comment by NyankoSong** [comment]
> 镜像内环境变量PATH的问题？ 你镜像的Dockerfiles贴一下，我看看。

感谢回复！

我直接使用的默认的Dockerfile，只添加了安装curl和其他依赖的部分（加粗）：

FROM ubuntu:18.04
ENV TZ=Asia/Shanghai
RUN sed -i -E 's/http:\/\/(archive|security).ubuntu.com/http:\/\/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list
RUN apt update && apt -y install libcurl4 **curl libicu-dev** && DEBIAN_FRONTEND="noninteractive" apt -y install tzdata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN mkdir -p /workspace
WORKDIR /workspace

**Comment by Bluemangoo** [comment]
那个更新的path查找确实很迷，之前有人也这里出问题过（好像还没解决吧），去翻一下源码可能真的是bug。

**Comment by NyankoSong** [comment]
> 那个更新的path查找确实很迷，之前有人也这里出问题过（好像还没解决吧），去翻一下源码可能真的是bug。

好的，那我干脆曲线救国改成启动时更新罢，谢谢~

**Comment by unitwk** [comment]
重新看了下更新的逻辑，更新实例命令并没有在 Docker 容器内执行，而是在宿主机上执行了更新命令。

所以你需要在宿主机上也安装 CURL 工具，并且配置好更新环境，然后更新的时候指定到你的实例目录即可。

**Comment by NyankoSong** [comment]
> 重新看了下更新的逻辑，更新实例命令并没有在 Docker 容器内执行，而是在宿主机上执行了更新命令。
> 
> 所以你需要在宿主机上也安装 CURL 工具，并且配置好更新环境，然后更新的时候指定到你的实例目录即可。

我的宿主机是有curl的（我直接执行是可以使用的），不过按你说的，如果真的是用root用户直接在宿主机执行更新，感觉有些过于危险了。。

**Comment by unitwk** [comment]
更新命令只能由管理员设定，除非你自己写错，否则没有什么危险的。

之所以做宿主机上执行是因为可以复用更新程序，比如 steamcmd.exe 这种程序通常只需要在宿主机上装一个，然后使用这个 exe 程序就可以更新所有实例。

**Comment by NyankoSong** [comment]
> 更新命令只能由管理员设定，除非你自己写错，否则没有什么危险的。
> 
> 之所以做宿主机上执行是因为可以复用更新程序，比如 steamcmd.exe 这种程序通常只需要在宿主机上装一个，然后使用这个 exe 程序就可以更新所有实例。

感谢解答！

有关root权限的危险性，只是个人会倾向于一切非必要的操作都尽量在隔离环境内执行，尤其是更新这种可能带有破坏性的操作。

这个issue最初是因为我的服务器并没有steamcmd这样方便的更新方法，只能我自己写脚本进行覆盖更新。我不敢说自己水平如何（笑），所以为了避免无法预料的事情发生，可能会更希望能在容器内执行更新。

**Comment by huangsijun17** [comment]
> > 更新命令只能由管理员设定，除非你自己写错，否则没有什么危险的。
> > 之所以做宿主机上执行是因为可以复用更新程序，比如 steamcmd.exe 这种程序通常只需要在宿主机上装一个，然后使用这个 exe 程序就可以更新所有实例。
> 
> 感谢解答！
> 
> 有关root权限的危险性，只是个人会倾向于一切非必要的操作都尽量在隔离环境内执行，尤其是更新这种可能带有破坏性的操作。
> 
> 这个issue最初是因为我的服务器并没有steamcmd这样方便的更新方法，只能我自己写脚本进行覆盖更新。我不敢说自己水平如何（笑），所以为了避免无法预料的事情发生，可能会更希望能在容器内执行更新。

所以，我改了/opt/mcsmanager文件夹的归属，也改了.service服务文件，去用没sudo权限的用户降权运行。
