### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by NullyIsHere** [MCSManager/MCSManager#1051]
Hi! I've found that MCSManager has an api (i think because of the api key) and i don't find the documentation.
If it exists, where is it?
If don't exist how can i learn how to use it?
![image](https://github.com/MCSManager/MCSManager/assets/140397732/04939062-e3ac-4722-9d8a-1264ef4e4577)
_Photo of the api panel_

Thanks

**Comment by Bluemangoo** [comment]
maybe you have to check chinese version of docs with translator.

**Comment by NullyIsHere** [comment]
Where are them?

**Comment by Bluemangoo** [comment]
https://docs.mcsmanager.com/#/zh-cn/README

Hope you read it comfortably with translator.

**Comment by NullyIsHere** [comment]
Thanks, that's it!

**Comment by Bluemangoo** [comment]
Appreciated to hear that😊
