### ISSUE TITLE
建议支持Windows自带添加“服务”的工具，快速实现开机自启动。（合并第三方仓库的工具）

### ISSUE THREAD

**Issue by bddjr** [MCSManager/MCSManager#1056]
MCSManager 在 Linux 上使用 `setup_cn.sh` 安装时自带设置“服务”，但 Windows 版并没有自带相关工具，导致在 Windows 设置**开机自启动**会有些困难。  

***

现在，这个工具已经给出完美的解决方案，可以参考下：  
<https://github.com/bddjr/mcsmanager-services-for-windows>  

主要原理是利用 MCSManager 的 Windows 版已经自带 `node_app.exe` 的特性（版本`18.12.1`），同时借助 [node-windows](https://github.com/coreybutler/node-windows) 插件创建有效的“服务”。

**Comment by unitwk** [comment]
很不错的项目！赞一个，已 star。

但是说句实话，我访问过这么多 IDC 商家和个人开发者，在 Windows 下他们也许更习惯于开启一个窗口来作为「服务器」程序24小时运行。

但是 MCSM 面板确实也没有查看控制台输出和输入命令的需求，可以考虑做成系统服务，但是我担心这会提高 MCSM 的使用门槛（毕竟 MCSM 面板的一键开服功能面对的就是小白用户），所以我太愿意将这种方式变成默认的安装和运行方式。

后续我可以看看能不能找到一种兼顾的方式（比如安装包内附加一个安装服务的脚本，但不主动启动），你的脚本很不错，如果以后需要使用到你的脚本，我会遵守你的开源协议。

**Comment by bddjr** [comment]
主要是有时候可能会因为意外导致服务器强制重启（例如服务器被DDos攻击了，或者机房不小心碰到电源线之类的），这种情况在小厂服务商或者家里云会较为常见。  
这时候还得服主连接远程桌面再启动会很麻烦。  

官方想要的是默认不污染 Windows 注册表，所以我想的就是比较兼顾的方式，也就是把脚本直接合并到官方打包的 Windows 版里，需要的自己翻出来运行脚本即可。  
同时最好在首页里标注这个脚本在哪运行，不然有些人不一定知道可以直接用里面的脚本设置开机自启。  

***
感谢官方的认可！

**Comment by bddjr** [comment]
您的回答里是不是有个地方漏了个字（如下图）  

![image](https://github.com/MCSManager/MCSManager/assets/109646559/32fb46ea-01c9-48cc-8f69-9f113b378fe2)

**Comment by unitwk** [comment]
> 您的回答里是不是有个地方漏了个字（如下图）
> 
> ![image](https://user-images.githubusercontent.com/109646559/281616988-32fb46ea-01c9-48cc-8f69-9f113b378fe2.png)

已更正。

**Comment by huangsijun17** [comment]
看了一下，`@echo off`建议放到每个文件的第一行，先于提权和cd。
建议改用参数来起停，而非多个文件。
另外，如果有想法，可以写一个安装脚本，直接把node和mcsm的安装写进去。

**Comment by huangsijun17** [comment]
你还不如PR到 https://github.com/MCSManager/Script 。

**Comment by bddjr** [comment]
打包程序似乎在当前仓库的next分支，不知道是不是完整的

**Comment by bddjr** [comment]
将 next 分支 clone 到本地，并且运行 install 与 build 后发现，并没有出现 windows 的 zip 和 linux 的 tar.gz  
只有 production-code 文件夹，里面正好包含了构建好的 daemon 和 web 两个文件夹，而且也没有 node_app.exe

不知道官方在后续是手动打包，还是使用未开源的脚本自动打包的，  
我觉得大概率是未开源的脚本进行自动打包，反正我是没翻到哪里有相关源码

**Comment by huangsijun17** [comment]
> 将 next 分支 clone 到本地，并且运行 install 与 build 后发现，并没有出现 windows 的 zip 和 linux 的 tar.gz 只有 production-code 文件夹，里面正好包含了构建好的 daemon 和 web 两个文件夹，而且也没有 node_app.exe
> 
> 不知道官方在后续是手动打包，还是使用未开源的脚本自动打包的， 我觉得大概率是未开源的脚本进行自动打包，反正我是没翻到哪里有相关源码

发布release时会自动将项目源码打包为zip和tgz。解析执行为主的项目，直接打包即可。

**Comment by unitwk** [comment]
> 打包程序似乎在当前仓库的next分支，不知道是不是完整的

next 分支是 MCSManager 10.0 源代码，目前正在开发中

**Comment by unitwk** [comment]
> 你还不如PR到 https://github.com/MCSManager/Script 。

你确实可以PR到这个仓库，不过我看你的 bat 文件有多点，理论上来说应该只需要五个才行了，启动Daemon/Web，关闭Daemon/Web，安装服务。

其他的卸载，重启之类的有点多了，可以先放着吧，后续精简。

**Comment by bddjr** [comment]
但是这PR到主分支不方便打包下载啊，是不是该创建一个单独的分支，或者直接fork整个仓库

**Comment by Bluemangoo** [comment]
感觉可以整合到一个文件里面，用后续stdio或者命令行参数做。

**Comment by bddjr** [comment]
直接写成exe安装程序更好（暴论）

**Comment by unitwk** [comment]
那就先维持现状吧，等新版开发完毕，有需要时，我再联系你。

**Comment by Bluemangoo** [comment]
> 直接写成exe安装程序更好（暴论）

不能exe哦。不管是从安全角度还是签名、杀软角度都不能。

**Comment by unitwk** [comment]
暂时已写入中文版 readme.md 中

https://github.com/MCSManager/MCSManager/blob/master/README_CN.md#windows

**Comment by bddjr** [comment]
> unitwk: 那就先维持现状吧，等新版开发完毕，有需要时，我再联系你。

但是这个提议暂未完成，我认为应该关闭为灰色（not planned）

**Comment by Bluemangoo** [comment]
> > Bluemangoo: 不能exe哦。不管是从安全角度还是签名、杀软角度都不能。
> 
> PCL启动器的exe就没有签名，虽然会因此被拦截，但是大家照样用。 MCSManager虽然没有安装包exe，但是内置启动器exe，照样能用，假如Defender不给运行，那么直接忽略就行了。 即便是bat，只要是下载的，Defender也会警告。

mcsm内置的exe是官方运行时。有 `OpenJS Foundation` 的签名的。杀软不拦。

你也不希望最后 mcsm 还要为了发布打个加密压缩包吧。

事实上脚本是最好的选择。最好是有可读性的。

~~碎碎念：正在为简单方便写出可读性强可维护性强的脚本努力。`Bluemangoo/WhirlScript` (yet private): A language that compiles to bat and sh scripts.~~

**Comment by bddjr** [comment]
![image](https://github.com/MCSManager/MCSManager/assets/109646559/56904da9-d177-4390-be6f-83c09aee73c5)

**Comment by bddjr** [comment]
然后还有，从MCSManager官网建议的地址下载的压缩包，解压出来的bat

![image](https://github.com/MCSManager/MCSManager/assets/109646559/01576253-652b-4c4b-8a9e-4d4b701c968c)

**Comment by unitwk** [comment]
> > > Bluemangoo: 不能exe哦。不管是从安全角度还是签名、杀软角度都不能。
> > 
> > 
> > PCL启动器的exe就没有签名，虽然会因此被拦截，但是大家照样用。 MCSManager虽然没有安装包exe，但是内置启动器exe，照样能用，假如Defender不给运行，那么直接忽略就行了。 即便是bat，只要是下载的，Defender也会警告。
> 
> mcsm内置的exe是官方运行时。有 `OpenJS Foundation` 的签名的。杀软不拦。
> 
> 你也不希望最后 mcsm 还要为了发布打个加密压缩包吧。
> 
> 事实上脚本是最好的选择。最好是有可读性的。
> 
> ~碎碎念：正在为简单方便写出可读性强可维护性强的脚本努力。`Bluemangoo/WhirlScript` (yet private): A language that compiles to bat and sh scripts.~

有一个由go编写而成的启动器二进制程序，这个你不知道很正常，最新版中国版才有。

**Comment by Bluemangoo** [comment]
我知道启动器，我不是很喜欢那个，太大了。

**Comment by huangsijun17** [comment]
> 然后还有，从MCSManager官网建议的地址下载的压缩包，解压出来的bat
> 
> ![image](https://user-images.githubusercontent.com/109646559/282235541-01576253-652b-4c4b-8a9e-4d4b701c968c.png)

这是因为Windows会标注从网络上下载的文件。在属性里可以看到这个标注，去掉就没提示了。

**Comment by bddjr** [comment]
理论上，MCSM的exe安装程序只需要执行：

1. 从自己本身内置的7z文件解压到指定目录  
2. 直接借助 [WinSW](/winsw/winsw) 安装服务（node-windows本质上也是使用WinSW安装服务）

**Comment by Bluemangoo** [comment]
> 理论上，MCSM的exe安装程序只需要执行：
> 
> 1. 从自己本身内置的7z文件解压到指定目录  
> 2. 直接借助 [WinSW](/winsw/winsw) 安装服务（node-windows本质上也是使用WinSW安装服务）  
> 

在不知道exe内部到底是什么玩意的时候我更倾向于用压缩包。从安全的角度和方便性统一性稳定性可维护性的角度我都不会让这种东西从安装包里面出来。

我想应该不止我一个把这种服务和需要绝对路径的东西放在类似 `D:\WorkDir\` 底下吧。

**Comment by bddjr** [comment]
我成功使用 `WinSW.NET2.exe` 直接把服务跑起来了，理论上已经可以把那个脚本里的 JS 部分整个扬了

**Comment by bddjr** [comment]
已经把脚本的JS部分扬了，直接WinSW.NET461

**Comment by Bluemangoo** [comment]
我支持把node windows作为mcsm的运行时依赖，然后翻源码在脚本里面做完服务安装。

**Comment by bddjr** [comment]
用node-windows进行服务安装有点脱裤子放屁了，实际上脚本只需要直接编辑WinSW的xml文件然后运行WinSW的exe后面加上install参数就行了

**Comment by bddjr** [comment]
powershell可以实现下载文件、解压zip，  
那么理论上bat只需要结合powershell命令就可以完成MCSManager的在线安装，  
安装的时候也可以直接把daemon和web设置为服务

**Comment by Bluemangoo** [comment]
草，node windows 调用winsw的是吧。。。。。。

**Comment by bddjr** [comment]
> 草，node windows 调用winsw的是吧。。。。。。

是的，而且它内置的WinSW已经7年没更新了

**Comment by bddjr** [comment]
然而我写好安装脚本后，尝试制作安装命令的时候，遇到了编码问题，翻了一堆搜索结果没找到解决方法，想放弃了

**Comment by bddjr** [comment]
Windows版安装脚本写好了

https://github.com/bddjr/MCSManager-setup-bat

**Comment by bddjr** [comment]
我在某个网友的提示下才知道7个月前官方文档就已经有个教程讲述怎么手动设置服务了，之前都没注意

（有点丢脸）
