### ISSUE TITLE
帮帮指导下镜像在哪里管理

### ISSUE THREAD

**Issue by NaiMu3862** [MCSManager/MCSManager#1074]
![image](https://github.com/MCSManager/MCSManager/assets/96154727/40e709ed-37af-4f0e-a000-5f535c18ede0)
我找不到创建、管理docker镜像的入口

**Comment by unitwk** [comment]
节点管理，查看一个节点，右上角有一个镜像管理，点进去就行了

**Comment by NaiMu3862** [comment]
> 节点管理，查看一个节点，右上角有一个镜像管理，点进去就行了
谢谢，看到了

**Comment by NaiMu3862** [comment]
谢谢，看到了
