### ISSUE TITLE
希望可以给MC Java 版的命令助手中辅助添加语言参数

### ISSUE THREAD

**Issue by huangsijun17** [MCSManager/MCSManager#1088]
部分Minecraft的服务端核心对于操作系统的语言识别可能存在问题，外加Docker运行时需要在镜像或容器启动命令中额外设置语言。在java启动参数中使用`-Duser.language=zh -Duser.region=CN`来指定语言是最佳方案之一。希望可以辅助添加该选项。

**Comment by unitwk** [comment]
下个大版本加！

**Comment by unitwk** [comment]
国家怎么变成 `-Duser.region` 参数了，你以前跟我说的是 `-Duser.country`

**Comment by huangsijun17** [comment]
> Duser.country

我搜的，应该是错了。

**Comment by unitwk** [comment]
> > Duser.country
> 
> 我搜的，应该是错了。

那你能保证这一次是正确的吗？🤪

**Comment by KagurazakaNyaa** [comment]
https://www.oracle.com/technical-resources/articles/javase/locale.html#using

看起来应当是`java -Duser.language=zh -Duser.country=CN` 会把locale设置为`zh_CN`

**Comment by unitwk** [comment]
感谢 @KagurazakaNyaa 提供的官方链接。

@huangsijun17 下次发言麻烦先查证后附上链接再说话，不要乱说。

<img width="644" alt="image" src="https://github.com/MCSManager/MCSManager/assets/18360009/ed871852-7463-44b3-817f-0ae828d63c03">

**Comment by huangsijun17** [comment]
> Duser.region

![image](https://github.com/MCSManager/MCSManager/assets/31504595/cce47b43-0e7f-466e-8407-045de6633fb2)
似乎，两者都对？！
