### ISSUE TITLE
上传实例，或者上传文件时提示网络错误

### ISSUE THREAD

**Issue by Jack-Maos** [MCSManager/MCSManager#1092]
**MCSManager Version**
9.9.0
**System Info/Version**
#51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 5.4.0-47-generic
**Node Version**
v14.19.1
**Step**
<img width="727" alt="截屏2023-12-15 15 15 07" src="https://github.com/MCSManager/MCSManager/assets/124993758/db0c7d72-e11f-48e2-b681-5997b6a9811f">

**Comment by huangsijun17** [comment]
是否使用了反向代理？

**Comment by Jack-Maos** [comment]
> 是否使用了反向代理？

还真是反向代理的问题，感谢🙏
顺便请问nginx反向代理绑了个域名后怎么解决这个问题，还是只能使用ip
