### ISSUE TITLE
程序点开就是乱码，不知道什么原因

### ISSUE THREAD

**Issue by EnterFor** [MCSManager/MCSManager#1093]
**MCSManager Version**
9.9.0
**System Info/Version**
windows 2008 R2
**Node Version**

**Step**
![image](https://github.com/MCSManager/MCSManager/assets/10114685/26f07a0d-c0d9-442b-bd8a-ce1e8bc34e9d)

**Comment by EnterFor** [comment]
第一个按钮是启动，点了也无反应

**Comment by huangsijun17** [comment]
系统语言？是不是未安装中文语言包？

**Comment by EnterFor** [comment]
是中文的系统
![image](https://github.com/MCSManager/MCSManager/assets/10114685/1d17dc2a-90ba-4969-a38c-a0c6b3cc42c8)

**Comment by huangsijun17** [comment]
> windows 2008 R2

地区和语言里的“非Unicode的程序语言”是否设为中文？

**Comment by EnterFor** [comment]
yep....
![image](https://github.com/MCSManager/MCSManager/assets/10114685/a2e61059-2f90-45d1-b487-b5e4fbdf952f)

**Comment by huangsijun17** [comment]
请问一下，你这个2008R2是怎么安装的？直接安装的中文本？还是英文版装的中文包？还是哪个云主机直接给的镜像？

**Comment by EnterFor** [comment]
> 请问一下，你这个2008R2是怎么安装的？直接安装的中文本？还是英文版装的中文包？还是哪个云主机直接给的镜像？

https://miaomiao.games/   选好套餐，选好系统，直接就装好了

**Comment by huangsijun17** [comment]
能否提供以下系统内置了哪些中文字体？

**Comment by EnterFor** [comment]
> 能否提供以下系统内置了哪些中文字体？

这个要在哪里查看？

**Comment by huangsijun17** [comment]
> > 能否提供以下系统内置了哪些中文字体？
> 
> 这个要在哪里查看？

一般可以在控制面板里的字体或字体目录下查看。

**Comment by EnterFor** [comment]
![image](https://github.com/MCSManager/MCSManager/assets/10114685/b67a270b-de33-465c-8979-f64fbc8d7fb4)

**Comment by unitwk** [comment]
不使用exe启动器，你直接用bat运行，安装包里面有

**Comment by EnterFor** [comment]
![image](https://github.com/MCSManager/MCSManager/assets/10114685/693b8063-d71c-41b5-8652-eca705ecfcb6)
我总觉得这个系统有问题，明明文件没有丢失

**Comment by EnterFor** [comment]
重新解压也不行，我放弃了...

**Comment by bddjr** [comment]
这个看起来可能是系统太老旧了导致的

**Comment by Bluemangoo** [comment]
其实修好了也没用。node不支持低版本win，很多包会直接报错。

**Comment by huangsijun17** [comment]
> windows 2008 R2

08 R2是Windows 7的服务器版本，Win7都不兼容了？

**Comment by bddjr** [comment]
换成2012可能就不会有问题了，或者直接LTSC2019

**Comment by unitwk** [comment]
windows 2008 R2 不支持

**Comment by Bluemangoo** [comment]
> > windows 2008 R2
> 
> 08 R2是Windows 7的服务器版本，Win7都不兼容了？

node12是最后一个兼容win7的版本。
