### ISSUE TITLE
Installation works 100% the rest i dont know

### ISSUE THREAD

**Issue by scherzbolds** [MCSManager/MCSManager#1095]
I love this software who has a really good readme file for installation.
Now as the panel is installed i need help with simply create a minecraft server there.
Sadly the name of this manager is too similar to find any relevant in google, youtube videos are 10 years old from the creator and nowhere you can find anything. Even a logfile location isnt working as its outdated location so i am stuck with a nother panel without working and error messages who say nothing absolutly nothing then stopped working.
I am so happy now

**Comment by unitwk** [comment]
https://docs.mcsmanager.com/#/getting-started/manual-install

Maybe this can help you.

**Comment by scherzbolds** [comment]
> https://docs.mcsmanager.com/#/getting-started/manual-install
> 
> Maybe this can help you.

wtf ? how should instruction manual for MCSManager installation, help me with USING the installed Manager?

**Comment by scherzbolds** [comment]
great, giving the wrong answers and simply close it. You are the best

**Comment by Bluemangoo** [comment]
which step you get stuck in? and screenshot please. i cant really understand what's your problem.
