### ISSUE TITLE
能不能把websocket的端口号填写去掉?

### ISSUE THREAD

**Issue by coolxitech** [MCSManager/MCSManager#1096]
搞个cdn折腾这玩意折腾半天.

**Comment by unitwk** [comment]
MCSManager 从来没有说过支持 CDN。

**Comment by Bluemangoo** [comment]
折腾cdn你这样：

要么合并端口，要么分两个域名。大部分cdn不支持一个域名反代两个端口。

cdn的话端口一般是443。

记得找一个支持WebSocket的端口。
