### ISSUE TITLE
bash实例每次点开都会自动输入 2RR0;276;0c

### ISSUE THREAD

**Issue by bddjr** [MCSManager/MCSManager#1099]
**MCSManager Version**
9.9.0
**System Info/Version**
Ubuntu 22.04
**Node Version**
14.19.1
**Step**
新建bash实例并且运行，每次点进去都会自动输入`2RR0;276;0c`

**Comment by unitwk** [comment]
有没有开启颜色渲染？尝试关闭终端的颜色渲染设备，在「终端设置」界面中。

然后再试试会不会继续出现。

我参考了这里的[信息](https://github.com/xtermjs/xterm.js/issues/4127)，怀疑是颜色渲染打乱了终端编码。

**Comment by bddjr** [comment]
实测不是，是仿真终端的问题，每次点开实例都会自动输入这串字符，再点开一次又在输入的内容后面叠加了这串字符。并且从命令运行结果来看，这串东西是真的输入了。

**Comment by bddjr** [comment]
![image](https://github.com/MCSManager/MCSManager/assets/109646559/eceef667-16da-44df-b411-c34bfbb9b62a)

**Comment by unitwk** [comment]
好吧，我暂时没有遇到过，等我遇到了我再研究一下吧，我也不清楚原因。

**Comment by bddjr** [comment]
不知道是不是ubuntu特有的问题
