### ISSUE TITLE
how to use codes from bukkit.yml in server.properties？

### ISSUE THREAD

**Issue by FangzhengDu** [MCSManager/MCSManager#1100]
Basically I want to use spawn limitation code from bukkit.yml below 
spawn-limits:
   monsters: 70
   animals: 10
   water-animals: 4
   water-ambient: 4
   ambient: 1
I tried to add “spawn-limits-monsters=1” in server.properties but not working. 
Is it possible? Or I just can’t use it.
Please help.

**Comment by unitwk** [comment]
Your question has nothing to do with MCSManager. Please go to the Spigot forum to ask.

**Comment by FangzhengDu** [comment]
Thank you so much.

**Comment by FangzhengDu** [comment]
Is it possible to add bukkit.yml file to mcsmanager under the same route as server.properties file?

**Comment by FangzhengDu** [comment]
Forget about that question, thank you for your answer .
