### ISSUE TITLE
建议Web端加载静态文件支持Etag与Last-Modified验证缓存

### ISSUE THREAD

**Issue by bddjr** [MCSManager/MCSManager#1101]
如题，这将大大减少重复加载Web静态文件的压力。（实测首次加载如果不开gzip要加载4.4MB，开gzip要加载1.1MB）

https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Etag

https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Last-Modified

https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/304

**Comment by Bluemangoo** [comment]
理论上对于vue可以全部直接缓存。有更改文件名会变。手动的静态文件没办法了。
