### ISSUE TITLE
使用Treafik 进行HTTPS反向代理连接Daemon 端出现问题

### ISSUE THREAD

**Issue by Raven-L** [MCSManager/MCSManager#1107]
**MCSManager Version**
9.9.0

**System Info/Version**
lxc ubuntu 23.10
**Node Version**
3.4.0
**Step**
1. 使用Treafik反向代理了面板端和Daemon端到443端口, 同时[参考这个](https://github.com/bddjr/nginx-proxy-docs-for-mcsm/blob/master/%E4%B8%BA%E5%90%8C%E4%B8%80%E4%B8%BB%E6%9C%BA%E7%9A%84443%E7%AB%AF%E5%8F%A3%E9%85%8D%E7%BD%AEHTTPS%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86.md)将其绑定到了同一个域名的443端口下。
2. 但“节点管理”处只能使用localhost:24444才能连接成功
![image](https://github.com/MCSManager/MCSManager/assets/47520028/6283cb76-f7b3-4822-a7e7-dd57477457a1)
尝试过: `wss://域名:443` , `域名:443`都连接失败
3. 设置localhost:24444可以连接成功,但无法管理节点。 
4. 将在路由将24444端口转发回到443端口, 这样就可以管理节点了，也测试过上传和下载文件，说明Treafik的功能是正常的。

需求：
能使用`wss://域名:443` 正常使用所有功能。

问题猜想：
1. 是否“节点管理”处的websocket连接没有带上host header导致反向代理无法识别流量？
因为使用`localhost:24444`管理节点时， 实际上连接的是“wss://域名:24444”，在通过我路由转为了443端口才能正常工作。

**Comment by bddjr** [comment]
🤔这是不是因为Treafik不支持针对localhost单独HTTP的写法，或者你弄错了什么

**Comment by Raven-L** [comment]
> 🤔这是不是因为Treafik不支持针对localhost单独HTTP的写法，或者你弄错了什么



我的Treafik 用kv配置的路由
```
consul kv put traefik/http/services/mcsm/loadbalancer/servers/0/url "http://10.40.20.100:23333"
consul kv put traefik/http/routers/mcsm/rule "Host(\`mcsm.XXX.top\`)"
consul kv put traefik/http/routers/mcsm/service "mcsm"
consul kv put traefik/http/routers/mcsm/tls "true"
consul kv put traefik/http/routers/mcsm/entrypoints/0 "websecure"
consul kv put traefik/http/routers/mcsm/tls/certresolver "myresolver"
consul kv put traefik/http/routers/mcsm/tls/domains/0/main "*.XXX.top"
consul kv put traefik/http/routers/mcsm/tls/domains/0/sans "*.XXX.top"


consul kv put traefik/http/services/mcservice1/loadbalancer/servers/0/url "http://10.40.20.100:24444"
consul kv put traefik/http/routers/mcservice1/rule "Host(\`mcsm.XXX.top\`) && (PathPrefix(\`/socket.io/\`) || PathPrefix(\`/upload/\`) || PathPrefix(\`/download/\`))"
consul kv put traefik/http/routers/mcservice1/tls "true"
consul kv put traefik/http/routers/mcservice1/entrypoints/0 "websecure"
consul kv put traefik/http/routers/mcservice1/tls/certresolver "myresolver"
consul kv put traefik/http/routers/mcservice1/tls/domains/0/main "*.XXX.top"
consul kv put traefik/http/routers/mcservice1/tls/domains/0/sans "*.XXX.top"
```
配置非常基础

而且核心问题不是traefik不支持localhost的问题, 而是mcsm直接用域名连不上的问题, 非常离奇
用localhost只是无奈之举

**Comment by bddjr** [comment]
贴出来的配置内容没看懂

但是已知有的路由器或光猫不支持使用自己的公网IP连接自己，可以试试更改服务器的hosts文件，将这个域名指向127.0.0.1。  
这是一种可能可行的备用方案，但由于nginx支持同端口针对localhost单独HTTP的写法，所以我的文章里并没有提到。

**Comment by Raven-L** [comment]
> 只有你点进一个实例的终端才是浏览器直接请求daemon，在线状态检测是web服务端进行的，节点有哪些实例也是web服务端返回的

原来如此，那可能是这边的问题，因为我网络结构还是有点复杂的，可能是这个原因导致的。我排查一下

**Comment by Raven-L** [comment]
> 只有你点进一个实例的终端才是浏览器直接请求daemon，在线状态检测是web服务端进行的，节点有哪些实例也是web服务端返回的

解决了,能用wss://域名:443访问了。

我是用PVE的LXC部署的MCSM，刚好主机名也设置成mcsm了，导致LXC的DNS解析域名到其本身,而不是解析到Treafik。
总结是web服务端上dns的问题。

推荐可以提示一下“在线状态检测是web服务端进行的”这一点。

**Comment by bddjr** [comment]
添加了“理论基础”

https://github.com/bddjr/nginx-proxy-docs-for-mcsm/blob/master/%E7%90%86%E8%AE%BA%E5%9F%BA%E7%A1%80.md
