### ISSUE TITLE
[活动] MCSManager 10.0 预览版正在内测中

### ISSUE THREAD

**Issue by unitwk** [MCSManager/MCSManager#1110]
我们将网页UI完全重写，现已支持自定义拖拽的方式设计网页，以小卡片的形式自由拼接出你喜欢的样子。

目前仅限【赞助成员】参与，如果你想参与进来，请前往[爱发电赞助](https://afdian.net/a/mcsmanager)后将得到进入赞助内测群资格。

更多详情请加入【[MCSManager 用户群](http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=4EaUe7AzUPaDajd0-kVpErmEAtlSt0tA&authKey=lEb1MeqO8Qap%2FdMlytpS8%2B0udqWnfQLr%2BD6URtnFIhDxkxSH57Z37ODvScF0m5yt&noverify=0&group_code=198646856)】了解。

**MCSManager 10.0 预览版群友内部截图：**

![IMG_4684(20240103-011538)](https://github.com/MCSManager/MCSManager/assets/18360009/b2d8bb62-c98f-4a68-948e-e876c1d458bd)

![b36b3515c711b289ee22282c33cbc667](https://github.com/MCSManager/MCSManager/assets/18360009/961cd009-227d-4ca5-a404-fa44bc691693)

![image](https://github.com/MCSManager/MCSManager/assets/18360009/54f812ef-191f-40ce-8201-d91783ceb5aa)

<img width="1280" alt="cca4fb0d4e5bfae27f9d9b312e54f125" src="https://github.com/MCSManager/MCSManager/assets/18360009/30e5b73d-150a-4a88-ad3c-8a1722a94a9c">

**Comment by alongw** [comment]
羡慕！！羽毛好强！！！！拉闸好强！！！！
