### ISSUE TITLE
[Suggestion] 关于MCSM10新UI方面的建议

### ISSUE THREAD

**Issue by Zhou-Shilin** [MCSManager/MCSManager#1112]
# 应用实例
应用实例界面长度太长了，图中的蓝线是正常PC显示器能在不下滑的情况下看到的最低位置，这意味着不下滑就不能使用功能组。开发者的显示器可能是竖过来的，不知道有没有试过在正常显示器上实际操作，看似只多一步下拉，实际有些时候需要短时间内频繁使用功能组，影响不小。变长是因为设计不合理，见下图：
![112C2180-96E4-45BB-8D5F-20888FFAA429](https://github.com/MCSManager/MCSManager/assets/86581525/51965378-60be-4b41-ad47-7e20896bce2b)

# 文件管理
见图，搜索栏向左移，*文件操作*下拉菜单里的项目完全可以放到搜索栏右边，可以少一步点开下拉菜单的操作。
![41EDE69F-46A8-4CB9-851C-B2ADD2D60E20](https://github.com/MCSManager/MCSManager/assets/86581525/3be2e662-6f3c-42f3-b8e5-ede4ed929aa4)
还有压缩/解压任务能否添加取消按钮，之前面板抽风，一个压缩任务可能陷入循环了，500mb的文件压缩体积一直在增大，30gb 50gb… 后来kill了面板才好的…

# 自定义UI
![1CBDBBDE-791B-47BB-81FE-52A7787870A2](https://github.com/MCSManager/MCSManager/assets/86581525/a0a275aa-21e4-4bfa-b2df-99a06705ea0e)
上图是编辑时的样子，下图是点击保存后的样子。为什么不一样…？个人推测是因为左边信息卡高度必须等于控制台高度
![](https://cdn.jsdelivr.net/gh/Zhou-Shilin/picx-images-hosting@master/20240117/5377667B-310F-4042-8074-B8C1FF87CD86.1r207perrl8g.jpeg)
***
mcsm目前只能实现下-左图，能否添加对下-右图的支持：
![E6C9E002-074C-4C9C-86E2-A84F094F63DE](https://github.com/MCSManager/MCSManager/assets/86581525/804ce5be-011a-4b12-9d3b-36d67d2d422f)

[.](https://blog.baimoqilin.top/index.php/2024/01/16/mcsm10/)

**Comment by unitwk** [comment]
关于「应用实例」：

首先控制台界面最高度使用的功能就是「控制台」，我们确保在 14 英寸左右的屏幕下，能够整个覆盖整个屏幕，这样能最大限度使用屏幕。而底部的那些信息和按钮，并不是高频需求。如果你认为底下的信息和功能区是高频需求，你可以将它们两个移动到顶部。

右上角那个按钮是为了兼容手机，平板等小屏幕，因为手机没有那么宽，这样就不需要做两遍样式。

关于「文件管理」：

解压缩的BUG后续我复现排查下，如果你有更多信息欢迎继续反馈。菜单下拉框那里也是为了兼容手机和小屏幕。


关于「自定义UI」：

由于浏览器前端布局技术就是以一行为基本单位，所以无法直接开发出你想要的那种可随意上下左右布局，当然也有解决方案，只是成本很高。

**Comment by unitwk** [comment]
有其他问题也可以继续反馈，最好是正式版上线之前完成所有潜在问题的修复。

**Comment by Zhou-Shilin** [comment]
> 右上角那个按钮是为了兼容手机，平板等小屏幕，因为手机没有那么宽，这样就不需要做两遍样式。
> 菜单下拉框那里也是为了兼容手机和小屏幕。
9代就做得很好，兼容手机，在电脑上没有下拉菜单、手机上则有
所以10代是退化了吗
> 至于你说功能组按钮太小，如果真要按照你那样设计，恐怕那一块就会显得空空如也，既不美观也不实用。
我说的不是“太小”，而是按钮太**大**，*既不美观也不实用*是对10代设计的最恰当的评价。
> 首先控制台界面最高度使用的功能就是「控制台」，我们确保在 14 英寸左右的屏幕下，能够整个覆盖整个屏幕，这样能最大限度使用屏幕。而底部的那些信息和按钮，并不是高频需求。
前面给出的图中可以看到右侧一半的空间完全没有使用，这部分空间是宁可浪费掉也不肯给功能组，即使你认为功能组部署所谓*“高频需求”*，这样也不是个好设计。不知道mcsmanager的全称是不是 *M*ine*c*raft *S*ever *M*anager，我这里开的是Minecraft Java服，大多数mcsm用户应该也开的是minecraft服务器，实在搞不懂是怎样的使用场景才会用到如此宽的屏幕。
> 如果你认为底下的信息和功能区是高频需求，你可以将它们两个移动到顶部。
先面也说了我试过了，然而效果也在上面截图了，仍然不能保证信息卡、功能组和控制台像9代那样摆放，不是控制台空一大块就是信息卡/功能组空一大块，页面空间就是这样一点一点浪费的。
> 解压缩的BUG后续我复现排查下，如果你有更多信息欢迎继续反馈。
那个确实是因为我的操作不当，试图在压缩一个超大文件夹的同时压缩其中的一个子文件夹…
> 由于浏览器前端布局技术就是以一行为基本单位，所以无法直接开发出你想要的那种可随意上下左右布局，当然也有解决方案，只是成本很高。
wordpress中的文章编辑器支持*“随意上下左右布局‘*，这一点所造成的*“成本”*没有妨碍它成为世界上43%的网站的选择。

**Comment by unitwk** [comment]
你说的有也有一定的道理。更好的用户体验一定是要更多的工作量（比如为了PC，平板手机单独做两套适配工作）。

这个工作量最终是负担到我「个人」的身上，而不是「你们」，我并没有什么回报，所以有开发成本最低的方案我一定会使用开发成本最低的方案，这是现实。

另外关于界面UI上大小等等，你用一段时间习惯之后也许就好了，UI不可能适用于每个人，多多少少有点看不顺眼的地方，后续我会适当调整，但不要指望能有过多更改。

**Comment by Zhou-Shilin** [comment]
话说命令历史是被砍掉了吗，能不能加到ui编辑器里面，想要的用户自己加

**Comment by Zhou-Shilin** [comment]
> 这个工作量最终是负担到我「个人」的身上，而不是「你们」
> 在赞助者QQ群内也没有听见过有人吐槽此情况，目前来说只有你一个人
10代没人说不好，9代就有人说不好了吗？与其在UI上大刀阔斧地做无意义的修改，还不如把有限的时间花在插件系统上。插件系统可以说是一劳永逸的*，f-req因为没时间没经理、会让面板变得更臃肿等原因wontadd，那为什么不把这些交给插件呢？于是这个工作量最终就不负担在「你」身上，而是「我们」了。
*一劳永逸：forge1.12.2已经2年没更新了，然而仅在[CurseForge](https://www.curseforge.com/minecraft/search?page=1&pageSize=20&sortBy=relevancy&class=modpacks&version=1.12.2&gameVersionTypeId=1)一个平台上就有将近一万个模组(9,519)支持1.12.2，该版本仍是最受欢迎的Minecraft版本之一。

**Comment by BuDingOwO** [comment]
终端区域中，能在一行里把原本一行的内容不用滑滑条就读完是非常舒服的一件事
不要为了你自己就把大家的使用体验都拉低，我不相信你靠鼠标去点那几个控件的时候滑动滚轮是多么难的事情
横向的滑条 比 竖向的滑条 体验差很多，因为没有按键&滚轮可以直接滑动，而需要使用鼠标去拉
你说完全能省掉一半的那你只是没遇到对的场景而已，当你要看报错信息的时候你就发现那个横向滑条是真的愚蠢了😠😠😠

**Comment by Zhou-Shilin** [comment]
> 终端区域中，能在一行里把原本一行的内容不用滑滑条就读完是非常舒服的一件事
> 不要为了你自己就把大家的使用体验都拉低，我不相信你靠鼠标去点那几个控件的时候滑动滚轮是多么难的事情
> 横向的滑条 比 竖向的滑条 体验差很多，因为没有按键&滚轮可以直接滑动，而需要使用鼠标去拉
> 你说完全能省掉一半的那你只是没遇到对的场景而已，当你要看报错信息的时候你就发现那个横向滑条是真的愚蠢了😠😠😠

9代的时候可以设置终端大小，太长的可以换行，用不着横向滑条
当然这个功能也被砍掉了，命令历史也被砍掉了，根据屏幕大小(手机/电脑区分)提供不同的页面布局也被砍掉了，实例界面查看daemon和实例id也被砍掉了，文本编辑器上方的快捷栏也被砍掉了
10代就是究极大退化，这才是你说的*“把大家的使用体验都拉低”*
***
> “我不相信你靠鼠标去点那几个控件的时候滑动滚轮是多么难的事情”
> “终端区域中，能在一行里把原本一行的内容不用滑滑条就读完是非常舒服的一件事”
> “当你要看报错信息的时候你就发现那个横向滑条是真的愚蠢了”

另外看报错的频率一定比使用文件管理低

**Comment by unitwk** [comment]
> > 终端区域中，能在一行里把原本一行的内容不用滑滑条就读完是非常舒服的一件事
> > 不要为了你自己就把大家的使用体验都拉低，我不相信你靠鼠标去点那几个控件的时候滑动滚轮是多么难的事情
> > 横向的滑条 比 竖向的滑条 体验差很多，因为没有按键&滚轮可以直接滑动，而需要使用鼠标去拉
> > 你说完全能省掉一半的那你只是没遇到对的场景而已，当你要看报错信息的时候你就发现那个横向滑条是真的愚蠢了😠😠😠
> 
> 9代的时候可以设置终端大小，太长的可以换行，用不着横向滑条 当然这个功能也被砍掉了，命令历史也被砍掉了，根据屏幕大小(手机/电脑区分)提供不同的页面布局也被砍掉了，实例界面查看daemon和实例id也被砍掉了，文本编辑器上方的快捷栏也被砍掉了 10代就是究极大退化，这才是你说的*“把大家的使用体验都拉低”*
> 
> > “我不相信你靠鼠标去点那几个控件的时候滑动滚轮是多么难的事情”
> > “终端区域中，能在一行里把原本一行的内容不用滑滑条就读完是非常舒服的一件事”
> > “当你要看报错信息的时候你就发现那个横向滑条是真的愚蠢了”
> 
> 另外看报错的频率一定比使用文件管理低，用文件管理不一定是因为报错，但是看了报错大概率得到文件管理里面需修

不是被砍掉，只是还没开发完，不要着急。目前MCSM10也没有发布正式版。

**Comment by Zhou-Shilin** [comment]
> > > 终端区域中，能在一行里把原本一行的内容不用滑滑条就读完是非常舒服的一件事
> > > 不要为了你自己就把大家的使用体验都拉低，我不相信你靠鼠标去点那几个控件的时候滑动滚轮是多么难的事情
> > > 横向的滑条 比 竖向的滑条 体验差很多，因为没有按键&滚轮可以直接滑动，而需要使用鼠标去拉
> > > 你说完全能省掉一半的那你只是没遇到对的场景而已，当你要看报错信息的时候你就发现那个横向滑条是真的愚蠢了😠😠😠
> > 
> > 
> > 9代的时候可以设置终端大小，太长的可以换行，用不着横向滑条 当然这个功能也被砍掉了，命令历史也被砍掉了，根据屏幕大小(手机/电脑区分)提供不同的页面布局也被砍掉了，实例界面查看daemon和实例id也被砍掉了，文本编辑器上方的快捷栏也被砍掉了 10代就是究极大退化，这才是你说的*“把大家的使用体验都拉低”*
> > > “我不相信你靠鼠标去点那几个控件的时候滑动滚轮是多么难的事情”
> > > “终端区域中，能在一行里把原本一行的内容不用滑滑条就读完是非常舒服的一件事”
> > > “当你要看报错信息的时候你就发现那个横向滑条是真的愚蠢了”
> > 
> > 
> > 另外看报错的频率一定比使用文件管理低，用文件管理不一定是因为报错，但是看了报错大概率得到文件管理里面需修
> 
> 不是被砍掉，只是还没开发完，不要着急。目前MCSM10也没有发布正式版。
> 
> 后续会加上支持所有Docker镜像，以及命令历史这些功能的，只是因为还没开发完成而已。

根据屏幕大小(手机/电脑区分)提供不同的页面布局也没被砍掉吗？

**Comment by unitwk** [comment]
过年期间谁有空天天看 Github，都在玩昵，既然这么不喜欢你可以继续用 9.X，此话题关闭。
