### ISSUE TITLE
Fast Download

### ISSUE THREAD

**Issue by Sh4d0wless** [MCSManager/MCSManager#1121]
this perfect CP must have fast download...
i advice this one https://github.com/rejetto/hfs  ( https://github.com/rejetto/hfs2 )

**Comment by unitwk** [comment]
I don't understand what you're trying to express?

**Comment by Sh4d0wless** [comment]
First of all, reason is that there is no normal CP for Windows... i tested lot of them... OGP, UGCC, TCAdmin2, and others... 
all they have some problems...
About my sugguestion..., i mean make something like module... HFS can be included in MCSManager dir and manage it from panel... as well MCSManager have support of STEAM games the **sv_download** links can be insterted to Instance...(for example drop down menu for some server)

sorry for my bad English :)

**Comment by Zhou-Shilin** [comment]
Adding support for plugins or modules is a very good idea. Maybe MCSM doesn't have to officially implement the *Fast Download* feature, just leave it to plugins.

- https://github.com/MCSManager/MCSManager/issues/972
- https://github.com/MCSManager/MCSManager/issues/962#issuecomment-1657397385

**Comment by Bluemangoo** [comment]
oops nobody write that.

双羽说他没空做，估计要社区pr。我没什么思路。你怎么看。

**Comment by unitwk** [comment]
There is no need to submit a PR, I will develop it later as appropriate.
