### ISSUE TITLE
Hide Console

### ISSUE THREAD

**Issue by Sh4d0wless** [MCSManager/MCSManager#1122]
hello again...
i advice to make run .bat .cmd file hiden 
or make option for hide or not to hide console screen...

**Comment by Bluemangoo** [comment]
try `start` command with `wait` argument.

**Comment by Sh4d0wless** [comment]
> try `start` command with `wait` argument.

`start /normal  /wait hlds.exe -console -game cstrike +map de_dust2 +maxplayers 32`

plz try and tell me what u`ll get...

**Comment by Bluemangoo** [comment]
wait, what is the '.bat' and '.cmd' file to run? what you exactly want to do? i don't really got you.

**Comment by Sh4d0wless** [comment]
does not metter its same with all methods from MCSManager, i tested it with .bat .cmd. with "command helper"....

**Comment by Bluemangoo** [comment]
i never got you. if you CANNOT describe your problem clearly, no one will help you. you never told what is "hide console". hide output? or another cmd console window? if the latter one you should not ask here. ask the game. it's not problem of mcsm.

**Comment by Sh4d0wless** [comment]
> i never got you. if you CANNOT describe your problem clearly, no one will help you. you never told what is "hide console". hide output? or another cmd console window? if the latter one you should not ask here. ask the game. it's not problem of mcsm.

i dont need your help... and i have not any problem... its Manager does not run game(apps) hiden, you can check OGP, UGCC, GameAP... lot of other, and see how they run games with cmd(or not with cmd i dunno) hiden, .exec process is showing only in taskmanager... thats all... good luck...
