### ISSUE TITLE
Users Registration

### ISSUE THREAD

**Issue by Sh4d0wless** [MCSManager/MCSManager#1123]
hope i dont bother you with lot of ideas :)
my advice to make aviable allow users register on CP...

**Comment by unitwk** [comment]
No, we don't bundle it with other software.

**Comment by Sh4d0wless** [comment]
what? did u read above? what do u do not bundle? users reg form? 🤔

**Comment by Bluemangoo** [comment]
even if you registered, you won't have access to any instance.

if you really need it, write your own registeration page, and call mcsm's apis to finish the registration and distribute instances.

plus, always remember, instances are running under **root** user. everyone who have access to them may control the whole machine.

**Comment by Sh4d0wless** [comment]
> even if you registered, you won't have access to any instance.
> 
> if you really need it, write your own registeration page, and call mcsm's apis to finish the registration and distribute instances.
> 
> plus, always remember, instances are running under **root** user. everyone who have access to them may control the whole machine.

tnx, i already refused MCSManager, there is 3 most importent things, that should be in CP, its - Users Reg Form, Fast Download support and FTP manager... and also process Monitor, MCSManager needs all of them... check GameAP and OGP... you`ll find lot of nice things for CP ( sure without bundle, u can write ur own :) ) good luck...

**Comment by Bluemangoo** [comment]
it seems like that you don't need a panel but a ssh server.

mcsm is not a vps manager but a game server manager. it doesnt designed to manage files, process, etc.
