### ISSUE TITLE
xhr poll error

### ISSUE THREAD

**Issue by alazeprt** [MCSManager/MCSManager#1125]
**MCSManager Version**
10.0.1

**System Info/Version**
#1 SMP Debian 5.10.178-3 (2023-04-22) 5.10.0-22-amd64

**Node Version**
v14.19.1

**Step**
创建新应用实例后进入该应用实例，无法进行操作
![image](https://github.com/MCSManager/MCSManager/assets/92018941/d41b631c-a6c7-4cea-a3a5-f728292d7363)

**Comment by unitwk** [comment]
开放服务器的 24444 端口，如果是 frp 则需要两条隧道。

**Comment by alazeprt** [comment]
解决了
