### ISSUE TITLE
MCSM10无法终止实例运行

### ISSUE THREAD

**Issue by alazeprt** [MCSManager/MCSManager#1126]
**MCSManager Version**
10.0.1

**System Info/Version**
#167~18.04.1-Ubuntu SMP Wed May 24 00:51:42 UTC 2023 5.4.0-150-generic

**Node Version**
v14.19.1

**Step**
1. 创建一个java版实例，往里面放入mohist-1.20.1的端
2. 游玩过程中服务器未响应
3. 点击停止没有反应，后面点击终止仍然没有停止运行
![image](https://github.com/MCSManager/MCSManager/assets/92018941/fcf5a011-8b36-4138-8ea8-119467ae5fef)
*该图是点击终止操作若干次后的图片，仍然没有关闭成功

**Comment by unitwk** [comment]
节点的服务器是否已经 100% CPU 使用率？

**Comment by alazeprt** [comment]
CPU使用率不确定，服务器未响应就是玩家都连接超时，无法进入

**Comment by alazeprt** [comment]
这是日志
[2024-01-26-3.log](https://github.com/MCSManager/MCSManager/files/14063467/2024-01-26-3.log)
