### ISSUE TITLE
服务器重启后就用systemctl start mcsm-{web, daemon}打不开面板了

### ISSUE THREAD

**Issue by pueu** [MCSManager/MCSManager#1132]
系统：ESXI上的x64 Ubuntu server虚拟机
我是用指令一键安装的mcsmanager，刚安装完可以正常使用，重启后输入systemctl start mcsm-{web, daemon} 
显示Failed to start daemon\x7d.service: Unit daemon\x7d.service not found. 手动添加后也没用

**Comment by huangsijun17** [comment]
你命令输错了吧。daemon\x7d.service中的\x7d是`}`转码。你这明显是`,`后面多打了一个空格……

**Comment by pueu** [comment]
> 你命令输错了吧。daemon\x7d.service中的\x7d是`}`转码。你这明显是`,`后面多打了一个空格，变成了`systemctl start mcsm-{web,` 和`systemctl start daemon}`

额...好像真是，谢谢
