### ISSUE TITLE
Annoying bug with console and docker

### ISSUE THREAD

**Issue by qtqgyt** [MCSManager/MCSManager#1133]
**MCSManager Version**
9.9?

**System Info/Version**
win 10
**Node Version**
18
**Step**
1. switch instances to docker mode
2. u cant type any commands in console
3. done

**Comment by huangsijun17** [comment]
Docker-Desktop support is not currently provided. Personally suggest checking the terminal encoding

**Comment by unitwk** [comment]
Only supports Linux version of Docker

**Comment by qtqgyt** [comment]
Oh, thanks. Nevermind I guess...
