### ISSUE TITLE
Is there a way to limit RAM?

### ISSUE THREAD

**Issue by TheCynn** [MCSManager/MCSManager#1134]
As in the title. My server always restarts because the RAM is full load. Is there no way to limit the server RAM?

**Comment by Bluemangoo** [comment]
limit what? ask your game.

for example, for minecraft, use `-Xmx 1G` to limit minecraft(exactly jvm) ram usage.

**Comment by TheCynn** [comment]
> limit what? ask your game.
> 
> for example, for minecraft, use `-Xmx 1G` to limit minecraft(exactly jvm) ram usage.

i know i limit my ram to 7G but yeah that not working. and i checking docker thats exactly like i want but thats always generated error

**Comment by Bluemangoo** [comment]
do not ask here. it's not our problem.

**Comment by TheCynn** [comment]
![Uploading image.png…]()
emm this?

**Comment by TheCynn** [comment]
![image](https://github.com/MCSManager/MCSManager/assets/108793564/95f24980-7914-4ef7-87b9-e9b412e9712e)

**Comment by TheCynn** [comment]
ahh. my fault. Sorry, it turns out I just need to install Docker as usual
