### ISSUE TITLE
无法启动node项目，提示“容器启动失败（PID 为空）”

### ISSUE THREAD

**Issue by XiaohCeale** [MCSManager/MCSManager#1135]
无法启动node项目，提示：
```
[MCSMANAGER] [ERROR] 检测到实例进程/容器启动失败（PID 为空），其可能的原因是：
1. 实例启动命令编写错误，请前往实例设置界面检查启动命令与参数。
2. 系统主机环境不正确或缺少环境，如 Java 环境等。
```
启动命令为`node run start`，*package.json*中，*start*对应命令为`node ./index.js`
已为*./index.js*设置777权限，直接运行`node .index.js`与`npm run start`报错相同
使用ssh连接服务器后在相同目录下直接使用`npm run start`则可以运行成功

尝试过重启Daemon端，没有效果

---

系统：Ubuntu 20.04，
MCSM：Web：9.9.0，Daemon：3.4.0，使用安装脚本安装
nodejs：20.11.0，使用nvm安装
运行的项目为[LX Msuic Sync Server](https://github.com/lyswhut/lx-music-sync-server)

**Comment by Bluemangoo** [comment]
1. 使用 `node xxx` 不需要给excute权限，只需要read就够了。
2. 尝试填写完整node路径。mcsm对于环境path变量识别有点问题，目前bug未知，不是第一次出问题了。

**Comment by XiaohCeale** [comment]
将启动命令改为`/root/.nvm/versions/node/v20.11.0/bin/npm run start`，报错*/usr/bin/env: ‘node’: No such file or directory*，在ssh连接后使用该命令可成功启动

**Comment by Bluemangoo** [comment]
用node，不要套npm。

**Comment by XiaohCeale** [comment]
好的，已解决。非常感谢！
