### ISSUE TITLE
面板安装后启动出错

### ISSUE THREAD

**Issue by Guyao146** [MCSManager/MCSManager#1136]
**MCSManager Version**
3.4.0
**System Info/Version**
Ubuntu 22.10
**Node Version**
12.22.9
**Step**
![Screenshot_2024-02-06-01-23-49-830_com sonelli juicessh](https://github.com/MCSManager/MCSManager/assets/61780021/4e1cde0c-f11a-432b-be5c-01dbda63c9cf)

**Comment by unitwk** [comment]
![image](https://github.com/MCSManager/MCSManager/assets/18360009/1bcc12d0-6c1d-45cd-afea-9d3bb7b51c72)

端口被占用

**Comment by Guyao146** [comment]
> ![image](https://private-user-images.githubusercontent.com/18360009/302486489-1bcc12d0-6c1d-45cd-afea-9d3bb7b51c72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxOTY1MzYsIm5iZiI6MTcwNzE5NjIzNiwicGF0aCI6Ii8xODM2MDAwOS8zMDI0ODY0ODktMWJjYzEyZDAtNmMxZC00NWNkLWFmZWEtOWQzYmI3YjUxYzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDA1MTAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNjUyYjQ5ZDE2MWQyZDExNDI0NWVmMDE0MWY1Nzg2ZTc0Njc3NmNjZjY1MDMwY2JjMWFiYWFkNzg4NGNkNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uMfx00WABc1lJeSAXNvEzbCrZvds-9dJg99B_joys_M)
> 
> 端口被占用

感谢你的回复，但是我在解决端口占用后仍显示
![image](https://github.com/MCSManager/MCSManager/assets/61780021/4d4a9d2d-506d-4f3a-bd0a-3014eff9a1cc)
是在启动了守护进程后启动面板进程时显示的报错

**Comment by Guyao146** [comment]
本人推测是否是未将node升级到14以上的版本而导致的适配符显示错误

**Comment by Bluemangoo** [comment]
可选链表达式，升级node吧。

**Comment by Guyao146** [comment]
> 可选链表达式，升级node吧。

谢谢你的回复，直接在环境里升级node即可吧

**Comment by Guyao146** [comment]
如果这么说的话，是不是gitee上的一键安装脚本有问题啊，因为安装的时候我是用gitee上的一键脚本安装的

**Comment by Bluemangoo** [comment]
对。把path里面的node升到14+就行了。

**Comment by Guyao146** [comment]
ok，已经全部解决并开服了，感谢大佬们
