### ISSUE TITLE
Terminal Theme Support

### ISSUE THREAD

**Issue by BuDingOwO** [MCSManager/MCSManager#1138]
Likes WindowsTerminal
* Font selection (Recommended built-in some font as [Jetbrains Mono](https://www.jetbrains.com/lp/mono/))
* Highlight Theme (Such as [OneHalf](https://github.com/sonph/onehalf))
* Site Theme

**Comment by Bluemangoo** [comment]
terminal哪来的外部highlight，那个外部highlight就是个废选项。把pty开起来，那个颜色是cli给的ansi控制的颜色，不由mcsm控制。

**Comment by unitwk** [comment]
> terminal哪来的外部highlight，那个外部highlight就是个废选项。把pty开起来，那个颜色是cli给的ansi控制的颜色，不由mcsm控制。

你应该使用正常的语气给别人解释原因，并不是每个人都懂 Terminal 的颜色原理，而不是直接用“怼人”的语气给别人解释。
