### ISSUE TITLE
Terminal Ctrl+C Support

### ISSUE THREAD

**Issue by BuDingOwO** [MCSManager/MCSManager#1139]
Sometimes when I want to copy text, I subconsciously press Ctrl C, but this causes the program to terminate.

When no character is selected, Ctrl C executes [Interrupt a running program]
When some characters are selected, Ctrl C executes [Copy selected characters]

In WindowsTerminal, when selecting text, copy it instead of terminating the program.

**Comment by thedarkcr0w** [comment]
The terminal is a linux terminal to copy something you do ctrl shift c
and ctrl shift v to paste
