### ISSUE TITLE
Refresh Instanceconfigs after manual Change

### ISSUE THREAD

**Issue by ironflipper** [MCSManager/MCSManager#1140]
Hi,
I made a script which changes the InstanceConfig of a Server directly in the .json file.
The problem is that the webserver doesn't recognize the change in the file. I'd need to restart the daemon service for the webserver to recognize it, but that would close all servers.
Is there any solution to this problem?
![image](https://github.com/MCSManager/MCSManager/assets/92023913/98104f29-16ad-4c7e-abc0-7379015b1882)
![image](https://github.com/MCSManager/MCSManager/assets/92023913/48d59328-be4f-4ce8-8958-01f70963dd3c)

**Comment by unitwk** [comment]
You can join the Discord discussion: https://discord.gg/9UgPGDFH
