### ISSUE TITLE
How to setup multiple servers / nodes under one network with ssl?

### ISSUE THREAD

**Issue by thedarkcr0w** [MCSManager/MCSManager#1145]
I have 2 servers running under same network and I made ssl work with this configuration 
```
http {
    ssl_certificate "/etc/nginx/ssl/cert.pem";
    ssl_certificate_key "/etc/nginx/ssl/key.pem";
    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout  10m;
    gzip on;
    gzip_types text/plain text/css application/javascript application/xml application/json;
    gzip_proxied any;
    gzip_comp_level 5;
    gzip_min_length 1k;
    server_tokens  off;
    client_max_body_size 0;
    
    server {
        listen 80;
        listen [::]:80;
        server_name domainhere;

        return 302 https://$server_name$request_uri;
    }

    server {
        listen 127.0.0.1:443 ;
        listen [::1]:443 ;
        server_name localhost;
        gzip off;
        location / {
            proxy_pass http://localhost:24444;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            add_header X-Cache $upstream_cache_status;
            expires -1;
        }
    }

    server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name domainhere;

        location ~ (^/socket.io/)|(^/upload/)|(^/download/) {
            proxy_pass http://localhost:24444 ;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        add_header X-Cache $upstream_cache_status;
            expires -1;
        }
        location / {
            proxy_pass http://localhost:23333 ;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            add_header X-Cache $upstream_cache_status;
            expires -1;
        }
    }

}
```

Now everything is working for the server #1, but what would i do to make the other server work. The current port for that other server is 24445 and I tried reverse proxying it to 8443 but it doesnt work. 

Also I paid support on your [](https://afdian.net/) page but i cant log into the group because QQ is chinese only and creating account on it is almost impossible. Could we have a telegram group for supporters? I want to test the new versions on english not chinese website. Thanks!

**Comment by thedarkcr0w** [comment]
![chrome_EI6V3coXgj](https://github.com/MCSManager/MCSManager/assets/100016905/f3f86990-9253-4d4c-9a7c-188badbc3736)
![chrome_IT2ZOkTyh6](https://github.com/MCSManager/MCSManager/assets/100016905/c79008fe-a383-468e-a6ba-d8865a570a7f)

**Comment by thedarkcr0w** [comment]
Update i set up 2 panels one on one machine with port 443 and one on the other with port 8443
both are ssl and both are working in ssl daemons and everything but i cant add both daemons to a single panel.

**Comment by thedarkcr0w** [comment]
![chrome_D20YtmBMi3](https://github.com/MCSManager/MCSManager/assets/100016905/6db7f2eb-d838-4553-bc66-3921e1147b68)
![chrome_dVWEqlRvRZ](https://github.com/MCSManager/MCSManager/assets/100016905/5731483f-d334-42b2-bc64-f788d1c4c58a)

**Comment by thedarkcr0w** [comment]
![chrome_eMMrYeZLeW](https://github.com/MCSManager/MCSManager/assets/100016905/3ffc02a3-cbb5-4bbb-96da-8f6b4c6d5580)

**Comment by thedarkcr0w** [comment]
it makes no sense

**Comment by huangsijun17** [comment]
The web side of MCSM does not support handshakes with the daemon side that is not the root directory. You can backend different daemons to different ports.

**Comment by thedarkcr0w** [comment]
Wdym backend different daemons to different ports, they are running on two different ports?

**Comment by thedarkcr0w** [comment]
How would I go around to connect another machine as another daemon to my panel then?

**Comment by huangsijun17** [comment]
The problem now is that filling in host:port/path on the web side will cause the program to be unable to correctly resolve the host and port, and the path cannot be included in communication.
You need to reverse proxy different daemons to the root directories of different ports.

**Comment by thedarkcr0w** [comment]
And how do i do that?

**Comment by huangsijun17** [comment]
My suggestion is to allocate an independent port for each daemon.

**Comment by thedarkcr0w** [comment]
But i have one is hosted on 24444 and the other on 24445 thats not the issue. I can't get the panel to recognize the one thats on 24445 --> 8443. Its ssl and it works in the browser i have the image above but the web ui doesnt see it

**Comment by thedarkcr0w** [comment]
How do i make the panel recognize the second machine? wss://domain:8443 works in browser and shows up as daemon but panel reports it as offline

**Comment by huangsijun17** [comment]
Is your router's port forwarding loopback disabled?

**Comment by thedarkcr0w** [comment]
I sent the picture above, its accessible. My router doesn't have that option at all, its simply porforwarded as it should be

**Comment by thedarkcr0w** [comment]
If anyone has an idea on how to figure this out it would be great

**Comment by unitwk** [comment]
It may be because you are using an intranet IP. Please do not use IPs such as `192.168.X.X`.

![image](https://github.com/MCSManager/MCSManager/assets/18360009/4990bd07-66ff-4fca-86e1-e17d3f5858fc)

**Comment by Bluemangoo** [comment]
- We use `$ip1` to refer to the internal ip of the one that works well(i mean, the main server, referred to as `machine1`).
- Use `$ip2` to refer to the ip of another one(referred to as `machine2`).
- Use `$domain` to refer to your domain.

## Let's check some details first

- [x] For both machine, panel works on `port 23333` and daemon works on `port 24444`.
- [x] For machine1, you have setup nginx.
- [x] You can use `ip1[:443]` and `ip2[:443]` to connect to each panel.
- [x] You want to proxy the daemon on machine2 to `ip1:8443`.
- [x] You can connect to `http://ip2:23333` (no ssl).

## Here we go

Add a server block in the nginx config of machine1, don't forget to fill your real `ip2` and `$domain`:

```conf
server {
        listen 8443 ssl http2;
        listen [::]:8443 ssl http2;
        server_name $domain;

        location / {
            proxy_pass http://$ip2:23333 ;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            add_header X-Cache $upstream_cache_status;
            expires -1;
        }
    }
```

Then try to open `https://$domain:8443` to check if the proxy works well.

If yes, add a daemon on the panel on machine1, ip `wss://$domain`, port `8443`. Check if this works.

## By the way

By the way, i wonder how did you proxy the backend to `/#/service`. I mean, it seems impossible to proxy anything to a path contains `#`.

I'm not native English speaker. Forgive my grammar mistakes.

**Comment by Bluemangoo** [comment]
we haven't had a telegram group yep. but we do have a discord channel: https://discord.com/invite/9UgPGDFH

**Comment by unitwk** [comment]
He is already in the Discord channel and the issue has been resolved
