### ISSUE TITLE
启动命令为docker start donotstarve时发生闪退

### ISSUE THREAD

**Issue by Deemo119** [MCSManager/MCSManager#1150]
已经使用docker搭建了饥荒服务器，
docker run --name donotstarve -v /opt/mcsmanager/daemon/data/InstanceData/123456789:/data -p 10999-11000:10999-11000/udp -p 12346-12347:12346-12347/udp -it jamesits/dst-server:latest
现在想要将控制台启动命令设置为
docker start donotstarve && docker logs -f donotstarve
以便于管理和查看输出命令，但是出现了闪退，请问有可能实现该功能吗
因为启动命令为下文时，终端是可以显示日志输出的
docker run --name donotstarve -v /opt/mcsmanager/daemon/data/InstanceData/123456789:/data -p 10999-11000:10999-11000/udp -p 12346-12347:12346-12347/udp -it jamesits/dst-server:latest
感谢作者

**Comment by unitwk** [comment]
已在QQ联系
