### ISSUE TITLE
关于批量管理的一些疑问

### ISSUE THREAD

**Issue by xiao9jun** [MCSManager/MCSManager#1152]
![{CB67F067-926A-4f4a-8A06-EC30146DE9B2}](https://github.com/MCSManager/MCSManager/assets/49909552/fedc5a6d-51b2-421e-bb65-4682d653dc61)
我希望对不同网段的实例进行批量操作，比如同时开启、关闭等，但是在管理员的批量视图中，无法在同一个页面查看到不同网段的实例
![{1AAF8DCF-6684-4c39-868A-9DF105F08950}](https://github.com/MCSManager/MCSManager/assets/49909552/c874fc85-8612-4080-8b59-fd718ab47af3)
需要手动切换不同网段来查看，然后我尝试分配给一个普通用户的账号中，好消息是，能全部查看到！
![{CDB574F0-0605-47e9-B134-F4319CDC7601}](https://github.com/MCSManager/MCSManager/assets/49909552/19921528-9523-49f5-9a9e-318cfd92d9f9)
坏消息是，没有批量开启/关闭之类的功能.....
我应该怎么才能做到不同网段的远程主机批量管理呢....

**Comment by unitwk** [comment]
抱歉，暂时不支持你所想的这种功能

**Comment by xiao9jun** [comment]
> 抱歉，暂时不支持你所想的这种功能

😭好吧
