### ISSUE TITLE
官方全新下载的压缩包中，start.bat路径有误

### ISSUE THREAD

**Issue by xiao9jun** [MCSManager/MCSManager#1153]
**MCSManager Version**
none
**System Info/Version**
none
**Node Version**
none
**Step**
![{45210D18-8771-4baa-986E-0C5064D1B32F}](https://github.com/MCSManager/MCSManager/assets/49909552/e74bde69-f44b-4ba6-b06d-d2f227264a96)
官方全新下载的包中，路径如图，第一行更改为cd mcsmanager\daemon 时，start.bat才能正确运行
![{FADFED15-9235-4d17-A9CB-DED1E2FF0F1A}](https://github.com/MCSManager/MCSManager/assets/49909552/401ef547-f43d-4572-aa24-154ad21cddc8)

**Comment by unitwk** [comment]
Fixed
