### ISSUE TITLE
在通过MCSM启动Docker时，Dockerfiles的用户指定失效，强制以root身份运行

### ISSUE THREAD

**Issue by huangsijun17** [MCSManager/MCSManager#1157]
**MCSManager Version**
9.9.0/3.4.0
**System Info/Version**
any linux/Docker version 25.0.4, build 1a576c5
**Node Version**
v20.11.0
**Step**
MCSM中启动命令改为bash，执行id命令，Docker内的用户为root。
使用`docker run`手动执行该镜像，用户id为制定的2000

**Comment by unitwk** [comment]
估计可能是这一行的问题，https://github.com/MCSManager/Daemon/blob/master/src/entity/commands/docker/docker_start.ts#L208

我怎么记得这一行是你加的，那我删除掉它吧，很Docker内部用户有关系的也只有这个参数了。

**Comment by huangsijun17** [comment]
> 估计可能是这一行的问题，https://github.com/MCSManager/Daemon/blob/master/src/entity/commands/docker/docker_start.ts#L208
> 
> 我怎么记得这一行是你加的，那我删除掉它吧，和Docker内部用户有关系的也只有这个参数了。

看了一下，是我跑MCSM的Docker-Compose里的用户没改。现在MCSM里的Docker是继承了MCSM的root用户。

**Comment by unitwk** [comment]
> > 估计可能是这一行的问题，https://github.com/MCSManager/Daemon/blob/master/src/entity/commands/docker/docker_start.ts#L208
> > 我怎么记得这一行是你加的，那我删除掉它吧，和Docker内部用户有关系的也只有这个参数了。
> 
> 看了一下，是我跑MCSM的Docker-Compose里的用户没改。现在MCSM里的Docker是继承了MCSM的root用户。

那我这行代码你觉得还需要删除吗？

**Comment by huangsijun17** [comment]
> > > 估计可能是这一行的问题，https://github.com/MCSManager/Daemon/blob/master/src/entity/commands/docker/docker_start.ts#L208
> > > 我怎么记得这一行是你加的，那我删除掉它吧，和Docker内部用户有关系的也只有这个参数了。
> > 
> > 
> > 看了一下，是我跑MCSM的Docker-Compose里的用户没改。现在MCSM里的Docker是继承了MCSM的root用户。
> 
> 那我这行代码你觉得还需要删除吗？

留着吧。
