### ISSUE TITLE
添加一个动画效果开关的按钮，弱网络下动画效果疑似导致卡加载

### ISSUE THREAD

**Issue by Seanboos667** [MCSManager/MCSManager#1159]
建议增加一个动画效果开关，用户自己选择动画效果开还是关。

**Comment by unitwk** [comment]
哪个页面的动画，能否提供截图和录屏

**Comment by yuyuko233** [comment]
一般跟动画效果没关系的, 一直卡在加载要么是 bug, 要么是确实在加载, 去掉动画效果也是卡着, 并且还不知道状态
