### ISSUE TITLE
无法进入面板

### ISSUE THREAD

**Issue by daxiangzi166** [MCSManager/MCSManager#1161]
**MCSManager Version**
最新版
**System Info/Version**
Ubuntu22.04

**Node Version**
14.19.1

**Step**
安装完成后没输出用户名和密码，在删除User文件夹后重新安装依旧无法进入面板
帮助中的默认密码以及用户名试过了

**Comment by unitwk** [comment]
最新版没有默认账号密码，不知道你用的是什么版本。
