### ISSUE TITLE
希望添加实例资源使用统计

### ISSUE THREAD

**Issue by 3414769627** [MCSManager/MCSManager#1162]
希望添加实例资源使用统计
如标题，加入资源统计，比如:**工作目录存储占用，实例程序内存占用，实例程序内存占用，实例网络流量统计，实例进程数量统计**
这些功能可以帮助系统管理员高效的对服务器进行维护排错

**此外我还有一个问题**:实例是否支持**自定义备注**？我并没有找到相关功能，唯一一个可能的：实例概览页面有一个其他信息，但是我没找到能定义其内容的方法

如开发者看到了望回复一下，谢谢

**Comment by unitwk** [comment]
1. 我们需要考虑 Windows ，Linux，以及有无 Docker 等各种环境，所以你希望的 `工作目录存储占用，实例程序内存占用，实例程序内存占用，实例网络流量统计，实例进程数量统计` 这些功能都无法在跨平台上有一个很好的方案，短期内难以实现。

2. 自定义备注不支持，后续可能会推出 tag 标签功能，用于分类。

**Comment by unitwk** [comment]
1. 我们需要考虑 Windows ，Linux，以及有无 Docker 等各种环境，所以你希望的 `工作目录存储占用，实例程序内存占用，实例程序内存占用，实例网络流量统计，实例进程数量统计` 这些功能都无法在跨平台上有一个很好的方案，短期内难以实现。

2. 自定义备注不支持，后续可能会推出 tag 标签功能，用于分类。
