### ISSUE TITLE
群晖反向代理 节点不成功

### ISSUE THREAD

**Issue by HelIwalker** [MCSManager/MCSManager#1170]
群晖反向代理面板可以访问，但是连接不上节点，节点直接在浏览器打开地址显示状态正常，websocket添加了，搞不清楚原因在哪里
![643E9DD86A36D52EC4A2C386C8058555](https://github.com/MCSManager/MCSManager/assets/19471848/820d99d9-f75c-4b6d-ba2e-1ea18bd19197)
![05D208E4D1DB5811AC5E6E878A3C8044](https://github.com/MCSManager/MCSManager/assets/19471848/f6c1de48-0a39-46c1-93bc-04bd3db4ef39)
![24F70A30394EED03096E3CA4456A0B74](https://github.com/MCSManager/MCSManager/assets/19471848/facc12a7-1c3a-4eaa-b4fc-6b4718ea7076)

**Comment by unitwk** [comment]
从这两张截图里面我也看不出是什么原因，你只能参考这份资料来研究：https://docs.mcsmanager.com/zh_cn/ops/proxy_https.html

**Comment by kingsznhone** [comment]
#1204 感觉应该是同样的问题

**Comment by LsrlYrsc** [comment]
启动web的服务器会尝试主动连接对应deamon节点才能实现在''节点''列表显示''在线''的状态
我认为你的服务器是类似于''家里云''的网络情况，无法直接通过公网访问
解决办法是给服务器修改HOST，填写本地IP和对应域名

**Comment by LsrlYrsc** [comment]
公网主机无法直接访问自身公网，我建议你配置HOST文件（我认为很大程度是这个原因）
在HOST文件的示例:
127.0.0.1 name.domain

mcsm-web的进程会首先主动访问deamon获取其状态和实例列表才会在面板显示，这与用户的浏览器无关

诊断办法:
1.使用另一台公网服务器使用ssl转发mcsm-deamon的端口，然后让本地具备ssl的web进行节点连接
2.在另一台服务器配置一个具备ssl的mcsm-web的来主动连接对象deamon节点
(离线状态与是否使用ssl只有ws://和wss://的配置关系，与配置无关)

注意:web和deamon两者之一是配置过ssl就必须全部都配置ssl，不然无法访问
目测应该与#1204的问题一样
