### ISSUE TITLE
MCSManager运行nginx存在显示实例退出但进程还在的问题

### ISSUE THREAD

**Issue by rootber** [MCSManager/MCSManager#1180]
![image](https://github.com/MCSManager/MCSManager/assets/122451668/d4df7208-e8ae-4dc2-8adc-2bbc1e0a7403)
![image](https://github.com/MCSManager/MCSManager/assets/122451668/1d68d99b-7d5b-4a60-a990-4486d9247eb8)
本来是想用MCSM管理nginx的更方便的结果总是显示实例已退出

**Comment by Bluemangoo** [comment]
nginx要daemon off。

**Comment by Bluemangoo** [comment]
补充一下，把运行命令改成 `nginx -g "daemon off;"` 。

**Comment by rootber** [comment]
> 补充一下，把运行命令改成 `nginx -g "daemon off;"` 。

没问题了，多谢

**Comment by Bluemangoo** [comment]
close吧。
