### ISSUE TITLE
应用实例没有汉化

### ISSUE THREAD

**Issue by Whirity404** [MCSManager/MCSManager#1181]
![Screenshot_20240406_211238_edit_588781185913572](https://github.com/MCSManager/MCSManager/assets/123949450/fc0b5c03-450b-46d0-aad9-a4dd060de5b3)

设置页面的实例类型没有汉化，旧版是有的

**Comment by alongw** [comment]
这个要怎么汉化....
水龙头？高性能叉？蹦极？速度城市？？？？

**Comment by huangsijun17** [comment]
“Minecraft Manager”还没汉化呢。建议先帮忙把软件名汉化一下。
