### ISSUE TITLE
Nginx 尝试反代 MCSM 到网站子目录发生错误

### ISSUE THREAD

**Issue by Mooling0602** [MCSManager/MCSManager#1183]
Nginx 配置如图：
![屏幕截图_20240407_234409](https://github.com/MCSManager/MCSManager/assets/147964268/0b3ebf96-dd0c-4e5e-a608-101865682163)
进入网站后的报错如图：
![屏幕截图_20240407_234507](https://github.com/MCSManager/MCSManager/assets/147964268/7429084f-be9c-4319-9776-eeac2169ac3a)
备注：没有测试过直接绑定到域名上的情况

**Comment by HappyMC-Dev** [comment]
可以参考一下我的
```
location ^~ / {
    proxy_pass http://127.0.0.1:23332; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header X-Cache $upstream_cache_status; 
    add_header Cache-Control no-cache; 
    add_header Strict-Transport-Security "max-age=31536000"; 
}
```

**Comment by Bluemangoo** [comment]
不支持这样有路径前缀的反代。

**Comment by Mooling0602** [comment]
> 不支持这样有路径前缀的反代。

后续能得到支持吗

**Comment by unitwk** [comment]
> > 不支持这样有路径前缀的反代。
> 
> 后续能得到支持吗

应该不能，老代码太多了，为了这个功能改动量可能会有点多吧

**Comment by Bluemangoo** [comment]
May be resolved in #1187. Require tests and feedback [here (with guide)](https://github.com/MCSManager/MCSManager/pull/1187#issuecomment-2042212475).

可能在 #1187 中被解决。[这里](https://github.com/MCSManager/MCSManager/pull/1187#issuecomment-2042212475)要一点测试和反馈（含教程）。

**Comment by Mooling0602** [comment]
> May be resolved in #1187. Require tests and feedback [here (with guide)](https://github.com/MCSManager/MCSManager/pull/1187#issuecomment-2042212475).
> 
> 可能在 #1187 中被解决。[这里](https://github.com/MCSManager/MCSManager/pull/1187#issuecomment-2042212475)要一点测试和反馈（含教程）。

10.2.1修复了吗，我刚装完好像还是一样的情况。

**Comment by Mooling0602** [comment]
> May be resolved in #1187. Require tests and feedback [here (with guide)](https://github.com/MCSManager/MCSManager/pull/1187#issuecomment-2042212475).
> 
> 可能在 #1187 中被解决。[这里](https://github.com/MCSManager/MCSManager/pull/1187#issuecomment-2042212475)要一点测试和反馈（含教程）。

找到了这个：
https://github.com/MCSManager/Documentation/blob/main/zh_cn/ops/path_prefix.md
有个小问题，登录进面板后的首页点击左上角的管理面板会直接进入域名的根目录，在我的配置下根域名是CMS服务，就直接跳转到那边去了
另外上传背景图片后不显示，不知道是什么问题

**Comment by Bluemangoo** [comment]
好像有人修掉了来着。

**Comment by Bluemangoo** [comment]
> 另外上传背景图片后不显示，不知道是什么问题

这个可能是的。

**Comment by Mooling0602** [comment]
![image](https://github.com/MCSManager/MCSManager/assets/147964268/8ffa13e0-d3c7-4e5f-9f1d-77f2c1fffca9)
反代还是有点问题，使用URL跳转的按钮点下去会直接回到主站并离开MCSM，建议reopen此issue @unitwk 
> 声明：图片仅供反馈交流使用，为方便项目开发者定位问题没有对网站地址进行遮盖或打码，域名已备案，站点仅作个人分享和后台管理使用，若有人恶意攻击我的服务器和网站，我必将采取一切合理合法的途径追究到底

**Comment by Bluemangoo** [comment]
- #1226 已经修掉了，是不是因为没发布/更新版本。 @unitwk

**Comment by Mooling0602** [comment]
> ![image](https://private-user-images.githubusercontent.com/147964268/342056128-8ffa13e0-d3c7-4e5f-9f1d-77f2c1fffca9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNTE0NzcsIm5iZiI6MTcyMjA1MTE3NywicGF0aCI6Ii8xNDc5NjQyNjgvMzQyMDU2MTI4LThmZmExM2UwLWQzYzctNGU1Zi05ZjFkLTc3ZjJjMWZmZmNhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwMzMyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDFjMzNkNDM2NTAyM2FiMzFlY2JhMTM2MWYzODQ0YTBmNjU0ZDEwMGU4OWI4MmM1MmFhOGM4NTYxOWM1NzliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jKLiPCfpLFsWWEO3vEAnfGSW_N3o9O_yIynIq_qrWwU) 反代还是有点问题，使用URL跳转的按钮点下去会直接回到主站并离开MCSM，建议reopen此issue @unitwk
> 
> > 声明：图片仅供反馈交流使用，为方便项目开发者定位问题没有对网站地址进行遮盖或打码，域名已备案，站点仅作个人分享和后台管理使用，若有人恶意攻击我的服务器和网站，我必将采取一切合理合法的途径追究到底

今日尝试用一键脚本更新后，bug 仍然存在；
守护进程节点没有使用子目录代理也没有设置前缀，仅 web 端的 mcsm 使用了子目录
