### ISSUE TITLE
对于文件管理搜索逻辑的建议

### ISSUE THREAD

**Issue by SeemWind** [MCSManager/MCSManager#1188]
当用户进入文件管理，进行这样一个操作，搜索目录名字→点击进入目录，此时搜索框仍然会生效并过滤目录内的内容，容易使用户误解目录内没有其他已经被过滤掉的文件，或者误解为目录为空。

建议增加一个设置，控制切换目录之后是否自动清空搜索栏。以及在搜索栏创建一个清空按键。
![image](https://github.com/MCSManager/MCSManager/assets/50366675/d5ecd276-c4b6-46dc-92c3-02c6a4bee878)

此外，目前路径栏不支持手动填写、复制粘贴，期待后续可以实现
![image](https://github.com/MCSManager/MCSManager/assets/50366675/3bb9e299-7d53-40b1-880d-ade46f43cfe5)

**Comment by LazyCreeper** [comment]
已修复
