### ISSUE TITLE
[Bug Report] 仿真终端模式下无法使用相对路径启动实例

### ISSUE THREAD

**Issue by kazuhaAyato** [MCSManager/MCSManager#1194]
### Platform

Debian 10

### Panel Version

10.1.0

### Daemon Version (Optional)

最新的

### Recurrence Probability

100%

### Bug Description

![image](https://github.com/MCSManager/MCSManager/assets/66939153/10246461-33c3-4c66-a7b7-4639b55cfc18)
当开启仿真终端时，没有办法使用./start.sh这样的启动实例。
关闭是可以启动的.
但使用绝对路径可以启动。

**Comment by unitwk** [comment]
如果使用 `sh ./start.sh` 昵？

**Comment by kazuhaAyato** [comment]
这个可以
