### ISSUE TITLE
[Feature] 能否删除或者缩短设置界面的margin-top

### ISSUE THREAD

**Issue by eya46** [MCSManager/MCSManager#1196]
### Description

![image](https://github.com/MCSManager/MCSManager/assets/61458340/783f0912-0c75-4345-9842-19d269aa3c8d)

### Reason

感觉怪怪的

**Comment by unitwk** [comment]
你新增一个空白卡片到底部就行了，当一个页面只有一个卡片时，它默认时居中的。

**Comment by eya46** [comment]
神医，解决了
