### ISSUE TITLE
[Bug Report]  Unable to start Minecraft Forge Servers

### ISSUE THREAD

**Issue by deinehardware** [MCSManager/MCSManager#1197]
### Platform

Ubuntu 23

### Panel Version

latest

### Daemon Version (Optional)

latest

### Recurrence Probability

100%

### Bug Description

Unable to start Minecraft Forge Server with default start command. Even when i was using the recomended startup command from forge is dont work.

Start Command 1:
java -jar forge-1.20.4-49.0.48-shim.jar --onlyCheckJava || exit 1

# Add custom program arguments (such as nogui) to the next line before the "$@" or pass them to this script directly
java @libraries/net/minecraftforge/forge/1.20.4-49.0.48/unix_args.txt "$@"

------------------------------------
Start Command 2:
java @libraries/net/minecraftforge/forge/1.20.4-49.0.48/forge-1.20.4-49.0.48-shim.jar  -jar forge-1.20.4-49.0.48-shim.jar --onlyCheckJava  nogui

------------------------------------

Error
[INFO] Preparing to start...
[INFO] Emulated terminal mode is active. You can directly input content in the terminal and use Ctrl, Tab, and other function keys.
Error: Could not find or load main class PK
Caused by: java.lang.ClassNotFoundException: PK
[ERROR] The instance appears to have exited shortly after startup, which may be due to an incorrect launch command or configuration error.

**Comment by unitwk** [comment]
I guess it may be a permissions issue. Could you please try executing  `chmod -R 777 /opt/mcsmanager/daemon/lib`  and try starting the forge server again?

**Comment by unitwk** [comment]
<img width="1127" alt="image" src="https://github.com/MCSManager/MCSManager/assets/18360009/a4f18538-b07f-45ec-bb89-d73011acdd46">

I tested it on Ubuntu and it runs normally. I didn't find the problem you mentioned. Please check to restart your server or check the Java environment.

Or, change the path of the Java environment to /aaa/foo/java -jar xxx
