### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by ElainaTGBS** [MCSManager/MCSManager#1198]
### Platform

windows server 2022

### Panel Version

v10

### Recurrence Probability

100%

### Bug Description

网页终端的“前端颜色渲染”功能有问题：
当“跳转到其他页面”时再回到终端，终端的颜色将不会保存，但是继续输指令时，仍然有颜色。

-当然这是一个小问题，但是对于我们这些强迫症来说是个灾难

**Comment by ElainaTGBS** [comment]
初步判断是颜色信息仅仅在本次打开页面时进行渲染，当刷新或者跳转到其他页面时控制台已有的颜色舍弃，而不是重新渲染

**Comment by Bluemangoo** [comment]
都说了“前端颜色渲染”当然是网页临时渲染的。

**Comment by Bluemangoo** [comment]
你要是想要正常的可以把这项关掉，把仿真终端打开。
