### ISSUE TITLE
错误报告

### ISSUE THREAD

**Issue by Minecraft0122** [MCSManager/MCSManager#1202]
### Platform

#197-Ubuntu SMP Thu Mar 28 22:45:47 UTC 2024 5.4.0-177-generic

### Panel Version

10.1.0

### Recurrence Probability

100%

### Bug Description

拖动文件到文件管理时，弹出对话框会显示的文件，但是这个大小的单位应是KB而不是MB
![1](https://github.com/MCSManager/MCSManager/assets/168195378/937da5ae-d8ed-4095-8dd0-bdb4ea1d1a7a)
![Uploading 2.png…]()

**Comment by Bluemangoo** [comment]
有人提了，好像修了。

**Comment by unitwk** [comment]
Fixed
