### ISSUE TITLE
[Bug Report] 节点代理问题

### ISSUE THREAD

**Issue by kingsznhone** [MCSManager/MCSManager#1204]
### Platform

ubuntu 22.04

### Panel Version

10.1.0

### Daemon Version (Optional)

1.3.0

### Recurrence Probability

100%

### Bug Description

节点运行在::24444，Web运行在::23333.
根据官网文档写的反向代理教程，配置nginx反代节点到domain.com:12444，反代web到domain.com:12333
可以正常访问web，在web中连接的localhost节点成功，然后进入实例显示连接失败，
查看F12发现实例的wws请求发到了wss://domain.com:24444/socket.io

如果设置节点列表中的节点为domain.com:12444，则显示连接失败
![image](https://github.com/MCSManager/MCSManager/assets/35349300/f94fff55-658c-4e27-ab85-df5d2290f513)

**Comment by Bluemangoo** [comment]
本来就是发到wss://.../socket.io的。你是不是没给daemon配置ssl。

**Comment by LsrlYrsc** [comment]
web需要尝试连接deamon才能实现在''节点''列表显示''在线''的状态
我认为你的服务器是类似于''家里云''的网络情况，无法直接通过公网访问
解决办法是添加HOST文件，填写本地IP和对应域名

**Comment by kingsznhone** [comment]
> 本来就是发到wss://.../socket.io的。你是不是没给daemon配置ssl。

都配置ssl了，发的端口不对

**Comment by kingsznhone** [comment]
> 启动web的服务器会尝试主动连接对应deamon节点才能实现在''节点''列表显示''在线''的状态 我认为你的服务器是类似于''家里云''的网络情况，无法直接通过公网访问 解决办法是给服务器修改HOST，填写本地IP和对应域名

我的服务器是公网上的

**Comment by kingsznhone** [comment]
如果直接用浏览器打开被反代的domain.com:12444可以成功显示
[MCSManager Daemon] Status: OK | reference: https://mcsmanager.com/

**Comment by unitwk** [comment]
无法排查出是哪里出的问题，你只能参考文档：https://docs.mcsmanager.com/zh_cn/ops/proxy_https.html

**Comment by LsrlYrsc** [comment]
> > 启动web的服务器会尝试主动连接对应deamon节点才能实现在''节点''列表显示''在线''的状态 我认为你的服务器是类似于''家里云''的网络情况，无法直接通过公网访问 解决办法是给服务器修改HOST，填写本地IP和对应域名
> 
> 我的服务器是公网上的

公网主机无法访问自身公网，我建议你配置HOST文件（我认为很大程度是这个原因）
在HOST文件的示例:
127.0.0.1 name.domain

**Comment by kingsznhone** [comment]
> > > 启动web的服务器会尝试主动连接对应deamon节点才能实现在''节点''列表显示''在线''的状态 我认为你的服务器是类似于''家里云''的网络情况，无法直接通过公网访问 解决办法是给服务器修改HOST，填写本地IP和对应域名
> > 
> > 
> > 我的服务器是公网上的
> 
> 公网主机无法直接访问自身公网，我建议你配置HOST文件（我认为很大程度是这个原因） 在HOST文件的示例: 127.0.0.1 name.domain （这是给服务器主机设置的）
> 
> mcsm-web的进程会首先主动访问deamon获取其状态和实例列表才会在面板显示，这与用户的浏览器无关
> 
> 诊断办法: 1.使用另一台公网服务器使用ssl转发mcsm-deamon的端口，然后让本地具备ssl的web进行节点连接 2.在另一台服务器配置一个具备ssl的mcsm-web的来主动连接对象deamon节点 (离线状态与是否使用ssl只有ws://和wss://的配置关系，与配置无关)
> 
> 注意:web和deamon两者之一是配置过ssl就必须全部都配置ssl，不然无法访问 ~总不可能是兄弟没开放端口导致的吧~

问题解决了，虽然daemon和web运行在同一台电脑上，但不是网络和host的问题。
得在远程节点列表里手动点几下刷新节点。过个三十秒一分钟才能显示连接成功，不知道是哪里出问题了
