### ISSUE TITLE
[Bug Report] V10无法删除文件

### ISSUE THREAD

**Issue by Wagoodnight** [MCSManager/MCSManager#1209]
### Platform

Ubuntu 20.04 & 23.04

### Panel Version

10.1.0

### Daemon Version (Optional)

4.2.0

### Recurrence Probability

100

### Bug Description

慕名奇妙不能够删除文件了，删除一个1MB的小文件都做不到，我只能使用命令行删了。以一个1MB的小文件为例，系统刚刚重启过，现在我删除这个文件，
![image](https://github.com/MCSManager/MCSManager/assets/89726674/29348dc4-36da-419b-bd12-c68ed5710c10)
刷新之后还有，使用ls命令查看还是存在
![image](https://github.com/MCSManager/MCSManager/assets/89726674/15402a1b-eb4c-4838-8ab6-f51b5502e091)
MCSM我也使用官方的脚本重新安装过了（不是删除，而是直接运行一遍“升级”）
不清楚是我的问题还是什么，但是希望能够解决。

**Comment by huangsijun17** [comment]
MCSM的运行账户是root吗？文件归属又是哪个用户？

**Comment by Bluemangoo** [comment]
下一版修。早就修了只是没发版。

**Comment by Wagoodnight** [comment]
> MCSM的运行账户是root吗？文件归属又是哪个用户？

都是sudo -i然后装的MCSM，文件都是用MCSM上传的。况且权限777

**Comment by Wagoodnight** [comment]
> 下一版修。早就修了只是没发版。

好的谢啦
