### ISSUE TITLE
[Bug Report] 删除文件功能存在问题

### ISSUE THREAD

**Issue by alazeprt** [MCSManager/MCSManager#1211]
### Platform

Fedora 39

### Panel Version

10.1.0

### Daemon Version (Optional)

4.2.0

### Recurrence Probability

100%

### Bug Description

如视频所示，直接通过右侧操作栏删除文件无效，需要选中文件后通过右侧操作栏删除文件才可行
视频：https://github.com/MCSManager/MCSManager/assets/92018941/29d61cee-ca11-46f5-ab69-36b9b0d00d9b

**Comment by unitwk** [comment]
新版已修复。
