### ISSUE TITLE
[Bug Report] [Operation Error] 实例状态不正确，有其他任务正在运行中

### ISSUE THREAD

**Issue by LOVE2CMOL** [MCSManager/MCSManager#1212]
### Platform

debian12

### Panel Version

10.1.0

### Daemon Version (Optional)

4.2.0

### Recurrence Probability

100%

### Bug Description

点击更新按钮的时候出现 [Operation Error] 实例状态不正确，有其他任务正在运行中 提示 无法更新程序

旧版本3.x一直都可以 现在新版本就不行了

指令啥的都跟以前一样 

更新指令 sudo -u steam /home/steam/Steam/steamcmd.sh +force_install_dir /mnt/disk01/software/steam/PalworldServer +login anonymous +app_update 2394010 validate +quit
启动指令 sudo -u steam /mnt/disk01/software/steam/PalworldServer/PalServer.sh -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS EpicApp=PalServer

![image](https://github.com/MCSManager/MCSManager/assets/28857775/e072d969-d0b5-4e77-a47e-32fb3bc7a411)

日志
```
[05/09 01:56:18] [INFO] 会话 syVuHOBFFm9Qrq25AAAF 要求实例 9da4d2d05224458eb0b6c4e81dbfedc1 执行异步 update 异步任务
[05/09 01:56:18] [ERROR] 实例 9da4d2d05224458eb0b6c4e81dbfedc1 update 异步任务执行异常: Error: 实例状态不正确，有其他任务正在运行中
[05/09 02:11:05] [INFO] 会话 syVuHOBFFm9Qrq25AAAF 要求实例 9da4d2d05224458eb0b6c4e81dbfedc1 执行异步 update 异步任务
[05/09 02:11:05] [ERROR] 实例 9da4d2d05224458eb0b6c4e81dbfedc1 update 异步任务执行异常: Error: 实例状态不正确，有其他任务正在运行中
````
![image](https://github.com/MCSManager/MCSManager/assets/28857775/d699f414-e101-4117-8ee1-e1450a09c683)

![image](https://github.com/MCSManager/MCSManager/assets/28857775/a0e6cf73-823f-4d3c-8000-f55ef86b6f99)

![image](https://github.com/MCSManager/MCSManager/assets/28857775/d8dbc52f-95da-42c8-8ae4-aeecbd669f01)

![image](https://github.com/MCSManager/MCSManager/assets/28857775/ea5c7724-c076-47bf-9fff-210d3fe71b71)

**Comment by LOVE2CMOL** [comment]
![Screenshot_2024-05-08-17-58-03-121_tech lolli toolbox-edit](https://github.com/MCSManager/MCSManager/assets/28857775/3b1b5432-c805-4dae-bbe3-5654eaa9ad40)

**Comment by LOVE2CMOL** [comment]
![Uploading IMG_20240508_180040.jpg…]()
![IMG_20240508_180102](https://github.com/MCSManager/MCSManager/assets/28857775/30e25235-7f8e-4df6-b02b-d4c9a88290bf)

**Comment by LOVE2CMOL** [comment]
![Uploading IMG_20240508_180040.jpg…]()

**Comment by LOVE2CMOL** [comment]
![IMG_20240508_180040](https://github.com/MCSManager/MCSManager/assets/28857775/f8a7c80a-23cf-441f-a715-e5768fd93da2)

**Comment by unitwk** [comment]
已确定是是 10.1.0 版本的BUG，10.2版本已修复，正在等待发布。

**Comment by unitwk** [comment]
新版已修复。
