### ISSUE TITLE
[Bug Report] 启用docker容器，网络模式host时，启动mc服务器的报错

### ISSUE THREAD

**Issue by SeemWind** [MCSManager/MCSManager#1214]
### Platform

ubuntu 22.04

### Panel Version

10.1.0

### Recurrence Probability

100%

### Bug Description

如标题所述，启动paper服务端，出现如下报错

```
[org.eclipse.aether.internal.impl.synccontext.named.DiscriminatingNameMapper] Failed to get hostname, using 'localhost'
java.net.UnknownHostException: MCSM-5dc27b: MCSM-5dc27b: Name or service not known
```

**Comment by alazeprt** [comment]
服务器配置的ip地址有问题吧，看看server.properties

**Comment by SeemWind** [comment]
> 服务器配置的ip地址有问题吧，看看server.properties

是127.0.0.1，不能这么用吗

**Comment by SeemWind** [comment]
> 服务器配置的ip地址有问题吧，看看server.properties

似乎是 `/etc/hostname` 的地址没有被添加进 `/etc/hosts` 中的原因，但我不确定这是否是mcsm的问题

**Comment by kelegele** [comment]
大佬有解决办法吗
