### ISSUE TITLE
快速部署中的下载节点全部无法ping通

### ISSUE THREAD

**Issue by lizina66** [MCSManager/MCSManager#1220]
### Platform

ub20

### Panel Version

10.1

### Recurrence Probability

100%

### Bug Description

https://mcsmanager.oss-cn-guangzhou.aliyuncs.com/quick_install.json
中的所有下载节点在itdog中和实机操作中都是超时状态？赞助商跑啦？

**Comment by yuyuko233** [comment]
@alongw

**Comment by yuyuko233** [comment]
我还以为是我服务器网的问题 😂

**Comment by alongw** [comment]
> 我还以为是我服务器网的问题 😂

- 如果你在使用最新版本的 MCSManager ，请将预设链接修改为 `https://script.mcsmanager.com/templates.json` 
- 目前官方的下载源 （`oss.duzuii.com/MCSManager`）暂时出现问题，请等待修复
- 目前其他除官方下载源外其他下载链接的整合包均正常，请等待官方修复或使用其他整合包

**Comment by yuyuko233** [comment]
> > 我还以为是我服务器网的问题 😂
> 
>     * 如果你在使用最新版本的 MCSManager ，请将预设链接修改为 `https://script.mcsmanager.com/templates.json`
> 
>     * 目前官方的下载源 （`oss.duzuii.com/MCSManager`）暂时出现问题，请等待修复
> 
>     * 目前除官方下载源外其他下载链接的整合包均正常，请等待官方修复或使用其他整合包

啊? 但是这个第三方包( `Quick install: Name: 1.19.2 基岩互通版 | Download: https://url.alww.top/mcsm/paper-geyser1.19.2` ) 我这里是超时的

**Comment by alongw** [comment]
使用 https://script.mcsmanager.com/templates.json

 

发件人: ***@***.*** ***@***.***> 代表 Yuyuko233
发送时间: 2024年5月19日 22:27
收件人: MCSManager/MCSManager ***@***.***>
抄送: 阿龙 ***@***.***>; Mention ***@***.***>
主题: Re: [MCSManager/MCSManager] 快速部署中的下载节点全部无法ping通 (Issue #1220)

 

我还以为是我服务器网的问题 😂

* 如果你在使用最新版本的 MCSManager ，请将预设链接修改为 `https://script.mcsmanager.com/templates.json`
 
* 目前官方的下载源 （`oss.duzuii.com/MCSManager`）暂时出现问题，请等待修复
 
* 目前除官方下载源外其他下载链接的整合包均正常，请等待官方修复或使用其他整合包

啊? 但是这个第三方包( Quick install: Name: 1.19.2 基岩互通版 | Download: https://url.alww.top/mcsm/paper-geyser1.19.2 ) 我这里是超时的

**Comment by alongw** [comment]
已经修复

**Comment by unitwk** [comment]
<img width="46" alt="image" src="https://github.com/MCSManager/MCSManager/assets/18360009/6d2fb66f-ba47-458d-aa78-8eb5a5b182ef">

主要还是因为没钱

**Comment by lizina66** [comment]
> <img alt="图像" width="46" src="https://private-user-images.githubusercontent.com/18360009/331929269-6d2fb66f-ba47-458d-aa78-8eb5a5b182ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODIxNDAsIm5iZiI6MTcxNjE4MTg0MCwicGF0aCI6Ii8xODM2MDAwOS8zMzE5MjkyNjktNmQyZmI2NmYtYmE0Ny00NThkLWFhNzgtOGViNWE1YjE4MmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA1MTA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNTEwNWY5ZWY3MzA0NjViZDZiMDEwNzllYzgxOTJhODBkZDkyMWYwNTM1YTU4YzUyN2M4MDliNzdhYTUzYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GyoiD3D9GqeM5aR-x1oLhWXVHFowHghB11zlHxdIiaY">
> 主要还是因为没钱

这种公益项目的下载其实可以不那么考虑速度，能用就行。建议放置在海外服务器中，以节约成本，非常感谢你们的付出

**Comment by huangsijun17** [comment]
> > <img alt="图像" width="46" src="https://private-user-images.githubusercontent.com/18360009/331929269-6d2fb66f-ba47-458d-aa78-8eb5a5b182ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODIxNDAsIm5iZiI6MTcxNjE4MTg0MCwicGF0aCI6Ii8xODM2MDAwOS8zMzE5MjkyNjktNmQyZmI2NmYtYmE0Ny00NThkLWFhNzgtOGViNWE1YjE4MmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA1MTA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNTEwNWY5ZWY3MzA0NjViZDZiMDEwNzllYzgxOTJhODBkZDkyMWYwNTM1YTU4YzUyN2M4MDliNzdhYTUzYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GyoiD3D9GqeM5aR-x1oLhWXVHFowHghB11zlHxdIiaY">
> > 主要还是因为没钱
> 
> 这种公益项目的下载其实可以不那么考虑速度，能用就行。建议放置在海外服务器中，以节约成本，非常感谢你们的付出

海外的问题是墙等导致的无法连接。MCSM有大量的中国非专业用户，海外服务器的可靠性太低了。

**Comment by yuyuko233** [comment]
> 主要还是因为没钱

可以考虑丢到网盘里, 然后用户人工上传的方式

**Comment by huangsijun17** [comment]
> > 主要还是因为没钱
> 
> 可以考虑丢到网盘里, 然后用户人工上传的方式

怎么下载？现在还有支持外链的免费网盘？而且，网盘动不动封禁文件。

**Comment by yuyuko233** [comment]
> > > 主要还是因为没钱
> > 
> > 
> > 可以考虑丢到网盘里, 然后用户人工上传的方式
> 
> 怎么下载？现在还有支持外链的免费网盘？而且，网盘动不动封禁文件。

不需要直链, 用户下载完用户上传也行, 就和整合包差不多, 网盘封文件也不会封 mc 整合包这种的吧
