### ISSUE TITLE
[Bug Report] 中文乱码且无法解决

### ISSUE THREAD

**Issue by Michaelwucoc** [MCSManager/MCSManager#1223]
### Platform

Windows Server 2022

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

100%

### Bug Description

1. 在一个Fabric 服务器输入 say 测试
2. 输出了 ??
3. 输入英文不会有这样的问题

**Comment by unitwk** [comment]
在终端设置里面更改输入输出编码，在启动命令里面加上 java 程序编码设置

**Comment by Michaelwucoc** [comment]
我的启动代码是 java -Xms1024M -Xmx8G -Dfile.encoding=utf-8 -jar server.jar nogui

编码也选择的是UTF 8 仍然没有解决
![image](https://github.com/MCSManager/MCSManager/assets/110759450/dd62ca21-afff-46e3-bded-9e2ef141242b)
![image](https://github.com/MCSManager/MCSManager/assets/110759450/f357b68b-c4e1-44ce-a443-c5519ee699ed)

**Comment by unitwk** [comment]
感觉不应该，你的终端设置里面都已经改成 utf-8 的编码了吗？尝试一下看看有没有其他方法？如果都不行，我也不清楚为什么会这样。

**Comment by huangsijun17** [comment]
如果启动参数带了` -Dfile.encoding=utf-8`，MCSM的终端的输入输出也都设置了UTF-8，那么建议排查：
1. CMD 默认的编码格式
2. 操作系统的语言设置
3. 操作系统的区域设置中的“Beta 版”是否勾选。

![image](https://github.com/MCSManager/MCSManager/assets/31504595/b41d5247-444f-448c-bdb0-124747707870)

**Comment by Michaelwucoc** [comment]
<img width="378" alt="image" src="https://github.com/MCSManager/MCSManager/assets/110759450/f9510b98-e3f8-45fd-b33f-1d67f281bf78">
<img width="568" alt="image" src="https://github.com/MCSManager/MCSManager/assets/110759450/08df5da7-822e-404c-a380-ecc8d5f85959">


都检查过了

**Comment by Michaelwucoc** [comment]
可能是吧，目前可以日常使用，closed

**Comment by lixianghao** [comment]
我今天也遇见了同样的问题，在MCSM终端执行say的时候发现中文会乱码，我也试了-Dfile.encoding=utf-8和修改终端编码，也都还是不行。但我发现了更离谱的事情：我在排查问题的时候，把-Dfile.encoding=utf-8改成了GBK，然后控制台的输入输出都是utf8，此时控制台、Forge Server控制台和游戏内的所有中文都正常了。但重启服务器后，MCSM终端执行say 中文字符 又会乱码，游戏内和Forge控制台却能正常显示。我把encoding改回utf-8后，MCSM的控制台输入中文在游戏内和Forge控制台显示都是乱码，但Forge控制台和游戏内输入中文，在MCSM终端内又能正常显示。
