### ISSUE TITLE
能否在新版本中查看mc中的人数的状态信息？

### ISSUE THREAD

**Issue by dsbzbc121233** [MCSManager/MCSManager#1228]
### Description

v10.2.1的最新版本似乎没有状态信息查询，在以前的版本中都有此功能，为什么要取消，希望能在以后的版本中延续此功能。谢谢

### Reason

状态信息能便于腐竹管理服务器

**Comment by Michaelwucoc** [comment]
Need this feature! +1 at #1177

**Comment by Bluemangoo** [comment]
+1的话可以在那个issue表情回应（

**Comment by unitwk** [comment]
既然这么多人请求这个功能，我后续会开发它的，时间问题。

**Comment by YuMao233** [comment]
fixed: https://github.com/MCSManager/MCSManager/releases/tag/v10.4.0
