### ISSUE TITLE
如何使用nssm将MCSM注册为Windows服务？

### ISSUE THREAD

**Issue by Smolder3955** [MCSManager/MCSManager#1229]
### Platform

Windows Server 2022

### Panel Version

10.1.0

### Daemon Version (Optional)

4.3.0

### Recurrence Probability

100%

### Bug Description

WindowsServer2022系统，使用NSSM将面板的bat批处理启动文件注册为服务并不能成功启动面板，通过查看任务管理器和输出日志一直在反复启动MCSM，不知道是哪里出了问题 
![QQ截图20240525001118](https://github.com/MCSManager/MCSManager/assets/39408740/92fe7fde-dfff-471d-bf37-668caf97b414)
![QQ截图20240525001204](https://github.com/MCSManager/MCSManager/assets/39408740/073d79c6-c986-476e-be25-06393ad70075)

**Comment by Bluemangoo** [comment]
启动脚本用的start开了个新窗口。你注册服务要对web和daemon单独注册，命令把bat里面对应那行的start去掉就好。记得把启动位置改进对应目录。

**Comment by Bluemangoo** [comment]
另外 @unitwk 你要不还是开个question分类吧或者开 discussion（

**Comment by unitwk** [comment]
![image](https://github.com/MCSManager/MCSManager/assets/18360009/b0919a77-7ffd-44e5-945c-7229cde95cad)
 

将启动脚本里面的命令作为开机启动命令，而不是启动 bat 本身。

**Comment by unitwk** [comment]
> 另外 @unitwk 你要不还是开个question分类吧或者开 discussion（

好的。
