### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by tyh1820732766** [MCSManager/MCSManager#1231]
### Platform

Ubuntu 24.04

### Panel Version

10.2.1

### Recurrence Probability

100%

### Bug Description

我将我的data文件夹全部删除了，然后它生成了一个新的data文件夹，然后我进行了systemctl restart mcsm-daemon.service和systemctl restart mcsm-web.service，但是子文件夹User中却没有用户的信息，请问该怎么办？

**Comment by Bluemangoo** [comment]
在浏览器中打开面板。
