### ISSUE TITLE
关于调用启动实例API的问题

### ISSUE THREAD

**Issue by Lecajoins** [MCSManager/MCSManager#1232]
### Platform

面板 ubuntu 22.04 节点 win10

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

100%

### Bug Description

很抱歉为这样一个问题提一个issue 因为我在文档 和q群寻找解决方法并花了很多时间但无果

首先我想确认一下 在调用启动实例里 文档中提到的“InstanceId”与“DaemonId”字段是不是对应面板上能够找到的应用实例的ID和远程节点的ID
如果是的话那要该如何进行鉴权？

1. 首先我尝试按照文档所写调用用户API接口/api/auth报403无法找到请求头 后来在改为api/auth?apikey=XXX(确认有管理员权限）后成功调用并返回200
2. 然后我按照调用用户API的方法以/api/protected_instance/open?uuid={InstanceId}&remote_uuid={DaemonId}?apikey=XXX调用启动实例API 却报403参数不正确或非法访问 删掉“?apikey=”后又重新报无法找到请求头
![4e36b9d9674bbab85ae1b6ca7f426bc5](https://github.com/MCSManager/MCSManager/assets/123373331/16868f0b-7174-4998-a8f6-b8c160665eb9)
![QQ截图20240526125644](https://github.com/MCSManager/MCSManager/assets/123373331/c31fb678-0a3f-4e87-93f5-c8800d975016)

另外我给面板和节点均上了https 具体方法是nginx+frp 并在nginx处做TLS终止 转发至frp后再做自签TLS加密连接远程节点 实例的连接和启动均正常 不知道是不是会有影响

最后还请继续完善并使官方文档的API调用部分和docker容器隔离部分更完善清晰 实在是看的有些云里雾里

**Comment by Bluemangoo** [comment]
https://github.com/MCSManager/MCSManager/blob/bd43643729ace58258326e8b9c39ccac5b597280/panel/src/app/routers/instance_operate_router.ts#L37

**Comment by aesopcmc** [comment]
即使用daemonId也无效：
![image](https://github.com/MCSManager/MCSManager/assets/25699609/9554609d-56f7-4fe7-9fbf-26d1176254b4)

**Comment by Bluemangoo** [comment]
你apikey没给当然没有权限啊。

**Comment by Lecajoins** [comment]
我试了改成daemonId字段并加入?apikey=XXX 还是没用 报错如下 
所以 uuid到底是实例的id还是 调用用户的id 
daemonId是在面板端-节点 处找到的id 还是在面板连接节点在节点config/global.json文件
找到的id
我怀疑这些都没搞对 文档里面都没说清楚 到底谁是谁 这些字段还那么相似
![IMG_1177](https://github.com/MCSManager/MCSManager/assets/123373331/3d6ff639-db27-4c08-a8b9-890897f54dd7)




> 所有类似remoteuuid、daemonid之类的字段都统一了。
> 
> https://github.com/MCSManager/MCSManager/blob/bd43643729ace58258326e8b9c39ccac5b597280/panel/src/app/routers/instance_operate_router.ts#L37

**Comment by Lecajoins** [comment]
> 所有类似remoteuuid、daemonid之类的字段都统一了。
> 
> https://github.com/MCSManager/MCSManager/blob/bd43643729ace58258326e8b9c39ccac5b597280/panel/src/app/routers/instance_operate_router.ts#L37

我试了改成daemonId字段并加入？apikey=XXX 还是没用 报错如下
所以 uuid到底是实例的id还是 调用用户的id
daemonId是在面板端-节点处找到的id，还是在面板连接节点在节点配置/global.json文件
找到的id
我怀疑这些都没搞对 文档里面都没说清楚 到底谁是谁 这些字段还那么相似
![IMG_1177](https://github.com/MCSManager/MCSManager/assets/123373331/8e8a1d18-9d35-4b60-8832-407511930ad3)

**Comment by Bluemangoo** [comment]
uuid是实例id。

**Comment by unitwk** [comment]
<img width="869" alt="image" src="https://github.com/MCSManager/MCSManager/assets/18360009/842a45ca-9380-4788-ae4c-06a0d32525c4">

**Comment by Lecajoins** [comment]
> <img alt="image" width="869" src="https://private-user-images.githubusercontent.com/18360009/333940600-842a45ca-9380-4788-ae4c-06a0d32525c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Nzg4NTEsIm5iZiI6MTcxNjc3ODU1MSwicGF0aCI6Ii8xODM2MDAwOS8zMzM5NDA2MDAtODQyYTQ1Y2EtOTM4MC00Nzg4LWFlNGMtMDZhMGQzMjUyNWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAyNTU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZmFhZjNjOTE5MzMyMDgyYmJhZTc2ZGM5MjMwYTYwYTBmN2NmNjMxNWNlOWIwYmJkZjAzMTcxNmZiMjg1MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qHRPJS0fqL-iardVzsIwuCFiDCI09WkI6pIAsvOaBHg">
> remote_uuid 和 daemonId 两种用法在 URL 中都支持。
> 
> 然后请求的 Headers 中加入 `x-requested-with: xmlhttprequest`

使用的完整URL如图 并且也加入了请求头 在面板用户界面处也为apikey对应的管理员用户分配了所要调用的实例 但仍有如下报错

![IMG_1181](https://github.com/MCSManager/MCSManager/assets/123373331/dbb2626b-8621-4281-8c89-bac170561a0e)
![IMG_1180](https://github.com/MCSManager/MCSManager/assets/123373331/7968dae7-07a9-457f-8f45-df68baceea98)

**Comment by Bluemangoo** [comment]
去面板抓个包吧（拍额头）。

**Comment by unitwk** [comment]
请再次确认你的面板是否是最新的 `10.2.1` 版本，你所描述的这种情况在 10.1 版本可能会出现，但是 10.2 版本应该已经修复。

**Comment by Lecajoins** [comment]
> 请再次确认你的面板是否是最新的 `10.2.1` 版本，你所描述的这种情况在 10.1 版本可能会出现，但是 10.2 版本应该已经修复。

是的 先前我翻看issue时 看你和别人提到10.v1版本API不可用 那时便已经检查了面板版本 的确是10.2.1 唯一特别的地方 只有这个面板是部署在一台云服务器上
![dd_20240528112359](https://github.com/MCSManager/MCSManager/assets/123373331/70a32cec-dea8-4287-93cf-cf45ddaf79dc)

**Comment by Lecajoins** [comment]
> 去面板抓个包吧（拍额头）。

我已经通过邮件将抓包文件发送到你github个人页面留下的邮箱中 因为我仅有抓包能力没能力看包 见谅

**Comment by Bluemangoo** [comment]
不是我现在够不到邮箱。

我帮你抓个吧。。。

**Comment by Bluemangoo** [comment]
其实看F12就好了改变不需要wireshark什么的。

**Comment by unitwk** [comment]
> 不是我现在够不到邮箱。
> 
> 我帮你抓个吧。。。
> 
> 哦我去我手上没环境。
> 
> 另外 @unitwk ：
> 
> ```
> Error: Dependency files are missing and cannot be started. Please reinstall the program:/workspaces/MCSManager/daemon/lib/file_zip_linux_x64
> ```
> 
> 直接npm dev daemon。这玩意强制了？

是强制了，安装包自带

**Comment by Bluemangoo** [comment]
是不是在git仓库里面放一个或者lfs放一个，方便开发。要么在readme里面写上或者在install-deps的脚本里面把下载写上什么的。

**Comment by unitwk** [comment]
> 是不是在git仓库里面放一个或者lfs放一个，方便开发。或者在install-deps的脚本里面把下载写上什么的。

看情况把，文件还挺大的

**Comment by Bluemangoo** [comment]
但是没有它也不能开发啊。

不想占用仓库可以放lfs。git lfs
