### ISSUE TITLE
[Bug Report] 无法强制终止

### ISSUE THREAD

**Issue by bobandbrony** [MCSManager/MCSManager#1233]
### Platform

win10 ltsc2019

### Panel Version

10.2.1

### Recurrence Probability

100%

### Bug Description

开始按的重启，但卡在启动中，这会按终止也没用
![image](https://github.com/MCSManager/MCSManager/assets/129247570/15ec2eec-3355-4957-8dee-ad930eb0c70e)
后台的报告
![image](https://github.com/MCSManager/MCSManager/assets/129247570/a2fdb37f-f190-4cc1-a397-69467109d6e5)

**Comment by huangsijun17** [comment]
1. 你运行的是什么？
2. 启动参数是什么？
3. 如果启动的bat/sh，请提供该文件代码。

**Comment by bobandbrony** [comment]
> 1. 你运行的是什么？
> 2. 启动参数是什么？
> 3. 如果启动的bat/sh，请提供该文件代码。

1 运行的是bat文件
2 call napcat.bat -q 4494*****（qq号，隐私打码）
3 代码如下
@echo off
setlocal enabledelayedexpansion
:loop_read
for /f "tokens=2*" %%a in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\QQ" /v "UninstallString"') do (
    set "RetString=%%b"
    goto :napcat_boot
)

:napcat_boot
for %%a in ("!RetString!") do (
    set "pathWithoutUninstall=%%~dpa"
)

set "QQPath=!pathWithoutUninstall!QQ.exe"
set ELECTRON_RUN_AS_NODE=1
echo !QQPath!
"!QQPath!" ./napcat.mjs %*
