### ISSUE TITLE
[Feature] 增加内存使用量显示

### ISSUE THREAD

**Issue by bobandbrony** [MCSManager/MCSManager#1234]
### Description

为每个实例加一个内存使用量显示
![image](https://github.com/MCSManager/MCSManager/assets/129247570/c59c6676-69b1-49a0-a735-699368159c51)
类似这种
如果可以，再加个CPU使用量吧

### Reason

更好更方便的查看实例运行情况

**Comment by huangsijun17** [comment]
无法实现。

**Comment by bobandbrony** [comment]
已了解，感谢回复
