### ISSUE TITLE
[Feature] 在“应用实例”界面添加启动/终止/重启按钮

### ISSUE THREAD

**Issue by bobandbrony** [MCSManager/MCSManager#1235]
### Description

类似这种效果
![image](https://github.com/MCSManager/MCSManager/assets/129247570/902bbe4c-98f8-4de9-9697-09f03c719e56)
![image](https://github.com/MCSManager/MCSManager/assets/129247570/5be8ec17-16a7-43b0-844a-e5b95f38f333)

### Reason

更方便的管理实例

**Comment by Michaelwucoc** [comment]
+1

**Comment by YeziMoanan** [comment]
+2

**Comment by huangsijun17** [comment]
@YeziMoanan @Michaelwucoc ，Github支持使用emoji来表达简单的赞成与反对等观点。请为了无内容的单纯表达支持而进行回复。任一回复都会通知所有关注者。

**Comment by YuMao233** [comment]
√fixed: https://github.com/MCSManager/MCSManager/releases/tag/v10.4.0
