### ISSUE TITLE
[Feature] 增加“应用实例”界面，实例可自定义拖动功能

### ISSUE THREAD

**Issue by bobandbrony** [MCSManager/MCSManager#1236]
### Description

希望能像自定义布局那样拖动各个实例块
![image](https://github.com/MCSManager/MCSManager/assets/129247570/ffc89948-3340-4d06-8f85-da53512d9cac)
比如这样拖动可以调换位置

### Reason

更方便的管理实例

**Comment by Michaelwucoc** [comment]
+1

**Comment by YuMao233** [comment]
新版支持自定义分类了，可以瞅瞅： https://github.com/MCSManager/MCSManager/releases/tag/v10.4.0
