### ISSUE TITLE
[Bug Report] windows下运行start.bat提示没有守护进程，本地也没有对应的文件夹

### ISSUE THREAD

**Issue by Frankxxxxxxx** [MCSManager/MCSManager#1240]
### Platform

windows10

### Panel Version

v10

### Recurrence Probability

100%

### Bug Description

![微信截图_20240530142705](https://github.com/MCSManager/MCSManager/assets/168388232/29cef473-80e1-4194-955a-1d8a5e353dd1)
![微信截图_20240530142810](https://github.com/MCSManager/MCSManager/assets/168388232/c9628ea7-bf68-46b4-ac05-7f8e730f0e42)

**Comment by huangsijun17** [comment]
确认一下，你的daemon有在运行吗？

**Comment by Frankxxxxxxx** [comment]
> 确认一下，你的daemon有在运行吗？

bat文件执行后闪退，应该是没有在运行的

**Comment by Bluemangoo** [comment]
其实不管怎么样我觉得控制台输出这么多遍是不应该的。可能要修一下？ @unitwk

**Comment by Bluemangoo** [comment]
重复输出。如果用户只是单纯运行web不需要daemon（daemon在另一台机器呢）。

**Comment by huangsijun17** [comment]
> 重复输出。如果用户只是单纯运行web不需要daemon（daemon在另一台机器呢）。

手动连接成功后，自动连接会停止。

**Comment by Bluemangoo** [comment]
反正我觉得最多提醒一遍。

**Comment by huangsijun17** [comment]
> 反正我觉得最多提醒一遍。

这是日志，不是前端输出。每次尝试，不用写日志？

**Comment by Bluemangoo** [comment]
尝试一遍，再不济过一分钟再试一遍。

**Comment by huangsijun17** [comment]
> 尝试一遍，再不济过一分钟再试一遍。

频次确实有点高了。

**Comment by unitwk** [comment]
> > 确认一下，你的daemon有在运行吗？
> 
> bat文件执行后闪退，应该是没有在运行的

删除所有文件，重新安装，重新启动
