### ISSUE TITLE
[Feature] 本地/网络 模板更新配置

### ISSUE THREAD

**Issue by YeziMoanan** [MCSManager/MCSManager#1242]
### Description

当前中文issue我已看完 没重复的
场景：
（服务器16c 384g）
1.Mc游戏-地图-小游戏 乃至 Steam游戏
2.多数地图小游戏有人数限制/或者朋友们想分组开
2.2 emmm 他们就是想开分服 几个人一小组 
2.3 一些rpg地图 解密地图 是一次性的 需要重新安装 更新 类似Steam游戏
      我知道有文件管理 可以删除地图文件 重新解压准备好的地图文件
      二改也做过 但能不能做成一个需求 以更便捷的方式
      而且我代码写的有点屎 纯后端java nodejs ts写的不多 能写但菜的程度

### Reason

需求：
其实某种程度上和 自定义文件配置 这个issue重复 我作为补充扩展
1.在新建实例时，增加一个勾选 "保存为模板" 选项，保存在本地某个目录中
1.2 衍生需求：配置文件同步/端口自动后移 在 自定义文件配置之后
1.3 在原现有功能上的 一键开服 增加 需求一产生的模板
1.32 其实就是在一键开服 获取的 json 下载文件 增加一个本地的 这个地址可以是本地的地址 直接从本地获取相关文件
       我尝试过Nas 以及 alist 似乎都会走到外网 从域名进走带宽流量下载文件（可能操作错误 我再尝试）
        这样开发 或许更方便点 因为服务端说什么 也就一个压缩包 配套环境 无论是我们上传还是从合作方那边提供的
       或者是MC核心 下载下来执行安装
1.33 在已配置保存模板的实例内 可操作 重开/另开

2.端口相关
2.2 扫描已开启实例使用端口、记录 自定义配置中 的端口
2.3 圈定一个范围 并与2.2协同 能不能实现 端口自动分配
2.4 端口自动分配联动需求1、1.33、 以及原有功能 一键开服

该issue 我认为可以更加完善 “一键开服”
不着急 也着急不了 确实需求多也挺大
Mcsm 对我而言 是真的好用 想变的更好用 
从搭建用户 以及 使用用户来说更为便捷

**Comment by YeziMoanan** [comment]
和朋友聊了一下 补充一点解释
1.端口现在需要手动配置
2.如果管理员或创建实例人有多个 配置端口这方面会有点麻烦 要一个个实例去看 或者 问其他人
3.这个端口 可以作为参数 我们手动标记 在 自定义配置文件模板 没做时
可以我们手动记录 再实现端口相关功能 这两个需求其实模块化描述了 可以联动 也可以分开实现

**Comment by Bluemangoo** [comment]
自动分配端口不一定会做，扩展下一键开服可以。

你把那个预设的json换成你自己的，自己本地开个静态服务器就可以了，地址写内网的，简单说下，不理解再问吧。

**Comment by huangsijun17** [comment]
MCSM本体是不可能存在任何网络模板一键开服功能的，因为这意味着MCSM团队将成为运营团队，从一个面板变成一个整个商业项目。定期、不定期维护各种游戏的数据。这显然是不小于现有面板所有代码量的规模。

**Comment by YeziMoanan** [comment]
> MCSM本体是不可能存在任何网络模板一键开服功能的，因为这意味着MCSM团队将成为运营团队，从一个面板变成一个整个商业项目。定期、不定期维护各种游戏的数据。这显然是不小于现有面板所有代码量的规模。

指的并不是你们来 可以说是一个入口 #120 这个issue 的自定义配置 实现了 可以自理 或者 发pr 并不需要开发团队来维护
网络模板 现有的json不就是吗 也不是让开发团队维护这个 只是在这个功能上 可以自适应端口 可以一键启动
是有点商业化的影子 这些做完都可以直接去商业了
那 端口功能和 bluemangoo说的 不一定做 或者 变成付费支持
扩展一键开服 现有实例复制粘贴成另一个实例 或者根据配置的网络模板 删除目录文件 下载压缩包 解压 启动 重开
我觉得 扩展开服 乃至端口 都符合面板用户需要 更完善方便 并非商业化 虽说这会使得商业化十分方便
或者 做一点阉割 端口自动分配不做 在列表 或 实例详情 显示实际使用端口  这个是不是合理点？
如果这个面板有多个人使用 甚至也不说多个了 一个人 时间长了也会忘
我也知道可以在名字上标注 但这显得名字太臃肿了
泰拉瑞亚-灾厄-30001
泰拉瑞亚-30001
脆骨症-30001
1.20.1-小游戏-30005

**Comment by Bluemangoo** [comment]
查询端口能做但是不优雅。你可以自己fork自己做自己用。

模板的url可以自己填的。

**Comment by YeziMoanan** [comment]
我知道有文件管理 可以删除地图文件 重新解压准备好的地图文件
而且我代码写的有点屎 纯后端java nodejs ts写的不多 能写但菜的程度
我也知道url可以自己填 预设我也换过
二改也做过 但能不能做成一个需求 以更便捷的方式

**Comment by unitwk** [comment]
我感觉你说的一键开服通过现有的快速安装功能就完全满足了，你在设置界面里面自定义你的「模板」，然后就能快速基于模板创建服务器了。
