### ISSUE TITLE
[Bug Report] 2FA绑定失败

### ISSUE THREAD

**Issue by Angels-D** [MCSManager/MCSManager#1243]
### Platform

OpenCloudOS 8.5.0-18

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

100%

### Bug Description

使用kabaka:mcsmv10的容器镜像
用户点击绑定2FA按钮后返回信息
```json
{
  "status": 400,
  "data": "Request parameters are incorrect",
  "time": 1717247468398
}
```
后台显示输出
```
[HTTP] POST: http://localhost:40056/api/auth/bind2fa?token=776df861bb394a898ba980d4a5dccdd31717247069539
[HTTP] IP: ::ffff:10.89.0.1 USER: AnglesD UUID: 0bd275c498fb43c8a2b5720c379cb6c6
```

**Comment by kabaka9527** [comment]
好的，今晚确认一下

**Comment by Angels-D** [comment]
编译后服务端要求：`body: {}` ，发送时实际为：`body: null`
将`bind2FA().execute();` 改为`bind2FA().execute(data: {});`后可以正常接受request

**Comment by kabaka9527** [comment]
> 编译后服务端要求：`body: {}` ，发送时实际为：`body: null`
> 将`bind2FA().execute();` 改为`bind2FA().execute(data: {});`后可以正常接受request

为mcsm问题吗

**Comment by Bluemangoo** [comment]
其实你改完可以直接提pr的（

**Comment by Angels-D** [comment]
测试没问题，不过不确定这是不是最好的改法，然后不清楚其他地方会不会有类似的问题
PR和issue绑定的并不是很熟练（

**Comment by rrrexfield** [comment]
这个bug现在依然存在，面板版本为10.2.1
点击绑定按钮后，后台输出
```
[07/29 00:31:17] [INFO] [HTTP] POST: http://mcsm.****.com/api/auth/bind2fa?token=e116c672eac34151b******
[07/29 00:31:17] [INFO] [HTTP] IP: ::ffff:127.0.0.1 USER: adminl UUID: a5a1c3ffce8841fca8******
```
网页返回 `status 400`

**Comment by unitwk** [comment]
> 这个bug现在依然存在，面板版本为10.2.1 点击绑定按钮后，后台输出
> 
> ```
> [07/29 00:31:17] [INFO] [HTTP] POST: http://mcsm.****.com/api/auth/bind2fa?token=e116c672eac34151b******
> [07/29 00:31:17] [INFO] [HTTP] IP: ::ffff:127.0.0.1 USER: adminl UUID: a5a1c3ffce8841fca8******
> ```
> 
> 网页返回 `status 400`

代码已经修复了，只是还没有发布新版本，所以此bug依然存在
