### ISSUE TITLE
[Bug Report] 守护进程的"defaultInstancePath"配置项不生效

### ISSUE THREAD

**Issue by Mooling0602** [MCSManager/MCSManager#1244]
### Platform

Arch Linux x86_64 (rolling)

### Panel Version

latest

### Daemon Version (Optional)

latest

### Recurrence Probability

100%

### Bug Description

如图所示，设置了/opt/mcsmanager/daemon/data/Config/global.json里面的"defaultInstancePath"项，连接到网页面板后尝试创建新的实例，发现配置项并未生效，新的实例仍然创建在默认的目录中。
![image](https://github.com/MCSManager/MCSManager/assets/147964268/60ddeb3b-717d-406a-a33a-ab8efd53d80b)
![image](https://github.com/MCSManager/MCSManager/assets/147964268/d091fce7-e310-4463-b15d-ab51f77d16db)

**Comment by Bluemangoo** [comment]
看了一下，应该是前端全责。我再确认一下。

**Comment by unitwk** [comment]
> 看了一下，应该是前端全责。我再确认一下。

有结果吗？我感觉是不是这个配置项因为时间太久，后续的迭代导致它已经不能生效

**Comment by Bluemangoo** [comment]
~~我手上没有环境啊。~~

你去翻一下吧我一时半会儿不一定可以。

**Comment by nandehututu** [comment]
+1 也是不生效，一样的就过来本来想提交bug，后来过来发现有了就不重复提交了，

**Comment by nandehututu** [comment]
版本已经更新到最新

**Comment by YuMao233** [comment]
fixed: https://github.com/MCSManager/MCSManager/releases/tag/v10.4.0
