### ISSUE TITLE
[Feature] 批量操作添加重启功能

### ISSUE THREAD

**Issue by alazeprt** [MCSManager/MCSManager#1249]
### Description

如题，批量操作应用实例时在选中项菜单中添加重启功能

### Reason

方便操作

**Comment by huangsijun17** [comment]
> ### Description
> 如题，批量操作应用实例时在选中项菜单中添加重启功能
> 
> ### Reason
> 方便操作

重启一般意味着较大的性能消耗，不建议添加。

**Comment by Bluemangoo** [comment]
v9是不是有过？

我没意见。

**Comment by huangsijun17** [comment]
> > 重启一般意味着较大的性能消耗，不建议添加。
> 
> 为什么这样说

游戏服务端重开，要不重新要加载地图等等？一些联机正版验证，资源的读取、解包、生成，等等等等，对于硬盘、CPU、内存都是一定的消耗。一次性启动多个服务端，势必会造出更大的开销。

**Comment by Bluemangoo** [comment]
我觉得没问题。我支持。而且改一下简单的。

**Comment by Bluemangoo** [comment]
我记得是有接口但是我没时间。我后天高考。

**Comment by unitwk** [comment]
> 我记得是有接口但是我没时间。我后天高考。

好的，我要lazy加下吧，你好好高考。

**Comment by LazyCreeper** [comment]
PR 了
