### ISSUE TITLE
[Feature] mcdr分开设置关闭服务器和强制关闭服务器的方法

### ISSUE THREAD

**Issue by Huangsam04-github** [MCSManager/MCSManager#1253]
### Description

我记得本来的mcsm可以**分开**设置**关闭服务器**和**强制关闭服务器**的方法
但是现在我找不到了。

我把功能组里面的选项**全部都看了一遍**，但是仍未找到如何设置强制关闭服务器的方法设置

我只在**终端设置**里面找到了”**关闭实例设置**“，描述是：当点击“关闭实例”按钮时，会立刻执行此命令，^C 代表 Ctrl+C 信号。

很显然这个是设置正常关闭时候的指令的，也许是我没有找到？

所以如果不是我的问题的话，能不能重新加入这个分开设置的功能？

### Reason

即使调到了mcdr模式，关闭还是默认stop

所以说我想要把关机设置为!!MCDR server stop_exit 和 !!MCDR server kill

但是我没找到

**Comment by Huangsam04-github** [comment]
我好像强制关闭mcdr但是我的世界服务器还活着

所以一直想解决这个问题，就希望能从mcdr的方式关闭服务器

但是我没找到

如果这个事是我纯粹记错了那也无所谓了

**Comment by Huangsam04-github** [comment]
我好像强制关闭mcdr但是我的世界服务器还活着

所以一直想解决这个问题，就希望能从mcdr的方式关闭服务器

但是我没找到

如果这个事是我纯粹记错了那也无所谓了

**Comment by Huangsam04-github** [comment]
我好像强制关闭mcdr但是我的世界服务器还活着

所以一直想解决这个问题，就希望能从mcdr的方式关闭服务器

但是我没找到

如果这个事是我纯粹记错了那也无所谓了

**Comment by Mooling0602** [comment]
MCDR上使用stop关闭服务器也是正常操作，用MCDR的指令关服有什么必要性吗

**Comment by huangsijun17** [comment]
> MCDR上使用stop关闭服务器也是正常操作，用MCDR的指令关服有什么必要性吗

MCSM的关服是发送指令，强制关服在Linux是kill -9来杀进程。前者会基于程序正常的退出处理流程，后者是强制杀死。

**Comment by Mooling0602** [comment]
> > MCDR上使用stop关闭服务器也是正常操作，用MCDR的指令关服有什么必要性吗
> 
> MCSM的关服是发送指令，强制关服在Linux是kill -9来杀进程。前者会基于程序正常的退出处理流程，后者是强制杀死。

那你的问题实际上不是针对 MCDR，而是针对所有实例的，即使用正常的方法结束进程（命令或 Ctrl+C 快捷键）和使用 kill 杀死进程（或自定义其他强制结束进程的方法）
MCSM 默认强制终止进程的方法似乎是 Ctrl+C 快捷键，无法进行修改

**Comment by Huangsam04-github** [comment]
> > > MCDR上使用stop关闭服务器也是正常操作，用MCDR的指令关服有什么必要性吗
> > 
> > MCSM的关服是发送指令，强制关服在Linux是kill -9来杀进程。前者会基于程序正常的退出处理流程，后者是强制杀死。
> 
> 那你的问题实际上不是针对 MCDR，而是针对所有实例的，即使用正常的方法结束进程（命令或 Ctrl+C 快捷键）和使用 kill 杀死进程（或自定义其他强制结束进程的方法）
> MCSM 默认强制终止进程的方法似乎是 Ctrl+C 快捷键，无法进行修改

但是旧版本mcsm是可以修改强制关闭的

**Comment by Bluemangoo** [comment]
默认强制终止是kill的。

**Comment by huangsijun17** [comment]
@Huangsam04-github @Mooling0602 @Bluemangoo 
强制关闭能且只能是kill -9来杀死进程。
任意进程都是有假死的几率的，假死后不会响应^C和kill。之前MCSM 9的强制结束的kill没-9参数，导致不能kill假死的进程，还是我加的，所以我很清楚。10的强制结束不可能改成别的。普通子进程管理的兜底方法都是且必须是强制杀死进程。强制结束也就是在这时候兜底的。

**Comment by Bluemangoo** [comment]
不是你自己去看源码啊。。。

**Comment by Bluemangoo** [comment]
https://github.com/MCSManager/MCSManager/blob/08d8553fa4d813e43ce1ae4f744995eb03540ef6/daemon/src/entity/commands/general/general_kill.ts#L21

**Comment by Bluemangoo** [comment]
要改你自己提pr。。。。

**Comment by unitwk** [comment]
你记错了，从来就没有支持「分开设置关闭服务器和强制关闭服务器的方法」，以前从来没有这个功能，强制关服的行为一直是强杀进程。

**Comment by Huangsam04-github** [comment]
> @Huangsam04-github @Mooling0602 @Bluemangoo 强制关闭能且只能是kill -9来杀死进程。 任意进程都是有假死的几率的，假死后不会响应^C和kill。之前MCSM 9的强制结束的kill没-9参数，导致不能kill假死的进程，还是我加的，所以我很清楚。10的强制结束不可能改成别的。普通子进程管理的兜底方法都是且必须是强制杀死进程。强制结束也就是在这时候兜底的。

好的，谢谢

**Comment by Huangsam04-github** [comment]
> https://github.com/MCSManager/MCSManager/blob/08d8553fa4d813e43ce1ae4f744995eb03540ef6/daemon/src/entity/commands/general/general_kill.ts#L21

好吧，谢谢你

**Comment by Huangsam04-github** [comment]
> 你记错了，从来就没有支持「分开设置关闭服务器和强制关闭服务器的方法」，以前从来没有这个功能，强制关服的行为一直是强杀进程。

那就奇了怪了，大概是我记错了吧，谢谢
