### ISSUE TITLE
[Bug Report] 英语版本单词拼写错误

### ISSUE THREAD

**Issue by littleblacklb** [MCSManager/MCSManager#1256]
### Platform

All

### Panel Version

10.2.1

### Recurrence Probability

100%

### Bug Description

`limitation` 打成 `limitatiom`了
https://github.com/MCSManager/MCSManager/blob/5aa182675ed943dc785ee36e1c74b7e039eef9b5/languages/en_US.json#L1686

**Comment by littleblacklb** [comment]
https://github.com/MCSManager/MCSManager/blob/5aa182675ed943dc785ee36e1c74b7e039eef9b5/languages/en_US.json#L1686

**Comment by unitwk** [comment]
你可以提交一个PR修正它
