### ISSUE TITLE
[Bug Report] xhr poll error

### ISSUE THREAD

**Issue by ink-ideal** [MCSManager/MCSManager#1259]
### Platform

Debian12

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

100%

### Bug Description

内网服务器使用1panel部署Frpc，拥有公网ip的服务器使用1panel部署Frps，内网穿透未存在问题，其他隧道项均可连接
内网服务器(树莓派4b)正常使用官网脚本安装MCSManager面板，使用内网ip可访问面板不会出现错误，使用无反向代理的域名（带端口）连接面板不会出现错误，但是使用经过反向代理之后的域名访问，Web面板可以访问，但是面板在尝试连接daemon时出现错误，我阅读了其他issues，找到一个匹配选项，但是无用，服务器开放了安全组，Frps的Docker也开放了23333和24444端口（内网穿透均无问题），这个代理成功了的，单独访问Daemon未经过反代的域名（此域名是和被反向代理的域名是同一个，不过反向代理的端口是23333）反馈 [MCSManager Daemon] Satus: OK  ，所以可以证明Frp和方向代理无误，不过面板却无法访问daemon

**Comment by ink-ideal** [comment]
使用其他部署了MCSM的服务器添加此服务器节点均不可访问

**Comment by ink-ideal** [comment]
反向代理用的openrasty，反代代理23333,24444不走openrasty

**Comment by unitwk** [comment]
看看这一段：https://docs.mcsmanager.com/zh_cn/ops/proxy_https.html#%E9%85%8D%E7%BD%AE-mcsm-%E4%BD%BF%E7%94%A8-https-%E8%BF%9E%E6%8E%A5

**Comment by SangBinSong** [comment]
I had the same problem.
The same thing can happen if you enter the panel https.
If you access the panel over https, it will force a connection to the blind WSS.

**Comment by huangsijun17** [comment]
> I had the same problem. The same thing can happen if you enter the panel https. If you access the panel over https, it will force a connection to the blind WSS.
> 
> Even if you have multiple daemons, you can't choose to connect over WS.

Use "wss://example.com/" if you are using "https://".

**Comment by ink-ideal** [comment]
分别配置一次反向代理后怎么连接，添加节点需要输入端口。

**Comment by ink-ideal** [comment]
用外网域名连接不加wss://可以连接显示在线，但是无法进入实例控制台，实例参数可以编辑

**Comment by ink-ideal** [comment]
ws://也可以连接显示在线，但是无法进入实例控制台，实例参数可以编辑

**Comment by wling-art** [comment]
我也遇到了相同问题（也是通过frp内网穿透并且在面板网页了https）
![image](https://github.com/MCSManager/MCSManager/assets/90316914/c4dfcb72-b460-41ad-a4c0-94751a4b0e53)

**Comment by thepiationesl** [comment]
可以试试替换为纯ip地址
________________________________
发件人: wling ***@***.***>
发送时间: 2024年7月9日 9:15
收件人: MCSManager/MCSManager ***@***.***>
抄送: PiationESL ***@***.***>; Comment ***@***.***>
主题: Re: [MCSManager/MCSManager] [Bug Report] xhr poll error (Issue #1259)


我也遇到了相同问题（也是通过frp内网穿透并且在面板网页了https）
image.png (view on web)<https://github.com/MCSManager/MCSManager/assets/90316914/c4dfcb72-b460-41ad-a4c0-94751a4b0e53>

―

**Comment by thepiationesl** [comment]
如果不设置成IP地址的话，那么这会出现xhr poor上述各位出现的问题，至少在现在的Frp穿透的情况下是这样
________________________________
发件人: Ren Redstone ***@***.***>
发送时间: 2024年7月9日 13:14
收件人: wling ***@***.***>; MCSManager/MCSManager ***@***.***>; MCSManager/MCSManager ***@***.***>
抄送: Comment ***@***.***>
主题: 答复: [MCSManager/MCSManager] [Bug Report] xhr poll error (Issue #1259)

大家可以把域名换成IP地址，像这样
________________________________
发件人: Ren Redstone ***@***.***>
发送时间: 2024年7月9日 13:10
收件人: wling ***@***.***>; MCSManager/MCSManager ***@***.***>; MCSManager/MCSManager ***@***.***>
抄送: Comment ***@***.***>
主题: 答复: [MCSManager/MCSManager] [Bug Report] xhr poll error (Issue #1259)

可以试试替换为纯ip地址
________________________________
发件人: wling ***@***.***>
发送时间: 2024年7月9日 9:15
收件人: MCSManager/MCSManager ***@***.***>
抄送: PiationESL ***@***.***>; Comment ***@***.***>
主题: Re: [MCSManager/MCSManager] [Bug Report] xhr poll error (Issue #1259)


我也遇到了相同问题（也是通过frp内网穿透并且在面板网页了https）
image.png (view on web)<https://github.com/MCSManager/MCSManager/assets/90316914/c4dfcb72-b460-41ad-a4c0-94751a4b0e53>

―

**Comment by ink-ideal** [comment]
使用ip地址一样不可以连接，尝试ws://和wss://开头和直接写IP地址

**Comment by thepiationesl** [comment]
我的可以，最新版本
________________________________
发件人: ink-ideal ***@***.***>
发送时间: 2024年7月12日 12:10
收件人: MCSManager/MCSManager ***@***.***>
抄送: PiationESL ***@***.***>; Comment ***@***.***>
主题: Re: [MCSManager/MCSManager] [Bug Report] xhr poll error (Issue #1259)


使用ip地址一样不可以连接，尝试ws://和wss://开头和直接写IP地址

―

**Comment by thepiationesl** [comment]
请问您填写的是frps的纯IP吗
________________________________
发件人: Ren Redstone ***@***.***>
发送时间: 2024年7月12日 12:39
收件人: ink-ideal ***@***.***>; MCSManager/MCSManager ***@***.***>; MCSManager/MCSManager ***@***.***>
抄送: Comment ***@***.***>
主题: 答复: [MCSManager/MCSManager] [Bug Report] xhr poll error (Issue #1259)

我的可以，最新版本
________________________________
发件人: ink-ideal ***@***.***>
发送时间: 2024年7月12日 12:10
收件人: MCSManager/MCSManager ***@***.***>
抄送: PiationESL ***@***.***>; Comment ***@***.***>
主题: Re: [MCSManager/MCSManager] [Bug Report] xhr poll error (Issue #1259)


使用ip地址一样不可以连接，尝试ws://和wss://开头和直接写IP地址

―

**Comment by ink-ideal** [comment]
纯IP不可行，从理论上来说都不行。节点必须得可以使用WebSocket协议

**Comment by ink-ideal** [comment]
你可能面板没有使用HTTPS，如果填写纯IP，他会自动给你加个ws://或者wss://

**Comment by thepiationesl** [comment]
我确实没有使用HTTPS，那接下来我退出讨论
________________________________
发件人: ink-ideal ***@***.***>
发送时间: 2024年7月13日 19:11
收件人: MCSManager/MCSManager ***@***.***>
抄送: PiationESL ***@***.***>; Comment ***@***.***>
主题: Re: [MCSManager/MCSManager] [Bug Report] xhr poll error (Issue #1259)


你可能面板没有使用HTTPS，如果填写纯IP，他会自动给你加个ws://或者wss://

―

**Comment by BoenShi128** [comment]
我找到解决方案了，仔细阅读下官方文档：

> 进入节点管理，你会发现可能是使用 localhost，123.x.x.x 或其他域名连接到远程节点的，此时你必须要给每一个远程节点分别配置一次反向代理，让它们全部使用 HTTPS+Websocket 连接。
> 
> 配置完成后，使用 wss://localhost，wss://123.x.x.x 或 wss://domain.com 替换原有的localhost，123.x.x.x 或 domain.com即可。

原本本地填写的是"localhost"，如果使用了反向代理，那么节点代理后的地址假如是x.x.x.x，如果面板使用http的话，填写"ws://x.x.x.x"，如果面板使用https的话，节点要反代https，填写"wss://x.x.x.x"。必须手动加上ws或者wss才行

**Comment by thepiationesl** [comment]
这很好了，我之前也是这么解决的，只是后面忘记回来回复了
________________________________
发件人: BoenShi ***@***.***>
发送时间: 2025年10月7日 15:13
收件人: MCSManager/MCSManager ***@***.***>
抄送: PiationESL ***@***.***>; Comment ***@***.***>
主题: Re: [MCSManager/MCSManager] [Bug Report] xhr poll error (Issue #1259)

[https://avatars.githubusercontent.com/u/89004452?s=20&v=4]BoenShi128 left a comment (MCSManager/MCSManager#1259)<https://github.com/MCSManager/MCSManager/issues/1259#issuecomment-3375509158>

我找到解决方案了，仔细阅读下官方文档：

进入节点管理，你会发现可能是使用 localhost，123.x.x.x 或其他域名连接到远程节点的，此时你必须要给每一个远程节点分别配置一次反向代理，让它们全部使用 HTTPS+Websocket 连接。

配置完成后，使用 wss://localhost，wss://123.x.x.x 或 wss://domain.com 替换原有的localhost，123.x.x.x 或 domain.com即可。

原本本地填写的是"localhost"，如果使用了反向代理，那么节点代理后的地址假如是x.x.x.x，如果面板使用http的话，填写"ws://x.x.x.x"，如果面板使用https的话，节点要反代https，填写"wss://x.x.x.x"。必须手动加上ws或者wss才行

―
