### ISSUE TITLE
[Bug Report] 一样的启动命令终端上可以开，面板上开不了。

### ISSUE THREAD

**Issue by clover1420** [MCSManager/MCSManager#1260]
### Platform

Ubuntu Server 22.04

### Panel Version

10.1.0

### Daemon Version (Optional)

4.3.0

### Recurrence Probability

100%

### Bug Description

在终端能启动
![image](https://github.com/MCSManager/MCSManager/assets/47273274/3416618a-4133-488b-9654-65bad4507efe)
在面板上启动不了
![image](https://github.com/MCSManager/MCSManager/assets/47273274/321ff1d4-e7d9-4dcf-b276-683ac2d9c0ea)
用快速部署也启动不了。

**Comment by clover1420** [comment]
工作路径也是一样的
![image](https://github.com/MCSManager/MCSManager/assets/47273274/d1b308c6-5581-4e35-82e6-670f7afa8429)

**Comment by clover1420** [comment]
工作路径也是一样的
![image](https://github.com/MCSManager/MCSManager/assets/47273274/d1b308c6-5581-4e35-82e6-670f7afa8429)

**Comment by huangsijun17** [comment]
$PATH问题，导致的找不到java程序？

**Comment by clover1420** [comment]
刚试了下。
用了java路径地址可以启动了。
用系统环境变量就启动不了。

**Comment by huangsijun17** [comment]
> 刚试了下。 用了java路径地址可以启动了。 用系统环境变量就启动不了。

你的MCSM是systemd启动的吧？java安装后是通过当前用户的.bashrc添加到$PATH等环境变量的话，systemd级下游进程是不会加载用户.bashrc来添加环境变量的。
很多人都这问题。
