### ISSUE TITLE
[Bug Report] Docker jdk17 环境中文乱码

### ISSUE THREAD

**Issue by SnowSwordScholar** [MCSManager/MCSManager#1261]
### Platform

Debian 12 bookworm

### Panel Version

10.1.0

### Daemon Version (Optional)

4.2.0

### Recurrence Probability

100

### Bug Description

在树莓派4B （ARM）上使用 MCSM 中  镜像管理 - 新增镜像 - 创建OpenJDK 17环境镜像 以默认参数搭建 Docker 环境并运行后，发现出现有乱码问题 （程序输出中文乱码，文件路径乱码，有中文的插件不加载）
```
sh-4.4# cd plugins
sh-4.4# ls
'[Tab'$'\345\261\225\347\244\272'']TitleManager-2.3.6 (1).jar'
'['$'\344\274\240\351\200\201'']LiteTeleport-1.9.1.jar'
```
运行 `locale -a`
```
sh-4.4# locale -a
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
C.utf8
POSIX
```
发现没有 zh_CN.utf8 语言 （宿主机有）
直接将构建的 Dockerfile 中所有 `zh_CN.utf8` 改为 `C.utf8`，问题解决，文件名正常显示，插件加载
```
sh-4.4# ls
 '[Tab展示]TitleManager-2.3.6 (1).jar'
 '[传送]LiteTeleport-1.9.1.jar'
```

**Comment by YuMao233** [comment]
这个影响的因素很多，没有办法一概而论，可以尝试开启或关闭仿真终端，调整输出编码等操作进行尝试。

虽然回复有点晚，抱歉。
