### ISSUE TITLE
[Bug Report] 新建实例时上传的压缩文件无法自动解压

### ISSUE THREAD

**Issue by CLOT-LIU** [MCSManager/MCSManager#1262]
### Platform

CentOS 7.9.2009 x86_64(Py3.7.9)

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

100%

### Bug Description

好像是面板更新到最新之后，就没法上传自动解压，基本每一个文件都是这样，上传后无法自动解压只能手动进行解压

**Comment by huangsijun17** [comment]
压缩文件格式？压缩时的参数有吗？

**Comment by CLOT-LIU** [comment]
> 压缩文件格式？压缩时的参数有吗？

都是用的ZIP格式，压缩参数这个我不太清楚，没有额外设置过，都是直接压缩的

**Comment by CLOT-LIU** [comment]
用的是Bandizip，系统是Win11，服务器是CentOS 7

**Comment by CLOT-LIU** [comment]
> > > 压缩文件格式？压缩时的参数有吗？
> > 
> > 
> > 都是用的ZIP格式，压缩参数这个我不太清楚，没有额外设置过，都是直接压缩的
> 
> 压缩工具和所在系统知道吗？



> > > 压缩文件格式？压缩时的参数有吗？
> > 
> > 
> > 都是用的ZIP格式，压缩参数这个我不太清楚，没有额外设置过，都是直接压缩的
> 
> 压缩工具和所在系统知道吗？

用的是Bandizip，系统是Win11，服务器是CentOS 7

**Comment by CLOT-LIU** [comment]
> > > 压缩文件格式？压缩时的参数有吗？
> > 
> > 
> > 都是用的ZIP格式，压缩参数这个我不太清楚，没有额外设置过，都是直接压缩的
> 
> 压缩工具和所在系统知道吗？

用的是Bandizip，系统是Win11，服务器是CentOS 7

**Comment by CLOT-LIU** [comment]
> > > 压缩文件格式？压缩时的参数有吗？
> > 
> > 
> > 都是用的ZIP格式，压缩参数这个我不太清楚，没有额外设置过，都是直接压缩的
> 
> 压缩工具和所在系统知道吗？
[1.21_server_pack.zip](https://github.com/user-attachments/files/15911128/1.21_server_pack.zip)

刚用这个文件测试了，还是不能自动解压

**Comment by unitwk** [comment]
确实不清楚缘由，这个问题我在 Linux 上尝试解压是正常的，猜测是权限导致的问题。

你可以执行 `chmod -R 777 /opt/mcsmanager/daemon/lib` 尝试一下。

**Comment by CLOT-LIU** [comment]
> 确实不清楚缘由，这个问题我在 Linux 上尝试解压是正常的，猜测是权限导致的问题。
> 
> 你可以执行 `chmod -R 777 /opt/mcsmanager/daemon/lib` 尝试一下。

还是不行，给完权限之后还是一样，换浏览器之后也还是无法解压
