### ISSUE TITLE
提供file-zip和pty的macOS Intel(Darwin_x64)版本

### ISSUE THREAD

**Issue by xycabcd** [MCSManager/MCSManager#1264]
[file-zip and pty darwin_x64.zip](https://github.com/user-attachments/files/15847677/file-zip.and.pty.darwin_x64.zip)
编译时间：2024/6/15

如果需要自己编译新版本，
先到https://go.dev/dl/下载amd64-macos的Go编译器，注意选择Archive，选pkg的话安装以后就删不掉了
到https://github.com/MCSManager/PTY和https://github.com/MCSManager/Zip-Tools下载源码
解压后打开.github/workflows/build.yml
在name: Build
        run: |
下面，GOARCH=某某某 后面就是命令了。
虽然有不同平台版本的，但是命令都是一样的。
拷出来大概是这样
go build -trimpath -ldflags '-s -w --extldflags "-static -fpic"' -o 
根据对应软件在-o后面写file_zip_darwin_x64或者pty_darwin_x64
将获得的两条命令存起来
解压Go编译器文件夹
进入解压的文件夹，打开终端，进行如下输入

`export PATH=`(将Go编译器文件夹里的“bin”文件夹拖进终端，此时会自动加一个空格，删掉)`:$PATH`
`cd `(将PTY/Zip-Tools文件夹拖进终端)
(前面保存的对应命令)
`cd `(将PTY/Zip-Tools文件夹拖进终端)
(前面保存的对应命令)

然后就可以关闭终端了
然后删除Go编译器文件夹
打开PTY/Zip-Tools,在里面可以看到编译好的文件。
将文件拖进MCSManager文件夹下面的对应地方即可

**Comment by Bluemangoo** [comment]
还是我有先见之明我早在半个月前就猜到会这样了。

**Comment by Bluemangoo** [comment]
乐。双羽好像甚至没有构建Darwin的。急的话自己构建一下。

https://github.com/MCSManager/Zip-Tools

**Comment by unitwk** [comment]
官网也没说支持 MacOS 呀~

**Comment by Bluemangoo** [comment]
你那个开发脚本（运行全部）都是macos特供的。。

**Comment by YuMao233** [comment]
fixed: https://github.com/MCSManager/MCSManager/releases/tag/v10.4.0
