### ISSUE TITLE
[Feature] 恳请官方开放更新实例的API接口文档

### ISSUE THREAD

**Issue by undefined-hestudio** [MCSManager/MCSManager#1266]
### Description

![屏幕截图(53)](https://github.com/MCSManager/MCSManager/assets/119711513/3c0b2ba0-c881-45ff-a209-601797bde24f)

我在点击更新按钮时候，通过日志抓到对应的POST请求，但未找到该接口的文档：`[INFO] [HTTP] POST: http://127.0.0.1:23333/api/protected_instance/asynchronous`

### Reason

我在做一个服务端程序，每当我更新后，我可以通过api快速完成开启或者关闭服务器功能，但是如果我需要更新服务器，需要手动登录管理平台手动点击更新，而不是通过api自动化操作。恳请官方开放对应的api文档

**Comment by Bluemangoo** [comment]
抓一下也差不多知道了。
