### ISSUE TITLE
[Bug Report] 在docker中运行MCSM时，启用容器化会出现bind error

### ISSUE THREAD

**Issue by longxiaokong** [MCSManager/MCSManager#1271]
### Platform

Synology DS923+

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

100%

### Bug Description

我目前在container manager上运行MCSM，但是即使映射以后的路径在NAS本机上的确存在，MCSM会汇报bind error。我不知道该如何解决。
报错：
```
[INFO] Preparing to start...
[Operation Error] (HTTP code 400) unexpected - invalid mount config for type "bind": bind source path does not exist: /opt/docker-mcsm/daemon/data/InstanceData/e20485bb780c44a2abcb4c5f4954fa52
```
路径：
<img width="502" alt="截屏2024-06-20 17 06 37" src="https://github.com/MCSManager/MCSManager/assets/48619396/a636c327-9ef9-4db0-89d1-f3355e58b68d">
映射配置：
<img width="670" alt="截屏2024-06-20 17 07 25" src="https://github.com/MCSManager/MCSManager/assets/48619396/c94efaf8-b87e-4c15-bc9d-3c715308ac5e">
其中，上方是本机daemon/data映射到容器daemon/data，下方是本机log映射到容器log。

**Comment by unitwk** [comment]
应该是两边映射的路径名字要相同：/opt/docker-mcsm/daemon/data/InstanceData/e20485bb780c44a2abcb4c5f4954fa52

**Comment by longxiaokong** [comment]
我用issue #1037 里的软连接的方法解决了。
nas环境实在有限我不太敢让两边映射的路径相同，因为官方说非volume内的文件夹重启的时候有可能会重置。
所以为什么需要两边映射的路径完全相同呢，是因为容器内的docker调用了宿主机的目录而非层层向上地映射路径吗（

**Comment by YuMao233** [comment]
fixed: https://github.com/MCSManager/MCSManager/releases/tag/v10.4.0

现在支持不绑定文件管理目录到 /workspace，留空即可。
