### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by SelimGOZ** [MCSManager/MCSManager#1275]
### Platform

Ubuntu 24.04

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

1% - 20%

### Bug Description

1. Setted up nginx proxy
2. domain connected working
3. terminal requires wss and errors out with either timeout or xhr poll error including http on domain
4. tryed http with the private ip worked public ip cant log in
5. tryed https with private ip nothin public ip still nothing
6. idk how i made this bug trigger btw it just happened.

**Comment by unitwk** [comment]
I think you made a mistake in one of the key steps. You can refer to this article:

https://docs.mcsmanager.com/ops/proxy_https.html

**Comment by SelimGOZ** [comment]
> I think you made a mistake in one of the key steps. You can refer to this article:
> 
> 
> 
> https://docs.mcsmanager.com/ops/proxy_https.html

I got it to work now but ws never accepted my ssl but everything else did any clue why?

**Comment by unitwk** [comment]
> > I think you made a mistake in one of the key steps. You can refer to this article:
> > https://docs.mcsmanager.com/ops/proxy_https.html
> 
> I got it to work now but ws never accepted my ssl but everything else did any clue why?

I don't know either, maybe there is something wrong with the configuration file.

**Comment by Bluemangoo** [comment]
paste your nginx config please.

**Comment by SelimGOZ** [comment]
# Sample HTTPS reverse proxy for MCSManager Web Panel
server
    {
		# Public HTTPS port for the panel (use multiple `listen` directive for multiple ports)
		listen 12333 ssl http2; #IPV4

		# Enable HSTS. Once enabled, it will enforce the use of HTTPS to connect to the panel and will continue for a year after this policy is cancelled, unless manually cleared in the browser.
		# Disable by default, uncomment to enable.
		#add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";

		# DNS resolver, only required when the traffic will be forwarded to a remote panel connected via a domain.
		resolver 8.8.8.8;

		# Automatically redirect HTTP to HTTPS
		error_page 497 https://$host:$server_port$request_uri;

		proxy_hide_header Upgrade;
		location / {
				# Request Headers. No need to change in general
				proxy_set_header Host $host;
				proxy_set_header X-Real-Ip $remote_addr;
				proxy_set_header X-Forwarded-For $remote_addr;
				proxy_set_header REMOTE-HOST $remote_addr;

				# Target daemon address and port. Support domain and HTTPS.
				proxy_pass http://localhost:23333;

				# Support WebSocket
				proxy_set_header Upgrade $http_upgrade;
				proxy_set_header Connection "upgrade";

				# Max size for a single file being transferred. 0 for unlimited.
				client_max_body_size 0;

				# Disable cache
				proxy_request_buffering off;
				proxy_buffering off;
				  }

		# Path to HTTPS certificate and key
		ssl_certificate /etc/nginx/ssl/domain.crt;
		ssl_certificate_key /etc/nginx/ssl/domain.key;

		# Enable gzip by default
		gzip on;

		# File that will be compressed during transfer
		gzip_types text/plain text/css application/javascript application/xml application/json;

		# Enable compression with reverse proxy
		gzip_proxied any;

		# Compression level during transmission; the higher the level, the more CPU is used for compression.
		# The maximum level is 9, but usually, level 5 is sufficient
		gzip_comp_level 5;

		# Only compress when the size during transmission reaches 1k, as compressing smaller content is pointless.
		gzip_min_length 1k;

		# Supported protocols, algorithms, and timeout settings, etc. Generally, there's no need to change these.
		ssl_session_timeout 5m;
		ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
		ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
		ssl_prefer_server_ciphers on;
    }
