### ISSUE TITLE
[Bug Report] 双重登录验证（2FA）无法使用

### ISSUE THREAD

**Issue by jesongit** [MCSManager/MCSManager#1279]
### Platform

docker

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

100%

### Bug Description

控制台报错如下
![image](https://github.com/MCSManager/MCSManager/assets/29886847/dd5bfa3b-a6bf-4944-93a2-510a8f2c872a)

**Comment by unitwk** [comment]
我们晚些时候复现并检查一下，谢谢你的反馈。

**Comment by alongw** [comment]
查看下面板后台的终端是否有报错

**Comment by jesongit** [comment]
> 查看下面板后台的终端是否有报错

docker日志中只能看到请求，没有任何报错
![image](https://github.com/MCSManager/MCSManager/assets/29886847/c519a641-22cd-46ec-a2c8-e696ac9e5c57)

**Comment by rrrexfield** [comment]
点击绑定按钮后，后台输出
```
[07/29 00:31:17] [INFO] [HTTP] POST: http://mcsm.****.com/api/auth/bind2fa?token=e116c672eac34151b******
[07/29 00:31:17] [INFO] [HTTP] IP: ::ffff:127.0.0.1 USER: adminl UUID: a5a1c3ffce8841fca8******
```

网页返回 `status 400`

参考issue #1243

**Comment by YuMao233** [comment]
fixed: https://github.com/MCSManager/MCSManager/releases/tag/v10.4.0
