### ISSUE TITLE
[Feature] 建议把支持登录页的markdown自定义文字的位置

### ISSUE THREAD

**Issue by Shizoukia** [MCSManager/MCSManager#1280]
### Description

将 自定义markdown登录页消息的位置调整在偏左并且支持独立一个区域显示

现在是:
`-------------------------`
`用户名`
`密码`
`自定义消息 登录按钮`
`---------------------------`

希望改成:

`---------------------------`
`自定义消息  | 用户名`
`            | 密码`
`            | 登入按钮`
`--------------------------`

### Reason

比如 这是mcsm8的页面 我想的是 让这个消息可以自然地放在左边 右边则是登录框 左边是详细信息等

现在这个umm 放在登录框下面如果文字太多看着可能有点怪
只是个建议 希望采纳
![image](https://github.com/MCSManager/MCSManager/assets/103182720/6f04a2dc-220f-4fdb-ba26-fc5e36c0a3b5)

**Comment by unitwk** [comment]
MCSM 10 已经满足了你的需求，MCSM右上角可以自定义卡片，自己设计布局，你只需要添加 Markdown 卡片放在登录框的旁边即可。

**Comment by Shizoukia** [comment]
奥 原来可以编辑登录页面的格式吗 感谢回复 麻烦了qwq
