### ISSUE TITLE
[Feature] 在守護進程關閉前等待所有實例完全停止

### ISSUE THREAD

**Issue by shou692199** [MCSManager/MCSManager#1282]
### Description

當daemon收到關閉訊號時，等待所有實例正確停止，或在超過30秒後強制停止未關閉的實例

### Reason

盡可能確保實例資料安全的儲存完畢

**Comment by Bluemangoo** [comment]
本来就等待啊。

**Comment by shou692199** [comment]
我修正一下說法：
現在v10的版本不像以前有一個啟動器exe，並沒有停止daemon的按鈕了，目前我是用Windows服務的方式去啟動，但是當關閉服務時並沒有所謂的“等待”

**Comment by unitwk** [comment]
> 我修正一下說法： 現在v10的版本不像以前有一個啟動器exe，並沒有停止daemon的按鈕了，目前我是用Windows服務的方式去啟動，但是當關閉服務時並沒有所謂的“等待”

我不清楚 Windows 服务停止的逻辑，但是我知道在 Linux 下如果你停止一个服务，系统会先发出退出事件信号，MCSM会捕捉到它并且开始强杀所有实例进程，但是系统只会给MCSM几秒钟的时间来做最后收尾，超过几秒钟系统会强杀服务所有子进程。

**Comment by Bluemangoo** [comment]
Windows的服务操作是个句柄。我觉得你应该找注册服务的那个工具。

**Comment by shou692199** [comment]
這個是我用 `.\node_app.exe app.js` 啟動完，透過Ctrl+C進行退出的結果:
![image](https://github.com/MCSManager/MCSManager/assets/45505768/a1bd6ba0-af9f-45c7-8b87-ea77f40463e7)

可以看到 `Instance *** is running or busy, and is being forced to end`，所以無論是否為服務，都沒有正確的向實例發送關閉訊號

至於我的服務建立工具為winsw，官方文檔標明預設給予15秒的等待時間，且可以自行調整，因此服務工具並不會造成問題

**Comment by shou692199** [comment]
> 我不清楚 Windows 服务停止的逻辑，但是我知道在 Linux 下如果你停止一个服务，系统会先发出退出事件信号，MCSM会捕捉到它并且开始强杀所有实例进程，但是系统只会给MCSM几秒钟的时间来做最后收尾，超过几秒钟系统会强杀服务所有子进程。

也許這就是你說的"強殺"，不過我個人覺得這對Minecraft伺服器的資料保存不是那麼安全，既然Windows的寬限時間比較高，我會希望盡可能避免採用強制停止的方式

**Comment by unitwk** [comment]
强制杀死进程的意思是使用 `taskkill /PID ${pid} /T /F` 系统命令杀死进程。

我不知道你想表达什么，很明显最后的那几个输出 `Instance *** (***) saved successfully.` 就已经代表 MCSM 成功的执行了 `taskkill /PID ${pid} /T /F` 系统命令。

至于说这种方式对数据保存不是那么安全，想必你也清楚 Windows 只会给你 15 秒的时间，但并不是所有人的 Minecraft 都那么简单，有些人安装了上百个插件或者 MOD，他们可能光是关服就需要一分钟，如果MCSM不及时终止进程，那么就很有可能会成为一个「野生的」进程，无法再被控制。

**Comment by shou692199** [comment]
謝謝你，那我再視需要自行修改就可以了
