### ISSUE TITLE
[Bug Report] 自配预设文件安装实例 应用实例内 重装功能按钮失效

### ISSUE THREAD

**Issue by YeziMoanan** [MCSManager/MCSManager#1291]
### Platform

windows 10

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4

### Recurrence Probability

100%

### Bug Description

背景：
首先我是使用我自己的预设文件并且在一键安装的时候能够正常安装(虽然会出现一个错误 实际上已经安装解压了)
我在应用实例内 进行重装的操作 确定之后弹窗消失无效果
我在后台没有看到直链流量消耗情况 应是调用失败
![预设渲染页面](https://github.com/MCSManager/MCSManager/assets/133692540/355782c0-02f4-4981-9f7b-36c923ac34d5)
提供：
123盘测试 预设文件直链
https://vip.123pan.cn/1812002214/5832157
可能性：
1.我通过languages字段达成了伪分类，第一遍加载不出页面/提示timeout 10000，第二遍或者实际上已经加载成功
或许因为这个地方 是因为什么默认的配置 导致的错误 以至于再重装时出现该问题
2.或许因为 我 updateCommand 字段为空 导致没有实际操作？
其他问题：
假设我的steam游戏预设是steamcmd已安装好的包 又或者 其他类型
在预设安装时 命令执行的流程 是 startCommand 还是 updateCommand 仅执行单个 还是 存在顺序
mc 可以 安装 启用 一体化
针对于steam游戏 启动安装是不一样的 针对steam游戏预设 有没有 先更新/安装 再执行启动命令的配置流程

**Comment by unitwk** [comment]
1. 你的第一点我没有看懂，我只知道你想表达报了一个错误。

2. 关于第二点已经其他问题：设置 updateCommand 字段后，可以实现选择一键部署后自动执行 updateCommand。

最后，写长文本的时候，请正确使用标点符号，不要用空格，看着难受。

**Comment by YeziMoanan** [comment]
我重新看了一下原来的提问，原来问题在背景里描述了，我重新描述一下未解决问题。
就是在使用自己配置的预设文件时，出现了一些问题。
主要问题：在预设安装的实例里，重装预设时没有反应。
其他衍生问题-方便定位
衍生问题1：本身没有“标签”这个类型，但我仿造languages字段，实现伪分类。在预设列表加载这个预设文件时会出现两种情况，弹出timeout 10000，或者无响应。重新点击预设列表或点击“所有语言”，预设列表窗口渲染正常。
衍生问题2：在安装我自己配置的预设文件中的实例时，出现了一个错误(提示就是出现什么什么错误)，但实际上已经下载解压完成了。
这是我的预设直链，可供于问题复现测试：https://vip.123pan.cn/1812002214/5832157

**Comment by alongw** [comment]
`languages` 字段需遵守国际标准化组织 ISO639 语言代码标准 [维基百科](https://en.wikipedia.org/wiki/ISO_639)，不能自定义或代替标签使用。  
如果强制使用，可能出现一些潜在的问题。  
如有需要，后续可能会增加相关功能。

**Comment by YuMao233** [comment]
fixed
