### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by cyxnzb** [MCSManager/MCSManager#1293]
### Platform

Windows Server 2022 Datacenter

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

99%

### Bug Description

通用控制台程序开启事件触发任务里的”自动重启“功能无效，当程序异常退出后，不会自动重启

**Comment by cyxnzb** [comment]
"goldsrcds.exe" -game cstrike +servercfgfile server.cfg +maxplayers 32 +map zm_five -port 27015 +sv_lan 0   -console -master  -pingboost 5 -noipx

我是用来开CS服务器的，这是我填的启动命令

**Comment by huangsijun17** [comment]
CS服务器？CS 2？Steam的？安装时的编号多少？

**Comment by cyxnzb** [comment]
> CS服务器？CS 2？Steam的？安装时的编号多少？

CS1.6的，然后准确的说是基于8684正版然后加上Regamedll结合而成的Rehlds的服务端开的，主要运行方式还是调用hlds.exe
编号没记错的话是90
不过现在通过90下载的好像是9XXX的版本
