### ISSUE TITLE
[Feature] 能不能在批量操作增加一个重启

### ISSUE THREAD

**Issue by kazuhaAyato** [MCSManager/MCSManager#1294]
### Description

![image](https://github.com/MCSManager/MCSManager/assets/66939153/29deb2f5-3a13-4437-b4d0-da70671f86e6)
这里

### Reason

手动再选择有点繁琐。

**Comment by kazuhaAyato** [comment]
补充一下，主要是经常要一整个大区下的所有游戏房间全部重启，一个一个点挺麻烦的*

**Comment by unitwk** [comment]
全部关闭+全部开启 = 全部重启。

好吧，这个当然不是一个很好的方案，你可以先这样使用，后续我会分配人加上的。

**Comment by LazyCreeper** [comment]
最新版代码已经包含重启的代码

**Comment by unitwk** [comment]
那就下次发新版会加上的
