### ISSUE TITLE
雨云MCSManager面板屏幕不适应

### ISSUE THREAD

**Issue by CraftBlockht6x** [MCSManager/MCSManager#1295]
### Platform

Android

### Panel Version

10.2.1

### Recurrence Probability

100%

### Bug Description

雨云更新了最新版本的MCSManager面板，但是面板出现了许多bug。不适应手机屏幕，页面样式不是特别好。并且窗口无法拖动，设置修改麻烦，实例控制组按钮与控制台冲突，不利于开关服务器，终端没有颜色渲染，文件编辑没有保存按钮，等等...各种bug。
这次更新不如更新前的版本，建议修好这些bug。

[Bug展示可以查看这个视频](https://b23.tv/vcLRuVO)
![Screenshot_20240706_160218](https://github.com/MCSManager/MCSManager/assets/153402187/936512ed-be1e-4715-881d-ddab940e338d)
![Screenshot_20240706_160204](https://github.com/MCSManager/MCSManager/assets/153402187/74432549-c836-43e2-898c-aa3e38ab2e7c)
![Screenshot_20240706_160137](https://github.com/MCSManager/MCSManager/assets/153402187/75aee69a-442d-47b7-905b-4d3013dc3f2e)
![Screenshot_20240706_160117](https://github.com/MCSManager/MCSManager/assets/153402187/9cadb36b-59b4-43ed-976e-9e88bb53b22f)
![Screenshot_20240706_160218](https://github.com/MCSManager/MCSManager/assets/153402187/bfedd96d-8d75-413d-8015-370ae0d7a9f1)

**Comment by huangsijun17** [comment]
css样式掉了？刷新几次试一下？？
什么系统的哪个浏览器？

**Comment by CraftBlockht6x** [comment]
> css样式掉了？刷新几次试一下？？什么系统的哪个浏览器？

使用的是vivo手机系统自带的浏览器，尝试多次刷新，但是样式没能出现，原有的bug依旧存在
![Screenshot_20240706_162355](https://github.com/MCSManager/MCSManager/assets/153402187/8b7443b3-a9cf-4261-ad98-9daea3cd7d26)

**Comment by unitwk** [comment]
这个是雨云的问题，请你找他们的客服前往反馈。
