### ISSUE TITLE
[Bug Report] 普通用户上传文件的时候会报错

### ISSUE THREAD

**Issue by cyxnzb** [MCSManager/MCSManager#1296]
### Platform

Windows Server 2022 Datacenter

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

99%

### Bug Description

用户上传压缩包超过500MB后会在上传的过程中出现提示“Network Error"的错误
查看控制台，提示错误：
[07/07 00:47:57] [ERROR] koaBody Lib Error: FormidableError: Request aborted
    at IncomingMessage.<anonymous> (D:\MCSManager-v10-windows-x64\mcsmanager\daemon\node_modules\formidable\dist\index.cjs:1223:21)
    at IncomingMessage.emit (node:events:518:28)
    at IncomingMessage._destroy (node:_http_incoming:224:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:793:9)
    at socketOnClose (node:_http_server:787:3)
    at Socket.emit (node:events:530:35)
    at TCP.<anonymous> (node:net:337:12) {
  code: 1002,
  httpCode: 500
}

**Comment by huangsijun17** [comment]
是否使用了Nginx反向代理？

[参考这个](https://docs.mcsmanager.com/zh_cn/ops/proxy_https.html#%E4%B8%BA%E8%8A%82%E7%82%B9%E5%BC%80%E5%90%AF%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86)，加入：
``` nginx
# 最大文件上传大小限制。设置0为不限制
client_max_body_size 0;
```

**Comment by cyxnzb** [comment]
> 是否使用了Nginx反向代理？
> 
> [参考这个](https://docs.mcsmanager.com/zh_cn/ops/proxy_https.html#%E4%B8%BA%E8%8A%82%E7%82%B9%E5%BC%80%E5%90%AF%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86)，加入：
> 
> ```nginx
> # 最大文件上传大小限制。设置0为不限制
> client_max_body_size 0;
> ```

没有使用反向代理，不过可能是因为我的主机同时还运行宝塔的缘故？

**Comment by unitwk** [comment]
可以检查一下，面板本身是没有限制上传文件大小的

**Comment by huangsijun17** [comment]
> > 是否使用了Nginx反向代理？
> > [参考这个](https://docs.mcsmanager.com/zh_cn/ops/proxy_https.html#%E4%B8%BA%E8%8A%82%E7%82%B9%E5%BC%80%E5%90%AF%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86)，加入：
> > ```nginx
> > # 最大文件上传大小限制。设置0为不限制
> > client_max_body_size 0;
> > ```
> 
> 没有使用反向代理，不过可能是因为我的主机同时还运行宝塔的缘故？

宝塔部署？有开https吗？

**Comment by cyxnzb** [comment]
> > > 是否使用了Nginx反向代理？
> > > [参考这个](https://docs.mcsmanager.com/zh_cn/ops/proxy_https.html#%E4%B8%BA%E8%8A%82%E7%82%B9%E5%BC%80%E5%90%AF%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86)，加入：
> > > ```nginx
> > > # 最大文件上传大小限制。设置0为不限制
> > > client_max_body_size 0;
> > > ```
> > 
> > 
> > 没有使用反向代理，不过可能是因为我的主机同时还运行宝塔的缘故？
> 
> 宝塔启动nodejs项目？Doocker项目？有开https吗？

按理说应该两者是独立开的，因为我宝塔啥web项目都没弄，仅仅借助宝塔起了个mysql，而且是就开了个应用程序，因为本身我主机是Windows Server操作系统，就没装Docker了

**Comment by cyxnzb** [comment]
> > > > > 是否使用了Nginx反向代理？
> > > > > [参考这个](https://docs.mcsmanager.com/zh_cn/ops/proxy_https.html#%E4%B8%BA%E8%8A%82%E7%82%B9%E5%BC%80%E5%90%AF%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86)，加入：
> > > > > ```nginx
> > > > > # 最大文件上传大小限制。设置0为不限制
> > > > > client_max_body_size 0;
> > > > > ```
> > > > 
> > > > 
> > > > 没有使用反向代理，不过可能是因为我的主机同时还运行宝塔的缘故？
> > > 
> > > 
> > > 宝塔启动nodejs项目？Doocker项目？有开https吗？
> > 
> > 
> > 按理说应该两者是独立开的，因为我宝塔啥web项目都没弄，仅仅借助宝塔起了个mysql，而且是就开了个应用程序，因为本身我主机是Windows Server操作系统，就没装Docker了
> 
> 你的MCSM不是从宝塔安装的对吧？

不是，两者是分开的，我直接下载下来mcsm然后运行的

**Comment by Bluemangoo** [comment]
status500应该不是体积限制问题。体积限制好像是513还是什么。
