### ISSUE TITLE
能否给文件管理添加一个压缩功能

### ISSUE THREAD

**Issue by RogueKGB** [MCSManager/MCSManager#1298]
### Description

文件管理可以解压压缩包，但是不能压缩文件/文件夹。我需要压缩文件/文件夹功能以便于取出我的官方基岩版服务器里的存档，如果有的话能告诉我在哪吗

### Reason

我需要取出存档调整存档里的行为包和资源包
找到了一个"Zip-tools"的工具但是不会用，也找不到教程(心累.jpg)

**Comment by unitwk** [comment]
目前版本选两个文件就才会显示压缩按钮，后续版本会优化这个问题。

**Comment by CodeZhangBorui** [comment]
支持，等待更新。

**Comment by YuMao233** [comment]
fixed: https://github.com/MCSManager/MCSManager/releases/tag/v10.4.0
