### ISSUE TITLE
[Bug Report] 就是用openwrt docker 装的mcsm无法定位到java目录，java环境也配置了

### ISSUE THREAD

**Issue by xiaomo-xxx** [MCSManager/MCSManager#1299]
### Platform

istoreos 2024/7/13

### Panel Version

10.1

### Recurrence Probability

100%

### Bug Description

![QQ截图20240713105633](https://github.com/user-attachments/assets/5ed948ce-0e51-4314-94c9-639e8b796cdb)
![QQ截图20240713105645](https://github.com/user-attachments/assets/3dd58495-cea2-462e-be02-0bf1587b1a7e)
怎么样都缺少不到java环境

**Comment by xiaomo-xxx** [comment]
java环境
![QQ截图20240713105814](https://github.com/user-attachments/assets/c2eb39ba-928d-44cf-9ebd-789b1749f6b4)

**Comment by unitwk** [comment]
你的java环境安装在主机上，但是MCSM 运行在 Docker 中？这样无论如何都是无法读取的。

**Comment by xiaomo-xxx** [comment]
> 你的java环境安装在主机上，但是MCSM 运行在 Docker 中？这样无论如何都是无法读取的。
> 

好的，知道了谢谢
