### ISSUE TITLE
where is # Install dependencies ./install.sh

### ISSUE THREAD

**Issue by mcfishyu** [MCSManager/MCSManager#1302]
### Platform

Ubantu 22

### Panel Version

10.0

### Daemon Version (Optional)

4.3.0

### Recurrence Probability

100%

### Bug Description

You can't find install.sh after decompressing the file when installing according to your document. You note the steps of installing dependencies./install.sh ("# Install dependencies
./install.sh") I was confused

就是按照你们的文档安装的时候 解压完文件找不到install.sh ，你们批注写了安装依赖的脚步./install.sh ("# Install dependencies
./install.sh") 我很疑惑

**Comment by mcfishyu** [comment]
node 16

**Comment by huangsijun17** [comment]
> I hope it can be solved as soon as possible, thank you. In addition, I hope we can communicate at noon. I am Chinese 希望可以尽快解决，谢谢你们，另外希望可以中午沟通，我是中国人

为什么中午沟通？因为早晚会出事？

**Comment by mcfishyu** [comment]
> > I hope it can be solved as soon as possible, thank you. In addition, I hope we can communicate at noon. I am Chinese 希望可以尽快解决，谢谢你们，另外希望可以中午沟通，我是中国人
> 
> 为什么中午沟通？因为早晚会出事？

hhh 打错字力，然后翻译也错了，哈哈哈哈哈，笑死

**Comment by mcfishyu** [comment]
问题也解决了，我下载了低版本的，这个issues怎么关？（疑惑）
