### ISSUE TITLE
[Feature] Add TOML syntax highlight support

### ISSUE THREAD

**Issue by Wesley-Young** [MCSManager/MCSManager#1306]
### Description

TOML syntax highlight support, just like what has be done for `.properties` and YAML.

### Reason

TOML is a relatively new configuration format and is adopted by Velocity and some other software.

As is shown in the picture, TOML files are not supported and experience a strange highlight recipe as follows:
<img width="854" alt="image" src="https://github.com/user-attachments/assets/ac71bbb7-add9-4508-9e0c-dd589ce0e0d6">

**Comment by unitwk** [comment]
Done
