### ISSUE TITLE
[Feature] Would you consider using Turborepo and bun to optimize your workflow

### ISSUE THREAD

**Issue by AH-dark** [MCSManager/MCSManager#1309]
### Description

Use bun to replace npm, and introduce turborepo to better manage ci and other workflows.

### Reason

I've seen projects using primitive methods to manage different packages. I think using bun workspaces and turborepo might bring better results.

**Comment by Bluemangoo** [comment]
bun cannot fully replace node currently.

but i support use pnpm workspace.

**Comment by AH-dark** [comment]
I will try to commit a replacement 😊.

**Comment by Bluemangoo** [comment]
btw i'm not in behalf of dev team. maybe ask @unitwk

**Comment by unitwk** [comment]
We will only consider using `pnpm` at most
