### ISSUE TITLE
[Feature] Auto-Start Server

### ISSUE THREAD

**Issue by bergenrackley** [MCSManager/MCSManager#1314]
### Description

A configuration setting for instances called "Run on Start" or "Auto-Start" that runs the instance when MCSManager comes online.

### Reason

Sorry if this is already a feature and I just couldn't find it, but from what I can tell this is not an option.
I run MCSManager at my server PC's startup, and it'd be nice if MCSManager could be set up to run some instances as it comes online. When I noticed this wasn't supported, I was hoping MCSManager could detect instances started externally, but it doesn't seem like it can, it can only tell the server is running if it started the server itself.

**Comment by Bluemangoo** [comment]
Duplicated of #1385

**Comment by bergenrackley** [comment]
Didn't realize it was a duplicate and already implemented, sorry about that.
For anyone who doesn't see it and finds this, it's under Event Tasks
