### ISSUE TITLE
[Bug Report] 添加URL前缀后，快捷跳转按钮没有改变跳转链接

### ISSUE THREAD

**Issue by HL-Light** [MCSManager/MCSManager#1316]
### Platform

Ubuntu22.04

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

100%

### Bug Description

![image](https://github.com/user-attachments/assets/7ed9b484-2455-4a7d-9986-cdfc713389ee)
如截图所示，点击上面的按钮可以正常调整，但下面的按钮为设置URL前缀之前的默认地址，导致跳转失败

**Comment by HL-Light** [comment]
![image](https://github.com/user-attachments/assets/5c0d0f56-bbc9-4f7f-ae81-0980c125629f)
在更新终端配置后此面板也会报错，但重新刷新网页可以正常访问，推测是更新后自刷新的连接也没用变更导致的

**Comment by Bluemangoo** [comment]
没发版导致的。

**Comment by HL-Light** [comment]
> 没发版导致的。

什么意思啊，没懂，我配置文件也修改了

**Comment by HL-Light** [comment]
> 修过了，没发布。
那我这个是等官方发修复版吗只有

**Comment by Bluemangoo** [comment]
你可以自己打包。

**Comment by HL-Light** [comment]
> 你可以自己打包。

了解了，感谢
