### ISSUE TITLE
[Bug Report] 建议将cn安装脚本里面的nodejs安装源改为清华等国内镜像源

### ISSUE THREAD

**Issue by Small-SaltedFish** [MCSManager/MCSManager#1320]
### Platform

CentOS

### Panel Version

latest

### Recurrence Probability

50%

### Bug Description

如题 nodejs.org链接全部超时 腾讯云上海报告
卡了半小时后手动修改脚本为清华源解决

**Comment by huangsijun17** [comment]
gitlab的安装包就是国内源。你都连上Github了，为什么还要国内源？

**Comment by Small-SaltedFish** [comment]
> gitlab的安装包就是国内源。你都连上Github了，为什么还要国内源？

我连上了github不代表我的国内服务器就可以很方便的解决网络问题呀！给服务器挂上梯子这个麻烦程度就大了

**Comment by Bluemangoo** [comment]
那你用gitlab的啊。

**Comment by Small-SaltedFish** [comment]
> 那你用gitlab的啊。

我不知道gitlab是国内源！我有观察到你们有分中文安装脚本 遂建议可以更改清华源

**Comment by unitwk** [comment]
已修复 https://github.com/MCSManager/Script/commit/8d9c710d3f030ebb7ffffd339a1ba9a1333620a3
