### ISSUE TITLE
[Bug Report] 启用`Steam Rcon功能`后服务器不能正常通过`Ctrl+C`命令关闭

### ISSUE THREAD

**Issue by EvolvedGhost** [MCSManager/MCSManager#1323]
### Platform

Ubuntu 22.04.4 LTS

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

100%

### Bug Description

1. 启用Steam Rcon功能
2. 设置服务器关闭方式为`^C`，设置为仿真终端，正常开启服务器
3. 点击关闭/重启服务器
4. 服务器无法接受`Ctrl+C`信号

初步分析我认为是MCSM将`Ctrl+C`信号以Rcon形式发送了

![Snipaste_2024-08-05_19-21-24](https://github.com/user-attachments/assets/43511535-22b8-4d2a-abf6-64c9decd04ee)

很显然在关闭的时候服务器通过Rcon发送了一个空信息，我认为应该把`^C`等操作排除Rcon发送，直接作用于服务器

**Comment by unitwk** [comment]
有道理，确实有问题，我后续处理下

**Comment by EvolvedGhost** [comment]
> 有道理，确实有问题，我后续处理下

嗯……这个ISSUE现在还关不了

在 aef5396 中并没有处理pty的关闭

在pty中关闭事件为

https://github.com/MCSManager/MCSManager/blob/bcda59c280f6f856ff86601566a6393cada34b72/daemon/src/entity/commands/pty/pty_stop.ts#L22-L24

他会调用到cmd.ts

https://github.com/MCSManager/MCSManager/blob/bcda59c280f6f856ff86601566a6393cada34b72/daemon/src/entity/commands/cmd.ts#L4-L12

而cmd.ts的这个command动作哪儿来的呢，是从这儿来的

https://github.com/MCSManager/MCSManager/blob/bcda59c280f6f856ff86601566a6393cada34b72/daemon/src/entity/commands/dispatcher.ts#L73-L75

pty的关闭相当于依然在用rcon发送^C

我简单修改了下cmd.ts的行为，如下：
```
import Instance from "../instance/instance";
import InstanceCommand from "./base/command";
import GeneralSendCommand from "./general/general_command";
import RconCommand from "./steam/rcon_command";

export default class SendCommand extends InstanceCommand {
  constructor(public readonly cmd: string) {
    super("SendCommand");
  }

  async exec(instance: Instance) {
    if(this.cmd == "\x03" && instance.config.enableRcon){
      instance.setPreset("command", new GeneralSendCommand());
      var temp = await instance.execPreset("command", this.cmd);
      instance.setPreset("command", new RconCommand());
      return temp
    }
    return await instance.execPreset("command", this.cmd);
  }
}
```

现在可以在启用pty和rcon的情况下正常关闭服务器了，但是这样的修复方式太野鸡了，所以不可能pr，可能还是得这边想办法怎么实现

**Comment by unitwk** [comment]
谢谢提醒，晚点我改改

**Comment by YuMao233** [comment]
fixed: https://github.com/MCSManager/MCSManager/releases/tag/v10.4.0

**Comment by EvolvedGhost** [comment]
> > 有道理，确实有问题，我后续处理下
> 
> 嗯……这个ISSUE现在还关不了
> 
> 在 [aef5396](https://github.com/MCSManager/MCSManager/commit/aef539633d8574bfa0198d4f10be05f617d22404) 中并没有处理pty的关闭
> 
> 在pty中关闭事件为
> 
> https://github.com/MCSManager/MCSManager/blob/bcda59c280f6f856ff86601566a6393cada34b72/daemon/src/entity/commands/pty/pty_stop.ts#L22-L24
> 
> 他会调用到cmd.ts
> 
> https://github.com/MCSManager/MCSManager/blob/bcda59c280f6f856ff86601566a6393cada34b72/daemon/src/entity/commands/cmd.ts#L4-L12
> 
> 而cmd.ts的这个command动作哪儿来的呢，是从这儿来的
> 
> https://github.com/MCSManager/MCSManager/blob/bcda59c280f6f856ff86601566a6393cada34b72/daemon/src/entity/commands/dispatcher.ts#L73-L75
> 
> pty的关闭相当于依然在用rcon发送^C
> 
> 我简单修改了下cmd.ts的行为，如下：
> 
> ```
> import Instance from "../instance/instance";
> import InstanceCommand from "./base/command";
> import GeneralSendCommand from "./general/general_command";
> import RconCommand from "./steam/rcon_command";
> 
> export default class SendCommand extends InstanceCommand {
>   constructor(public readonly cmd: string) {
>     super("SendCommand");
>   }
> 
>   async exec(instance: Instance) {
>     if(this.cmd == "\x03" && instance.config.enableRcon){
>       instance.setPreset("command", new GeneralSendCommand());
>       var temp = await instance.execPreset("command", this.cmd);
>       instance.setPreset("command", new RconCommand());
>       return temp
>     }
>     return await instance.execPreset("command", this.cmd);
>   }
> }
> ```
> 
> 现在可以在启用pty和rcon的情况下正常关闭服务器了，但是这样的修复方式太野鸡了，所以不可能pr，可能还是得这边想办法怎么实现

PTY仿真终端下的关闭还是没有修复，需要新开一个issue吗？

**Comment by YuMao233** [comment]
> MCSManager/daemon/src/entity/commands/pty/pty_stop.ts

没看见这一段，不用新开 issue。

**Comment by YuMao233** [comment]
已修复，有兴趣可以看下 commit: https://github.com/MCSManager/MCSManager/commit/abb20ad0f1ec18ee3a4da560869f68f42bf72d16
