### ISSUE TITLE
[Feature] 添加服务端文件修改记录

### ISSUE THREAD

**Issue by zzj2039** [MCSManager/MCSManager#1328]
### Description

1、文件的修改日志记录，需要准确时间以及修改内容的差异对比，同时记录修改的用户
2、可以与某个版本进行差异化对比，类似Github的对比功能

### Reason

更加清楚的看到文件被谁修改了，以及修改了什么内容，方便服务器团队内溯源以及沟通！

**Comment by unitwk** [comment]
想法很不错，但是性能损耗会很大，所以不考虑开发这样的功能。

比如有些 Steam 服务器工作目录下会产生几千个细小文本文件，或者数据文件，如果想记录它们的状态，就必须引入一些列入 git 版本管理的工具，这势必会导致磁盘空间浪费以及性能损失，得不偿失。
