### ISSUE TITLE
[Bug Report]  Not working on phones

### ISSUE THREAD

**Issue by SkyKingPX** [MCSManager/MCSManager#1337]
### Platform

Ubuntu 24.04 LTS / Bug on IOS and iPadOS

### Panel Version

latest

### Recurrence Probability

100%

### Bug Description

When I am taken to the login page and type in my credentials it prompts me with a "Network Error". Is this intended?

**Comment by unitwk** [comment]
I don't think this is an issue with MCSManager, but rather a problem with your server's firewall or some error caused by a reverse proxy.

We've done thorough testing on mobile devices long ago, and we didn't encounter any problems like this.

**Comment by unitwk** [comment]
![f95f80cd6070b3ea45d8ce79372d1afc](https://github.com/user-attachments/assets/c4a7e40a-142f-47ab-a36c-f05c4e174bb7)

**Comment by SkyKingPX** [comment]
I have this on every IOS device and I tried to log into 2 different Panels

**Comment by SkyKingPX** [comment]
iPhone 11:
![image](https://github.com/user-attachments/assets/c5e70d0e-5bad-47ac-9e3f-ae636429b49f)

**Comment by SkyKingPX** [comment]
And my friend (second user) tried to start the server but couldn't because of this error:
[Operation Error] Command execution failed because the instance's actual process does not exist

When I tried it worked but why not for him?

**Comment by SkyKingPX** [comment]
> Everything is normal, you should check if there is something causing the network error, maybe Nginx reverse proxy is causing the error?

How? And I don't even have Ngnix iirc. Or was it shipped with the installation?

**Comment by SkyKingPX** [comment]
I tried disabling my VPN but still.
My mother's phone works.
Maybe it is because I have IOS and iPadOS 18 installed?

**Comment by SkyKingPX** [comment]
@unitwk 
Sorry for "spamming" but I need a fast solution if there is one

**Comment by unitwk** [comment]
I can't help you, I don't know why, and I can't reproduce the situation you described.
