### ISSUE TITLE
[Bug Report] 启动次数与同名实例累加

### ISSUE THREAD

**Issue by alazeprt** [MCSManager/MCSManager#1340]
### Platform

Alpine Linux

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

99%

### Bug Description

如题，在删除某个实例后，创建新的同名（文件夹也相同）的实例，其中的启动次数不是0而是删除的实例的启动次数

**Comment by YuMao233** [comment]
已修复
