### ISSUE TITLE
[Bug Report] Breadcrumb navigation does not respect "prefix" setting

### ISSUE THREAD

**Issue by zbx1425** [MCSManager/MCSManager#1341]
### Platform

Ubuntu 24.04

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

100%

### Bug Description

1. Set up MCSM-Web with reverse proxy and path prefix.
2. Visit the web console.
3. The breadcrumb navigation links on the top will have incorrect URL (path prefix not included).

**Comment by unitwk** [comment]
We will fix it in the next version.

**Comment by YuMao233** [comment]
fixed: https://github.com/MCSManager/MCSManager/releases
