### ISSUE TITLE
[Bug Report] 屏蔽启动命令里的换行符

### ISSUE THREAD

**Issue by kazuhaAyato** [MCSManager/MCSManager#1343]
### Platform

Debian

### Panel Version

latest

### Daemon Version (Optional)

latest

### Recurrence Probability

100%

### Bug Description

java -jar xxx.jar后有时候会不小心多打个换行符然后导致无法启动
找了半天才发现是这个问题，希望直接屏蔽换行符

**Comment by huangsijun17** [comment]
转义为空格？
以前这是一个单行文本框，不能换行，导致较长的启动命令只能复制粘贴……

**Comment by unitwk** [comment]
后续我加一个，检测到换行符拒绝保存的操作

**Comment by YuMao233** [comment]
> 后续我加一个，检测到换行符拒绝保存的操作

已完成
