### ISSUE TITLE
[Feature] 基于已有容器创建实例

### ISSUE THREAD

**Issue by duncai233** [MCSManager/MCSManager#1348]
### Description

基于已有容器创建实例  可以让已经有的容器让mcsm获取控制权 

### Reason

可以快速创建实例

**Comment by huangsijun17** [comment]
MCSM不是一个标准的Docker容器管理程序，不支持管理非自身启动的Docker容器。

**Comment by unitwk** [comment]
> MCSM不是一个标准的Docker容器管理程序，不支持管理非自身启动的Docker容器。

是的，很难做到复用已经启动的 Docker 容器。
