### ISSUE TITLE
[Feature] 2个在Windows下的建议

### ISSUE THREAD

**Issue by kaoyu555666777** [MCSManager/MCSManager#1349]
### Description

注：下面所有东西全扔到[https://gitee.com/kaoyu666/mcs-win](url)中了。

1. 希望使用node-windows将app.js添加到系统服务中，以实现开机自启，并且没有CMD窗口挡害。

实现方法：分别在web和daemon文件夹  `npm install node-windows`
                  然后分别创建文件start.js，代码如下

> var Service = require('node-windows').Service;
> var Path = __dirname + "\\app.js"
> var svc = new Service({
>   name:'mcsm-web',
>   description: 'MCSManager的Web进程。', 
>   script: Path
> });
> svc.on('install',function(){
>   svc.start();
> });
> svc.install();

用node.js启动后会在服务中出现
![image](https://github.com/user-attachments/assets/e53b6511-14d1-43d3-9201-766864a7a69e)
启动服务后就可以了

2.建议Windows下安装像Linux一样使用安装脚本（Powershell）,可以配合上面使用

> echo "=================================================================="
> echo " "
> echo " 欢迎使用MCSManager Windows安装脚本                              "
> echo " "
> echo "=================================================================="
> $DownloadLink = “https://kaoyu666-my.sharepoint.com/:u:/g/personal/kaoyu666_kaoyu666_onmicrosoft_com/EbTo2EyuZR5JtDVggWMn6ikB4OCP1nLEoAipbtJ1oS_Irw?download=1"           #下载链接，这里我给保存到我的onedrive上了，下载速度可能有些慢
> $FileName = "macmanager.zip"                                                                          #文件名
> $Path = Read-Host "请输入MCSManager的安装路径，并请确保您已创建此文件夹，且目录末尾没有\"                #安装路径 
> New-Item -Path $Path -ItemType Directory -Force -ErrorAction SilentlyContinue                         #创建文件夹并不输出任何信息
> Get-ChildItem -Path $Path -Recurse -File | Remove-Item -Force                                         #删除所有文件
> cd $Path
> Invoke-WebRequest -Uri $DownloadLink -OutFile "$PWD\$FileName"                                        #下载安装包
> Add-Type -AssemblyName System.IO.Compression.FileSystem                                               #引入System.IO.Compression.FileSystem命名空间  
> $zipFilePath = "$PWD\$FileName"  
> $extractPath = $PWD  
> [System.IO.Compression.ZipFile]::ExtractToDirectory($zipFilePath, $extractPath)                       #解压
> Remove-Item $zipFilePath                                                                              #删除压缩包
> sc.exe delete mcsmweb.exe                                                                                 #删除旧的web进程
> sc.exe delete mscmdaemon.exe                                                                              #删除旧的daemon进程
> if ($LASTEXITCODE -eq 0) 
> {                                                                                                     #检测是否成功执行
>     echo "请重启计算机并重新执行此命令"                                                                 #使用sc.exe删除服务需要重启计算机
>     exit 0                                                                                            #退出
> }
> cd web
> start node_app.exe start.js                                                                           #使用start.js将app.js添加到系统服务中，下同
> cd ..
> cd daemon
> start node_app.exe start.js
> echo "=================================================================="                             #从setup.sh里复制过来的
> echo "安装已完成！欢迎使用 MCSManager 面板！"
> echo " "
> echo "控制面板地址：   "
> echo "http://你的公网IP:23333"
> echo "你必须开放 23333（面板）和 24444（守护进程用）端口，控制面板需要这两个端口才能正常工作。"
> echo " "
> echo "请在services.msc开启mcsm-web和mcsm-daemon"
> echo " "
> echo "官方文档（必读）：https://docs.mcsmanager.com/"
> echo "=================================================================="

这个扔在[https://[gitee.com/kaoyu666/mcs-win/raw/master/install-mcs-win.ps1](https://gitee.com/kaoyu666/mcs-win/raw/master/install-mcs-win.ps1)](url)中了，直接在管理员Powershell执行`Invoke-Expression (Invoke-WebRequest -Uri https://gitee.com/kaoyu666/mcs-win/raw/master/install-mcs-win.ps1 -UseBasicParsing).Content`即可

### Reason

添加到服务是由于用start.bat启动mcs的话每次重启服务器都要重新运行脚本（Win服务器稳定性比较...），而且运行时CMD的大黑框还不能关

另一个用脚本（至少我觉得）比下载安装包省事多了。

**Comment by Bluemangoo** [comment]
我建议往文档写。

**Comment by unitwk** [comment]
后续可以考虑写到文档里面，但是不想将Windows服务作为默认行为，因为它很烂，开启和关闭也不方便，也不方便实时查看日志。

而且国内一部分用户甚至都不知道如何启动和关闭服务，能简单化就简单化吧，降低学习成本。

**Comment by RecRivenVI** [comment]
> 重复造轮子：
> 
> https://github.com/bddjr/mcsmanager-services-for-windows

该方法已删库，建议将类似方法写入文档，或直接在windows版中提供，确实存在开机时MCSM自动在后台静默运行的需求
