### ISSUE TITLE
[Bug Report] 个人信息页面的注册时间和最后登录时间都为注册时间

### ISSUE THREAD

**Issue by Miraitowa-max** [MCSManager/MCSManager#1351]
### Platform

Windows 10

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

100

### Bug Description

登陆后，在个人资料页面，注册时间和最后登录的时间都为账号的注册时间
![image](https://github.com/user-attachments/assets/41d19463-cf81-41df-b3c8-d8e8657343c0)

问题似乎发生在仓库的 frontend\src\components\MyselfInfoDialog.vue 中的 120行和125行 
![image](https://github.com/user-attachments/assets/76bbbc5e-b4b4-4580-aefc-933cd62b34e7)

二者都引用了 state.userInfo?.registerTime

**Comment by unitwk** [comment]
https://github.com/MCSManager/MCSManager/pull/1354
