### ISSUE TITLE
[Bug Report] 安卓手机Termux因缺少依赖无法启动daemon

### ISSUE THREAD

**Issue by SmilingEnchanter** [MCSManager/MCSManager#1353]
### Platform

Ubuntu 23.10（我在安卓手机使用Termux的proot-distro安装的）

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

100%

### Bug Description

当我尝试启动start-daemon.sh时报错并退出，信息为
`Dependency files are missing and cannot be started. Please reinstall the program:/opt/mcsmanager/daemon/lib/file_zip_android_arm64`
推测是没做安卓Termux的适配？

![image](https://github.com/user-attachments/assets/eab38906-6a47-4a2f-bf48-b30e8fa89043)

记得半年前的旧版本也会报没有这个依赖的错误，但是仍能启动daemon

**Comment by huangsijun17** [comment]
建议用[AidLux](https://aidlux.com/)，我N年前拿上版本MCSM实测可用。理论上本版本也可以。

**Comment by unitwk** [comment]
去这里下载相关的二进制文件，并且放入到报错的位置。

https://github.com/MCSManager/PTY/releases/tag/latest

**Comment by Bluemangoo** [comment]
zip-tool要自己编译，https://github.com/MCSManager/Zip-Tools

**Comment by Bluemangoo** [comment]
你可以把 `linux_arm64` 版本的改一下名字拿去试试。

**Comment by SmilingEnchanter** [comment]
改名的方法成功了，把`file_zip_linux_arm64`和`pty_linux_arm64`分别改为`file_zip_android_arm64`和`pty_android_arm64`后可以正常启动。谢谢大佬们的回复！（之后的版本是不是可以加一下这两个文件

**Comment by unitwk** [comment]
> 之后的版本是不是可以加一下这两个文件

兼容安卓版本不是必须项，考虑到安装包的大小，应该不会加。

**Comment by Capslock800000** [comment]
> > 之后的版本是不是可以加一下这两个文件
> 
> 兼容安卓版本不是必须项，考虑到安装包的大小，应该不会加。

这俩文件大小应该不会太大
