### ISSUE TITLE
[Feature] 2fa auth

### ISSUE THREAD

**Issue by bestzige** [MCSManager/MCSManager#1356]
### Description

More security by 2fa

### Reason

More secure

**Comment by ikun-mr** [comment]
是不是没啥用
不允许公网访问mcsm什么的比2fa好用多了

**Comment by huangsijun17** [comment]
https://github.com/MCSManager/Documentation/blob/e8cdc9b302f05dddf5c9a7461975a15f3a35b1f1/apis/api_users.md#request-body-1

Features that are already supported.
