### ISSUE TITLE
[Bug Report] 在未启用IPv6的服务器上聆听ipv6端口

### ISSUE THREAD

**Issue by kkc141** [MCSManager/MCSManager#1357]
### Platform

Ubuntu 20.04.6 LTS

### Panel Version

10.2.1

### Recurrence Probability

100%

### Bug Description

在未启用IPv6的服务器上只聆听ipv6端口 :::23333/:::24444

'''
netstat -tuplen

tcp6       0      0 :::23333                :::*                    LISTEN      0          37008      -                   
tcp6       0      0 :::24444                :::*                    LISTEN      0          33365      -           
'''

通過 https://script.mcsmanager.com/setup.sh 安裝

**Comment by huangsijun17** [comment]
MCSM还要判断你是不是开启了IPv6？MCSM是不是还要在没IPv6的服务器开启IPv6后的瞬间初始化IPv6？
MCSM只是一个程序，不是操作系统，还要管你服务器也没有IPv6？难不成你是想安装到Linux 2.2.1-或者Windows 9X系统上，系统不支持IPv6，需要软件移除该功能，不然不能启动？

**Comment by Bluemangoo** [comment]
好像不是第一次提了。

@huangsijun17 你再读一遍。

**Comment by huangsijun17** [comment]
> 好像不是第一次提了。
> 
> @huangsijun17 你再读一遍。

1. 标题写的是**在未启用IPv6的服务器上聆听ipv6端**
2. 显示tcp6纯粹是netstat的特性，在没有`IPV6_V6ONLY`的情况下，一般都是同时监听v4和v6的。使用ss可以看出是`*`：
```
$ sudo ss -tlnp
State    Recv-Q   Send-Q     Local Address:Port      Peer Address:Port   Process
LISTEN   0        511                    *:24444                *:*       users:(("node",pid=1119,fd=18))
LISTEN   0        511                    *:23333                *:*       users:(("node",pid=1120,fd=22))
$ sudo netstat -tlnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::23333                :::*                    LISTEN      1120/node
tcp6       0      0 :::24444                :::*                    LISTEN      1119/node
```
