### ISSUE TITLE
[Bug Report] 进入MCSM应用实例需要等待一小段时间才能加载

### ISSUE THREAD

**Issue by MCheping8108** [MCSManager/MCSManager#1359]
### Platform

Ubuntu Server 20.04.6 LTS x86_64

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

100%?

### Bug Description

1. 进入应用实例
2. 等待一小会
![image](https://github.com/user-attachments/assets/cf1a215f-01f4-4832-9bb6-db2e9c2540c5)

**Comment by MCheping8108** [comment]
这是常见的bug吗？有什么解决方案吗？

**Comment by Bluemangoo** [comment]
看着像网络波动。

**Comment by huangsijun17** [comment]
> 看着像网络波动。

局域网，还是400，不太像。

**Comment by YipSzeho** [comment]
同样遇到这个问题，反代后每次进实例都要等一段时间，F12显示400

**Comment by assassinliujie** [comment]
同样遇到这个问题，一直没有解决，之前以为是我的隧道的问题，但是换成FRP和内网也这样，打开F12就一直看到socket链接400错误

**Comment by yumao233** [comment]
终端能正常使用吗？是不是 24444 端口没有反向代理？

**Comment by assassinliujie** [comment]
> 终端能正常使用吗？是不是 24444 端口没有反向代理？

能正常使用，功能一切正常，只是每次网页打开进去之后在终端界面要一直转圈一小会，时间不定，打开F12能看到400错误，但是等上一会就可以开始操作 。实际使用中只是感觉比较烦，如果能修复就最好了

**Comment by WinExp** [comment]
我也有这个问题 一直没有解决 f12看到在101 switching protocol后面会跟着两个400 bad request 本地直连也是这样 但是我用移动端的浏览器没这个问题
