### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by xiaomo-xxx** [MCSManager/MCSManager#1362]
### Platform

Centos 9

### Panel Version

10.1

### Daemon Version (Optional)

4.3

### Recurrence Probability

%50

### Bug Description

![QQ20240901-171341](https://github.com/user-attachments/assets/f48eaf99-a83b-44b0-9f40-3daa026b3e37)
不知道这是什么问题

**Comment by unitwk** [comment]
尝试手动安装吧，https://docs.mcsmanager.com/#linux-manual-installation
