### ISSUE TITLE
[Bug Report] 僵尸进程

### ISSUE THREAD

**Issue by yanxuplay** [MCSManager/MCSManager#1363]
### Platform

Ubuntu 24.04.1 LTS

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

10%

### Bug Description

守护进程变成了僵尸进程，面板进程正常，但面板无法连接守护节点

**Comment by yanxuplay** [comment]
其中僵尸进程为 pty_linux_x64，其父进程为守护进程
![image](https://github.com/user-attachments/assets/e7b14f75-ba52-4384-a10f-26955c8b2d53)

**Comment by unitwk** [comment]
感觉从日志上分析不出来原因，看起来你只运行了不到10分钟守护进程就陷入这种状态了？你有其他的线索可以供分析的吗？比如内存是否充足？或者你启动了什么很奇特的实例进程？又或者你是在进行某个操作的时候才会进入这种状态。

另外，有没有那种实例终端快速输出大量日志的情况？这种情况可能会导致性能问题，最新的代码已经修复这种情况。

**Comment by yanxuplay** [comment]
实际上运行了好几天，但当我昨天**用手机上传文件（以确保实例已关闭）**后立即就无法连接远程节点了，接着我用 systemctl restart mcsm-daemon.service 重启之后就发现 daemon 变僵尸进程了
内存肯定足够，当时至少还有 1.5GB 的空余内存
实例没有快速输出大量日志的情况
反复 systemctl restart mcsm-daemon.service 均不好使
在这里附上正常和昨天上传文件时、重启后异常的 daemon 和 web 日志（注：我在 daemon 重启后多次尝试连接节点）

Daemon:
[正常 2024-8-31_21-24-35.log](https://github.com/user-attachments/files/16838982/2024-8-31_21-24-35.log)
[上传文件时 2024-9-1_17-53-49.log](https://github.com/user-attachments/files/16839211/2024-9-1_17-53-49.log)
[重启后 2024-9-1_23-6-8.log](https://github.com/user-attachments/files/16838981/2024-9-1_23-6-8.log)
Web:
[正常 2024-8-31_21-24-36.log](https://github.com/user-attachments/files/16839228/2024-8-31_21-24-36.log)
[上传文件时 2024-9-1_17-53-49 (1).log](https://github.com/user-attachments/files/16839233/2024-9-1_17-53-49.1.log)
[2024-9-1_22-53-7.log](https://github.com/user-attachments/files/16839237/2024-9-1_22-53-7.log)

**Comment by yanxuplay** [comment]
目前正备份文件尝试重装 MCSM

**Comment by TuanZiGit** [comment]
备份重装无效 只要instance放回去就gg

**Comment by yanxuplay** [comment]
> 备份重装无效 只要instance放回去就gg

奇迹出现了，在我把 web 和 daemon 的 data 从服务器下载下来之后，再 systemctl restart mcsm-(web,daemon).service 竟神奇般的好使了
结果发现是改启动命令之后命令写错了，控制台显示“Unable to access jarfile purpur-1.21.1-2230.jar”，但不知道为什么无法访问文件会导致 daemon 变僵尸进程

**Comment by TuanZiGit** [comment]
> > 备份重装无效 只要instance放回去就gg
> 
> 奇迹出现了，在我把 web 和 daemon 的 data 从服务器下载下来之后，再 systemctl restart mcsm-(web,daemon).service 竟神奇般的好使了 结果发现是改启动命令之后命令写错了，控制台显示“Unable to access jarfile purpur-1.21.1-2230.jar”，但不知道为什么无法访问文件会导致 daemon 变僵尸进程

似乎不是daemon变僵尸了 是pty变僵尸然后卡住了mcsm-daemon

**Comment by yanxuplay** [comment]
> > > 备份重装无效 只要instance放回去就gg
> > 
> > 
> > 奇迹出现了，在我把 web 和 daemon 的 data 从服务器下载下来之后，再 systemctl restart mcsm-(web,daemon).service 竟神奇般的好使了 结果发现是改启动命令之后命令写错了，控制台显示“Unable to access jarfile purpur-1.21.1-2230.jar”，但不知道为什么无法访问文件会导致 daemon 变僵尸进程
> 
> 似乎不是daemon变僵尸了 是pty变僵尸然后卡住了mcsm-daemon

我的确删过pty，后来就好使了，最后还是重装恢复的

**Comment by TuanZiGit** [comment]
不行 新版本更新完pty还是炸裂的

**Comment by TuanZiGit** [comment]
> 不行 新版本更新完pty还是炸裂的

> [!warning]
> 更新记得先删/lib/pty*再跑更新脚本

**Comment by TuanZiGit** [comment]
> > 不行 新版本更新完pty还是炸裂的
> 
> Warning
> 
> 更新记得先删/lib/pty*再跑更新脚本

更：实际上没修好 最新版的mcsm似乎只是禁用掉了pty（？莫名其妙的pty: false了

**Comment by YuMao233** [comment]
> > > 不行 新版本更新完pty还是炸裂的
> > 
> > 
> > Warning
> > 更新记得先删/lib/pty*再跑更新脚本
> 
> 更：实际上没修好 最新版的mcsm似乎只是禁用掉了pty（？莫名其妙的pty: false了

没有禁用啊，可能是你更新没有手动覆盖一次文件吧。
