### ISSUE TITLE
无法安装 求助

### ISSUE THREAD

**Issue by yjq010709** [MCSManager/MCSManager#1366]
### Platform

群晖ds923

### Panel Version

最新

### Recurrence Probability

0

### Bug Description

sudo su -c "wget -qO- https://script.mcsmanager.com/setup_cn.sh | bash"
回车后
提示
+----------------------------------------------------------------------
| MCSManager 安装脚本
+----------------------------------------------------------------------

[-] Architecture: x64
[+] Installing dependent software (git, tar, wget)... [!] Cannot find your package manager! You may need to install git, tar and wget manually!
=================================================
[x] Failed to find git, tar and wget, please install them manually!

这怎么解决呢
有没有docker可以安装的办法

**Comment by unitwk** [comment]
readme 里面有手动安装教程：

https://github.com/MCSManager/MCSManager?tab=readme-ov-file#linux
