### ISSUE TITLE
[Feature] 在quick_install.json中为每个预设增加一个启动命令参数

### ISSUE THREAD

**Issue by Relief156** [MCSManager/MCSManager#1367]
### Description

今天尝试写quick_install.json时，发现如果我部署的是别的控制台应用，启动参数都是需要我自己重新再写一个的，我希望可以直接在json中增加一个 "Start command" : "xxxx.exe" 

### Reason

部署之后可以直接启动 省去自己写启动命令的不愁

**Comment by unitwk** [comment]
<img width="667" alt="image" src="https://github.com/user-attachments/assets/ca5f64ef-217a-49ed-84f1-145262ffc3dd">

你就按照现有的格式写不就行了？

**Comment by Relief156** [comment]
> <img alt="image" width="667" src="https://private-user-images.githubusercontent.com/18360009/365873280-ca5f64ef-217a-49ed-84f1-145262ffc3dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MzY2NzIsIm5iZiI6MTcyNTkzNjM3MiwicGF0aCI6Ii8xODM2MDAwOS8zNjU4NzMyODAtY2E1ZjY0ZWYtMjE3YS00OWVkLTg0ZjEtMTQ1MjYyZmZjM2RkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDAyNDYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1MTY0M2JjOWVlN2Q1YTRlZGY2MWJmZmIzMmRmY2VjYWRkMmQ0MmQwMGVjMjk4MjRjMzA2YTkzYmU0YjE0NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SiY2VeZo49ox5BYZYjWZtc2Rzinm5CcmU-ODN7zsucc">
> 你就按照现有的格式写不就行了？

这 我在官方部署的那个json里也没看见这一段呐  谢谢你
