### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by nandehututu** [MCSManager/MCSManager#1372]
### Platform

ubuntu

### Panel Version

Ubuntu server 24.04 LTS

### Daemon Version (Optional)

10.2.1

### Recurrence Probability

服务器高负载情况下100%

### Bug Description

以下是一些日志，总的来说，在服务器瞬间满载的情况下(大约3分钟)，唯有mcsm的daemon后端节点炸了，其他例如docker，前端web，还有其他服务器上的进程都没啥问题。
建议，前后端互相心跳检测是否掉线，互相拉起(qq就是这么流氓的后端几个进程互相拉起保持在线虽然流氓但是确实有效啊)，实在不行至少搞一个掉线推送通知也行。啥都不知道就炸了每次都是好几天想起来了才发现。这不行不合适。
![123](https://github.com/user-attachments/assets/d58c8187-f8e6-45fc-8227-329df87fd11d)
![QQ截图20240911221553](https://github.com/user-attachments/assets/389b9390-864e-4049-8421-5f8463506f10)
![QQ截图20240911221718](https://github.com/user-attachments/assets/4a3dcd52-e825-421b-85e1-4252220a5f45)
![QQ截图20240911224601](https://github.com/user-attachments/assets/c4c0eefd-01d4-46a3-85c0-9583fa0f4ec7)

**Comment by huangsijun17** [comment]
互相拉起？用什么方案？SSH+私钥吗？

**Comment by unitwk** [comment]
内存不足，系统把占用内存最高的程序杀死了

**Comment by nandehututu** [comment]
> 互相拉起？用什么方案？SSH+私钥吗？

互相拉起所能想到的方案也只有这个了，要不加一个限制节点内脚本的限制内存和限制cpu占用也可以，至少不会因为占用过高而炸节点。java启动脚本有最大内存使用量也没有cpu线程数好像？要是放个python脚本上去好像也得使用第三方库才可以限制以上两个，想不到其他的更好方案了，

**Comment by nandehututu** [comment]
> 内存不足，系统把占用内存最高的程序杀死了

是啊，cpu满载内存不足导致直接炸了节点，要是有个机制检测到节点下cpu线程异常或者内存使用异常就自动重启的选项大概就不会有炸节点的事了，跑着东西的服务器短期满载点东西挺正常的，又不是时时刻刻满载跑。

**Comment by nandehututu** [comment]
> 互相拉起？用什么方案？SSH+私钥吗？

要不加个可开关的机制检测选项，检测到节点下cpu线程异常或者内存使用异常就自动重启某一个占用过高的脚本，这样也能解决问题。毕竟ssh暴露公网这种东西确实不妥

**Comment by nandehututu** [comment]
> 互相拉起？用什么方案？SSH+私钥吗？

其实这么一说，好像这些东西docker都能实现，可以限制cpu占比可以指定线程数可以指定内存使用，就消耗一些性能罢了，这么一来好像并不需要了。我把后端节点封个docker好像确实就完事了。不行就一个机子多docker运行后端就好，好像也不是不行。

不过满载炸后端这个bug也确实百分百存在。看看各位大佬怎么搞一搞。说白了即使脚本炸了，节点也不能炸，节点炸了不合适的。

**Comment by Bluemangoo** [comment]
1. 我支持这个功能。
2. 我记得qq是四个保活进程互相拉起，有兴趣具体可以去看下原理。
3. 暂时你可以试试用docker运行mcsm。

**Comment by nandehututu** [comment]
> 内存不足，系统把占用内存最高的程序杀死了

其实不对，按照日志来说，内存占满后，起码一个小时不炸。而cpu占满不到10分钟就杀了这个占用最高的进程。
这可能是ubuntu的机制(?)，内存保留一些供自己系统使用，cpu是杀进程。这个机制保护了整个系统不被炸。

这不是内存的问题，是cpu满载的问题

**Comment by nandehututu** [comment]
> 1. 我支持这个功能。
> 2. 我记得qq是四个保活进程互相拉起，有兴趣具体可以去看下原理。
> 3. 暂时你可以试试用docker运行mcsm。
> 4. 可以考虑写个类uptime的工具在其它机器上检测然后自动化重启。

回答3 正在把web和节点都封docker运行，希望不会遇到一些bug
回答4 这个工具最好放在前端内，因为一般分布式用户来说，都是web唯一，多个节点。

**Comment by Bluemangoo** [comment]
一直都支持封docker的。很多人也在docker里面运行的。

**Comment by nandehututu** [comment]
> 一直都支持封docker的。很多人也在docker里面运行的。

其实封docker挺麻烦的，要注意挺多东西，而且官方doc里也没有封docker的教程，再加上自封docker其实挺占用空间的。一般情况下都是忽略这种解决办法，实在没有办法了才会使用。下面是封docker解决的办法，给后来人一些帮助(建议可以整理一下写在文档里面，文档内没有相关内容，说实话没有办法了才会使用这个不是谁都会去研究的)。
mcsm如何使用docker封包运行程序。

1.确定你的脚本是用什么语言，比如我是使用python3.11，那去dockerhub下载关于3.11.10的docker包，大概是900m。其他语言同理，以下使用python进行举例。

2.写一个关于sh的脚本，运行命令大概就是'/opt/mcsm/XXXX/start-docker.sh'是该脚本的绝对路径。

3.脚本内容：

‘’‘
#!/bin/bash

# 设置环境变量，脚本内使用‘os.environ.get('USERNAME', 'default_value')’读取环境变量
export USERNAME="XXXX"
export PASSWORD="XXXX" 
export HOST="XXXX" 
export PORT="XXXX" 
export DATABASE="XXXX"
SCRIPT_DIR="/opt/mcsm/krile_ff14_que"




# 切换到指定目录
cd $SCRIPT_DIR

# 检查虚拟环境是否存在
if [ ! -d "$SCRIPT_DIR/.venv" ]; then
  # 如果不存在，创建虚拟环境
  python3 -m venv $SCRIPT_DIR/.venv
fi

# 激活名为.venv的虚拟环境
source $SCRIPT_DIR/.venv/bin/activate

# 判断虚拟环境是否激活成功
if [ $? -eq 0 ]; then
    echo "虚拟环境已成功激活"
else
    echo "虚拟环境激活失败"
    exit 1
fi

# 安装依赖前先检查requirements.txt是否存在
if [ -f "requirements.txt" ]; then
    # 使用pip安装依赖
    pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
    pip install -r requirements.txt
    # 检查安装是否成功
    if [ $? -eq 0 ]; then
        echo "依赖安装成功"
    else
        echo "依赖安装失败"
        exit 1
    fi
else
    echo "未找到requirements.txt文件，请确认该文件存在"
    exit 1
fi

# 运行python程序
python3 /opt/mcsm/krile_ff14_que/ff14_krile_que.py

# 判断python程序是否运行成功
# if [ $? -eq 0 ]; then
#     echo "Python程序已成功运行"
# else
#     echo "Python程序运行失败"
#     exit 1
# fi

# 当所有任务完成后，关闭虚拟环境
deactivate
’‘’

4.完美运行
![image](https://github.com/user-attachments/assets/8d8ff6e7-eaec-4d10-9e34-9ea33f575954)

**Comment by nandehututu** [comment]
> 一直都支持封docker的。很多人也在docker里面运行的。

其实封docker挺麻烦的，要注意挺多东西，而且官方doc里也没有封docker的教程，再加上自封docker其实挺占用空间的。一般情况下都是忽略这种解决办法，实在没有办法了才会使用。下面是封docker解决的办法，给后来人一些帮助(建议可以整理一下写在文档里面，文档内没有相关内容，说实话没有办法了才会使用这个不是谁都会去研究的)。
mcsm如何使用docker封包运行程序。

1.确定你的脚本是用什么语言，比如我是使用python3.11，那去dockerhub下载关于3.11.10的docker包，大概是900m。其他语言同理，以下使用python进行举例。

2.写一个关于sh的脚本，运行命令大概就是'/opt/mcsm/XXXX/start-docker.sh'是该脚本的绝对路径。

3.脚本内容：
```
#!/bin/bash

# 设置环境变量，脚本内使用‘os.environ.get('USERNAME', 'default_value')’读取环境变量
export USERNAME="XXXX"
export PASSWORD="XXXX" 
export HOST="XXXX" 
export PORT="XXXX" 
export DATABASE="XXXX"
SCRIPT_DIR="/opt/mcsm/krile_ff14_que"




# 切换到指定目录
cd $SCRIPT_DIR

# 检查虚拟环境是否存在
if [ ! -d "$SCRIPT_DIR/.venv" ]; then
  # 如果不存在，创建虚拟环境
  python3 -m venv $SCRIPT_DIR/.venv
fi

# 激活名为.venv的虚拟环境
source $SCRIPT_DIR/.venv/bin/activate

# 判断虚拟环境是否激活成功
if [ $? -eq 0 ]; then
    echo "虚拟环境已成功激活"
else
    echo "虚拟环境激活失败"
    exit 1
fi

# 安装依赖前先检查requirements.txt是否存在
if [ -f "requirements.txt" ]; then
    # 使用pip安装依赖
    pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
    pip install -r requirements.txt
    # 检查安装是否成功
    if [ $? -eq 0 ]; then
        echo "依赖安装成功"
    else
        echo "依赖安装失败"
        exit 1
    fi
else
    echo "未找到requirements.txt文件，请确认该文件存在"
    exit 1
fi

# 运行python程序
python3 /opt/mcsm/krile_ff14_que/ff14_krile_que.py

# 判断python程序是否运行成功
# if [ $? -eq 0 ]; then
#     echo "Python程序已成功运行"
# else
#     echo "Python程序运行失败"
#     exit 1
# fi

# 当所有任务完成后，关闭虚拟环境
deactivate
```

4.完美运行
![image](https://github.com/user-attachments/assets/8d8ff6e7-eaec-4d10-9e34-9ea33f575954)

**Comment by Bluemangoo** [comment]
压根不需要py为什么要把py封进去。应该web和daemon封两个docker，写好dockerfile就好了。

**Comment by nandehututu** [comment]
> 压根不需要py为什么要把py封进去。应该web和daemon封两个docker，写好dockerfile就好了。

![image](https://github.com/user-attachments/assets/fa362664-c9e5-4ebe-bb23-2a3925af507d)

**Comment by huangsijun17** [comment]
你完全可以使用Docker嵌套技术，将宿主机的docker.sock挂载进MCSM-Daemon的Docker，就可以并行Docker了。Python那些封装放在你实例的Docker镜像内，而无需封装在MCSM Daemon的镜像内。
