### ISSUE TITLE
[Feature] Posibility/Tutorial on how to change frontend-directory

### ISSUE THREAD

**Issue by Shmalle** [MCSManager/MCSManager#1374]
### Description

Hey there, I am running a software called [MIAB](https://github.com/mail-in-a-box/mailinabox) which prevents me from manipulating the nginx.config. It would be awesome if I was able to set the fronted-path of MCSM right into one of my domains, so I can access the panel through there. Would that be possible considering that you have to use the port to access the web-application?

### Reason

More flexibility with stricter configured solutions.

Edit: Typo

**Comment by YuMao233** [comment]
Although it's a bit late, we have completed the development of this feature.

https://docs.mcsmanager.com/ops/path_prefix.html
