### ISSUE TITLE
Control panel not loading after installation

### ISSUE THREAD

**Issue by grinheckerdev** [MCSManager/MCSManager#1377]
### Platform

Ubuntu 24.04

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

100%

### Bug Description

I installed the MCSManager, 
<img width="972" alt="Снимок экрана 2024-09-17 в 16 32 20" src="https://github.com/user-attachments/assets/18661e7b-4ff4-4882-8c53-5da58d08a891">
It is just loading indefinitely. Checked the logs, nothing there.

**Comment by grinheckerdev** [comment]
Here is the log:
[09/17 13:25:14] [INFO] [HTTP] GET: http://109.248.7.31:23333/
[09/17 13:25:14] [INFO] [HTTP] IP: ::ffff:109.252.170.249 USER: undefined UUID: undefined
[09/17 13:30:51] [INFO] [HTTP] GET: http://109.248.7.31:23333/
[09/17 13:30:51] [INFO] [HTTP] IP: ::ffff:109.252.170.249 USER: undefined UUID: undefined
[09/17 13:30:51] [INFO] [HTTP] GET: http://109.248.7.31:23333/assets/ant-25a63267.css
[09/17 13:30:51] [INFO] [HTTP] IP: ::ffff:109.252.170.249 USER: undefined UUID: undefined

**Comment by grinheckerdev** [comment]
Ok, I figured it out. It was an issue with safari. It wasn't loading a vital resource. 
<img width="250" alt="Снимок экрана 2024-09-17 в 16 54 04" src="https://github.com/user-attachments/assets/b4875a83-628d-479f-b2ba-70fa523e205a">

**Comment by grinheckerdev** [comment]
It works perfectly fine with Chrome

**Comment by huangsijun17** [comment]
> Ok, I figured it out. It was an issue with safari. It wasn't loading a vital resource. <img alt="Снимок экрана 2024-09-17 в 16 54 04" width="250" src="https://private-user-images.githubusercontent.com/148703318/368197100-b4875a83-628d-479f-b2ba-70fa523e205a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1OTA4NTgsIm5iZiI6MTcyNjU5MDU1OCwicGF0aCI6Ii8xNDg3MDMzMTgvMzY4MTk3MTAwLWI0ODc1YTgzLTYyOGQtNDc5Zi1iMmJhLTcwZmE1MjNlMjA1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QxNjI5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjZkZGQ2Y2MwYjQ1NjFkZDM4Zjk3ZWI2NGVmOWFhODM4MWRlNDI2ZGZiYTNmZmRhZTAyYzYyM2YzYTQ3ZGE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R42FutVwIMuvZMh3u7Vj89WW-JSWd6z7az0TxTEiQak">

What are your Mac and Safari versions?
