### ISSUE TITLE
[Bug Report] [终端]终端颜色渲染在刷新后失效

### ISSUE THREAD

**Issue by lao-pan** [MCSManager/MCSManager#1379]
### Platform

服务端：Windows_NT win32 Windows Server 2019 Standard 10.0.17763，客户端：win11 edge浏览器

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

100%

### Bug Description

仿真终端 未开启
网页颜色渲染 开启
此时网页内容在刷新后 颜色失效，只有新输出控制台log会渲染颜色
----------------------------------------------------
仿真终端 未开启
网页颜色渲染 未开启
颜色代码无渲染
----------------------------------------------------
仿真终端开启，容易在复制粘贴时关闭终端，一直没使用过

**Comment by YuMao233** [comment]
```
仿真终端 未开启
网页颜色渲染 未开启
颜色代码无渲染
```

这个是正常的，因为普通终端是不会有任何颜色的。

至于历史记录没有颜色，确实是问题，优先级不高，有空我看看吧
