### ISSUE TITLE
[Bug Report] 向面板发送api请求时出现500错误

### ISSUE THREAD

**Issue by yxjsxl** [MCSManager/MCSManager#1380]
### Platform

Windows 11

### Panel Version

10.1.0

### Daemon Version (Optional)

4.3.0

### Recurrence Probability

100%

### Bug Description

向面板发送api请求时出现500错误
错误JSON:{'status': 500, 'data': "TypeError: Cannot read properties of undefined (reading 'toLowerCase')", 'time': 1726997314054}
请求API:GET /api/service/remote_service_instances
请求参数:
paramas = {
            "page":int(page),
            "page_size":int(pagesize),
            "apikey":self.apikey,
            "daemonId":self.daemonId
        }

**Comment by yxjsxl** [comment]
已经自行解决,故此关闭

**Comment by YuMao233** [comment]
估计是没有传递 instance_name 之类的参数，导致查询出错。
