### ISSUE TITLE
关于 Minecraft 服务端配置项的释义

### ISSUE THREAD

**Issue by jiajiu123** [MCSManager/MCSManager#1381]
### Platform

Debian Bookworm

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

100%

### Bug Description

在 Minecraft 服务端配置项中，"spawn-protection"的释义有误，根据[Minecraft wiki](https://zh.minecraft.wiki/w/%E5%87%BA%E7%94%9F%E7%82%B9%E4%BF%9D%E6%8A%A4?variant=zh)和[Minecraft Bugs](https://bugs.mojang.com/browse/MC-666)中的描述，在版本1.5（13w05a）后，设置为0或负值会禁用生成保护，而在面板中的描述为设置为0将只保护出生点下方那一个方块。

**Comment by YuMao233** [comment]
已修复
