### ISSUE TITLE
[Bug Report] 关于前后端ssl的讨论

### ISSUE THREAD

**Issue by nandehututu** [MCSManager/MCSManager#1382]
### Platform

ubuntu22.04

### Panel Version

10.2.1

### Daemon Version (Optional)

4.4.1

### Recurrence Probability

100%

### Bug Description

总所周知，mcsm前后端可分离部署，所以针对前端后端是否使用nginx的ssl反向代理就有4种情况，分别是前端ssl+后端ssl、前端ssl+后端无ssl、前端无ssl+后端ssl、前端无ssl+后端无ssl。

针对第一种和第四种情况，也就是前后端都开ssl和前后端都不开ssl，正常情况下一定是能互相wss或者ws对接的。
但是要是放在分布式存储的时候，情况复杂多变，多少web端互相连接多个节点后端的时候，并不一定能保证ws所有节点都保持ssl开启的一致性，一定会出现第二种情况以及第三种情况。

以下是第二种情况，前端ssl+后端无ssl，节点可连接，显示非离线，但是打开应用实例提示xhr poll error无法正常连接。
猜想下第三种情况(没测过)应该也是一样的xhr poll error

前端ssl：
![image](https://github.com/user-attachments/assets/fc12c6a5-fbbc-4987-862b-759d23a48351)

两个不同的连接同一个节点：
![image](https://github.com/user-attachments/assets/1e733348-e4e0-4cc0-9d10-6666ee16c734)

后端无ssl的无法连接：
![image](https://github.com/user-attachments/assets/c19b2abc-f396-4322-9d1c-a949eccc98d5)

后端有ssl的可以连接：
![image](https://github.com/user-attachments/assets/aaeb70dc-e786-46a2-9ac2-739eccee1269)

总结：既然给了可分布式应用的结构，有些bug能修尽量修下把，十分感谢，这应该算bug把，不知道该放啥选项下。就放bug里把

**Comment by Bluemangoo** [comment]
当然你有精力魔改chromium当我没说。

**Comment by nandehututu** [comment]
> 当然你有精力魔改chromium当我没说。
工作中有用到所以我说一下，不用魔改，https页面下访问非ssl的websocket服务，火狐的默认配置下禁止了但是降低安全设置可以连接。
我只是想问问有没有一种可能，有没有内置设置可以忽略安全设置，要是没有那就算了。

**Comment by nandehututu** [comment]
> 当然你有精力魔改chromium当我没说。

工作中有用到所以我说一下，不用魔改，https页面下访问非ssl的websocket服务，火狐的默认配置下禁止了但是降低安全设置可以连接。
我只是想问问有没有一种可能，有没有内置设置可以忽略安全设置，要是没有那就算了。

**Comment by huangsijun17** [comment]
> > 当然你有精力魔改chromium当我没说。
> 
> 工作中有用到所以我说一下，不用魔改，https页面下访问非ssl的websocket服务，火狐的默认配置下禁止了但是降低安全设置可以连接。 我只是想问问有没有一种可能，有没有内置设置可以忽略安全设置，要是没有那就算了。

chromiumd的限制，不是MCSManager的限制。建议向W3C提案，制定“忽略https页面下访问非ssl的websocket服务”的标签后，再向下游提交添加标签的issues。

**Comment by nandehututu** [comment]
@YuMao233 好的谢谢明白了，说的很清楚。我以前是用火狐把安全性关闭然后才可以使用的，才想着说有没有可能绕过什么的，然后上面两位和我说向w3c提案，这明显是不可能通过的，谢谢各位的回答，没其他的我就关问题了。
