### ISSUE TITLE
[Bug Report] 覆盖更新后无法通过23333端口访问面板

### ISSUE THREAD

**Issue by AkihaZhang** [MCSManager/MCSManager#1386]
### Platform

windows server 2022

### Panel Version

10.4.0

### Daemon Version (Optional)

4.5.0

### Recurrence Probability

100%

### Bug Description

最新releases内提供的压缩包大小跟官网下载的版本不一致，前者大小仅60余MB，使用前者更新会导致无法通过23333端口访问面板，官网版本覆盖更新无此问题
![image](https://github.com/user-attachments/assets/bd77390f-c729-4300-be59-90a8822ac73d)

![image](https://github.com/user-attachments/assets/e8fdb5f9-4de8-46cf-a6f8-cc1dbf8cce15)

**Comment by YuMao233** [comment]
构建脚本遗漏了文件，下个小版本修复

**Comment by YuMao233** [comment]
已修复
