### ISSUE TITLE
[Bug Report] 面板语言包问题导致错误显示“Linux负载”

### ISSUE THREAD

**Issue by CreeperKong** [MCSManager/MCSManager#1388]
### Platform

FreeBSD-14.1-p5 and OpenBSD-7.5#2

### Panel Version

10.4.0

### Recurrence Probability

100%

### Bug Description

语言包问题，在FreeBSD、OpenBSD等其它类Unix系统环境下显示“Linux负载”

建议改为“面板端系统负载”以避免发生误解。

![image](https://github.com/user-attachments/assets/b90e56b7-7877-4f80-9554-e3b1f76fb7e9)

![image](https://github.com/user-attachments/assets/e19ab1ce-5511-4908-976e-610c0330dfe5)

**Comment by YuMao233** [comment]
这个细节还是算了，看到这个术语的人，能明白这个意思就行，太抽象的话有些用户又不知道这个是什么指标了

**Comment by KagurazakaNyaa** [comment]
其实标准术语应该是`unix load average(1m,5m,15m)`,`Unix 负载均值（1分钟，5分钟，15分钟）`

**Comment by YuMao233** [comment]
好，下次改
