### ISSUE TITLE
[Bug Report] SSL反代后无法连接到daemon端

### ISSUE THREAD

**Issue by XuanSuHS** [MCSManager/MCSManager#1391]
### Platform

Ubuntu 24.04 Docker

### Panel Version

10.4.0

### Daemon Version (Optional)

4.5.0

### Recurrence Probability

100%

### Bug Description

SSL 代理后web端无法访问daemon端，web端 log显示 远程节点 已断开，daemon端 log 显示 会话因长时间未验证身份而断开连接
代理后 daemon端 可通过 https 访问
面板端直连则可以连通

**Comment by huangsijun17** [comment]
地址开头填`wss://`了吗？

**Comment by XuanSuHS** [comment]
> 地址开头填`wss://`了吗？

有的

**Comment by XuanSuHS** [comment]
我原来的直连是 ipv6 的，用 nps 开隧道到v4 服务器上之后就可以连上了
可能是 docker swarm 问题？

**Comment by huangsijun17** [comment]
`wss://[::1]:24444`url中的IPv6地址用方括号括起来试试看。IPv6一般用方括号来区分地址和端口。
