### ISSUE TITLE
[Feature] 发出关闭命令后模拟“按下任意键”

### ISSUE THREAD

**Issue by izumiChan16** [MCSManager/MCSManager#1397]
### Description

我在使用定时任务的时候发现，MC的进程定时关闭后，无法定时开启
<img width="989" alt="043c15dcfa897c4a6c4cb89fe9b88f9" src="https://github.com/user-attachments/assets/95dca1a7-9f0d-4841-aaf5-9496cdd97391">
可能是由于没有“按下任意键”结束进程，导致实例无法停止。从而无法通过定时任务启动。

### Reason

希望可以增加在发出关闭请求后选择按下任意键的选项。

**Comment by huangsijun17** [comment]
MCSM的关闭示例的本质就是模拟发送字符。例如发送exit字符等。你多写一些字符不就完了？
