### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by 960545213** [MCSManager/MCSManager#1399]
### Platform

Windows 24H2 

### Panel Version

10.4.1

### Daemon Version (Optional)

4.5.0

### Recurrence Probability

100%

### Bug Description

在使用24H2和windos server 2025时，开始运行网页和守护程序时发生闪退。

**Comment by huangsijun17** [comment]
node version? log?

**Comment by YuMao233** [comment]
升级一下MCSM版本，再尝试一下，旧版本的 MCSM 面板对新系统兼容有点问题

**Comment by 960545213** [comment]
在官网下载后修复了，谢谢
