### ISSUE TITLE
[Bug Report] 终端会吞最后一行字

### ISSUE THREAD

**Issue by alazeprt** [MCSManager/MCSManager#1401]
### Platform

Ubuntu 18.04

### Panel Version

10.4.0

### Daemon Version (Optional)

4.5.0

### Recurrence Probability

80%

### Bug Description

如[视频](https://github.com/user-attachments/assets/2a64c297-8f73-4ca8-917a-b5b2dcc87eec)所展示，
在使用节点终端时进行nano操作时，下面原来有两行的编辑教程只剩下一行，同时用鼠标滚动时下面的编辑教程消失不见

**Comment by YuMao233** [comment]
浏览器是Chrome吗？只有操作 nano 的时候会有这种情况吗？正常的其他程序，比如ping程序会有这种情况吗？

**Comment by alazeprt** [comment]
Edge浏览器，其它程序均为该情况

**Comment by Redapple-one** [comment]
> Edge浏览器，其它程序均为该情况

你不是MCJPG那个星际穿越腐竹吗

**Comment by YuMao233** [comment]
复现没成功，算了不修了
