### ISSUE TITLE
[Bug Report] no instructions for windows 10

### ISSUE THREAD

**Issue by Vitokhv** [MCSManager/MCSManager#1402]
### Platform

Windows 10

### Panel Version

10.4.2

### Daemon Version (Optional)

10.4.2

### Recurrence Probability

1%

### Bug Description

no instructions for windows 10
bat files for windows 10 do not work

**Comment by YuMao233** [comment]
Can you provide a specific error message?

For example, what error will occur when running Bat in the terminal?
