### ISSUE TITLE
[Feature] Lazymc-type integration into mcsm

### ISSUE THREAD

**Issue by Im-CatDev** [MCSManager/MCSManager#1406]
### Description

Integrating something like https://github.com/timvisee/lazymc to mcsmanager

### Reason

Some servers eat a lot of resources even when nobody is online, so why not stop the server when nobody is online and start it automatically when someone tries to join?

**Comment by huangsijun17** [comment]
You can install lazymc by yourself and start it through mcsm. Then let lazymc start the MC server core.

**Comment by Im-CatDev** [comment]
But it would be much more convenient to integrate it

**Comment by huangsijun17** [comment]
Only increases risk. Adding Lazymc may make more misconfigurations possible. MCSM should not be a family bucket.
Unless you have evidence that lazymc is popular enough, has a large number of users, and is compatible with most MC official and third-party cores.

**Comment by Bluemangoo** [comment]
even mcdr dont get integrated.
