### ISSUE TITLE
[Bug Report] 文件管理 根据文件名搜索 翻页后搜索导致分页不正确的bug（文件管理搜索框逻辑错误）

### ISSUE THREAD

**Issue by kukinghan** [MCSManager/MCSManager#1409]
### Platform

Windows 11 Pro build 10.0.22631

### Panel Version

10.4.3

### Daemon Version (Optional)

4.5.2

### Recurrence Probability

100%

### Bug Description

BUG1：
  当文件数量超过一页时（例如每页展示10个文件，你有20个文件），用户在非第一页（如第二页或第三页）使用搜索框输入查询条件进行文件搜索时，仍然保留当前页码参数发送请求，导致无法正确地从第一页开始搜索相关文件，并且前端界面显示页码为1，但实际没有展示出匹配的搜索结果。
预期结果：
  可以搜索到第一页的文件，或者可以翻回第一页。
实际结果：
  页码显示为1，处于第一页，但无法正确搜索到文件。

完整复现流程：
  1. 新建名称为a-z的26个文件夹
  2. 分页改为10条每页 ![image](https://github.com/user-attachments/assets/701e29d8-a249-4034-9c9e-2440bb065e85)
  3. 搜索a，正常显示
  4. 翻页到第二页或第三页，搜索a
  5. 无法搜索到文件，分页页码显示为1 ![image](https://github.com/user-attachments/assets/1d033cae-bf86-4138-8e1a-54cda2788107)
  6. 此时无法翻页，刷新无效，未能搜索到文件a
  
BUG2（可能的bug）:
  搜索框包含内容时，切换到下一页搜索框会被清空。导致无法搜索到第一页以外的文件。（最大只能搜索到100个文件）
关联的提交：
  https://github.com/kukinghan/MCSManager/commit/f4c6c3fb7940baa7e8a8532f450136e8de56b112

**Comment by kukinghan** [comment]
修复：pull 1401
https://github.com/MCSManager/MCSManager/pull/1410

**Comment by YuMao233** [comment]
FIX
