### ISSUE TITLE
[Bug Report] 节点状态一直为离线

### ISSUE THREAD

**Issue by yuzhuangshi** [MCSManager/MCSManager#1412]
### Platform

CentOS 7.9 64位

### Panel Version

10.4.0

### Recurrence Probability

100%

### Bug Description

24444端口没响应，找到相似问题的解答试着解决也没用。
![363ff2ea91f72be989929846da2282e](https://github.com/user-attachments/assets/1605def9-527f-4e57-9bca-037db6ace820)
![41768906135a4ec67c20dd249c52161](https://github.com/user-attachments/assets/ea1aa26e-f9d3-4250-a3e6-f35bff5b702a)

**Comment by yuzhuangshi** [comment]
![image](https://github.com/user-attachments/assets/bafa17f0-f007-4388-ab24-bbcdf96838bf)

**Comment by yuzhuangshi** [comment]
尝试kill并重启之后只有两三秒的时间会显示在线，之后就又掉了

**Comment by huangsijun17** [comment]
浏览器直接打开24444呢？
`systemctl status mcsm-daemon`呢？

**Comment by yuzhuangshi** [comment]
![image](https://github.com/user-attachments/assets/88b9e66f-72b0-40b8-8677-0332e8fd5504)
24444的话显示为无法访问此网页
![3907c2e0c22555fb69d5991c6808ecb](https://github.com/user-attachments/assets/9ad43da1-34de-42d3-b533-58e1bb50945f)

**Comment by huangsijun17** [comment]
> ![image](https://private-user-images.githubusercontent.com/94734381/380532197-88b9e66f-72b0-40b8-8677-0332e8fd5504.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODE3NTAsIm5iZiI6MTczMDA4MTQ1MCwicGF0aCI6Ii85NDczNDM4MS8zODA1MzIxOTctODhiOWU2NmYtNzJiMC00MGI4LTg2NzctMDMzMmU4ZmQ1NTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDAyMTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMjFlZmU1MWRjMjM5OTQ2MDY1YzYzNGI1MzI2ZTc0Nzg3ZWUzZTk3Yjg2YzM0MDdmMzM5MWJlMmFhYTBhYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.od8OuVEoDNqUvDSm3ROYFcfLHArQnTAMKWebgFNNb6A) 24444的话显示为无法访问此网页 ![3907c2e0c22555fb69d5991c6808ecb](https://private-user-images.githubusercontent.com/94734381/380532526-9ad43da1-34de-42d3-b533-58e1bb50945f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODE3NTAsIm5iZiI6MTczMDA4MTQ1MCwicGF0aCI6Ii85NDczNDM4MS8zODA1MzI1MjYtOWFkNDNkYTEtMzRkZS00MmQzLWI1MzMtNThlMWJiNTA5NDVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDAyMTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzMDRmOTBiZTk5YWFlNTRiOWQ5YWM3ZTdjYzdjNTM0N2VhMDFkOGNjM2Y5NjlkNzJlM2RhNjA5NDI5MGE0Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iduVMaGACcGnQ7F3tpatYtKwwVMf_tZiGhgMJ1k5PF4)

浏览器开[http://47.95.204.21:24444/](http://47.95.204.21:24444/)，我开过了，似乎是网络问题？

**Comment by YuMao233** [comment]
看起来是网络问题，无法公网访问。
