### ISSUE TITLE
[Bug Report] 日志记录与显示异常

### ISSUE THREAD

**Issue by Bkm016** [MCSManager/MCSManager#1413]
### Platform

Windows 11

### Panel Version

10.4.3

### Daemon Version (Optional)

4.5.0

### Recurrence Probability

100%

### Bug Description

日志记录受浏览器终端宽度影响，永久性影响历史记录。

<details>
<summary>测试表现</summary>
测试方法在 instance_event_router.ts 第 42 行插入 console.log(text);

窗口化浏览器终端页面，调整为最小宽度，随后观察日志输出：

<img src="https://github.com/user-attachments/assets/9d851f5d-8c57-4b19-aff4-929caa89e4b2" width="600"/>

<img src="https://github.com/user-attachments/assets/7e0963cd-8d3a-4acd-91b8-c0c1d366b8ce" width="600"/>
</details>

<details>
<summary>生产环境表现</summary>
<img src="https://github.com/user-attachments/assets/c5c37714-5e85-4fd3-9a34-11a81541ce02" width="600" />
</details>

说实话挺蛋疼的，有时候打开一个很久没管的控制台，结果日志全是坏的。  
这个问题很久以前就存在了。

**Comment by Bkm016** [comment]
![image](https://github.com/user-attachments/assets/a42b79c7-c680-48ee-8421-b44897e1659c)
这张图你能看出问题吗？

1. 终端窗口会随浏览器宽度动态调整这没毛病，但是为什么会影响所有人？
2. 第二张是 MCSManager 的 log 文件

**Comment by YuMao233** [comment]
> ![image](https://private-user-images.githubusercontent.com/27818531/381007521-a42b79c7-c680-48ee-8421-b44897e1659c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODU4OTYsIm5iZiI6MTczMDE4NTU5NiwicGF0aCI6Ii8yNzgxODUzMS8zODEwMDc1MjEtYTQyYjc5YzctYzY4MC00OGVlLTg0MjEtYjQ0ODk3ZTE2NTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA3MDYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyNDhmYjk0NGJlNjY2ZjRjNWJjMjcxZmEwMGJhNWZmM2RlNmFkNWVmYWQ3YWZjYmNiMjJmZjNkYWU5MGZkN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J4baBW5c3lyoZTGx-Cw1qmYM7Pxwkg9baaF9trlHT84) 这张图你能看出问题吗？
> 
> 1. 终端窗口会随浏览器宽度动态调整这没毛病，但是为什么会影响所有人？
> 2. 第二张是 MCSManager 的 log 文件
> 
> 虚拟终端会采用所有客户端中最小的长宽比，如果一个人正在用手机访问实例，所有人看这个实例都是这个大小，日志写入也会受到影响。

感谢抽出时间来提供截图。

终端调整窗口会影响所有人这个是故意设计，并非BUG，会自动采用访问屏幕最小的尺寸。

这样设计的目的是确保在所有人的屏幕上都能正常显示内容，比如用户A打开了 htop 程序用于查看控制台信息，这个程序是一个全屏终端程序，用户B的窗口如果比用户A小的话，会导致显示排版错乱，所以必须使用双方最小的尺寸才能确保所有人看到的内容排版不错乱。

当然，我们也做了最小尺寸的限制，可以防止有些人恶意缩小窗口过度影响其他人。

将鼠标移动到此处可以知道此时有几个人正在访问本终端：
![image](https://github.com/user-attachments/assets/54c03dab-47ca-4914-8ff8-22f7cfa1e8ab)

可能你认为这样设计不合理，因为会有一个大屏的用户无法完全享受到大屏的输出内容，但是至少不会因为排版错乱而无法阅读。
