### ISSUE TITLE
[Feature] 自动清理用户数据中不存在的实例

### ISSUE THREAD

**Issue by kukinghan** [MCSManager/MCSManager#1415]
### Description

为了清理磁盘空间，或是实例长期过期。实例被从节点中永久删除后用户的实例列表中仍然会保留显示。显示为“故障中”。

用户获取用户信息时，如果是被删除，希望显示“已删除”。或者从用户的实例列表移除。因为我们知道这个“故障”永远不可能被修复。这是一条脏数据了！

这大概是个麻烦的问题，节点离线的原因还是蛮复杂的。可能从删除实例时入手比较安全？
![image](https://github.com/user-attachments/assets/180d50c5-4090-4708-a710-5e14f35084ba)

### Reason

提示系统运维自动化程度。修改描述优化用户体验。

**Comment by kukinghan** [comment]
大概是个麻烦的问题，节点离线的原因还是蛮复杂的。可能需要从删除时入手

**Comment by YuMao233** [comment]
后续我们会在删除实例时，清理掉用户残留的数据，目前应该是一步没有做导致的。
