### ISSUE TITLE
[Bug Report] 实例启动失败

### ISSUE THREAD

**Issue by 5eveNight** [MCSManager/MCSManager#1421]
### Platform

Android termux-linux

### Panel Version

10.4.3

### Daemon Version (Optional)

4.5.2

### Recurrence Probability

100

### Bug Description

有个废的安卓机想利用一下开个paper服，用的zerotermux，用pty_linux_arm64适配安卓，面板成功运行
但用面板启动jar显示失败
前台截图
![Screenshot_2024-10-31-16-36-22-972_com android chrome](https://github.com/user-attachments/assets/51230617-1785-49ac-8668-210c89d37f9c)
后台报错
![Screenshot_2024-10-31-17-05-38-395_com termux](https://github.com/user-attachments/assets/31b5e72a-1fc3-4287-a4ce-950101efde92)
感觉是在tmp/mcsmanager-instance-pipe目录里创建不了pipe-***
但用chmod给了777权限还是不行。
手动用命令 java -Xmx2048M -Xms1024M -jar 121130.jar nogui 开服正常
![Screenshot_2024-10-31-17-25-39-757_com termux](https://github.com/user-attachments/assets/72651089-4065-4dc5-a22d-fd3fcfe9750f)

可以的话还是想用mcsm管理paper后台
不行那我就手动开服了

**Comment by YuMao233** [comment]
java 路径使用绝对路径试试吧。

**Comment by 5eveNight** [comment]
[自动回复]：来信已收到，我将会尽快给您回复

**Comment by 5eveNight** [comment]
> java 路径使用绝对路径试试吧。

下载过Amazon的linux的openjdk21的包解压，启动命令用绝对路径"~/jdk/bin/java" -Xmx2048M -Xms1024M -jar 121130.jar nogui
也是一样报错。


今天试了试https://github.com/zhuyejun520/Android-for-MCSManager 里面的步骤
下载mcsm 9.9.0版本，daemon 3.4.0版本的，完美运行了paper 1.21的服！

termux先pkg update更新一下，再手动安装openjdk21跟node.js，
然后mcsm跟daemon都是用git clone：（https://github.com/MCSManager/MCSManager-Web-Production.git；https://github.com/MCSManager/MCSManager-Daemon-Production.git）
剩下的基本就能手输指令安装，基本没报错。

最后，感谢作者开发的mcsm面板。
说到底拿安卓手机开mc服务器还是太小众，自己研究研究得了。

**Comment by YuMao233** [comment]
> > java 路径使用绝对路径试试吧。
> 
> 下载过Amazon的linux的openjdk21的包解压，启动命令用绝对路径"~/jdk/bin/java" -Xmx2048M -Xms1024M -jar 121130.jar nogui 也是一样报错。
> 
> 今天试了试https://github.com/zhuyejun520/Android-for-MCSManager 里面的步骤 下载mcsm 9.9.0版本，daemon 3.4.0版本的，完美运行了paper 1.21的服！
> 
> termux先pkg update更新一下，再手动安装openjdk21跟node.js， 然后mcsm跟daemon都是用git clone：（[https://github.com/MCSManager/MCSManager-Web-Production.git；https://github.com/MCSManager/MCSManager-Daemon-Production.git）](https://github.com/MCSManager/MCSManager-Web-Production.git%EF%BC%9Bhttps://github.com/MCSManager/MCSManager-Daemon-Production.git%EF%BC%89) 剩下的基本就能手输指令安装，基本没报错。
> 
> 最后，感谢作者开发的mcsm面板。 说到底拿安卓手机开mc服务器还是太小众，自己研究研究得了。

如果你能弄清楚原因，并且告诉写在这里，可能会更好，后续如果有遇到了可以参考。
