### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by solakcemalettin** [MCSManager/MCSManager#1422]
### Platform

Debian 10

### Panel Version

latest

### Daemon Version (Optional)

latest

### Recurrence Probability

60%

### Bug Description

![Adsız](https://github.com/user-attachments/assets/0e7b0255-987c-4397-a49f-841930319166)

**Comment by huangsijun17** [comment]
node version? Docker?

**Comment by YuMao233** [comment]
出现这个的可能性，大概率是 NodeJS 版本过低，请升级 NodeJS 版本到最新。
