### ISSUE TITLE
[Bug Report] Docker 实例不指定工作目录无法启动

### ISSUE THREAD

**Issue by littlekan233** [MCSManager/MCSManager#1433]
### Platform

[Web] Ubuntu 24.04.1 LTS [Daemon] Ubuntu 20.04.6 LTS

### Panel Version

10.4.0

### Daemon Version (Optional)

4.5.0

### Recurrence Probability

100%

### Bug Description

创建一个 Docker 实例，随便一个镜像，工作目录空内容
启动实例就会报错：
```
[Operation Error] (HTTP code 400) unexpected - invalid mount config for type "bind": field Target must not be empty
```
这个问题直到最新版本 10.4.3 也没有修复

**Comment by YuMao233** [comment]
fixed: https://github.com/MCSManager/MCSManager/commit/137808048dd86b81bddd881d0b1c941cb2c22b28

将于下个版本发布。
