### ISSUE TITLE
[Bug Report] 浏览器不兼容

### ISSUE THREAD

**Issue by ChenXu-Huang** [MCSManager/MCSManager#1436]
### Platform

Windows 11 Pro 10.0.22631

### Panel Version

10.4.3

### Daemon Version (Optional)

4.5.0

### Recurrence Probability

90%

### Bug Description

当使用Firefox Nightly打开MCSManager面板，并且打开终端页面的时候，一直在转圈，要等待好久，才有可能转好。
![屏幕截图 2024-12-01 213904](https://github.com/user-attachments/assets/fd00eb83-8ac1-4c92-8567-451de8d21b36)
![屏幕截图 2024-12-01 213944](https://github.com/user-attachments/assets/85da1534-e40a-4f8b-8013-63ff817e3e70)

**Comment by huangsijun17** [comment]
Firefox具体版本？

**Comment by ChenXu-Huang** [comment]
Firefox Nightly 135.0a1.20241201095257

**Comment by YuMao233** [comment]
你使用其他浏览器，比如 Chrome，Edge 等也会出现这种情况吗？只限于 Firefox Nightly ？这个转圈一般来说是网络问题，但是你访问的是 localhost 域名所以排除这种可能。

你的节点也在本地吗？是否有多个节点，连接了其他的机器？

你可以打开浏览器的开发者工具，点击 console（控制台）一栏，然后看看有没有红色的错误信息。

如果没有明显错误，可以点击 network（网络）一栏，看看是哪个请求导致时间，提供一些截图给我们也许能帮助定位到具体原因。

**Comment by ChenXu-Huang** [comment]
在使用chrome的时候，没有出现这样的问题。我的节点在本地，没有连接其他机器。
![屏幕截图 2024-12-02 112248](https://github.com/user-attachments/assets/f29ad8e9-0a6d-4e21-aaa3-01ba011db8ef)

**Comment by huangsijun17** [comment]
测试环境：

> Firefox Nightly Version
> 35.0a1 (2024-12-01) (64-bit)
> Node.js Version
> v20.12.2
> Panel Version
> 10.4.0
> Matched Daemon Version
> 4.5.0

终端页面一切正常。使用无痕反复访问终端页面，未发现卡顿。
