### ISSUE TITLE
[Feature] 自动安装Java环境，多个服务器之间Java环境隔离

### ISSUE THREAD

**Issue by lnbiuc** [MCSManager/MCSManager#1447]
### Description

1、可以自动根据游戏版本安装Java环境
2、如果一个服务器运行了多个版本的游戏，版本文件隔离，Java环境隔离

### Reason

考虑到都已经使用面板了，仍需要手动安装Java，切换Java版本，十分不方便，不优雅。

**Comment by huangsijun17** [comment]
1. MCSM不可能主动识别你运行的jar文件等是需要什么JVM版本。
 2. MCSM只是一个webshell，不是操作系统，不可能管理其他程序之间的数据隔离。请使用Docker。

**Comment by lnbiuc** [comment]
> 1. MCSM不可能主动识别你运行的jar文件等是需要什么JVM版本。
> 2. MCSM只是一个webshell，不是操作系统，不可能管理其他程序之间的数据隔离。
> 3. 请使用Docker。

1、已经内置了一些整合包，这些已经有明确的版本了，是否可以支持自动配置Java环境
2、自动下载需要的Java版本，通过绝对路径使用是否可以实现隔离

**Comment by huangsijun17** [comment]
> > 1. MCSM不可能主动识别你运行的jar文件等是需要什么JVM版本。
> > 2. MCSM只是一个webshell，不是操作系统，不可能管理其他程序之间的数据隔离。
> > 3. 请使用Docker。
> 
> 1、已经内置了一些整合包，这些已经有明确的版本了，是否可以支持自动配置Java环境 2、自动下载需要的Java版本，通过绝对路径使用是否可以实现隔离

1. MCSM没有内置整合包。怎么明确版本？至于用户上传的整合包，请给出可行的版本判断方案。
MC所需的Java版本是一个和MC版本强相关、MOD弱相关的。MC 1.12可能需要Java8-11或Java11或Java17+，如何判断？更不要说一些小版本的以上以下的要求，如何确认？
2. 自动下载需要的Java版本，那么下载谁家的Java？OracleJDK的授权问题怎么解决解决？AdoptOpenJDK？Amazon Corretto JDK？Azul Zulu JDK？Eclipse Temurin JDK？IBM Semeru Runtime Open Edition JDK？还是华为？阿里？等等等等。
3. 下载JDK的兼容问题专门解决？Win x64/arm64 Linux x86/x64/armv7/armv8/armv8_64 MacOS x64/arm64 等等，怎么适配？谁来验证？
4. 不使用Docker，任何一个MC整合包都是**可以**访问其他整合包的内容的。要隔离，只能用Docker。我看不懂你说的绝对路径对于隔离有何作用。
