### ISSUE TITLE
MCSManager 9.0 版本测试版已经发布

### ISSUE THREAD

**Issue by Suwings** [MCSManager/MCSManager#467]
**如何参与**

加入QQ群 287215485 了解具体规则。

**关于新版本**

新版本采用 Typescript 作为后端语言且90%的功能全部重写或重构，测试版不会公布在 GitHub（目的是为了防止所有人都下载测试版使用），暂时采用压缩包下载的方式提供测试使用，后续会逐渐开源。欢迎有兴趣的朋友尝鲜。

功能主要是新增分布式管理，一个面板可以同时控制多台远程主机和更加丰富的API，总体分为面板端与守护进程端。

新版本的功能在初期阶段可能还不具备商业价值和 MCSManager 8 的现已实现功能，会初步在后期做功能添加。

**关于旧版本**

在新版本发布后，8.6.x版本将进行最后一次更新，修复一些bug且不新增任何功能，便不再继续更新8.x版本。如果你有众多数据需要迁移到新版本暂时还无法做到，后续会考虑写一些批量转换脚本帮助你将数据迁移到新版本。

**关于商业价值**

相信已经有少许服务商使用 MCSManager 面板进行出租，但是旧版本在设计之初并未完全考虑到商业出租等需求，主要还是方便个人为主。新版本将尽可能提高商业活动的价值，但是测试版并不具备商业价值。

**关于正式版发布**

测试版主要是测试功能和客户体验，测试周期可能会较长以避免后续出现问题，正式版发布待定。

**Comment by AlexanderMC8533** [comment]
表示期待

**Comment by Anders233** [comment]
那么怎么参与测试呢

**Comment by zhangfh-cq** [comment]
好耶，期待新版本

**Comment by Suwings** [comment]
> 那么怎样参与测试呢

正好补充参与方式：

测试版会直接公开下载地址，不用报名。

**Comment by AlexanderMC8533** [comment]
（uesless info）add some bugs and features


  
那么怎样参与测试呢
  
正好补充参与方式：
 
测试版会直接公开下载地址，不用报名。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AlexanderMC8533** [comment]
> > 那么怎样参与测试呢
> 
> 正好补充参与方式：
> 
> 测试版会直接在QQ群里面公开下载地址，不用报名。群：287215485

能不能在显眼的地方显示群QR码

**Comment by DreamVoid** [comment]
能不能让社区开源版也支持多用户？
可以设为多用户共同管理所有服务器，用来适应一个服务器有多个管理员的情况。

**Comment by Mitpoppy** [comment]
期待新版本，一直在用mcsm希望mcsm越来越好！
