### ISSUE TITLE
系统信息监控中的内存占用加入了buff/cache内存

### ISSUE THREAD

**Issue by Botium1** [MCSManager/MCSManager#474]
**图片:**
![image](https://user-images.githubusercontent.com/88444250/130602392-7084abca-c755-41d8-b817-81312e552214.png)
![image](https://user-images.githubusercontent.com/88444250/130602425-5b3eb82d-cdc5-4025-9d26-dd9811816274.png)
![image](https://user-images.githubusercontent.com/88444250/130602457-e0d7864b-7779-4e53-966f-6f297761ae05.png)

**内容:**
如上图所示，系统信息监控中的内存占用是加入了buff/cache后的数据，实际空闲的内存比显示的要大很多（从用户的角度看）。
（从操作系统的角度看这块内存确实被使用了）
最后建议把这一块改成用户能够使用的内存
![image](https://user-images.githubusercontent.com/88444250/130602582-73b67796-bd48-4650-a7e9-b64ae9e8507f.png)

**Comment by Suwings** [comment]
此为 Node 原生 API 获取的剩余内存数据，将来会寻找代替方案修复此问题。

**Comment by Botium1** [comment]
> 此为 Node 原生 API 获取的剩余内存数据，将来会寻找代替方案修复此问题。

好！

**Comment by dzoer** [comment]
> 此为 Node 原生 API 获取的剩余内存数据，将来会寻找代替方案修复此问题。

这个有影响吗？什么时候能修复

**Comment by Suwings** [comment]
无很大使用影响，就是容易让用户产生误判。

已有代替方案，未来版本将使用 https://www.npmjs.com/package/systeminformation 这个库来获取内容可用信息。

**Comment by huangsijun17** [comment]
> > 此为 Node 原生 API 获取的剩余内存数据，将来会寻找代替方案修复此问题。
> 
> 这个有影响吗？什么时候能修复

我在多年前就上报nodejs了，作者不修。若有疑问，建议向nodejs反馈。
PS，关键是在Windows获取到的和Linux的策略都不一样。

**Comment by Suwings** [comment]
新版已修。
