### ISSUE TITLE
将用户数据页面的UUID和玩家名的分两排显示改为单排显示

### ISSUE THREAD

**Issue by MiaoAXin** [MCSManager/MCSManager#484]
**你对哪些功能有建议或想法？**
将用户修改页面，uuid和玩家名合并单排显示
**这些功能有哪些代替方案？**
不知道
**对应你提出的内容，你觉得有什么价值？**
移动端方便浏览与修改
**其他内容:**

（功能请求或者功能建议均准许自由发挥，无特定限制模板，你可以在这里写下任何你想说的文字。）

**Comment by MiaoAXin** [comment]
请注意，这个issue是提供9.0 捐赠内测 的反馈

**Comment by huangsijun17** [comment]
建议您去9.0的UI仓库反馈：
https://github.com/Suwings/MCSManager-UI

**Comment by MiaoAXin** [comment]
> 建议您去9.0的UI仓库反馈：
> https://github.com/Suwings/MCSManager-UI

其实看过，但是这个仓库貌似是前端的东西

**Comment by AlexanderMC8533** [comment]
我感觉这个地方应该和前端部分无关，所以没有在UI那个仓库提及





建议您去9.0的UI仓库反馈：
https://github.com/Suwings/MCSManager-UI

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
