### ISSUE TITLE
关于现有以及未来MCSM9中Server List Ping的问题

### ISSUE THREAD

**Issue by huangsijun17** [MCSManager/MCSManager#496]
> > > tps是需要侵入性监测的内容，例如Forge、LaggRemover等。启动面板只是一个模拟shell，不通过网络通信来获取信息。什么时候ping/pang包可以获取到tps信息了，MCSManager便有可能加入该功能。玩家id是可以pang到的，但正版头像获取不行。
> > 
> > 
> > 或许可以通过定时ping来进行统计
> > Ping是包含玩家列表的(包括UUID): [Server List Ping | wiki.vg](https://wiki.vg/Server_List_Ping) 也可以通过ID来获取UUID: [MOJANG API | wiki.vg](https://wiki.vg/Mojang_API#Username_to_UUID) 可以通过UUID来获取玩家皮肤进而显示头像: [MOJANG API | wiki.vg](https://wiki.vg/Mojang_API#UUID_to_Profile_and_Skin.2FCape)
> > 但是我觉得读取服务端存储的包含用户UUID的文件获取是个好办法（这些文件是否包含有类似于 `lastLogin` 的信息？）
> 
> 我能说，现有代码里的 Server List Ping 获取服务器名都还有BUG吗？UUID都没获取。现有没有完善的nodejs的Server List Ping代码。

![image](https://user-images.githubusercontent.com/36162655/139777712-bb65dd2d-1dd8-4107-9c96-4a2e02dc59bf.png)

但是 ping 服务端确实可以正确返回玩家的UUID，理论上可行，可以尝试编写nodejs的代码。

如果实现起来难度较大就再思考别的解决方案吧，而且我记得类似统计功能似乎是有某个插件实现过，或许可以不在面板实现此功能

_Originally posted by @nidbCN in https://github.com/Suwings/MCSManager/discussions/455#discussioncomment-1573581_

之前我试过，网上的Python代码等可以获取。但是我抓包以及分析Python代码都难以写出一个相对完善的JS-Ping插件。若您有能力，可以自行建立一个仓库，写一个独立的Server List Ping组件。

**Comment by Suwings** [comment]
想法不错，但是太忙，且正在更新MCSM9且测试其稳定性，最高优先级应该是这个。

关于获取玩家列表，这个功能确实很实用，不是必须，写一个Node版本的获取代码需要点时间，

我希望能有人贡献这份代码，而不是啥都是我来写。如果你愿意，你可以研究一下，尝试写出来，写出后我将会把你的Github名字写入到此功能模块代码中的第一行。

**Comment by nidbCN** [comment]
> 想法不错，但是太忙，且正在更新MCSM9且测试其稳定性，最高优先级应该是这个。
> 
> 关于获取玩家列表，这个功能确实很实用，不是必须，写一个Node版本的获取代码需要点时间，
> 
> 我希望能有人贡献这份代码，而不是啥都是我来写。如果你愿意，你可以研究一下，尝试写出来，写出后我将会把你的Github名字写入到此功能模块代码中的第一行。
> 
> （虽然我是做MCSM面板，但是我对MC协议这一方面无任何了解）

我的顾虑是定时ping服务器然后记录统计是不是不太优雅，而且nodejs也不是很会，可以尝试。那个包看起来也不是很复杂的样子

**Comment by Suwings** [comment]
MCSM 面板在以后会支持 Steam 游戏服务端程序或其他可开私服程序，其局限性将不在 Minecraft，以后各种游戏的通讯协议不可能一个个的去编写。

包括 MCSM 9 版本的配置中心功能，我甚至只做了几个基本的MC服务端的配置兼容，其他的内容将交给你们，每一位贡献者均将可显示名字，以后也会出这方面的教程，教你们如何把 MCSM 9 对接到新的配置文件。

**Comment by Suwings** [comment]
> > 想法不错，但是太忙，且正在更新MCSM9且测试其稳定性，最高优先级应该是这个。
> > 关于获取玩家列表，这个功能确实很实用，不是必须，写一个Node版本的获取代码需要点时间，
> > 我希望能有人贡献这份代码，而不是啥都是我来写。如果你愿意，你可以研究一下，尝试写出来，写出后我将会把你的Github名字写入到此功能模块代码中的第一行。
> > （虽然我是做MCSM面板，但是我对MC协议这一方面无任何了解）
> 
> 我的顾虑是定时ping服务器然后记录统计是不是不太优雅，而且nodejs也不是很会，可以尝试。那个包看起来也不是很复杂的样子

可以试试，写好了可以在 QQ 群内跟我说，提交 PR 可能不太行，因为面板没有做 `玩家列表` 的显示功能，如果你提交PR的话只能作为一个功能模块来进行提交，但是此功能模块是无用的，因为它未对接到 MCSM。

**Comment by Suwings** [comment]
只要能获取到玩家列表 UUID ，基本问题就解决了 90%，至于你说的头像问题，不论是缓存还是不缓存都可行。

> https://github.com/deathcap/node-minecraft-ping
> 
> 我刚才搜索出来一个，看上去像是支持1.7协议以及Unicode字符的。 要是可以，再加一个获取UUID和头像进去。
> 
> 问题是，头像未来考虑前端获取还是后端获取？后端获取的话，还要涉及缓存问题，毕竟不可能每次都从麻将下一遍头像。

**Comment by huangsijun17** [comment]
> 只要能获取到玩家列表 UUID ，基本问题就解决了 90%，至于你说的头像问题，不论是缓存还是不缓存都可行。
> 
> 可直接请求官方的 API，获取玩家数据。
> 
> > https://github.com/deathcap/node-minecraft-ping
> > 我刚才搜索出来一个，看上去像是支持1.7协议以及Unicode字符的。 要是可以，再加一个获取UUID和头像进去。
> > 问题是，头像未来考虑前端获取还是后端获取？后端获取的话，还要涉及缓存问题，毕竟不可能每次都从麻将下一遍头像。

也不用我去了，UUID的现有的就有：

https://www.npmjs.com/package/minecraft-status/v/1.1.0

找对关键词，谷歌一搜一大把。

**Comment by nidbCN** [comment]
> https://github.com/deathcap/node-minecraft-ping
> 
> 我刚才搜索出来一个，看上去像是支持1.7协议以及Unicode字符的。 要是可以，再加一个获取UUID和头像进去。
> 
> 问题是，头像未来考虑前端获取还是后端获取？后端获取的话，还要涉及缓存问题，毕竟不可能每次都从麻将下一遍头像。

这个仓库我测试了一下，1.17.1版本应该是不兼容，至少他没有给我玩家的列表（我也很迷惑）
![image](https://user-images.githubusercontent.com/36162655/139820086-2e6e341b-4fd5-4058-902c-810e12c703eb.png)

**Comment by Suwings** [comment]
如果能有兼容 Minecraft Java 的全版本的那就很不错，如果可能，最好还能找找针对基岩版服务器的获取玩家列表。

目前MCSM9已经有人为项目贡献基本的 Java 版与基岩版的 Ping 协议代码。但是获取玩家列表的，暂时还没有任何代码。

**Comment by nidbCN** [comment]
> 如果能有兼容 Minecraft Java 的全版本的那就很不错，如果可能，最好还能找找针对基岩版服务器的获取玩家列表。
> 
> 目前MCSM9已经有人为项目贡献基本的 Java 版与基岩版的 Ping 协议代码。但是获取玩家列表的，暂时还没有任何代码。

玩家列表是在ping的包里面的，我或许能试试能不能摸一个出来。基岩版的话看文档吧，能找到Wiki没准就行

**Comment by Doctor-Yin** [comment]
如果是ping包,在线玩家超过12(大概)就不能获取到全部了

**Comment by Suwings** [comment]
> > 如果能有兼容 Minecraft Java 的全版本的那就很不错，如果可能，最好还能找找针对基岩版服务器的获取玩家列表。
> > 目前MCSM9已经有人为项目贡献基本的 Java 版与基岩版的 Ping 协议代码。但是获取玩家列表的，暂时还没有任何代码。
> 
> 玩家列表是在ping的包里面的，我或许能试试能不能摸一个出来。基岩版的话看文档吧，能找到Wiki没准就行

一年过去了，还考虑摸一摸吗？

**Comment by Doctor-Yin** [comment]
> 

我写了Java的模拟登录,ping,但面板好像不能直接接入
https://github.com/Forsaken-Land/doctor

**Comment by Doctor-Yin** [comment]
> > > 如果能有兼容 Minecraft Java 的全版本的那就很不错，如果可能，最好还能找找针对基岩版服务器的获取玩家列表。
> > > 目前MCSM9已经有人为项目贡献基本的 Java 版与基岩版的 Ping 协议代码。但是获取玩家列表的，暂时还没有任何代码。
> > 
> > 
> > 玩家列表是在ping的包里面的，我或许能试试能不能摸一个出来。基岩版的话看文档吧，能找到Wiki没准就行
> 
> 一年过去了，还考虑摸一摸吗？
我写了Java的模拟登录,ping,但面板好像不能直接接入
https://github.com/Forsaken-Land/doctor

**Comment by Doctor-Yin** [comment]
> > > 如果能有兼容 Minecraft Java 的全版本的那就很不错，如果可能，最好还能找找针对基岩版服务器的获取玩家列表。
> > > 目前MCSM9已经有人为项目贡献基本的 Java 版与基岩版的 Ping 协议代码。但是获取玩家列表的，暂时还没有任何代码。
> > 
> > 
> > 玩家列表是在ping的包里面的，我或许能试试能不能摸一个出来。基岩版的话看文档吧，能找到Wiki没准就行
> 
> 一年过去了，还考虑摸一摸吗？


我写了Java的模拟登录,ping,但面板好像不能直接接入
https://github.com/Forsaken-Land/doctor

**Comment by Suwings** [comment]
那确实，语言不一样，有空我看看把，谢谢了
