### ISSUE TITLE
MD5 不安全 & `Math.random()` 不安全

### ISSUE THREAD

**Issue by andylizi** [MCSManager/MCSManager#507]
<a href="https://github.com/Suwings/MCSManager/wiki/%E7%99%BB%E5%BD%95%E5%AF%86%E7%A0%81%E4%BC%A0%E9%80%92%E8%BF%87%E7%A8%8B%E5%9B%BE" target="_blank"><img src="https://github.com/Suwings/Suwings.github.io/raw/master/mcserver/pass.png" alt="登录验证流程" width="70%"/></a>

### 关于 MD5

MD5 在 1996 年就已经暴露出了安全隐患，2004 年实现了第一个完整的碰撞，而现在随便一台家用电脑都能在几秒内做到，因此在许多年前就早已不建议将 MD5 用于任何用途了。

目前最推荐使用的密码散列算法是 Argon2id。

以及，像 `md5(md5(md5(password) + salt) + salt)` 这样的方式[对提升安全并没有帮助](https://softwareengineering.stackexchange.com/q/115406)。

### 关于 `Math.random()`

https://github.com/Suwings/MCSManager/blob/f4114820dd26a968977b070bd5618724d3691496/core/User/CryptoMine.js#L17-L26

登录验证时生成随机令牌的算法用的是 `Math.random()`，而它生成的随机数不是 cryptographically secure 的，理论上可以被攻击者预测，[实践中也有人做到了](https://blog.securityevaluators.com/hacking-the-javascript-lottery-80cc437e3b7f)，因此不建议将其用于与安全有关的用途。[MDN 中 `Math.random()` 的条目](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random) 写道：

> **Note**: Math.random() does not provide cryptographically secure random numbers. Do not use them for anything related to security. Use the Web Crypto API instead

**Comment by Suwings** [comment]
感谢你的优秀意见反馈，安全问题确实需要与时俱进。

新版本将会尽可能支持 HTTPS 并提供详细的安装教程，来代替旧版本的原始加密算法。

**Comment by andylizi** [comment]
唔，新版本好像还是在用 md5，并且这回连盐都不加了……？

https://github.com/MCSManager/MCSManager/blob/66ca1cb97de745fc9e1f71324ffe4d533c4d4c35/src/app/service/system_user.ts#L85-L92

**Comment by Cubik65536** [comment]
> 唔，新版本好像还是在用 md5，并且这回连盐都不加了……？
> 
> https://github.com/MCSManager/MCSManager/blob/66ca1cb97de745fc9e1f71324ffe4d533c4d4c35/src/app/service/system_user.ts#L85-L92

目前新版本仍然是测试版，我相信在正式发布之前还会再进行改进

**Comment by andylizi** [comment]
> **第一个发行版**
> 这是 9.0 内测版开始到现在的第一个公开发行版，功能依然在完善与优化，但已经过数百名用户测试使用，所有问题已经全部解决。
