### ISSUE TITLE
建议支持向上翻动控制台自动加载历史

### ISSUE THREAD

**Issue by jiajiaxd** [MCSManager/MCSManager#511]
**你对哪些功能有建议或想法？**
建议支持向上翻动控制台自动加载历史
**这些功能有哪些代替方案？**
翻动控制台时一直点击历史按钮
**对应你提出的内容，你觉得有什么价值？**
在查日志时更加方便
**其他内容:**
如果可以的话，能出个TAB补全功能更好。CMD控制台是支持自动补全功能的。
（功能请求或者功能建议均准许自由发挥，无特定限制模板，你可以在这里写下任何你想说的文字。）

**Comment by Mr-Ao-Dragon** [comment]
8.0寿终正寝，不再处理新Issue，请考虑mcsm9.
