### ISSUE TITLE
关闭面板时停止Docker容器

### ISSUE THREAD

**Issue by efsg** [MCSManager/MCSManager#512]
之前有人提过关闭时停止实例，经过测试关闭面板时会同时关闭服务器，但并不会停止Docker容器，因为要运行多个不同Java版本所以Docker容器必不可少，希望能在面板关闭时停止容器。
PS：最好可以指定容器名

**Comment by Suwings** [comment]
操作系统版本，面板版本（8？9?）。

**Comment by efsg** [comment]
> 操作系统版本，面板版本（8？9?）。

忘记写了，面板是最新的8.7.0，系统是裸机装的debian10

**Comment by Suwings** [comment]
感谢你的反馈，8.7 已经封版不再维护更新，此问题不会修复，9 版本刚发布时可能会有此问题，后续会处理此问题。

https://github.com/Suwings/MCSManager/releases/tag/v8.7.0
