### ISSUE TITLE
unraid能部署吗？

### ISSUE THREAD

**Issue by abo2029** [MCSManager/MCSManager#515]
**内容:**
有大佬能教一下如何再unraid上部署吗？

**Comment by huangsijun17** [comment]
理论上可以。MCSManager只是一个Nodejs程序。不考虑Docker组件的话，是跨一切能跑nodejs的系统。
unraid似乎内置了nodejs，参考一般Linux的手动安装方法即可。

**Comment by xrh0905** [comment]
我跑在VMs里的Debian虚拟机上
看看有没有人封装Docker?

**Comment by efsg** [comment]
> 我跑在VMs里的Debian虚拟机上 看看有没有人封装Docker?
Linux推荐直接使用node.js部署，自用Docker镜像
https://hub.docker.com/r/efsg/mcsm-docker/
