### ISSUE TITLE
管理和设置点进去都是同一个界面，无法修改设置

### ISSUE THREAD

**Issue by maxpan0811** [MCSManager/MCSManager#521]
**系统环境:**
windows server 2019
**面板版本:**
8.6.9和8.7
**Node 版本:**
12.16
**出现概率:**
每次
**出现的问题 (BUG):**
点“管理”按钮和“设置”按钮都出来的是管理界面
**复现操作步骤:**

**Comment by Suwings** [comment]
请具体说明复现步骤，比如菜单栏->服务端管理->参数按钮这样描述。

否则我不知道你在描述什么。

**Comment by maxpan0811** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    你好，就是点左侧的“服务端管理”进去，再点击“管理”按钮或者“参数”按钮，出来的都是管理界面，我本来希望能够进入参数界面修改java程序所在目录。谢谢。
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                潘渤
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2022年01月9日 ***@***.***> 写道： 




请具体说明复现步骤，比如菜单栏->服务端管理->参数按钮这样描述。

否则我不知道你在描述什么。



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you authored the thread.Message ID: ***@***.***>
