### ISSUE TITLE
文档与WiKi有关SSL部分内容部分过期

### ISSUE THREAD

**Issue by xrh0905** [MCSManager/MCSManager#522]
自8.7.0后 SSL无需修改`public/common/URL.js`WiKi与Readme.md中相关条目过时.

**Comment by Suwings** [comment]
已更新，谢谢反馈，如有遗漏，请指出。

https://github.com/MCSManager/MCSManager/wiki/%E5%85%B3%E4%BA%8E%E5%AE%9D%E5%A1%94%E9%9D%A2%E6%9D%BF%E7%9A%84-Nginx-%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86%E4%BB%A5%E5%8F%8ASSL%E8%AF%81%E4%B9%A6%E9%83%A8%E7%BD%B2

https://github.com/MCSManager/MCSManager/wiki/%E4%BD%BF%E7%94%A8-Apache2.4-%E8%BF%9B%E8%A1%8C%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86
