### ISSUE TITLE
登录时提示服务器错误

### ISSUE THREAD

**Issue by CCBlueX666** [MCSManager/MCSManager#523]
**系统环境:**  Linux_x86-64

**面板版本:**  8.7.0

**Node 版本:**  

**出现概率:**  100%

**出现的问题 (BUG):**  如题

**复现操作步骤:**  安装面板后，运行服务器，突然与服务器断开连接（意外），接着重启服务器就出现服务器错误提示
![image](https://user-images.githubusercontent.com/60721270/149043176-b864daa8-4c6f-4d4b-ae09-58e3a16eb331.png)

**Comment by Suwings** [comment]
`突然与服务器断开连接（意外）` 指的是你的 SSH 链接断开？是否是 MCSM 后台程序已经因为断开而关闭所导致？

具体错误信息可以在 Chrome 中按 F12 点击 Console 查看具体错误信息。

可能的解决方案：

1. 删除 core/info.json
2. 重启面板所有服务或程序（如果不清楚可以重启 Linux 主机）
3. 清理浏览器缓存，强制刷新再尝试。

**Comment by CCBlueX666** [comment]
已解决，十分感谢！

**Comment by Suwings** [comment]
> 已解决，十分感谢！

能麻烦说说具体原因与解决方案吗？谢谢。~

**Comment by CCBlueX666** [comment]
清理浏览器缓存，重启服务器后端即可
