### ISSUE TITLE
繁體環境控制面板會產生亂碼

### ISSUE THREAD

**Issue by kazma258** [MCSManager/MCSManager#525]
**内容:**
請問如何修改終端的編碼，簡體編碼會與繁體的編碼相衝突
![image](https://user-images.githubusercontent.com/52396503/149256422-7bf3d62c-172a-4cfa-b2cc-8a8ddbf14bb2.png)

**Comment by Suwings** [comment]
在實例參數設置界面，有一個輸入編碼與輸出編碼的功能，通過此設置更改成 big5 或 utf-8 也許能修復此問題。
