### ISSUE TITLE
这东西用着用着就无法登录了，显示服务器错误，不知道是咋回事……

### ISSUE THREAD

**Issue by foyue5666** [MCSManager/MCSManager#526]
[https://ae01.alicdn.com/kf/Ha4cea3965fbe430fab443043cc1823daa.png](url)

**Comment by Suwings** [comment]
请提供更详细的系统信息，面板版本，按 F12 点 Console 选项卡提供更详细的报错信息。

**Comment by foyue5666** [comment]
![image](https://user-images.githubusercontent.com/82329134/149509013-c1b4713e-7e8a-4cf8-a971-f6e2592902a8.png)
这是具体的报错：
jquery-3.2.1.min.js:4 
 POST http://localhost:23333/user/login 500 (Internal Server Error)
send @ jquery-3.2.1.min.js:4
ajax @ jquery-3.2.1.min.js:4
r.<computed> @ jquery-3.2.1.min.js:4
logging @ login.js:25
success @ login.js:15
i @ jquery-3.2.1.min.js:2
fireWith @ jquery-3.2.1.min.js:2
A @ jquery-3.2.1.min.js:4
(匿名) @ jquery-3.2.1.min.js:4
load(异步)  
send @ jquery-3.2.1.min.js:4
ajax @ jquery-3.2.1.min.js:4
r.<computed> @ jquery-3.2.1.min.js:4
MCSERVER.login @ login.js:4
MCSERVER.btnLogin @ login.js:74
enKeyPress @ (索引):79
onkeypress @ (索引):62
