### ISSUE TITLE
反代

### ISSUE THREAD

**Issue by Gingmzmzx** [MCSManager/MCSManager#530]
**系统环境:** centos7.7

**面板版本:** mcsm8.7

**Node 版本:** 额我忘了懒得查了

**出现概率:** 每次

**出现的问题 (BUG):** 配置nginx反代后通过域名访问提示与服务器链接中断

**复现操作步骤:** 刷新网页也没用，同样的提示

**Comment by Suwings** [comment]
应该是未能反向代理 Websocket 连接所致，详情参考：

https://github.com/MCSManager/MCSManager/wiki 右边列表
