### ISSUE TITLE
未定义登录的突然错误，无法启动服务器。

### ISSUE THREAD

**Issue by Gamershy** [MCSManager/MCSManager#538]
提交 BUG 需要很多信息，请尽可能完善以下信息，若无法全面完善也无妨，写好之后请删除这行文字。

**系统环境:** Windows 10

**面板版本:** 8.7.0

**Node 版本:** 16.13.2

**出现概率:**  未知

**出现的问题 (BUG):** 我不是以中文为母语的人，所以我使用谷歌翻译，我希望这不是问题。 问题是在启动 MCSManager 时向控制台发送垃圾邮件的错误。 错误是“无法读取未定义的属性”。 这会导致 MCSManager 最终自行重启，导致我运行的服务器无法正常启动。 有什么帮助吗？ 我试过重新安装 MCSManager，删除服务器，重置登录，都无济于事。

**复现操作步骤:** 未知，它只是随机开始发生。
![image](https://user-images.githubusercontent.com/25855662/150983545-851f1cd5-1434-41df-8d89-d71cf75e317e.png)

**Comment by Dudu308308** [comment]
same problem

**Comment by cngege** [comment]
> 

感谢感谢 一样的问题，解决了

**Comment by Gamershy** [comment]
thank you, this fixed it. And also thank you for the translation.
