### ISSUE TITLE
[MCSM9]关于基岩版服务器适配的一些建议

### ISSUE THREAD

**Issue by echoker** [MCSManager/MCSManager#539]
在MCSM9的“新建实例引导程序”中选择基岩版BDS服务端后，会出现和Java服务端一样的“上传单个服务端软件”，但是BDS服务端并不存在“单个服务端软件”，并不像Java服务端一样，只需要一个jar文件就可以生成其它文件。

希望能够删除在BDS服务端选项中的“上传单个服务端软件”按钮

还有一个建议是，因为BDS服务端并不像Java服务端一样有多种第三方服务端可以选择，只有官方版本和一些第三方插件加载器
可以添加一个自动安装服务端的功能，输入版本号即可下载对应BDS服务端

官方下载链接：
[https://minecraft.azureedge.net/bin-{系统，linux/win}/bedrock-server-{版本}.zip](https://minecraft.azureedge.net/bin-{系统，linux/win}/bedrock-server-{版本}.zip) 

当然，在国内一些网络环境中，通过官方链接可能无法下载或者是速度很慢，但这个功能还是很方便的

同样也希望能够有类似翼龙面板、MU面板的“模板”功能，可以通过预设好的模板（通常含有容器运行环境、启动命令、自动安装脚本、配置文件自动化配置，如自动更改端口、通过普通用户界面设置的变量值来修改配置文件内容等）快速配置服务器，实现一键安装/重装/切换服务端环境等功能。
这样Java的一些常用服务端也可以通过这样的功能实现一键安装

在商用环境中，类似这样的功能比较也重要

顺便提醒一下：基岩版不仅有官方的BDS服务端，还有两大第三方服务端——NukkitX(NK，原分支名为Nukkit)和PocketMine-MP(PMMP，也常简称为PM)。
NK是Java编写的，与Java服务端的管理基本一致；PM是PHP编写的，服务端文件为一个.phar文件，和Java服务端类似，启动命令执行后，会自动生成其它文件。

**Comment by Suwings** [comment]
谢谢你的意见，想法都很不错，但个人的力量是有限的，不可能一应俱全的做完所有功能，如果可以，我希望你能提供功能代码贡献。
