### ISSUE TITLE
8.70版本把崩溃自启删了

### ISSUE THREAD

**Issue by Alloy81284** [MCSManager/MCSManager#540]
服务器有时候崩溃但是我有时没空重启

**Comment by huangsijun17** [comment]
啥意思？

**Comment by Suwings** [comment]
可以降级到 8.6.X 版本或升级到 9.X 版本，此功能均已实现。

Linux 版本一键安装：
wget -qO- https://cdn.jsdelivr.net/gh/MCSManager/Script/setup.sh | bash
Windows 版本下载地址：
https://mcsmuuwinn.coding.net/s/4b2e9f85-1e7b-4f3e-a04d-c1af1631e848
