### ISSUE TITLE
mcsm9可能存在误删文件的bug

### ISSUE THREAD

**Issue by QFLSqfls** [MCSManager/MCSManager#541]
**系统环境:**
linux
**面板版本:**
9.0.0
**Node 版本:**
v16.13.2
**出现概率:**
10%(一个月内出现两次)
**出现的问题 (BUG):**
mcsm9可能在删除文件的逻辑上存在问题
**复现操作步骤:**
删除一个实例
改面板下面的所有服务器文件会被删除 （不确定是否是这操作
**补充**
针对mc服务器
其他自定义无波及
其他mc服务器的实例未被删除 且在运行 但是出现报错
其他mc服务器的根文件仅留下了world/plugin文件夹
（大概率 未能准确判断 其他日志（包括mc，mcsm，系统等）

**Comment by Suwings** [comment]
尝试了很多次，没有办法触发你这个情况。
