### ISSUE TITLE
分布式服务更新地址和端口后没更新秘钥导致连接失败后版本会显示不一致

### ISSUE THREAD

**Issue by Cjsah** [MCSManager/MCSManager#542]
![_WP($)UF}~43B(5BOC7@H)H](https://user-images.githubusercontent.com/46415647/151916260-55f79b97-1779-4b90-8e95-00cf9975408e.png)

**Comment by Suwings** [comment]
感谢反馈，原因是无法连接守护进程时，自然无法获取守护进程版本数据，导致显示不一致，稍后修复。

**Comment by Suwings** [comment]
已修
