### ISSUE TITLE
[BUG] 服务端启动进程时显示 进程启动失败，进程PID为空，请检查启动命令和相关参数

### ISSUE THREAD

**Issue by XIAO-DOU-ZI** [MCSManager/MCSManager#545]
**操作系统版本**
Linux
**面板版本**
9.2.1
**出现概率**
100%触发

**BUG 详情描述**
开启服务端时显示[错误] 进程启动失败，进程PID为空，请检查启动命令和相关参数

**复现步骤**
在Linux根目录下新建server文件夹
服务端启动参数为java -jar BungeeCord.jar
启动类型为蹦极端

**Comment by Suwings** [comment]
这不是 bug，这是您本地环境没有安装正确，安装java后重启面板，或者指定java路径，如 /opt/java/bin/java -jar BungeeCord.jar。

**Comment by gtlx** [comment]
能100%触发的那不叫bug

**Comment by huangsijun17** [comment]
> 能100%触发的那不叫bug

MCSM通过systemd管理时，继承系统的环境变量，而你JAVA环境变量通过.bashrc设置时是**安装给当前用户**的。
系统服务调不到用户自己安装的程序能叫BUG？
