### ISSUE TITLE
[BUG]使用mcsm解压压缩包时目录大小变为4kb

### ISSUE THREAD

**Issue by XIAO-DOU-ZI** [MCSManager/MCSManager#546]
操作系统版本
Linux
面板版本
9.2.1
出现概率
100%触发

BUG 详情描述
解压压缩包时文件夹大小4kb 无任何文件
压缩包使用mcsm创建
unzip可以正常解压

复现步骤
解压特定压缩包即可触发

**Comment by Doctor-Yin** [comment]
文件夹大小问题看这个#590
