### ISSUE TITLE
[BUG] 关闭或重启bungeecord服务器

### ISSUE THREAD

**Issue by RimuruChan** [MCSManager/MCSManager#548]
**操作系统版本**
Centos 8
**面板版本**
9.2.1

**出现概率**
100%

**BUG 详情描述**
command not found

**复现步骤**
关闭或重启bungeecord服务器

**Comment by Suwings** [comment]
请将关闭命令设置为 end 之后再进行尝试。

**Comment by RimuruChan** [comment]
没看到这个设置项，我以为预置进去了
