### ISSUE TITLE
[BUG] 原生终端渲染错误

### ISSUE THREAD

**Issue by RimuruChan** [MCSManager/MCSManager#551]
**操作系统版本**
Centos 8
**面板版本**
9.2.1

**出现概率**
100%

**BUG 详情描述**
![image](https://user-images.githubusercontent.com/42002296/152675504-7a1562a0-06a9-4c64-b51e-f88210a74d5b.png)

**复现步骤**
正常启动服务器

**Comment by Suwings** [comment]
你这个是不是程序自己带了一个颜色渲染，你应该把 MCSManager 自带的颜色渲染关掉，用程序自己的颜色渲染。

关闭方法在终端左侧的终端设置按钮上，关掉以正确显示程序自带的颜色。

**Comment by RimuruChan** [comment]
已更新issue

**Comment by Suwings** [comment]
你这个更新的意思是不是指无缘无故多了一个换行，跟颜色还有关系吗？

**Comment by RimuruChan** [comment]
是

**Comment by RimuruChan** [comment]
颜色也有问题，看我在ui里发的issue
