### ISSUE TITLE
[BUG]开启L4D2服务端时出现错误

### ISSUE THREAD

**Issue by SealsTak** [MCSManager/MCSManager#552]
**操作系统版本**
win11 win server2016
**面板版本**
 9.2 发行版

**出现概率**
100%

**BUG 详情描述**
L4D2服务端出现报错窗口
CTextConsoleWin32::GetLine: !GetNumberOfConsoleInputEvents
![image](https://user-images.githubusercontent.com/65878832/152725019-a88443bc-9a86-4d9e-8f08-018e7cc2ec36.png)

**复现步骤**
![image](https://user-images.githubusercontent.com/65878832/152725061-bd075b53-dc4e-4a0c-9178-78bdb6186b17.png)
虽然应该是l4d2的锅，但是能修复的话岂不是一端多用2333

**Comment by Suwings** [comment]
这不算 BUG，L4D2 我估计需要一个终端环境，但是 MCSM 暂不支持这个特性。
