### ISSUE TITLE
一丢丢小问题

### ISSUE THREAD

**Issue by Cjsah** [MCSManager/MCSManager#553]
1. 左边的图片之间有一条黑线

   ![image](https://user-images.githubusercontent.com/46415647/152831300-5bac396d-ebb2-4790-91bd-b6449cb43dca.png)

2. 自己加的颜色符号在终端中颜色渲染正常, 但在终端日志中出现大量的颜色字符希望去掉

3. 终端日志超级卡

   ![image](https://user-images.githubusercontent.com/46415647/152831706-36406bd4-9ba9-40a9-9d2d-0fe99b0d60eb.png)

**Comment by RimuruChan** [comment]
建议自己修（
我都提了四个pr了

**Comment by RimuruChan** [comment]
我想给终端加个像以前一样的上翻功能，然后把这个终端日志去掉

**Comment by Suwings** [comment]
> 我想给终端加个像以前一样的上翻功能，然后把这个终端日志去掉

我建议你一个一个功能来，先把你原先说的坑提交PR填了，一次更新太多我也审计不过来。

另外你这个想法，恐怕很难实现但是不是不可能，不建议尝试做。
