### ISSUE TITLE
[Feature] 建议在一键安装脚本内的初始化依赖软件安装中加入wget的安装

### ISSUE THREAD

**Issue by SuperPokeS** [MCSManager/MCSManager#556]
**面板版本**
9.2.0

**想法/建议**
对于一些刚刚进行系统最小安装的主机来说可能没有及时安装wget，这会导致下载nodejs压缩包失败而且安装脚本并不会提示你，需要自行查看

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
IDK

**Comment by huangsijun17** [comment]
那玩意我在重写……
记得去加上了。
