### ISSUE TITLE
[BUG] 开发文档勘误

### ISSUE THREAD

**Issue by SuperPokeS** [MCSManager/MCSManager#557]
**操作系统版本**
Centos7
**面板版本**
9.2.0

**出现概率**
100%

**BUG 详情描述**
[截图](https://imgs.wiki/imgs/2022/02/b216defd297231ef.png)

**复现步骤**
访问API /api/auth

**Comment by Suwings** [comment]
已修，预计 4 小时左右缓存刷新到全球各地区。

https://github.com/MCSManager/Documentation/blob/main/panel/user_register.md
