### ISSUE TITLE
[Feature] 支援github自動部屬

### ISSUE THREAD

**Issue by Anonymous6214** [MCSManager/MCSManager#559]
**面板版本**
9.2

**想法/建议**
希望能像是PAAS服務一樣可以抓取github的commit webhook並自動部屬github上的內容, 偵測專案類型的話可以使用herokuish(類似heroku的Procfile), 最理想的話可以用github登入並創建一個github app就可以自動抓取專案了(可參考ledodokku)。

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
如果非開MC伺服器的人70%

**Comment by Suwings** [comment]
感谢反馈，这个软件不是专门针对技术人员的，还是尽可能希望能够降低使用门槛，因为并不是每个人都有一个 Github 账号，也不是每一个人都明白 PAAS，Git，CI/CD 等。

最简单的部署方式依然还是现有的 Linux 一键脚本安装，Windows 下使用压缩包即可。

更新方法的话，Linux 一键安装后与生产版本的 Github 已经自动关联，只需两个目录只需 git pull 即可，这方面以后也可以写个脚本一键处理。

Windows 的话需要手动下载最新代码覆盖更新（因为 Windows 并不自带 Git）。

**Comment by Anonymous6214** [comment]
不是的，我是說使用實例的時候支援GitHub,不是mcsmanager軟件需要GitHub自動部署

**Comment by huangsijun17** [comment]
> 不是的，我是說使用實例的時候支援GitHub,不是mcsmanager軟件需要GitHub自動部署

是指从git获取服务端文件吗？
为防止滥用，MCSM可能不会添加远程下载的功能。

**Comment by Anonymous6214** [comment]
像我有時候需要跑discord bot程序, 每次寫好東西上傳到github之後還要手動從服務器主機下載檔案, 添加"自動從github部屬"這個服務可以省略掉手動從服務器主機下載檔案這個步驟

具體的話因為github可以設定每次commit的時候會有webhook, mcsmaneger就可以抓取該webhook然後開始自動部屬

**Comment by huangsijun17** [comment]
> 像我有時候需要跑discord bot程序, 每次寫好東西上傳到github之後還要手動從服務器主機下載檔案, 添加"自動從github部屬"這個服務可以省略掉手動從服務器主機下載檔案這個步驟
> 
> 回復 @huangsijun17 遠程下載可以改成只有自己對該儲存庫有管理權限才能添加進mcsmanager
> 
> 具體的話因為github可以設定每次commit的時候會有webhook, mcsmaneger就可以抓取該webhook然後開始自動部屬

给你一个建议，你可以试试看把启动命令改一下，加一个git pull的拉取在前面。
