### ISSUE TITLE
[BUG] 面板无法建立 wss 连接

### ISSUE THREAD

**Issue by meepuru** [MCSManager/MCSManager#560]
**环境**
FedoraServer 35
NodeJS 16.14.0
Nginx 1.20.2

**软件版本**
Web 9.2.1
Daemon 1.3.0

**BUG 详情描述**
因为面板本身使用 https 进行访问, 所以也将后端配置上了 wss , 但此时面板无法连接 wss 地址, 同时 Nginx 未记录到访问日志, 防火墙已放行相关端口并已测通, 面板为全新手动安装
将面板切换到 http 环境下使用默认端口时功能正常

**具体配置**
Nginx(daemon.conf) :
```properties
server {
    listen 9900 ssl;
    server_name mydomain.tld;
    ssl_certificate /path/to/crt;
    ssl_certificate_key /path/to/key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;
    ssl_session_tickets off;
    ssl_dhparam /etc/ssl/certs/dhparam.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    client_max_body_size 2048m;

    location / {
        proxy_pass http://localhost:24444/;
        root   html;
        index  index.html index.htm;
        proxy_set_header Host localhost;
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        add_header X-Cache $upstream_cache_status;
        add_header Cache-Control no-cache;
        expires 12h;
    }
}
```
此时直接访问 https://mydomain.tdl:9900/ 时可以得到 "MCSManager Deamon: Status: OK."

面板守护进程各种配置下的情况 :
    1. 地址 : wss://mydomain.tld , 端口 : 9900 (此时无法连接, 提示 "无法连接到指定ip或者密钥错误", Nginx 未记录到请求)
    2. 地址 : ws://mydomain.tld , 端口 : 24444 (此时面板正常连接后端, 但提示 "浏览器无法连接到ws://mydomain.tld:24444")
    3. 地址 : localhost , 端口 : 24444 (同上)
    4. 地址 : mydomain.tld , 端口 : 9900 (此时无法连接, Nginx 记录到请求, 并返回 400 错误)

**Comment by huangsijun17** [comment]
你必须可以直连24444端口。
另外，该端口存在http服务，可以尝试连接。

**Comment by meepuru** [comment]
所以面板是不支持 wss ?
因为面板本身使用的是 https , 所以在浏览器与 daemon 使用 ws 进行连接时会报 Mixed Content 错误
但地址填写 wss:// 时面板似乎不能正确处理

**Comment by Suwings** [comment]
在面板的守护进程管理界面中使用  wss://mydomain.tdl:9900/ 去连接守护进程，并且确保守护进程已经被反向代理且支持 WSS，然后再试试。

**Comment by meepuru** [comment]
经过排查发现是因所用证书 CA 太新, 导致少数系统环境下不信任该证书, 目前已经解决, 抱歉耽误了你们的时间

**Comment by zxc136360** [comment]
> 经过排查发现是因所用证书 CA 太新, 导致少数系统环境下不信任该证书, 目前已经解决, 抱歉耽误了你们的时间

这个怎么解决的呢，我现在遇到了跟你一样的情况，https可以访问，但是使用wss协议就不能访问了

**Comment by meepuru** [comment]
> > 经过排查发现是因所用证书 CA 太新, 导致少数系统环境下不信任该证书, 目前已经解决, 抱歉耽误了你们的时间
> 
> 这个怎么解决的呢，我现在遇到了跟你一样的情况，https可以访问，但是使用wss协议就不能访问了

只需要在环境变量中配置 nodejs 的额外 CA 信任即可, 具体字段为 
`NODE_EXTRA_CA_CERTS=path/to/your/ca.crt`

我是使用 pm2 来管理 mcsm 进程的, 你也可以像我这样编写 pm2 的配置文件
`mcsm-pm2.config.js`:
```js
module.exports = {
  apps : [{
    name   : "mcsm-web",
    script : "path/to/your/mcsm_dir/app.js",
    env    : {
                "NODE_EXTRA_CA_CERTS" : "path/to/your/ca.crt"
             },
    cwd    : "path/to/your/mcsm_dir"
  }]
}
```

希望这可以帮助到你

**Comment by zxc136360** [comment]
> > > 经过排查发现是因所用证书 CA 太新, 导致少数系统环境下不信任该证书, 目前已经解决, 抱歉耽误了你们的时间
> > 
> > 
> > 这个怎么解决的呢，我现在遇到了跟你一样的情况，https可以访问，但是使用wss协议就不能访问了
> 
> 只需要在环境变量中配置 nodejs 的额外 CA 信任即可, 具体字段为 `NODE_EXTRA_CA_CERTS=path/to/your/ca.crt`
> 
> 我是使用 pm2 来管理 mcsm 进程的, 你也可以像我这样编写 pm2 的配置文件 `mcsm-pm2.config.js`:
> 
> ```js
> module.exports = {
>   apps : [{
>     name   : "mcsm-web",
>     script : "path/to/your/mcsm_dir/app.js",
>     env    : {
>                 "NODE_EXTRA_CA_CERTS" : "path/to/your/ca.crt"
>              },
>     cwd    : "path/to/your/mcsm_dir"
>   }]
> }
> ```
> 
> 希望这可以帮助到你

非常感谢你的回复，我发现是我这边的网络问题，我这边的服务方无法通过公网ip访问自己的服务， 已经靠[这里的逻辑](https://github.com/MCSManager/UI/blob/2c5d5cec4ebf41f0b3aad873d986573c9d35741c/src/app/service/protocol.js#L131C1-L132C90)解决了这个问题。
