### ISSUE TITLE
[Feature]实例的实时玩家数量在哪显示?

### ISSUE THREAD

**Issue by Illusionika** [MCSManager/MCSManager#561]
刚从8.7.0换到9.2.0

实时玩家数量显示怎么找不到了. 就是那个--/--人数显示,8.6.x在外面就看得到.8.7.0要点进实例才看得到,现在找不到这个东西在哪了

每次都要进去敲list看人数真的很麻烦

**Comment by Suwings** [comment]
你要选择具体的实例类型，比如 Java 版通用类型，然后启动在左上角会显示玩家数量。

**Comment by Illusionika** [comment]
emm....刚刚试了下,应该是实例的"状态查询"有点小问题,我之前看IP那栏注明了"不填写则自动为 localhost 地址"就没填IP,就填了端口,就没人数显示功能. 刚刚把IP填了localhost就显示出来了..

状态查询的"不填写则自动为 localhost 地址"这个功能好像没有生效...

还有Linux一键脚本的 github.com.cnpmjs.org 镜像站好像嗝屁了,我本地江苏电信和服务器的上海腾讯云都解析不这域名了了.我手动改了才装上去
