### ISSUE TITLE
DockerFile for java 11

### ISSUE THREAD

**Issue by huangsijun17** [MCSManager/MCSManager#562]
```
FROM openjdk:11.0.13
RUN mkdir -p /workspace
ENV TZ=Asia/Shanghai
WORKDIR /workspace
```

另外，推荐的Java启动参数
` -Dfile.encoding=UTF-8 `#强制UTF-8编码，解决中文显示问题。
` -Duser.language=cn `#指定中文输出，解决默认英文问题。

**Comment by Suwings** [comment]
话说，这个为什么你自己关掉了？哪里有问题？

**Comment by Suwings** [comment]
-Dfile.encoding=UTF-8 这个参数我觉得还是有必要加到命令生成的那个地方去，这里我加个标记，下次加进去。

**Comment by huangsijun17** [comment]
`-Dfile.encoding=UTF-8 -Duser.language=cn -Duser.country=ZH`
建议是这三个启动参数都加上。

**Comment by Suwings** [comment]
最新开发中的版本已经提交，将于下个版本一并发布。
