### ISSUE TITLE
[BUG]模拟终端不输出显示下划线"_"

### ISSUE THREAD

**Issue by Illusionika** [MCSManager/MCSManager#564]
就是下划线"_"这个符号在模拟终端中不输出显示,在终端日志里面是有记录的,如图

我这边centos7.9和debian10 字体都装全的,都一样这问题

![1](https://user-images.githubusercontent.com/46653839/153594582-0f979f71-3efa-4349-b223-eeb198fd2e63.png)
![2](https://user-images.githubusercontent.com/46653839/153594638-a8743265-d261-4424-9a7b-6e1caffe6cb2.png)

**Comment by Suwings** [comment]
谢谢反馈BUG，正在开发的新版本 9.3 已经修改了终端的字体，到时候你可以尝试升级到 9.3 来修复此问题。

**Comment by Illusionika** [comment]
> 9.3好过一阵子,更到9.4.2下划线又双叒叕不显示了,看起来是firefox特有的问题,chrome正常,我可的主浏览器是firefox,救救我(

捞一下(

**Comment by Suwings** [comment]
你的浏览器是 Firefox，你的操作系统是什么？

**Comment by Illusionika** [comment]
Windows 10 21H2 x64 ,最新版firefox 64位,试过在两台电脑上都一样不显示. 隐私窗口里也一样,可以排除是扩展带来的问题

**Comment by Suwings** [comment]
好的，这个 9.3 版本曾经在终端上加入了自定义字体，所以才不会出现你这种情况。但是与此同时，也有人反馈在 Firefox 上因为字体加载失败从而导致的文字变成超宽字体，影响阅读，从而上次更新已恢复到原代码，那么此问题再次出现也是必然的。

解决方案依然还是需要更改终端字体，可以采用系统字体或者自定义字体，但是难免又会出现超宽文字的BUG，所以这里暂时不太好修复。

**Comment by Illusionika** [comment]
9.3的时候确实会变成超宽字体,但是仅限于每次刚登陆面板后第一次打开终端.然后返回主界面,再次打开实例的终端后字体是正常的,恢复了正常字间距.所以还能忍.

下划线主要是非常多的正版用户名都是带_的,如果终端上不显示,需要复制的时候就造成很多麻烦.(有个需要手动输入用户名的东西,懒得打字就直接复制终端上)

**Comment by huangsijun17** [comment]
不显示，但可以直接复制出下划线。
