### ISSUE TITLE
9.2.1基岩版服务器创建问题

### ISSUE THREAD

**Issue by LucasJX** [MCSManager/MCSManager#567]
第一次使用这个面板，服务器文件已经上传目录解压好了。点击启动出错，不知是什么情况。
![image](https://user-images.githubusercontent.com/50724432/153717149-b2289aa9-b987-4936-9661-263a04f3aba0.png)
![image](https://user-images.githubusercontent.com/50724432/153717167-35896490-1f71-4abd-8f75-a4f8a6297b67.png)

**Comment by black7024** [comment]
我也在寻找尝试解决这个问题的办法，但是我是在安卓手机上使用termux运行

**Comment by szyy666** [comment]
同问

**Comment by zeruns** [comment]
同问
![L06BT1MEW748SG2PG.png](https://img.zeruns.tech/2022/02/25/L06BT1MEW748SG2PG.png)
![0AJCQMO7HZB_D4N9B3.png](https://img.zeruns.tech/2022/02/25/0AJCQMO7HZB_D4N9B3.png)
![2022-02-25_19-17-36.png](https://img.zeruns.tech/2022/02/25/2022-02-25_19-17-36.png)
![2022-02-25_19-18-09.png](https://img.zeruns.tech/2022/02/25/2022-02-25_19-18-09.png)

**Comment by zeruns** [comment]
> 可能你没给程序可执行文件，可以chmod +x 文件，然后./文件 运行试试

我试过了，直接在终端运行没问题，但用mcsm9的docker就不行了，闪退，看我上面的图片

**Comment by black7024** [comment]
> 可能你没给程序可执行文件，可以chmod +x 文件，然后./文件 运行试试

看这个报错，启动以后立马就关闭了
![Uploading Screenshot_20220225-215301.jpg…]()

**Comment by black7024** [comment]
![Screenshot_20220225-215301](https://user-images.githubusercontent.com/61902118/155727278-397ea83a-d7ce-46da-b6cb-7b38708ecfe2.jpg)
这个报错

**Comment by KagurazakaNyaa** [comment]
看起来是某些依赖没有被正确安装，你是通过容器运行的吗，检查一下PATH变量和镜像是否有正确安装和配置依赖项

**Comment by Suwings** [comment]
这个启动命令来自官方，但是这个命令似乎不是适用于所有环境，貌似有专门供基岩版开服的 Docker 镜像可以试试。

**Comment by nkxingxh** [comment]
可以试一下把启动命令改成
./bedrock_server

然后构建docker镜像时
在apt更新之后加一句
RUN apt -y install wget
