### ISSUE TITLE
请给出8.x版本的api啊！目前9.x不稳定不敢用。但是8.x的api文档已被删除

### ISSUE THREAD

**Issue by Shapaper** [MCSManager/MCSManager#568]
请给出8.x版本的api啊！目前9.x不稳定不敢用。但是8.x的api文档已被删除

**Comment by Suwings** [comment]
MCSM 8 的所有代码与资料在这个仓库，欢迎访问。

https://github.com/MCSManager/Backup-v8.7/wiki/API-Documentation

晚些会将此信息写入到 Readme 文件中。
