### ISSUE TITLE
[Feature]需要个账号历史登录记录的功能

### ISSUE THREAD

**Issue by Illusionika** [MCSManager/MCSManager#571]
刚刚面板可能由于网络原因突然登不上了,以防万一翻了下web那边日志

发现有大量118.126.124.* 来自广州腾讯云的连接记录.从面板安装完毕开始就一直有记录,请问这是你们官方的么?不是的话我要封掉了

然后我想看看是不是我账号被泄露了.结果个人资料那边只有这次的登录记录(只有一个最新的)我要看之前的也看到不到,请推出一个查看历史登录记录并且旁边有登录IP的功能.方便排查(不只是能看自己的,还要看别人的账号记录,当然管理员才能看别人,包括看别的管理员)

关于118.126.124.*这个IP段的logs如下举例

118.126.124.198 GET - http://X.X.X.X:23333/api/service/remote_service_instances?remote_uuid=X&page=1&page_size=20&instance_name=&token=X

118.126.124.7 GET - http://X.X.X.X:23333/api/protected_instance/stream_channel?remote_uuid=XXXXX&uuid=XXX&token=XXXX

118.126.124.141 GET - http://X.X.X.X:23333/api/auth/search?userName=&page=1&page_size=50&token=XX

118.126.124.7 GET - http://XXXX:23333/api/auth/?token=

我也看不懂这有没有登录什么账号,不像8.X版本logs直接告诉你登录行为.如果可以 能不能顺便告诉我下这日志代表什么行为

**Comment by Illusionika** [comment]
看了下api说明文档,麻了...这上来就是获取面板配置 获取实例配置 搜索用户账号...

而且看不到任何从网页登录记录(就是加载网页的那些资源的记录比如图片 css js),直接就一条/api/auth/?token=

麻了...面板刚装上去半小时不到就有这个IP段的记录了.而且第一条记录是api/protected_instance/stream_channel前面都没auth记录的

**Comment by Suwings** [comment]
官方没有任何主动请求的在线服务，只有静态数据的更新版本和信息服务，你这个情况应该是有人恶意扫描或者你将地址公开发到了某些群里。

登录记录功能暂且没有，但是会产生一条 HTTP 请求，你可以根据 log 中的请求，封禁所有可疑 IP。

**Comment by Mr-Ao-Dragon** [comment]
> 官方没有任何主动请求的在线服务，只有静态数据的更新版本和信息服务，你这个情况应该是有人恶意扫描或者你将地址公开发到了某些群里。
> 
> 登录记录功能暂且没有，但是会产生一条 HTTP 请求，你可以根据 log 中的请求，封禁所有可疑 IP。
> 
> 另外请确保密码复杂度高，请相信此面板，在密码复杂的情况下，可以有效阻挡攻击。

有希望增加认证插件吗
