### ISSUE TITLE
9.2版本服务器文件管理问题

### ISSUE THREAD

**Issue by Guodo** [MCSManager/MCSManager#576]
**操作系统版本**Windows10和ubuntu

**面板版本**9.2

**出现概率**100%

**BUG 详情描述**Windows版和ubuntu版都无法下载服务器内的文件

**复现步骤**

**Comment by Suwings** [comment]
是不是点下载的时候直接把文本显示出来了？请描述具体一点，无法下载总有个错误提示还是说点下载按钮没有任何反应。

**Comment by Guodo** [comment]
点了下载，下载管理器任务创建了但是下载不下来

**Comment by Suwings** [comment]
好的，此问题你与我QQ沟通，我已得知其具体表现，但是还不清楚原因。

Android 版的 Chrome 浏览器是支持的，但是 Android 的 QQ浏览器，小米浏览器等不支持下载文件功能，因为手机查看错误信息有点难度，所以此问题暂时不好排查。

**Comment by huangsijun17** [comment]
> 好的，此问题你与我QQ沟通，我已得知其具体表现，但是还不清楚原因。
> 
> Android 版的 Chrome 浏览器是支持的，但是 Android 的 QQ浏览器，小米浏览器等不支持下载文件功能，因为手机查看错误信息有点难度，所以此问题暂时不好排查。

MIUI内置“浏览器” V15.9.18 测试，下载 .jar 文件正常；text 格式文件下载异常，直接在浏览器内显示文件内容。

**Comment by Suwings** [comment]
> > 好的，此问题你与我QQ沟通，我已得知其具体表现，但是还不清楚原因。
> > Android 版的 Chrome 浏览器是支持的，但是 Android 的 QQ浏览器，小米浏览器等不支持下载文件功能，因为手机查看错误信息有点难度，所以此问题暂时不好排查。
> 
> MIUI内置“浏览器” V15.9.18 测试，下载 .jar 文件正常；text 格式文件下载异常，直接在浏览器内显示文件内容。

好的，谢谢测试，9.4 发行版将会修复这个问题。
