### ISSUE TITLE
[Feature]关于在MCSM9编辑server.properties与MCSM8相比不太方便

### ISSUE THREAD

**Issue by Airhelym** [MCSManager/MCSManager#578]
**面板版本**

9.2
**想法/建议**
我先前使用MCSM8时，看到有一个功能可以直接管理server.properties文件，修改数据之类的可以直接在面板端，还有注释之类的，很快捷方便。但MCSM9中，虽然仍可以在面板修改，但却是直接以文本方式呈现（对比MCSM8修改此文件便会发现）。我希望先前那个修改形式【附上图，前者为MCSM9，后者为MCSM8】
<img width="421" alt="1" src="https://user-images.githubusercontent.com/74526568/156905170-3cc35572-3413-4188-8b37-d006087c3650.png">
<img width="758" alt="2" src="https://user-images.githubusercontent.com/74526568/156905173-a911f638-b9a7-4658-9921-a7e531f49386.png">
能够回来（若还能放到显眼的地方就更好了）

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
大约95人

**Comment by Suwings** [comment]
这个界面是有的，实例类型选择 Java 版通用类型（默认应该是这个），然后控制台界面的左边有一个 `特定配置`按钮，里面就有更人性化的配置文件界面。

**Comment by Airhelym** [comment]
> 这个界面是有的，实例类型选择 Java 版通用类型（默认应该是这个），然后控制台界面的左边有一个 `特定配置`按钮，里面就有更人性化的配置文件界面。

找到了，谢谢

**Comment by wifi-left** [comment]
这个还是有 bug

> 这个界面是有的，实例类型选择 Java 版通用类型（默认应该是这个），然后控制台界面的左边有一个 `特定配置`按钮，里面就有更人性化的配置文件界面。

这个界面还是有 bug
他保存时不会转 u 码，导致配置文件中文乱码（如果原本是u码会转换为中文，再保存不会自动转换）

**Comment by huangsijun17** [comment]
> 这个还是有 bug
> 
> > 这个界面是有的，实例类型选择 Java 版通用类型（默认应该是这个），然后控制台界面的左边有一个 `特定配置`按钮，里面就有更人性化的配置文件界面。
> 
> 这个界面还是有 bug 他保存时不会转 u 码，导致配置文件中文乱码（如果原本是u码会转换为中文，再保存不会自动转换）

只解码，不编码还行……

**Comment by wifi-left** [comment]
> > 这个还是有 bug
> > > 这个界面是有的，实例类型选择 Java 版通用类型（默认应该是这个），然后控制台界面的左边有一个 `特定配置`按钮，里面就有更人性化的配置文件界面。
> > 
> > 
> > 这个界面还是有 bug 他保存时不会转 u 码，导致配置文件中文乱码（如果原本是u码会转换为中文，再保存不会自动转换）
> 
> 只解码，不编码还行……

反正是个bug了。

**Comment by Suwings** [comment]
> 这个还是有 bug
> 
> > 这个界面是有的，实例类型选择 Java 版通用类型（默认应该是这个），然后控制台界面的左边有一个 `特定配置`按钮，里面就有更人性化的配置文件界面。
> 
> 这个界面还是有 bug 他保存时不会转 u 码，导致配置文件中文乱码（如果原本是u码会转换为中文，再保存不会自动转换）

配置文件中有U码的地方会转换成中文，但是中文不会转换成U码，我不记得我有写过任何 U 码转换的代码，可能是某个依赖库意外的解析了，你保存的时候输入 U 码进行保存不知道是否可以？

**Comment by wifi-left** [comment]
> > 这个还是有 bug
> > > 这个界面是有的，实例类型选择 Java 版通用类型（默认应该是这个），然后控制台界面的左边有一个 `特定配置`按钮，里面就有更人性化的配置文件界面。
> > 
> > 
> > 这个界面还是有 bug 他保存时不会转 u 码，导致配置文件中文乱码（如果原本是u码会转换为中文，再保存不会自动转换）
> 
> 配置文件中有U码的地方会转换成中文，但是中文不会转换成U码，我不记得我有写过任何 U 码转换的代码，可能是某个依赖库意外的解析了，你保存的时候输入 U 码进行保存不知道是否可以？
似乎是可以。希望还是能保存的时候转换成 u 码。
因为读取时转换好像是 js 的文体。

**Comment by LingMuQingYu** [comment]
> > > 这个还是有 bug
> > > > 这个界面是有的，实例类型选择 Java 版通用类型（默认应该是这个），然后控制台界面的左边有一个 `特定配置`按钮，里面就有更人性化的配置文件界面。
> > > 
> > > 
> > > 这个界面还是有 bug 他保存时不会转 u 码，导致配置文件中文乱码（如果原本是u码会转换为中文，再保存不会自动转换）
> > 
> > 
> > 配置文件中有U码的地方会转换成中文，但是中文不会转换成U码，我不记得我有写过任何 U 码转换的代码，可能是某个依赖库意外的解析了，你保存的时候输入 U 码进行保存不知道是否可以？
> > 似乎是可以。希望还是能保存的时候转换成 u 码。
> > 因为读取时转换好像是 js 的文体。

该问题已经处理了，待验证可靠性

**Comment by Suwings** [comment]
> 这个还是有 bug
> 
> > 这个界面是有的，实例类型选择 Java 版通用类型（默认应该是这个），然后控制台界面的左边有一个 `特定配置`按钮，里面就有更人性化的配置文件界面。
> 
> 这个界面还是有 bug 他保存时不会转 u 码，导致配置文件中文乱码（如果原本是u码会转换为中文，再保存不会自动转换）

已修复，最新版应该已经包含。
