### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 1131122860** [MCSManager/MCSManager#579]
**操作系统版本**
CentOS 7.9.2009 x86_64(Py3.7.9)

**面板版本**
9.3.2

**出现概率**
100%

**BUG 详情描述**
使用一键安装命令，安装完成之后面板和守护进程都正常运行了，但是添加应用实例之后不能启动，

```
[MCSMANAGER] [ERROR] 检测到实例进程/容器启动失败（PID 为空），其可能的原因是：
1. 实例启动命令编写错误，请前往实例设置界面检查启动命令与参数。
2. 系统主机环境不正确或缺少环境，如 Java 环境等。
原生启动命令：
java -jar 1.16.4.jar
启动命令解析体:
程序：java
参数：["-jar","1.16.4.jar"]
请将此信息报告给管理员，技术人员或自行排查故障。
[MCSMANAGER] [错误] 实例启动失败，请检查启动命令，主机环境和配置文件等
```

**复现步骤**

![image](https://user-images.githubusercontent.com/82645160/157083832-f57a25c7-5e95-4693-9c8e-800aac65c73d.png)
![image](https://user-images.githubusercontent.com/82645160/157083882-a7e7d2a2-ea5c-44c6-bfc1-9c9147b957d9.png)
![image](https://user-images.githubusercontent.com/82645160/157083907-f5f56aa5-d891-4ce9-bc42-bc5752bc2b83.png)
![image](https://user-images.githubusercontent.com/82645160/157083959-2949aa13-ce84-43eb-95ac-00126175b629.png)
![image](https://user-images.githubusercontent.com/82645160/157084043-515ff434-ba48-4f27-a85b-67391e2773e3.png)

**Comment by Suwings** [comment]
请进行报错上所显示的修复方法进行修复：

1. 实例启动命令编写错误，请前往实例设置界面检查启动命令与参数。
2. 系统主机环境不正确或缺少环境，如 Java 环境等。

如果依然无效，请将命令中的 java 修改为绝对路径，如 `/opt/java -jar 1.16.4.jar`

**Comment by 1131122860** [comment]
**您好，首先非常感谢您的回复，无法启动的问题现在已经解决  ，运行一切正常，但是我通过HMCL启动器，无法进入服务器**
![image](https://user-images.githubusercontent.com/82645160/157181539-4eb8eda5-9c97-41ae-af54-54364f39d185.png)
![image](https://user-images.githubusercontent.com/82645160/157181620-3fac649e-e540-4b11-993e-9fd1da4d83e6.png)
**我可以确定我的宝塔和腾讯云防火墙均已放行25565端口，并且可以查询到25565端口的进程**
![image](https://user-images.githubusercontent.com/82645160/157181730-4bdce54b-93e1-4c29-879c-fb6951365655.png)
![image](https://user-images.githubusercontent.com/82645160/157181793-bf4775c6-1daf-4827-8739-f7b7f369a1d5.png)
![image](https://user-images.githubusercontent.com/82645160/157181847-4de9fc07-89e0-416c-b910-b68b1a280129.png)

**Comment by Suwings** [comment]
此问题已经不属于此项目管理范围之内，面板只能控制你的服务器启动与关闭等，无法控制你的主机网络情况。
