### ISSUE TITLE
[BUG]压缩文件问题

### ISSUE THREAD

**Issue by yhzx233** [MCSManager/MCSManager#580]
压缩文件的过程中如果目标文件发生变化压缩会失败
压缩失败后如果试图删除压缩到一半的那个文件会报错
![image](https://user-images.githubusercontent.com/16619108/158324590-fa737975-e83e-405c-827e-233b9a426fb8.png)
并且之后无法通过面板进入对应文件夹
![image](https://user-images.githubusercontent.com/16619108/158324876-c5043f64-3683-4863-81d1-14282f4860ba.png)

**Comment by yhzx233** [comment]
最新版解决了，，，

**Comment by Suwings** [comment]
我觉得可能没有解决，新版只对同时最大压缩任务做了限制，压缩方式的代码应该是没有改变的，不过还是谢谢你。
