### ISSUE TITLE
[BUG] 需要停机才能修改到期时间

### ISSUE THREAD

**Issue by yzy613** [MCSManager/MCSManager#581]
**操作系统版本**
Ubuntu 20.04

**面板版本**
8（你修好了我就用9，嘿嘿）

**出现概率**
101%

**BUG 详情描述**
需要停机才能修改到期时间

**复现步骤**
不停机修改到期时间

**Comment by Suwings** [comment]
此问题确实存在，下个小版本修复。

**Comment by Suwings** [comment]
最新版已经修复
