### ISSUE TITLE
[BUG]BC特定配置listeners/0/query_port更改后会导致出错

### ISSUE THREAD

**Issue by Cnzw** [MCSManager/MCSManager#582]
**操作系统版本**
centos 7

**面板版本**
9.3.2

**出现概率**
可以稳定复现

**BUG 详情描述与复现步骤**
1. 建立BungeeCord端, 在特定配置内编辑config.yml
2. 编辑listeners/0/query_port内端口
3. 保存
4. 在文件管理中查看, 原```query_port: 2001```变为```query_port: "2002"```
5. 启动Bungee, 报错, 大意为该配置项必须为整数

@LazyCreeper

**Comment by Suwings** [comment]
谢谢反馈BUG，可能此问题确实存在，以后将想办法修复此问题。

这个问题应该是配置项目的双向绑定底层有点点小问题，与 Lazy 关系可能不大，有时间我会仔细看看，不过最近事情多，修复时间可能要久一点。

**Comment by Suwings** [comment]
最新代码已经修复，将于下个版本一并发布。
