### ISSUE TITLE
[BUG]面板内切换界面后颜色渲染将会失效

### ISSUE THREAD

**Issue by inwinter04** [MCSManager/MCSManager#583]
**操作系统版本**
Windows Server 2019 Standard 10.0.17763

**面板版本**
面板版本 9.3.2
对应守护进程版本 1.4.2

**出现概率**
一定出现

**BUG 详情描述**
当从其他页面进入控制台页面时，控制台原本已颜色渲染的日志颜色全部消失

**Comment by Suwings** [comment]
感谢反馈。此问题在开发版本中已经修复，将于下个发行版（9.4.0）一并发布。

https://github.com/MCSManager/UI/commit/a72e9bf6d9d35502fdf19715762608d18f2fc6ff

**Comment by Suwings** [comment]
已修
