### ISSUE TITLE
 错误报告:[ERROR] TypeError: Cannot read property 'login' of undefined

### ISSUE THREAD

**Issue by zeroz-cpu** [MCSManager/MCSManager#587]
● mcsm.service - MCSManager
     Loaded: loaded (/lib/systemd/system/mcsm.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-03-21 19:33:00 PDT; 5s ago
   Main PID: 17743 (node)
      Tasks: 11 (limit: 7000)
     Memory: 28.7M
     CGroup: /system.slice/mcsm.service
             └─17743 /usr/bin/node /opt/MCSManager/app.js

Mar 21 19:33:02 ubuntu node[17743]:     at Object.module.exports.get (/opt/MCSManager/core/counter.js:68:18)
Mar 21 19:33:02 ubuntu node[17743]:     at Timeout._onTimeout (/opt/MCSManager/route/websocket/center.js:72:27)
Mar 21 19:33:02 ubuntu node[17743]:     at listOnTimeout (internal/timers.js:549:17)
Mar 21 19:33:02 ubuntu node[17743]:     at processTimers (internal/timers.js:492:7)
Mar 21 19:33:04 ubuntu node[17743]: [03/21 19:33:04] [ERROR] 错误报告:
Mar 21 19:33:04 ubuntu node[17743]: [03/21 19:33:04] [ERROR] TypeError: Cannot read property 'login' of undefined
Mar 21 19:33:04 ubuntu node[17743]:     at Object.module.exports.get (/opt/MCSManager/core/counter.js:68:18)
Mar 21 19:33:04 ubuntu node[17743]:     at Timeout._onTimeout (/opt/MCSManager/route/websocket/center.js:72:27)
Mar 21 19:33:04 ubuntu node[17743]:     at listOnTimeout (internal/timers.js:549:17)
Mar 21 19:33:04 ubuntu node[17743]:     at processTimers (internal/timers.js:492:7)
**一直提示这个报错，无论是关闭或者运行时都会出现**

**Comment by Suwings** [comment]
这个是 8.7 版本的错误信息，请删除 /core/info.json 即可修复。
