### ISSUE TITLE
[BUG]使用MCDR会导致终端输出有很大间隔

### ISSUE THREAD

**Issue by Glucy-2** [MCSManager/MCSManager#588]
**操作系统版本**
debian 11
**面板版本**

面板版本
9.3.2
对应守护进程版本
1.4.2

**出现概率**
100%

**BUG 详情描述**
不用MCDR：
![Screenshot_2022-03-21-21-35-02-48_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/53287753/159466038-0384e748-a475-4659-a7d9-03aa0b90eafb.jpg)
用MCDR：
![IMG_20220321_223257](https://user-images.githubusercontent.com/53287753/159467286-021d52ce-ab27-4c98-abb3-f848b5e95ad6.jpg)

使用MCDR会导致每次终端输出都会后面一行有一个`>`加上一大堆空格，导致终端输出间隔很大影响阅读

**Comment by Cubik65536** [comment]
> MCSManager 不会兼容 MCDR。这两个软件的功能应该是一样的，请不要使用 MCDR，并且使用 MCSManager 来全权管理您的服务器。

MCDR 不仅可以维持 MC 进程，也支持各种功能性插件，我想同时使用 MCSM 管理服务端和使用 MCDR 加载插件不是一个没有必要的事情

**Comment by KYLN24** [comment]
> MCSManager 不会兼容 MCDR。这两个软件的功能应该是一样的，请不要使用 MCDR，并且使用 MCSManager 来全权管理您的服务器。

Actaully MCDR is something
 completely different from MCSM. (maybe the only same thing is the word 'daemon' in its name🐶) MCDR provides some Python APIs to extend the server's function without injecting to the server core. There are many plugins developed upon MCDR such as Location Marker, joinmotd++ and Lazy teleport. MCDR is getting popular among many Minecraft servers so I think supporting MCDR is such a good choice for MCSM.

**Comment by LingMuQingYu** [comment]
复现不了

**Comment by HIM049** [comment]
> MCSManager 不会兼容 MCDR。这两个软件的功能应该是一样的，请不要使用 MCDR，并且使用 MCSManager 来全权管理您的服务器。

MCDR 可以算作一个插件API，两者功能是不重复的

**Comment by Suwings** [comment]
兼容mcdr的话，除了这个输出问题，还有其他需要兼容的操作吗？

**Comment by LingMuQingYu** [comment]
> 兼容mcdr的话，除了这个输出问题，还有其他需要兼容的操作吗？

不需要处理，最新版我自己试了下，并没有发现间隔太大的问题，也并不需要其他兼容处理，只是配置文件什么的因为不是放在根目录，用不了自带的配置文件编辑器罢了

**Comment by HIM049** [comment]
目前除了这个输出问题没有遇到其他问题（MCDR和一个普通的服务端并无太大差别）。但是输出问题在最新版MCDR+最新版MCSM中仍然是存在的。

**Comment by LingMuQingYu** [comment]
> 目前除了这个输出问题没有遇到其他问题（MCDR和一个普通的服务端并无太大差别）。但是输出问题在最新版MCDR+最新版MCSM中仍然是存在的。

或许你可以把端发给我调试(地图删掉)，群里搜“凌慕轻语”，可以发给我，有空我看下能不能重现

**Comment by HIM049** [comment]
> 兼容mcdr的话，除了这个输出问题，还有其他需要兼容的操作吗？

补充一些信息：经过 @LingMuQingYu 的帮助测试以后，发现该 bug 仅在守护进程运行于 Linux 系统时出现。

**Comment by Suwings** [comment]
就是说在 Linux 下，会出现换行有大量间隔的问题？我猜测应该是 `\r\n` 转换问题。

**Comment by yaosiqian** [comment]
这是MCDR的配置问题
请在MCDR的config.yml里找到
`advanced_console: true`
并修改为
`advanced_console: false`
[MCDReforged 2.0 文档](https://mcdreforged.readthedocs.io/zh_CN/latest/configure.html#advanced-console)：如果你需要重定向 MCDR 的标准输入/输出，请关闭高级控制台

**Comment by Glucy-2** [comment]
> 这是MCDR的配置问题 请在MCDR的config.yml里找到 `advanced_console: true` 并修改为 `advanced_console: false` [MCDReforged 2.0 文档](https://mcdreforged.readthedocs.io/zh_CN/latest/configure.html#advanced-console)：如果你需要重定向 MCDR 的标准输入/输出，请关闭高级控制台

谢谢，终于解决了

**Comment by HIM049** [comment]
> 这是MCDR的配置问题 请在MCDR的config.yml里找到 `advanced_console: true` 并修改为 `advanced_console: false` [MCDReforged 2.0 文档](https://mcdreforged.readthedocs.io/zh_CN/latest/configure.html#advanced-console)：如果你需要重定向 MCDR 的标准输入/输出，请关闭高级控制台

感谢解决

**Comment by Suwings** [comment]
https://docs.mcsmanager.com/#/tutorial/mcdr
