### ISSUE TITLE
[Feature] 添加外链资源包功能

### ISSUE THREAD

**Issue by wifi-left** [MCSManager/MCSManager#589]
**面板版本**
任意

**想法/建议**
允许上传资源包到服务器，并提供资源包的链接。
当服务器需要资源包时，这个功能更加便捷。
~~不过这个安全性好像有可能会出问题。~~

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
反正我觉得很有用

**Comment by huangsijun17** [comment]
上传资源包？
你自己另建一个HTTP服务器，提供下载不就行了？
MCSM本就不和玩家直接交互。

**Comment by wifi-left** [comment]
> 上传资源包？ 你自己另建一个HTTP服务器，提供下载不就行了？ MCSM本就不和玩家直接交互。

我觉得加上更方便些

**Comment by huangsijun17** [comment]
> > 上传资源包？ 你自己另建一个HTTP服务器，提供下载不就行了？ MCSM本就不和玩家直接交互。
> 
> 我觉得加上更方便些

MCSM是且只是一个管理软件，不是一整套Minecraft开服解决方案。MCSM**不应包含**皮肤站、资源站、下载站、Wiki站、论坛等一系列**玩家**应用。
