### ISSUE TITLE
[BUG]强制终止实例无法杀死MCDR子进程

### ISSUE THREAD

**Issue by Glucy-2** [MCSManager/MCSManager#591]
**操作系统版本**
debian 11
**面板版本**

面板版本
9.3.2
对应守护进程版本
1.4.2
（gitee源，使用git pull显示最新）

**出现概率**
100%

**BUG 详情描述**
强制终止实例无法杀死MCDR子进程，会使MCDR启动的进程变成一个单独的进程，比喻用其他工具杀死

**复现步骤**
1. 在面板启动一个使用MCDR的服务器
2. 在面板强制终止实例

**Comment by Suwings** [comment]
这个不算 BUG，MCSM 面板本来就没有兼容 MCDR。或者说，MCSM 本身就拥有 MCDR 的服务器管理能力，请不要使用 MCDR 并且用 MCSManager 全权管理您的服务器。
