### ISSUE TITLE
能否添加回v8的一键安装脚本？

### ISSUE THREAD

**Issue by Yangtzeus** [MCSManager/MCSManager#596]
我使用腾讯云ubuntu18.04服务器
执行最新的一键安装脚本
当我创建新实例，上传了mohist-1.16.5-963-server.jar后
面板崩溃
之后重启服务器再
systemctl start mcsm-{web,daemon}
终端那边是启动了，但

**面板不见了。**
**无法访问此网站**

而以前用v8版本上传mohist-1.16.5-963-server.jar
直接就创建成功
感觉目前的v9版本还不是很稳定，
希望能添加回原来的v8一键安装脚本

**Comment by Suwings** [comment]
面板崩溃的话，希望你能提供 log 以帮助我们排查问题，log 日志在 /opt/mcsmanager/daemon/log /opt/mcsmangaer/web/log 两个地方，上传最后一段时间的部分日志将有助于我们分析问题。

另外，能否提供你的服务器配置，有些可能是内存太低导致的崩溃。

V8 版本的安装脚本在此: https://mcsmanager.com/mcsm8.html

**Comment by Yangtzeus** [comment]
谢谢，我的服务器配置是2核2G（感觉是超售机），应该是腾讯云的ubuntu系统的初始内存占用太大了，一开机可用内存才200多M，我换成debian系统（开机可用内存1.5G）后就从没出现过崩溃问题。
