### ISSUE TITLE
虚假的 MCSManager 的未来发展规划

### ISSUE THREAD

**Issue by Suwings** [MCSManager/MCSManager#600]
**为响应 4月1日 活动号召，预计更新功能如下**

- 全面支持 Steam 系列部分游戏，包括但不限于：方舟，僵尸毁灭工程，战术小队，CSGO，泰拉瑞亚。
- 全面支持多语言，预计支持，中文，英文，日文，韩文，法，德，等。
- 内嵌界面 DIY 功能，管理员可自行排版。
- 支持 K8S 编排，动态扩容，热更新等。
- 提供在线应用商店，支持 Linux 下一键安装 MySQL，Apache 等主流软件。

<br />

**计划推出衍生产品：羽塔面板「暂定名」**

安全高效的服务器运维面板。

- 使用羽塔前：需要花半天时间配置安装web环境，管理Linux服务器各种不顺畅，想部署个网站，半天都没成功，很烦很累。
- 使用羽塔后：2分钟装好面板，一键管理服务器，一键部署LNMP/LAMP，无限建站，安全风险看得见，一切尽在掌握中。

<br />

**计划推出衍生产品：MCSM 能量控制面板**

如图所示（如果看不见可能需要科学上网）：

![QQ20220331-0](https://user-images.githubusercontent.com/18360009/161048449-7cb1059d-8403-452b-9e0c-d5a4e26cb03e.png)

<br />

**计划推出衍生产品：MCSM 在线服务平台**

安装 Daemon 程序之后，会有一个密钥，在官方的在线平台填写密钥之后即可直接在线控制 Daemon 程序，无需自己搭建面板与数据储存等。

并且支持在线状态统计，一年的数据绘制等。

<br />

**以上产品或相关计划，将有可能在 2040 年前全部实现，谢谢理解。**

**Comment by z2005319** [comment]
么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么

**Comment by Longtianmu** [comment]
整挺好 有没有在线挖矿平台

**Comment by Threegr3** [comment]
MCSM114514什么时候出

**Comment by z2005319** [comment]
羽哥不要~

**Comment by KernSSSS** [comment]
MCSM攻击平台不打爆usa.gov，收不了我一分钱~~

**Comment by z2005319** [comment]
么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么


么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么


么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么


么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么


么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么


么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么


么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么


么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么


么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么


么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么


么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么


么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么


么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么


么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么


么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么


么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么


么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么么

**Comment by Frkovo** [comment]
能不能推出在线DDoS平台
![IOVNROEV1K2HQF7S2J6DTOG](https://user-images.githubusercontent.com/66939153/161054910-eed5df39-c637-4630-832e-25e4ce9e4999.png)

**Comment by Hi-awaBlack** [comment]
<iframe src="//player.bilibili.com/player.html?aid=80433022&bvid=BV1GJ411x7h7&cid=137649199&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"> </iframe>

**Comment by 493Arceus** [comment]
断电、跑路、被D

**Comment by Hi-awaBlack** [comment]
![SN6O8OZ$WCP86%NJG~8@ IV](https://user-images.githubusercontent.com/63138378/161176425-814e6b05-bb2a-42ce-b9e2-cb143bdf028a.png)

**Comment by 3328429240** [comment]
免费 => 看广告启动
