### ISSUE TITLE
[Bug Report] 安装后无法正常进入面板

### ISSUE THREAD

**Issue by cloud-echo** [MCSManager/MCSManager#602]
![2](https://user-images.githubusercontent.com/46893121/161415568-14f9171b-ae3e-4f37-b415-1c3c7b2ba2dc.png)
![3](https://user-images.githubusercontent.com/46893121/161415573-16e8c322-9956-4136-bd41-fbcc30f3b74b.png)
![1](https://user-images.githubusercontent.com/46893121/161415574-13efb7a9-0dd1-4181-a979-20a7a04f7135.png)
新手一枚，求帮助
程序运行正常无报错，防火墙未开启，但无法从外网访问24444端口和23333端口

**Comment by Suwings** [comment]
你的棒版本是 9.4 和 1.5，这个版本应该还没有到线上才对，请问你是怎么安装的面板？

请在官网用一键脚本安装脚本重新安装

**Comment by cloud-echo** [comment]
这个版本的面板是通过文档里面的手动安装的
通过一键脚本安装后，没有报错，但还是无法通过外网访问。貌似因为所用的架构不是AMD64
在此issue的第三张图中似乎显示面板程序没有监听ipv4的23333端口与24444端口，不知道是否与此有关

**Comment by Suwings** [comment]
就在刚刚更新了一键安装脚本，已经支持 ARM 64，可以尝试再试试。

如果还不行，请手动安装 ARM64 的 NodeJS 环境，再启动面板。

**Comment by RERASER** [comment]
> 你的棒版本是 9.4 和 1.5，这个版本应该还没有到线上才对，请问你是怎么安装的面板？
> 
> 请在官网用一键脚本安装脚本重新安装

我使用的是Readme中手动Clone仓库的方式安装，版本也是9.4,1.5

**Comment by Suwings** [comment]
重新安装一下吧，在昨天下午5点的样子我更新了最新版本，用官网上的一键安装脚本。
