### ISSUE TITLE
实例文件增加历史记录

### ISSUE THREAD

**Issue by TalexDreamSoul** [MCSManager/MCSManager#603]
**希望开发什么新功能到 MCSManager ？**
实例文件增加历史记录

**新增此功能到意义与目的？**
- 允许用户编辑后类似于 git 一样有历史记录并且支持一键回档（考虑必须停服后才可回档等措施）

**简述功能实现思路**
- 可直接采用 git 或 可采用 MySql数据库映射记录到某一个具体文件夹

**Comment by Suwings** [comment]
想法很好，但是这个东西并不是那么容易实现的，如果只是增加一个文件操作的日志，这个倒是有点用，但是你所说的还需要支持回档与撤销更改文件等功能，这个是很难而且很麻烦实现的。
你说的给基于 git 的文件变动方案是可以做到文件改动检测和回档，但是对面偌大的文件数量以及某些程序对文件的频繁读写，我相信这会导致git产生巨大的冗余和对磁盘的巨大压力。

为了实现这个回档需求而付出的代价过大，我并不赞成此功能的开发。

文件改动日志的话可以考虑，看你打算显示在哪个地方，以何种方式记录之类的。

另外，面板没有数据库，尽可能以文本文件的方式储存更佳。

**Comment by TalexDreamSoul** [comment]
1. 当用户执行保存的时候加入git队列，当十五分钟内没交互时自动提交到git 这似乎并不会产生较大的冗余
2. 回档等功能也很简单，并且同样可以直接使用git的命令调度
3. 配置文件这个东西似乎量也不是特别大，加入之后能大幅度提升安全保障
4. 文件操作似乎比数据库操作更消耗io 我认为就算没有文件也应该使用文件数据库之类的(可以先放放 毕竟不是特别大的需求) [建议可以选择存储类型，更适合某些服务商和群组服管理者 提供数据库监控能力等]



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月3日(周日) 下午5:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MCSManager/MCSManager] 实例文件增加历史记录 (Issue #603)




 
想法很好，但是这个东西并不是那么容易实现的，如果只是增加一个文件操作的日志，这个倒是有点用，但是你所说的还需要支持回档与撤销更改文件等功能，这个是很难而且很麻烦实现的。
 你说的给基于 git 的文件变动方案是可以做到文件改动检测和回档，但是对面偌大的文件数量以及某些程序对文件的频繁读写，我相信这会导致git产生巨大的冗余和对磁盘的巨大压力。
 
为了实现这个回档需求而付出的代价过大，我并不赞成此功能的开发。
 
文件改动日志的话可以考虑，看你打算显示在哪个地方，以何种方式记录之类的。
 
另外，面板没有数据库，尽可能以文本文件的方式储存更佳。

**Comment by Suwings** [comment]
感谢回复，经过考虑，我依然不赞成开发基于 git 的文件回档，历史恢复等功能，付出的代价较大，如果你很感兴趣可以在自己的 fork 仓库上进行开发。
