### ISSUE TITLE
[Pull Request]实例分组

### ISSUE THREAD

**Issue by CNCoreSteb** [MCSManager/MCSManager#604]
**希望开发什么新功能到 MCSManager ？**
将不同实例进行分组，创建时若不选择分组则分为默认，可以一次性对该分组的实例进行操作（重启、终止、启动等）
**新增此功能到意义与目的？**
比如我有一堆bc、frp和服务端，创建顺序是无序的，如果我需要批量重启frp，就需要挨个选中frp的实例
有分组之后可以对有大量实例的用户提供一种批量操作的选择
**简述功能实现思路**
可以使用类似标签的形式对同一分组的实例进行标记？
添加实例到分组可以以标签的形式，也能实现单实例加入多分组（比方说服务器1分组下的实例有bc1/frp1/server1，而同时bc1/frp1/server1也存在于各自的bc分组、服务器分组等）
（就是一种思路，具体实现不太清楚）

**Comment by Suwings** [comment]
这个功能建议很不错，但是你应该理解错了这个 pull request issue 类型的意思。

这个的意思是你自己提出一个新功能并且想加入到 MCSManager 中，然后说明你打算怎么做，我们一起讨论，同意之后你来做，再提交PR合并进来。

你说实现思路具体不太清楚，那还怎么实现呢。我觉得你应该是要提交【Feature】功能建议型的 issue 吧，你是想要我实现这个分组对吗？

**Comment by CNCoreSteb** [comment]
啊！是这样的吗，抱歉了
re:你是想要我实现这个分组对吗？
是这样的，要是让我来提交估计mcsm就无了/哭
如果这个功能可以实现应该是挺不错的
（话说api那个issue能答复下吗）

**Comment by Suwings** [comment]
MCSManager 9 在设计的时候对于每个实例是有一个tag标签的，可以根据这个标签来进行查询，不过短期内暂时不做。
