### ISSUE TITLE
[Bug Report] 任务计划重启（或运行系统崩溃）后概率消失

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#605]
**操作系统版本**
Windows Server 2019 Standard 10.0.17763
**面板版本**
9.3.2

**出现概率**
100%

**BUG 详情描述**
正常关闭面板后开启，任务计划有概率消失
运行系统崩溃后，任务计划有概率消失
**复现步骤**
1.关闭面板
2.开启面板

**Comment by XiaoXiaoYang233** [comment]
我设置的是无限次数，并非有限次数，重启后仍然消失

**Comment by Suwings** [comment]
> 我设置的是无限次数，并非有限次数，重启后仍然消失

好的，谢谢提供线索，我明天在本地尝试复现一下你说的情况。

详细操作步骤就是创建一个计划任务，计划任务是重启服务器或者发送命令等，接下来重启面板端和守护进程端，就会出现计划任务丢失的情况，是吗？

**Comment by XiaoXiaoYang233** [comment]
是的

**Comment by XiaoXiaoYang233** [comment]
守护进程使用exit关闭，我上次在升级面板到最新版时丢了几个，而且事件任务没有重启也会莫名奇妙消失，账号只有我自己一个人用

**Comment by Illusionika** [comment]
> 经过测试，Windows 11,Ubuntu 系统。
> 
> 创建两个计划任务，分别是重启和发送命令，两种类型（定时和指定时间），重启面板端和守护进程端，没有发现计划任务丢失情况。
> 
> 你所说的情况我无法复现。
> 
> 你说的有概率消失是指多少概率，10次会出现几次？重启是使用的什么方式重启？

我也碰到了.原因是每个实列有相同的计划名称,比如A实列的一个计划叫stop,B计划也有一个计划叫stop.TaskConfig里只有最新的那一个文件,导致重启服务或升级后置读取到新的stop计划,另外一个实列的计划任务消失了(但是在重启服务之前2个实列的计划任务是同时存在的,估计是在内存里)

**Comment by Suwings** [comment]
谢谢提供线索，已确定存在此问题，下个版本将会修复。

**Comment by Suwings** [comment]
最新开发中的版本已经提交，将于下个版本一并发布。
