### ISSUE TITLE
[Bug Report] 文件管理无法下载文件

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#606]
**操作系统版本**
Windows Server 2019 Standard 10.0.17763
**面板版本**
9.3.2

**出现概率**
100%

**BUG 详情描述**
在文件管理下载文件时不会下载文件
使用safari浏览器点击下载无反应
![image](https://user-images.githubusercontent.com/99535761/161582282-09eb4a51-2297-473d-9628-d44ca6b36421.png)

**复现步骤**
1.打开文件管理
2.下载文件

**Comment by Suwings** [comment]
`在文件管理下载文件时不会下载文件` 这个问题在最新版本已经修复（今天下午4点），请前往官网重新下载安装即可体验。

`使用safari浏览器点击下载无反应` 这个问题暂未明确，目前手上没有MAC无法进行复现测试，等下周我再看看吧。

**Comment by XiaoXiaoYang233** [comment]
好的，感谢作者
