### ISSUE TITLE
一波功能建议（速看）

### ISSUE THREAD

**Issue by MengYang8481** [MCSManager/MCSManager#609]
**面板版本**
9.x

**想法/建议**
1.现在部分服务器都有web地图或者web白名单，在实例控制面板增加自定义按钮直接跳转
![无标题](https://user-images.githubusercontent.com/23436744/161725579-5021618a-f04a-40da-813a-4b752e59625c.png)

2.网站备案号设置
![无标题1](https://user-images.githubusercontent.com/23436744/161725722-4972ff11-5d9e-4f4d-9d2c-4447cf8e50ba.png)
![无标题w](https://user-images.githubusercontent.com/23436744/161725748-dcbcabdf-e0cc-4a91-8faf-95c3b2a6ee24.png)

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
第一个可能在Bedrock服务器非常实用，一般来说有就有人会去用（谁不希望更方便）
第二个的话直接看图（最好备案号设置边上放一下这句话，人人都需要合法使用面板）
![屏幕截图 2022-04-05 174104](https://user-images.githubusercontent.com/23436744/161726168-b23b1818-62c8-4ba1-813b-36f75e13eee1.png)

**Comment by Aqingfeng** [comment]
为什么非要使用80端口？

**Comment by KernSSSS** [comment]
> 为什么非要使用80端口？

不备案域名访问封全端口（鹅厂云），备案了你不用80 443备案什么，再说了备案也不难呀，合法上网没问题吧./doge

**Comment by Suwings** [comment]
感谢提供建议。

备案这个可以加入，已安排到进度列表。

自定义按钮的话半个月前就有考虑做，以后一定也会做，但是要先延迟一段时间。

**Comment by Suwings** [comment]
备案号，终端右上角进入全屏，已经实现。

其他功能暂时不考虑。
