### ISSUE TITLE
[Bug Report] 覆盖更新后会导致密码错误。无法登录

### ISSUE THREAD

**Issue by cdcp998** [MCSManager/MCSManager#610]
**操作系统版本**
Windows Server 2019 Datacenter 10.0.17763

**面板版本**
9.2 to 9.4.2

**出现概率**
100%

**BUG 详情描述**
9.2 to 9.4.2 覆盖更新后。root密码错误无法登录。

**复现步骤**
覆盖更新

**Comment by Suwings** [comment]
感谢反馈，解决方案请先删除 data/user 中的所有 json 文件来还原默认账号，后续我会尝试进行测试复现。
