### ISSUE TITLE
[Feature Request] 简化基岩原版服务端使用容器的部署过程

### ISSUE THREAD

**Issue by MoeField** [MCSManager/MCSManager#611]
**面板版本**
9.3

**想法/建议**
基岩原版服务端在docker中运行时需要给bedrock_server运行权限，在容器第一次启动时预先运行chmod命令使./bedrock_server 启动命令直接运行，简化基岩原版服务器部署过程

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
20

**Comment by Suwings** [comment]
感谢提供建议，你能提供 dockerfile 文件吗？

不过我感觉是不是你在启动之前这个文件的权限就设置不正确，理应只要你在容器运行之前的权限可以执行，映射到容器中后应该也有权限运行才对。
