### ISSUE TITLE
压缩包解压出来的文件名含有中文就乱码了

### ISSUE THREAD

**Issue by zeruns** [MCSManager/MCSManager#612]
**操作系统版本**
Debian11

**面板版本**
9.3.2

**出现概率**
100%

**BUG 详情描述**
压缩包解压出来的文件 凡是文件名含有中文就乱码了
![image](https://user-images.githubusercontent.com/17943073/162350460-5089a253-9cf4-4e6b-9670-3be3f77e497c.png)

**复现步骤**

**Comment by Suwings** [comment]
在实例配置界面，有个文件管理的编码设置，可以尝试更改那个设置来解决编码问题，不过也有可能无效，如果是无效请继续反馈。

**Comment by zeruns** [comment]
> 在实例配置界面，有个文件管理的编码设置，可以尝试更改那个设置来解决编码问题，不过也有可能无效，如果是无效请继续反馈。

默认的UTF-8应该是支持中文的，就解压出来的中文乱码，单独上传文件时是正常的没有乱码
