### ISSUE TITLE
[Feature Request] 希望可以加入单实例控制可使用端口数量

### ISSUE THREAD

**Issue by acm233** [MCSManager/MCSManager#613]
**面板版本**
9.4.2

**想法/建议**
希望可以加入单实例控制可使用端口数量，方便管理

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
约60%可能的服务商（我一个

**Comment by Suwings** [comment]
在 Linux 下使用 Docker 进行管理，在端口限制那里就有相应的设置，可以进行尝试。


Windows 下暂无好方案。
