### ISSUE TITLE
[Feature Request] 希望对command_instance这个API添加执行命令后的返回结果

### ISSUE THREAD

**Issue by ColorfulGhost** [MCSManager/MCSManager#614]
**想法/建议**
https://docs.mcsmanager.com/#/instance/command_instance
这个向实例发送命令我看过之前也有人提过需要返回结果，但是某些Mod的命令或者返回的内容比较多的场景RCON返回的数据可能缺失或者不全。
希望可以有通过控制台匹配返回的内容

**Comment by Suwings** [comment]
这个功能很多人都喜欢，这一点我也知道，但是在实现上难以完成。

首先命令的结果是根据程序输出流呈现的，你可以理解为一个小溪，源源不断的有各种命令的结果输出。

这些输出是乱序的，混乱的，除非以极高的工作量来匹配关键字，否则你根本无法知道那一部分输出的文本是命令的正确结果，也就是永远都会多余的内容包含在命令的结果。

从而就无法得到正确的命令返回结果，此API也就不可能实现命令结果返回。

**Comment by ColorfulGhost** [comment]
好吧我这边会想想用mod或插件去实现这个功能。

**Comment by Suwings** [comment]
已经有解决方案，只是做不到完美，请求 instance/outputlog 这个接口即可获取短时间的日志，从而获取命令返回结果。

**Comment by YakumoReddo** [comment]
我的做法是先区一次outputlog，然后执行命令后再取output。虽然混杂着别的东西但是勉强能用

**Comment by limbang** [comment]
如果是向 minecraft 服务器发送命令,可以对比发命令的时间来,然后过滤掉玩家消息和系统消息,来获取返回内容

<img width="437" alt="281DA0B7-AC53-436F-BEDA-7C5F4A69BF8C" src="https://user-images.githubusercontent.com/6381512/170817077-6077e0a4-4019-4b22-a3b9-7a88eb10d5a1.png">

``` kotlin
runCatching { service.sendCommandInstance(server.uuid, server.daemonUUid, apiKey, spliceVararg(command)) }.onSuccess {
                val time = LocalTime.now().withNano(0)
                delay(1000)
                var message = ""
                service.getInstanceLog(server.uuid, server.daemonUUid, apiKey).toRemoveColorCodeMinecraftLog()
                    .filter { it.channels == "minecraft/DedicatedServer" }
                    .filter { it.time >= time }
                    .filter { !"""[\[<].*\[>]""".toRegex().containsMatchIn(it.message) }
                    .forEach { message += "${it.message}\n" }
                sendMessage(message.substring(0, message.length - 1))
            }.onFailure { sendMessage(it.localizedMessage) }
```

**Comment by huangsijun17** [comment]
为何那么多人不喜欢用minecraft自带的rcon呢？rcon直接可以返回所执行命令的返回信息。
MCMS的命令执行是直接向终端中输入，而非对于Minecraft服务端的操作。无法得知终端输入后返回了哪几行。

**Comment by limbang** [comment]
> 

看起来应该挺好用的。 还真不知道有这个功能

**Comment by limbang** [comment]
> 为何那么多人不喜欢用minecraft自带的rcon呢？rcon直接可以返回所执行命令的返回信息。 MCMS的命令执行是直接向终端中输入，而非对于Minecraft服务端的操作。无法得知终端输入后返回了哪几行。

这个开了好像很吃性能的

**Comment by Doctor-Yin** [comment]
> > 为何那么多人不喜欢用minecraft自带的rcon呢？rcon直接可以返回所执行命令的返回信息。 MCMS的命令执行是直接向终端中输入，而非对于Minecraft服务端的操作。无法得知终端输入后返回了哪几行。
> 
> 这个开了好像很吃性能的

我在0.11.0pe的时候测试过,性能暴降,好早以前了
我也记不清是不是pe还是pc了

**Comment by huangsijun17** [comment]
> > > 为何那么多人不喜欢用minecraft自带的rcon呢？rcon直接可以返回所执行命令的返回信息。 MCMS的命令执行是直接向终端中输入，而非对于Minecraft服务端的操作。无法得知终端输入后返回了哪几行。
> > 
> > 
> > 这个开了好像很吃性能的
> 
> 我在0.11.0pe的时候测试过,性能暴降,好早以前了 我也记不清是不是pe还是pc了

PE现在都没有这个功能，JE有。但我没有查到任何说RCON可能影响性能的说明、测试等。

**Comment by huangsijun17** [comment]
另外，提示一下，RCON是明文传输，包括密码。为防止可能存在的中间人攻击，RCON的数据不应在公网传输，也最好不要在局域网内传输。

**Comment by Doctor-Yin** [comment]
> > > > 为何那么多人不喜欢用minecraft自带的rcon呢？rcon直接可以返回所执行命令的返回信息。 MCMS的命令执行是直接向终端中输入，而非对于Minecraft服务端的操作。无法得知终端输入后返回了哪几行。
> > > 
> > > 
> > > 这个开了好像很吃性能的
> > 
> > 
> > 我在0.11.0pe的时候测试过,性能暴降,好早以前了 我也记不清是不是pe还是pc了
> 
> PE现在都没有这个功能，JE有。但我没有查到任何说RCON可能影响性能的说明、测试等。

那可能是当时刚刚好遇到什么卡服吧
