### ISSUE TITLE
[Bug Report] 云服务器重启后MCSM面板无法连接

### ISSUE THREAD

**Issue by Elaina525** [MCSManager/MCSManager#616]
**操作系统版本**
Windows 10
**面板版本**
9.3 发行版

**出现概率**
100%

**BUG 详情描述**
小白根据教程一步步来的，服务器一开始运转都很好，后来服务器因为内存不够开启后会自动关闭（line 2: 23742 Killed，经过网上查询，初步判定为OOM(Out of Memory)），于是我就把租用的云服务器重启了一下，之后就无法连接至 localhost:23333 了，修改端口也连不上。

**复现步骤**
1. 浏览器打开 localhost:23333
2. 连接失败

**Comment by Suwings** [comment]
因为你并没有提供有价值的线索，无法推导问题所在，请尝试：

systemctl restart mcsm-{web,daemon} 
systemctl status mcsm-{web,daemon} 查看报错

如果依然无效，备份 /opt/mcsmanger/*/data 目录，重装面板。

**Comment by Elaina525** [comment]
![Picture1](https://user-images.githubusercontent.com/101787144/162575771-cad4e675-1a4b-42e3-82c1-c152a4582286.png)
 当我输入命令时显示这个请问该怎么解决？

**Comment by Elaina525** [comment]
噢，我在SSH面板上用命令关闭了防火墙后可以连接了。感谢帮助。

**Comment by Elaina525** [comment]
另外，我的服务器RAM占用率即使在服务器未开启时也有60%+，我租用的服务器是腾讯云的4核8G轻量级云服务器，请问有什么办法可以清理内存吗？

**Comment by vlssu** [comment]
> 另外，我的服务器RAM占用率即使在服务器未开启时也有60%+，我租用的服务器是腾讯云的4核8G轻量级云服务器，请问有什么办法可以清理内存吗？


你可以尝试回收内存
```
echo 3 > /proc/sys/vm/drop_caches
```
- 0：0是系统默认值，默认情况下表示不释放内存，由操作系统自动管理
- 1：释放页缓存
- 2：释放dentries和inodes
- 3：释放所有缓存
