### ISSUE TITLE
[Bug Report] 控制台输出包含不正确的空行

### ISSUE THREAD

**Issue by HIM049** [MCSManager/MCSManager#617]
**操作系统版本**
前端 CentOS 7.6
相关后端 Fedora 35

**面板版本**
面板 9.4.2
守护进程 1.5.2

**BUG 详情描述**
控制台输出包含不正确的空行。而直接在服务器命令行中启动是没有这种情况的。问题症状可以查看附带的图片
**防止github图片无法显示，此处附带第三方图床[ 链接 ](https://s1.328888.xyz/2022/04/09/X1R1y.png)**
![示例图](https://user-images.githubusercontent.com/67405384/162578255-bc20a94f-5bb9-415a-8b1f-59f28034064a.png)

**复现**
启动使用了[ MCDR ](https://github.com/Fallen-Breath/MCDReforged) 的服务端便会出现该问题

**Comment by huangsijun17** [comment]
详见 https://github.com/MCSManager/MCSManager/issues/588

**Comment by HIM049** [comment]
谢谢，有看到了
