### ISSUE TITLE
[Bug Report] 守护进程会占用大量的UDP端口

### ISSUE THREAD

**Issue by nkxingxh** [MCSManager/MCSManager#618]
**操作系统版本**
Rocky 8.5 (Green Obsidian) x86_64

**面板版本**
9.4.0

**守护进程版本**
1.5.0

**Node 版本**
v14.17.6

**出现概率**
每次启动守护进程后不会立刻出现，往往在运行1天后出现。

**BUG 详情描述**
使用宝塔面板自带的Node项目管理，创建了面板端和守护进程，都是使用的root账户，启动命令是 `node app.js`。
但在运行一段时间后，守护进程会占用大量的UDP端口。确定不是由守护进程运行的程序造成的。

**复现步骤**
使用宝面板创建并启动node项目。

**相关截图**
![image](https://user-images.githubusercontent.com/25559053/162600763-98fdf1c6-5e3e-4eee-9642-2a6880b2a16f.png)
![image](https://user-images.githubusercontent.com/25559053/162600861-f0d52926-dfc6-4f13-9bb0-778c9fa0d1f2.png)
![image](https://user-images.githubusercontent.com/25559053/162600776-ed00cbc2-5be7-4056-b387-df7e27a68c61.png)
![image](https://user-images.githubusercontent.com/25559053/162600783-69b37d84-3916-42fe-91cb-2d6cdd6702a3.png)

**Comment by Suwings** [comment]
好的感谢反馈，我会去尝试复现你这个情况，守护进程所有协议应该全部是tcp，至于这个情况我暂且不清楚具体原因。

可能是 socket.io 自己附带的。

如果你有什么其他线索，欢迎继续反馈。

**Comment by nkxingxh** [comment]
昨晚我重启了守护进程，到现在差不多24个小时了。情况再次复现，现在占用了十几个UDP端口，情况如下
![image](https://user-images.githubusercontent.com/25559053/162748670-336f3267-b159-4744-a75a-c3c54744bc4e.png)
![image](https://user-images.githubusercontent.com/25559053/162748708-f68ee3d5-c6fb-46ad-9e57-6a262ed415e9.png)

**Comment by Suwings** [comment]
感谢提供更多信息，但是我这里未能复现你所说的情况。

我也找了几个长期使用的人查看了情况，没有发现udp端口大量使用的情况，具体原因依然不明。

**Comment by Suwings** [comment]
你有使用 状态查询 这个功能吗？就是用于显示服务器人数和版本号的功能，有可能是这个功能在使用这些 UDP 通信。

**Comment by nkxingxh** [comment]
> 你有使用 状态查询 这个功能吗？就是用于显示服务器人数和版本号的功能，有可能是这个功能在使用这些 UDP 通信。

是的，我给每个MC服务器实例都设置了状态查询，其中包括几个JE的服务端和BE的服务端

**Comment by nkxingxh** [comment]
现在只设置了Java版的状态查询，但是UDP占用仍然存在。且相比起3天前 多占用了许多UDP端口
![image](https://user-images.githubusercontent.com/25559053/163407575-cc70333a-59fc-4c3c-8456-c799ae8ad270.png)
![image](https://user-images.githubusercontent.com/25559053/163407633-1f75dc06-dc9c-4590-ad17-25517e68bb52.png)
![image](https://user-images.githubusercontent.com/25559053/163407688-abf0306f-89d6-4325-9dec-ef6eae43f97e.png)
![image](https://user-images.githubusercontent.com/25559053/163407781-54afcd4e-cf3b-4f7f-9939-8823bc8b9796.png)

**Comment by Suwings** [comment]
要不你尝试一下关掉所有的状态查询，重启 Daemon，然后等待一天的样子再看看 UDP 占用情况？以便于我们查找问题所在，谢谢了。

**Comment by XiaoXiaoYang233** [comment]
我也遇到了

**Comment by Suwings** [comment]
> 我也遇到了

关掉所有人数查询的功能，再重启 Daemon 服务，看看还会不会复现？

**Comment by XiaoXiaoYang233** [comment]
> > 我也遇到了
> 
> 关掉所有人数查询的功能，再重启 Daemon 服务，看看还会不会复现？

关掉人数查询功能仍会占用，重启daemon后不再占用

**Comment by Suwings** [comment]
> > > 我也遇到了
> > 
> > 
> > 关掉所有人数查询的功能，再重启 Daemon 服务，看看还会不会复现？
> 
> 关掉人数查询功能仍会占用，重启daemon后不再占用

重启 daemon 之后，占用情况还会出现吗？

**Comment by XiaoXiaoYang233** [comment]
> > > > 我也遇到了
> > > 
> > > 
> > > 关掉所有人数查询的功能，再重启 Daemon 服务，看看还会不会复现？
> > 
> > 
> > 关掉人数查询功能仍会占用，重启daemon后不再占用
> 
> 重启 daemon 之后，占用情况还会出现吗？

目前没有占用的情况

**Comment by nkxingxh** [comment]
昨天我关闭了人数查询，UDP端口依然占用，不过今日占用的端口貌似没有增加。
![image](https://user-images.githubusercontent.com/25559053/163673163-de4f4ce8-08bb-4ff7-a45c-585df054ea02.png)
![image](https://user-images.githubusercontent.com/25559053/163673179-949c8451-4aca-4185-92af-732331bc9031.png)

**Comment by Suwings** [comment]
> 昨天我关闭了人数查询（没有重启守护进程），UDP端口依然占用，不过今日占用的端口貌似没有增加。
>

感觉可以断定是人数查询的问题，我会复查这方面的代码。请问大部分是基岩版吗？

**Comment by nkxingxh** [comment]
> > 昨天我关闭了人数查询（没有重启守护进程），UDP端口依然占用，不过今日占用的端口貌似没有增加。
> >
> 
> 感觉可以断定是人数查询的问题，我会复查这方面的代码。请问大部分是基岩版吗？

大部分是Java版(有6个)，只有一个是基岩版。

**Comment by XiaoXiaoYang233** [comment]
目前守护进程使用了一天，并没有使用状态查询，仍然占用大量端口

**Comment by nkxingxh** [comment]
相比昨天，今天多了2个UDP端口占用，原因可能是我的一个用户设置了基岩版服务器的状态查询（随后我又关闭了）

**Comment by Suwings** [comment]
> 

那我下午挂个 Daemon 试试吧，但是我问了很多用了很久的人，没有出现过 UDP 大量使用的情况，他们都没有用状态查询。

我感觉应该是这方面的问题，因为 Daemon 程序除此之外，没有其他主动 UDP 连接的业务 。

**Comment by yhzx233** [comment]
> 

有一说一，确实。我也遇到了大量UDP端口占用的问题，而且是一万多个（指所有的临时端口，49152到65535）
经过一些排查发现确实是因为状态查询，而我这么多的原因是因为我服务器因为某种原因更换了端口而状态查询里我并没有更改端口，在启动实例后的每几秒netstat里就会多占用一个UDP连接，直到所有临时端口都被占用。
复现方法就是在状态查询里设置一个连不上的服务器
例如：
localhost
19134
（正确的开服端口在19132）
然后启动实例

**Comment by Mr-Ao-Dragon** [comment]
> > 
> 
> 那我下午挂个 Daemon 试试吧，但是我问了很多用了很久的人，没有出现过 UDP 大量使用的情况，他们都没有用状态查询。
> 
> 我感觉应该是这方面的问题，因为 Daemon 程序除此之外，没有其他主动 UDP 连接的业务 。

估计是忘记设置丢弃了
