### ISSUE TITLE
[Feature Request] 希望日志功能能查看更多

### ISSUE THREAD

**Issue by n0tssss** [MCSManager/MCSManager#620]
**面板版本**
发行版本: 8.7.0 发行版本

**想法/建议**
希望日志查看能和原来一样支持大量查询，如卡顿再手动清理，又或者是能允许自定义设置最大行数

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
50%？

**Comment by Suwings** [comment]
8.7.0 已经不再更新。请升级到 9.4.0
