### ISSUE TITLE
[Bug Report] 状态查询过一段时间后会消失

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#621]
**操作系统版本**
Windows Server 2019 Standard 10.0.17763
**面板版本**
9.4.2
**出现概率**
100%
**BUG 详情描述**
状态查询过一段时间会莫名奇妙消失，不清楚是因为什么原因。

并且开始统计几个小时后还是跟原来一样只有一个时间点的人数
要过一段时间才会显示10小时的在线人数趋势
**复现步骤**
1.添加状态查询

**Comment by Suwings** [comment]
你是开启的什么类型的MC服务器？Java？基岩版？

你的状态查询的ip地址是使用的 localhost 还是公网地址？也就是说有一段时间突然查不到人数显示，然后过一段时间又自然正常。

**Comment by XiaoXiaoYang233** [comment]
基岩版，localhost和公网地址都尝试过，消失后再也无法恢复

**Comment by Suwings** [comment]
消失后再也无法恢复是什么意思？你的意思是状态查询里面写的 地址 和 端口 两个配置都没有了？

还是说，再也不会显示人数，版本号这些信息，包括底下的玩家人数图表也再也不会显示。

**Comment by OldGodShen** [comment]
基岩版什么时候能用状态查询功能了？不是只有java版能用吗？

**Comment by Suwings** [comment]
> 基岩版什么时候能用状态查询功能了？不是只有java版能用吗？

MCSM9 新增了基岩版的查询功能，根据服务端类型自动切换。

**Comment by OldGodShen** [comment]
> > 基岩版什么时候能用状态查询功能了？不是只有java版能用吗？
> 
> MCSM9 新增了基岩版的查询功能，根据服务端类型自动切换。

那为什么我这里怎么没有效果，查不到

**Comment by XiaoXiaoYang233** [comment]
> 消失后再也无法恢复是什么意思？你的意思是状态查询里面写的 地址 和 端口 两个配置都没有了？
> 
> 还是说，再也不会显示人数，版本号这些信息，包括底下的玩家人数图表也再也不会显示。

是的，也不会显示人数，版本号信息，但是底下的玩家人数图表仍然会显示

**Comment by Suwings** [comment]
> 

玩家人数图表依然在显示的话，这个图表里面的数据还有在刷新吗？

另外，你确定 “状态查询里面写的 地址 和 端口 两个配置” 都没有了？就是状态查询那个小窗口里面，有ip和端口，用来查询你的服务器的人数信息的，这个也没有了？

大概平均是过了多久出现一次这种情况？

谢谢你的耐心回复。

**Comment by XiaoXiaoYang233** [comment]
没有，是的，是的，无法确定

**Comment by zeruns** [comment]
把实例目录里的文件清空后状态查询里的配置也没了
