### ISSUE TITLE
[Feature Request] 希望给服务器实例界面新增排序功能

### ISSUE THREAD

**Issue by KumaKorin** [MCSManager/MCSManager#622]
**面板版本**
9.4.2

**想法/建议**
希望能够对服务器实例按照 昵称(A-Z)、创建时间、实例ID 等规则进行排序

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
40%

**Comment by huangsijun17** [comment]
排序、分组、自动排序（按照名称、到期日期等）。

**Comment by HIM049** [comment]
也希望可以有一个可以显示全部守护进程上实例的列表，且具备一定的排序功能。

**Comment by lovemercer** [comment]
很需要，每次重启面板，排序就乱了，要是能排序或者分组，就太好了
