### ISSUE TITLE
[Bug Report] XXXXXXX

### ISSUE THREAD

**Issue by xiqoqi** [MCSManager/MCSManager#623]
**操作系统版本**
Linux linux   #1 SMP Tue Nov 30 15:51:32 UTC 2021 3.10.0-1160.49.1.el7.x86_64
**面板版本**
9.4.2
**出现概率**
100%
**BUG 详情描述**
docker方式启动选择环境镜像的下拉栏重复点击会使镜像的个数叠加，并且是无限叠加的，不影响使用，只是会影响使用体验

https://user-images.githubusercontent.com/58991169/163679529-85901159-3a16-4ac7-81de-b7e317382887.mp4

**复现步骤**
重复点击环境镜像的下拉栏

**Comment by Suwings** [comment]
这个在几天前已经得知并且已经修复，会随着下个版本一并发布。

**Comment by xiqoqi** [comment]
> 这个在几天前已经得知并且已经修复，会随着下个版本一并发布。

好的，我是在已经关闭的issue里没有找到这个bug所以反馈了一下
