### ISSUE TITLE
[Bug Report] 远程守护进程的状态经常显示为离线

### ISSUE THREAD

**Issue by Trivitt** [MCSManager/MCSManager#624]
**操作系统版本**
#1 SMP Debian 5.10.106-1 (2022-03-17) 5.10.0-13-amd64
**面板版本**
9.4.2；1.5.2
**出现概率**
一天内出现两三次
**BUG 详情描述**
mcsm-web 位于海外节点，mcsm-daemon 位于国内节点，
守护进程管理里经常出现守护进程处于离线状态的问题（其实是在线的），需要手动连接才能恢复正常。
其中国内节点为动态 IP，但动态 IP 也不可能一天变个两三次。
**复现步骤**
怀疑是网络问题，两边延迟有 200ms 多，丢包也有可能。
可能 mcsm 没有自动重连功能？

**Comment by Suwings** [comment]
MCSM 有自动重连功能，而且会尝试很多次，有可能是延迟实在太高，导致每次都无法连上，不过这个概率较低。

动态ip，你是根据域名连接，也有可能存在 DNS 缓存问题，导致连接错误，如果遇到连接错误底层连接框架可能不会再发起重试，可以考虑试试没有动态 ip 的国内节点。

https://github.com/MCSManager/MCSManager/blob/master/src/app/entity/entity_interface.ts#L70
