### ISSUE TITLE
[Feature Request] 在 Docker 容器配置 添加环境变量设置

### ISSUE THREAD

**Issue by kexue-z** [MCSManager/MCSManager#625]
**面板版本**

9.4.0

**想法/建议**

- 在 Docker 容器配置 添加环境变量设置

**您认为这个想法/建议在每100人中会有多少人遇到/使用**

因为，要用，但是没有 不然就只能写 dockerfile 传入了

**Comment by huangsijun17** [comment]
为啥不直接写在启动参数里？面板是可以通过运算符执行多条命令的。

**Comment by kexue-z** [comment]
> 为啥不直接写在启动参数里？面板是可以通过运算符执行多条命令的。

好主意 但是我的参数有点多 就很长了

这样也能用吧！
