### ISSUE TITLE
[Feature Request] 目录大小限制

### ISSUE THREAD

**Issue by ThebestkillerTBK** [MCSManager/MCSManager#628]
**面板版本**

9.4.2

**想法/建议**

每一个实例可以设置其目录下文件的大小限制，定时扫描，如果超过其限制，实例将无法启动且只能下载或删除文件

**您认为这个想法/建议在每100人中会有多少人遇到/使用**

50

**Comment by Suwings** [comment]
这个实现的话还是有点困难，一层目录还好，两层，三层等等，一层套一层，文件总大小的统计将会非常耗时，很容易造成性能问题。
