### ISSUE TITLE
[Bug Report] 我面板安装出问题了想卸载重来，请问怎么卸载面板

### ISSUE THREAD

**Issue by LjyLab** [MCSManager/MCSManager#629]
**操作系统版本**

**面板版本**

**出现概率**

**BUG 详情描述**

**复现步骤**

**Comment by ThebestkillerTBK** [comment]
你这是什么系统，还有是出什么问题了

**Comment by LjyLab** [comment]
> 你这是什么系统，还有是出什么问题了

也没啥问题呀 就想重装一下面板 想问一下咋卸载

**Comment by Suwings** [comment]
删除 /opt/mcsmanager 就是卸载。

**Comment by LjyLab** [comment]
> 删除 /opt/mcsmanager 就是卸载。

我试了rm -rf   /opt/mcsmanager 但是再次重装就老多问题了

**Comment by Suwings** [comment]
先关闭面板再删除这个目录。
```
systemctl stop mcsm-{daemon,web}.service
systemctl disable mcsm-{daemon,web}.service
rm -rf /opt/mcsmanager
```

**Comment by LjyLab** [comment]
> 先关闭面板再删除这个目录。
> 
> ```
> systemctl stop mcsm-{daemon,web}.service
> systemctl disable mcsm-{daemon,web}.service
> rm -rf /opt/mcsmanager
> ```

好的！感谢大佬 在百忙之中给予回复

**Comment by voidgodl** [comment]
为什么我的面板，每次访问，都会自动进入， 127.0.0.1/#/install

**Comment by unitwk** [comment]
> 为什么我的面板，每次访问，都会自动进入， 127.0.0.1/#/install

因为没有用户存在，进入安装流程

**Comment by voidgodl** [comment]
> > 为什么我的面板，每次访问，都会自动进入， 127.0.0.1/#/install
> 
> 因为没有用户存在，进入安装流程

可是，我已经有一个，用户存在了，为何还会这样，
![image](https://github.com/MCSManager/MCSManager/assets/169233441/89156a68-2003-4a98-b288-9f1440598361)

**Comment by voidgodl** [comment]
> > > 为什么我的面板，每次访问，都会自动进入， 127.0.0.1/#/install
> > 
> > 
> > 因为没有用户存在，进入安装流程
> 
> 可是，我已经有一个，用户存在了，为何还会这样， ![image](https://private-user-images.githubusercontent.com/169233441/329121093-89156a68-2003-4a98-b288-9f1440598361.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjczMTMsIm5iZiI6MTcxNTIyNzAxMywicGF0aCI6Ii8xNjkyMzM0NDEvMzI5MTIxMDkzLTg5MTU2YTY4LTIwMDMtNGE5OC1iMjg4LTlmMTQ0MDU5ODM2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQwMzU2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZmE4ZTIwZWUyYjkxNTlkNjQ5YzAyOTkyN2ZlMTA2NzYwZDIxODA5ZjgwYTE1NGRkYTU2MmIzNTRmNmFiZGM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jpxdZer1mLaPqUJFycw5U-RX4TbkFCvIp-n8FATWfrA)

哦，我找到问题所在了，是因为我保存到，收藏夹的时候，就带了，这样的连接，所以每次进入的时候，就会这样。哈哈，

**Comment by voidgodl** [comment]
嗯，谢谢，问题已解决。
