### ISSUE TITLE
[Bug Report] 泰拉瑞亚服务器无法输入指令

### ISSUE THREAD

**Issue by well-itwasbad** [MCSManager/MCSManager#630]
**操作系统版本**

Windows 10

**面板版本**

9.4.2

**出现概率**

100

**BUG 详情描述**

启动泰拉瑞亚TShock插件服务器，输入指令，均无反应

**复现步骤**

启动泰拉瑞亚TShock服务器，输入指令

**Comment by Suwings** [comment]
需求目标中还没有包含兼容泰拉瑞亚，不算 BUG，以后可以考虑做。
