### ISSUE TITLE
[Bug Report] Docker下配置出现的错误问题，linux萌新请各位大佬看看

### ISSUE THREAD

**Issue by SeaGull1919** [MCSManager/MCSManager#631]
**操作系统版本**
docker 最新的ubantu镜像
**面板版本**
2022.5.3拉取的面板
错误信息：配置完linux后安装面板 linux提示如下
+----------------------------------------------------------------------
| MCSManager Installer
+----------------------------------------------------------------------
| Copyright © 2022 Suwings All rights reserved.
+----------------------------------------------------------------------
| Shell Install Script by Nuomiaa & CreeperKong
+----------------------------------------------------------------------

[-] Architecture: x64
[+] Check network connection(ping gitee.com)... bash: line 293: ping: command not found
Fail
=================================================
[x] Unable to connect to gitee.com repository!
=================================================
root@OpenWrt:/# wget -qO- https://gitee.com/Suwingser/MCSManager-installer/raw/master/install.sh | bash
Start to install MCSManager...

--2022-05-03 13:34:21--  https://npm.taobao.org/mirrors/node/v12.16.1/node-v12.16.1-linux-x64.tar.gz
Resolving npm.taobao.org (npm.taobao.org)... 114.55.80.225
Connecting to npm.taobao.org (npm.taobao.org)|114.55.80.225|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://cdn.npmmirror.com/binaries/node/v12.16.1/node-v12.16.1-linux-x64.tar.gz [following]
--2022-05-03 13:34:21--  https://cdn.npmmirror.com/binaries/node/v12.16.1/node-v12.16.1-linux-x64.tar.gz
Resolving cdn.npmmirror.com (cdn.npmmirror.com)... 183.232.147.118, 183.240.216.248, 183.240.216.243, ...
Connecting to cdn.npmmirror.com (cdn.npmmirror.com)|183.232.147.118|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23005690 (22M) [application/gzip]
Saving to: 'node-v12.16.1-linux-x64.tar.gz'

node-v12.16.1-linux-x64.tar.gz    100%[==========================================================>]  21.94M  19.1MB/s    in 1.1s    

2022-05-03 13:34:22 (19.1 MB/s) - 'node-v12.16.1-linux-x64.tar.gz' saved [23005690/23005690]

Unpacking...
> tar -zxf node-v12.16.1-linux-x64.tar.gz
complete.
Linking...
> ln -s /opt/node-v12.16.1-linux-x64//node-v12.16.1-linux-x64/bin/node /usr/bin/node
> ln -s /opt/node-v12.16.1-linux-x64//node-v12.16.1-linux-x64/bin/node /usr/bin/node
complete.
--------------- Node Version ---------------
 node: v12.16.1
 npm: 6.13.4
--------------- Node Version ---------------
Installing git...
bash: line 44: yum: command not found
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
bash: line 46: pacman: command not found
complete.
Download MCSManager...
Cloning into 'MCSManager'...
remote: Enumerating objects: 9131, done.
remote: Counting objects: 100% (436/436), done.
remote: Compressing objects: 100% (193/193), done.
remote: Total 9131 (delta 254), reused 382 (delta 241), pack-reused 8695
Receiving objects: 100% (9131/9131), 8.19 MiB | 1.19 MiB/s, done.
Resolving deltas: 100% (5691/5691), done.
complete.
Start to install dependent libraries...
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> ssh2@1.5.0 install /opt/MCSManager/node_modules/ssh2
> node install.js

gyp WARN EACCES current user does not have permission to access the dev dir "/root/.cache/node-gyp/12.16.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/MCSManager/node_modules/ssh2/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/MCSManager/node_modules/ssh2/.node-gyp'
gyp ERR! System Linux 5.15.36
gyp ERR! command "/opt/node-v12.16.1-linux-x64/node-v12.16.1-linux-x64/bin/node" "/opt/node-v12.16.1-linux-x64/node-v12.16.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "--target=v12.16.1" "rebuild"
gyp ERR! cwd /opt/MCSManager/node_modules/ssh2/lib/protocol/crypto
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
Failed to build optional crypto binding
added 163 packages from 125 contributors in 5.534s

1 package is looking for funding
  run `npm fund` for details

--------------- Complete ---------------
 Successfully installed!!!
 Directory: /opt/MCSManager/
--------------- Complete ---------------
Joining system service...
Create file: /usr/lib/systemd/system/mcsm.service
complete.

--------------- Quickstart ---------------
 Start： systemctl start mcsm
 Stop:   systemctl stop mcsm
 Status: systemctl status mcsm
--------------- Quickstart ---------------

**Comment by SeaGull1919** [comment]
什么也不懂的新手 第一次配置MCSM 遇到了错误不知道怎么解决 烦请各位路过的大佬帮忙看一下 指点一二... 谢谢

**Comment by huangsijun17** [comment]
面板依赖“ping”命令？若是，安装脚本加一个安装网络工具的命令吧。
@Suwings

**Comment by OldGodShen** [comment]
问题是没有问题啊，不是装好了嘛?
![image](https://user-images.githubusercontent.com/57306382/166643089-0b1f7ba6-95f7-4560-8f58-7ebd686befbe.png)

**Comment by ThebestkillerTBK** [comment]
permission denied?可能权限不够

**Comment by SeaGull1919** [comment]
> 问题是没有问题啊，不是装好了嘛? ![image](https://user-images.githubusercontent.com/57306382/166643089-0b1f7ba6-95f7-4560-8f58-7ebd686befbe.png)

装好了，也可以进到登录界面。但是账号密码登录始终错误，我是在X86软路由Docker环境下边配置的  应该是这个问题....

**Comment by SeaGull1919** [comment]
> root，123456 是默认密码，是否错误？

是的，错误 登录不上 猜测是没有正确生成对应的配置文件。官方文档有提，要用发行版的ubuntu，应该是我使用的docker版linux缺少了组件或者其他问题吧。

**Comment by unitwk** [comment]
> ping没装，先去装ping。

不要挖坟
