### ISSUE TITLE
[Bug Report] 对于Safari浏览器来说，可能无法进行上传文件

### ISSUE THREAD

**Issue by MoeCinnamo** [MCSManager/MCSManager#632]
**操作系统版本**
#1 SMP PVE 5.13.19-15 (Tue, 29 Mar 2022 15:59:50 +0200) 5.13.19-6-pve

**面板版本**
9.4.4

**出现概率**
100%

**BUG 详情描述**
在Safari浏览器里打开控制面板，登录管理员用户，在面板文件管理处点击上传文件，无任何反应。

**复现步骤**
使用Safari浏览器打开控制面板即可复现

**Comment by Cinnamoroll-Rabbit** [comment]
对于iPad OS和iOS系统来说，此BUG依然有效，而且对于iOS/iPad OS下的其它浏览器内核环境(例如Chrome、Alook)等依然有效。

**Comment by huangsijun17** [comment]
> 现在手上没有MAC，过段时间再测试和修复。

昨天我拿我妈iPhone试了一下，确实不行。

**Comment by zhang12c** [comment]
不会呀，我一直在用safari。可以上传的。
我Mac 是M1 芯片。系统：macOS Monterey 版本：12.3.1

**Comment by Cinnamoroll-Rabbit** [comment]
> 不会呀，我一直在用safari。可以上传的。
> 我Mac 是M1 芯片。系统：macOS Monterey 版本：12.3.1

对于Mac电脑来说，可能确实没有问题，受影响的是除Mac和Windows版Safari浏览器外的iPhone、iPad设备，你拿你的iPhone测试下，应该是没任何反应的，对于Mac来说，可能确实没有问题。

**Comment by Cinnamoroll-Rabbit** [comment]
> 现在手上没有MAC，过段时间再测试和修复。

不影响Mac，受影响的是iPhone和iPad等设备，默认这些设备是可以上传的，不知道怎么的，只有面板不能上传。

**Comment by Longtianmu** [comment]
我也是，iPadOS/iOS 15.4.1均无法使用，可能16有解决？
我回去试试

**Comment by Suwings** [comment]
在Mac上的Safari是可行的，iphone 上的确实不行，具体原因还不清楚。

**Comment by Longtianmu** [comment]
> 在Mac上的Safari是可行的，iphone 上的确实不行，具体原因还不清楚。

Apple的Mobile和Desktop的Webkit版本与类型不一样吧
