### ISSUE TITLE
[Feature Request] 希望添加Windows版本的docker容器或者VBox镜像功能

### ISSUE THREAD

**Issue by Cinnamoroll-Rabbit** [MCSManager/MCSManager#633]
**面板版本**
9.4.4

**想法/建议**
如题，希望添加Windows版本的docker容器或者直接使用VBox API实现VBox虚拟机镜像功能。

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
60-80

**Comment by ThebestkillerTBK** [comment]
我感觉这个功能不实用，linux装docker好好的，windows可能会很烦

**Comment by KagurazakaNyaa** [comment]
不如开个Linux虚拟机跑docker

**Comment by Cinnamoroll-Rabbit** [comment]
> 不如开个Linux虚拟机跑docker

已经有虚拟机了，为啥还要跑docker呢？不如直接虚拟机跑镜像，可以是ubuntu laster的镜像并且内置java8-17的所有版本，可以直接通过面板调用，何必还要用docker呢？

**Comment by huangsijun17** [comment]
已经实验性得适配了windows 的Docker，但是并不推荐，因为一切VM都非常吃性能。
你都已经是虚拟机了，为什么不直接在VBOX里跑Linux跑MCSM呢？一个MC实例跑一个虚拟机，一整个操作系统，不是大量消耗性能吗？

**Comment by Cinnamoroll-Rabbit** [comment]
> 已经实验性得适配了windows 的Docker，但是并不推荐，因为一切VM都非常吃性能。
> 你都已经是虚拟机了，为什么不直接在VBOX里跑Linux跑MCSM呢？一个MC实例跑一个虚拟机，一整个操作系统，不是大量消耗性能吗？

并不是一个MC实例跑一个虚拟机，而是一个虚拟机跑Linux，在同一个虚拟机内部署多个MC实例，这样就不会大量消耗性能了，而且还会保证稳定性。

**Comment by ThebestkillerTBK** [comment]
> > 已经实验性得适配了windows 的Docker，但是并不推荐，因为一切VM都非常吃性能。
> > 你都已经是虚拟机了，为什么不直接在VBOX里跑Linux跑MCSM呢？一个MC实例跑一个虚拟机，一整个操作系统，不是大量消耗性能吗？
> 
> 并不是一个MC实例跑一个虚拟机，而是一个虚拟机跑Linux，在同一个虚拟机内部署多个MC实例，这样就不会大量消耗性能了，而且还会保证稳定性。

那不是多此一举了吗

**Comment by Cinnamoroll-Rabbit** [comment]
> > > 已经实验性得适配了windows 的Docker，但是并不推荐，因为一切VM都非常吃性能。
> > > 你都已经是虚拟机了，为什么不直接在VBOX里跑Linux跑MCSM呢？一个MC实例跑一个虚拟机，一整个操作系统，不是大量消耗性能吗？
> > 
> > 
> > 并不是一个MC实例跑一个虚拟机，而是一个虚拟机跑Linux，在同一个虚拟机内部署多个MC实例，这样就不会大量消耗性能了，而且还会保证稳定性。
> 
> 那你直接在Linux里装MCSM-Deamon啊。甚至前端都可以直接装VM里面。为何要使用VBox API？

装VM里面稳定性欠佳，对于某些不能装Linux的Windows服务器来说确实有用

**Comment by huangsijun17** [comment]
> > > > 已经实验性得适配了windows 的Docker，但是并不推荐，因为一切VM都非常吃性能。
> > > > 你都已经是虚拟机了，为什么不直接在VBOX里跑Linux跑MCSM呢？一个MC实例跑一个虚拟机，一整个操作系统，不是大量消耗性能吗？
> > > 
> > > 
> > > 并不是一个MC实例跑一个虚拟机，而是一个虚拟机跑Linux，在同一个虚拟机内部署多个MC实例，这样就不会大量消耗性能了，而且还会保证稳定性。
> > 
> > 
> > 那你直接在Linux里装MCSM-Deamon啊。甚至前端都可以直接装VM里面。为何要使用VBox API？
> 
> 装VM里面稳定性欠佳，对于某些不能装Linux的Windows服务器来说确实有用

装VM里面稳定性欠佳，所以要控制VBOX，来跑在VM里面？为啥不直接Docker？或者直接跑Windows下面？

**Comment by Cinnamoroll-Rabbit** [comment]
> > > > > 已经实验性得适配了windows 的Docker，但是并不推荐，因为一切VM都非常吃性能。
> > > > > 你都已经是虚拟机了，为什么不直接在VBOX里跑Linux跑MCSM呢？一个MC实例跑一个虚拟机，一整个操作系统，不是大量消耗性能吗？
> > > > 
> > > > 
> > > > 并不是一个MC实例跑一个虚拟机，而是一个虚拟机跑Linux，在同一个虚拟机内部署多个MC实例，这样就不会大量消耗性能了，而且还会保证稳定性。
> > > 
> > > 
> > > 那你直接在Linux里装MCSM-Deamon啊。甚至前端都可以直接装VM里面。为何要使用VBox API？
> > 
> > 
> > 装VM里面稳定性欠佳，对于某些不能装Linux的Windows服务器来说确实有用
> 
> 装VM里面稳定性欠佳，所以要控制VBOX，来跑在VM里面？为啥不直接Docker？或者直接跑Windows下面？

因为直接跑Windows下面对于某些客户端来说，是不行的。用docker在Windows里面是很麻烦的。为了兼容性，控制VBOX跑在VM里面是最稳妥的，虽然稳定性并不是特别高。

**Comment by huangsijun17** [comment]
> > > > > > 已经实验性得适配了windows 的Docker，但是并不推荐，因为一切VM都非常吃性能。
> > > > > > 你都已经是虚拟机了，为什么不直接在VBOX里跑Linux跑MCSM呢？一个MC实例跑一个虚拟机，一整个操作系统，不是大量消耗性能吗？
> > > > > 
> > > > > 
> > > > > 并不是一个MC实例跑一个虚拟机，而是一个虚拟机跑Linux，在同一个虚拟机内部署多个MC实例，这样就不会大量消耗性能了，而且还会保证稳定性。
> > > > 
> > > > 
> > > > 那你直接在Linux里装MCSM-Deamon啊。甚至前端都可以直接装VM里面。为何要使用VBox API？
> > > 
> > > 
> > > 装VM里面稳定性欠佳，对于某些不能装Linux的Windows服务器来说确实有用
> > 
> > 
> > 装VM里面稳定性欠佳，所以要控制VBOX，来跑在VM里面？为啥不直接Docker？或者直接跑Windows下面？
> 
> 因为直接跑Windows下面对于某些客户端来说，是不行的。用docker在Windows里面是很麻烦的。为了兼容性，控制VBOX跑在VM里面是最稳妥的，虽然稳定性并不是特别高。

1. 既然要求那么高的稳定性，和兼容性，为啥不直接跑Linux？
2. WSL、Docker Desktop的稳定性、兼容性、可靠性、性能损耗也远低于VBOX，为何不用WSL、Docker Desktop？
3. 况且，你认为VM里面稳定性欠佳，却偏偏觉得一个面板可以监测到VBOX虚拟机的正常运行？难不成还要面板周期性得去监测，再去重启卡死的操作系统？为何不用现成的，使用VBOX API的虚拟机管理软件管理，然后全部跑到在VBOX里面呢？

**Comment by Cinnamoroll-Rabbit** [comment]
> > > > > > > 已经实验性得适配了windows 的Docker，但是并不推荐，因为一切VM都非常吃性能。
> > > > > > > 你都已经是虚拟机了，为什么不直接在VBOX里跑Linux跑MCSM呢？一个MC实例跑一个虚拟机，一整个操作系统，不是大量消耗性能吗？
> > > > > > 
> > > > > > 
> > > > > > 并不是一个MC实例跑一个虚拟机，而是一个虚拟机跑Linux，在同一个虚拟机内部署多个MC实例，这样就不会大量消耗性能了，而且还会保证稳定性。
> > > > > 
> > > > > 
> > > > > 那你直接在Linux里装MCSM-Deamon啊。甚至前端都可以直接装VM里面。为何要使用VBox API？
> > > > 
> > > > 
> > > > 装VM里面稳定性欠佳，对于某些不能装Linux的Windows服务器来说确实有用
> > > 
> > > 
> > > 装VM里面稳定性欠佳，所以要控制VBOX，来跑在VM里面？为啥不直接Docker？或者直接跑Windows下面？
> > 
> > 
> > 因为直接跑Windows下面对于某些客户端来说，是不行的。用docker在Windows里面是很麻烦的。为了兼容性，控制VBOX跑在VM里面是最稳妥的，虽然稳定性并不是特别高。
> 
> 1. 既然要求那么高的稳定性，和兼容性，为啥不直接跑Linux？
> 2. WSL、Docker Desktop的稳定性、兼容性、可靠性、性能损耗也远低于VBOX，为何不用WSL、Docker Desktop？
> 3. 况且，你认为VM里面稳定性欠佳，却偏偏觉得一个面板可以监测到VBOX虚拟机的正常运行？难不成还要面板周期性得去监测，再去重启卡死的操作系统？为何不用看门狗监视VBOX，然后全部跑到在VBOX里面呢？

对于某些服务器来说，linux和Windows可用区隔离，没硬件虚拟化虚拟Linux会卡死，所以可以搞vm用精简镜像，而检测也仅仅监视VBOX里面的进程，然后再去控制

**Comment by huangsijun17** [comment]
> > > > > > > > 已经实验性得适配了windows 的Docker，但是并不推荐，因为一切VM都非常吃性能。
> > > > > > > > 你都已经是虚拟机了，为什么不直接在VBOX里跑Linux跑MCSM呢？一个MC实例跑一个虚拟机，一整个操作系统，不是大量消耗性能吗？
> > > > > > > 
> > > > > > > 
> > > > > > > 并不是一个MC实例跑一个虚拟机，而是一个虚拟机跑Linux，在同一个虚拟机内部署多个MC实例，这样就不会大量消耗性能了，而且还会保证稳定性。
> > > > > > 
> > > > > > 
> > > > > > 那你直接在Linux里装MCSM-Deamon啊。甚至前端都可以直接装VM里面。为何要使用VBox API？
> > > > > 
> > > > > 
> > > > > 装VM里面稳定性欠佳，对于某些不能装Linux的Windows服务器来说确实有用
> > > > 
> > > > 
> > > > 装VM里面稳定性欠佳，所以要控制VBOX，来跑在VM里面？为啥不直接Docker？或者直接跑Windows下面？
> > > 
> > > 
> > > 因为直接跑Windows下面对于某些客户端来说，是不行的。用docker在Windows里面是很麻烦的。为了兼容性，控制VBOX跑在VM里面是最稳妥的，虽然稳定性并不是特别高。
> > 
> > 
> > 
> > 1. 既然要求那么高的稳定性，和兼容性，为啥不直接跑Linux？
> > 2. WSL、Docker Desktop的稳定性、兼容性、可靠性、性能损耗也远低于VBOX，为何不用WSL、Docker Desktop？
> > 3. 况且，你认为VM里面稳定性欠佳，却偏偏觉得一个面板可以监测到VBOX虚拟机的正常运行？难不成还要面板周期性得去监测，再去重启卡死的操作系统？为何不用看门狗监视VBOX，然后全部跑到在VBOX里面呢？
> 
> 对于某些服务器来说，linux和Windows可用区隔离，没硬件虚拟化虚拟Linux会卡死，所以可以搞vm用精简镜像，而检测也仅仅监视VBOX里面的进程，然后再去控制

**？？？？**

1. 区分linux和Windows，请去用ESXI、PVE、Unraid等虚拟化系统。
2. WSL2基于hyper-v，怎么变成没有虚拟化了？
3. 退一万步说，MCSM-Deamon和JVM之间是使用了管道通信，你咋让windows去Linux里执行jar并实现通信？难不成再去开发一个新的daemon2程序，跑在Linux里面？
