### ISSUE TITLE
[Bug Report] 守護進程異常强制關閉

### ISSUE THREAD

**Issue by Kokored7214** [MCSManager/MCSManager#635]
**操作系统版本**
#45-Ubuntu SMP Tue Mar 29 14:48:14 UTC 2022 5.13.0-40-generic

**面板版本**
9.4.3

**出现概率**
每天下午約5點05分 (已經連續兩天了)

**BUG 详情描述**
到了大約5點30分的時候守護進程會被强制關閉
不知道該問題是屬於mcsmanager的問題或是系統的問題

經過查閲 /opt/mcsmanager/daemon/logs 後發現在該時間會有一條 "WARN" 信息
`WARN SIGTERM close process signal detected.`
然後在 17:33 會顯示守護進程啓動的信息

在兩次同樣的問題發生期間log中沒有任何錯誤記錄

**复现步骤**
未知

**Comment by ThebestkillerTBK** [comment]
应该是你系统的问题吧，mcsm不会发出sigterm的

**Comment by Suwings** [comment]
应该是系统发出来的，这个错误信息只有在人工手动Ctrl+C和系统要杀掉程序的时候才会出现。

检查一下是不是你的内存不足？

**Comment by Kokored7214** [comment]
我將系統重裝後就沒再發生了，應該是某個軟件導致的
