### ISSUE TITLE
[Bug Report] 密码错误

### ISSUE THREAD

**Issue by AZureDracula** [MCSManager/MCSManager#636]
**操作系统版本**
linux
**面板版本**
MCSM9

**出现概率**
100%

**BUG 详情描述**
默认密码登录错误root 123456

**复现步骤**

**Comment by ThebestkillerTBK** [comment]
最新版本有了密码安全策略，可以删除user下文件试试看

**Comment by Suwings** [comment]
你第一次刚安装的时候才是root 123456，进入面板之后会要求你更改密码。
