### ISSUE TITLE
[Bug Report] 面板刷新后，终端文字颜色丢失

### ISSUE THREAD

**Issue by CCBlueX666** [MCSManager/MCSManager#637]
**操作系统版本**
macOS 12.4 Chrome 101.0.4951.54（正式版本） (arm64)
**面板版本**
9.4 发行版

**出现概率**
100%

**BUG 详情描述**
面板刷新后，原先终端文字颜色丢失，只有新的消息有颜色
![20220508085046](https://user-images.githubusercontent.com/60721270/167277198-607f305f-0d69-4840-ac66-0bc849790b63.jpg)

**复现步骤**
打开一个运行中的实例，切换到其他标签页约10s，返回实例，刷新实例标签页，文字颜色丢失（变白色），只有新消息才有颜色，需要返回实例列表再次进入或再次刷新才有颜色

**Comment by Suwings** [comment]
面板 9.4.4 版本并未发现你所说的情况，请升级面板即可。

**Comment by CCBlueX666** [comment]
好的
