### ISSUE TITLE
[Bug Report] 文件操作卡进程

### ISSUE THREAD

**Issue by qiongqi-empty** [MCSManager/MCSManager#640]
**操作系统版本**
windows server 2019 Datacenter
**面板版本**
9.4.2

**出现概率**
100%

**BUG 详情描述**
对文件的一个操作没有结束或者还在运行的时候进行另外一个操作会卡住，导致面板无法访问那个文件夹
必须得重启服务端才能恢复，非常麻烦

能否给复制粘贴压缩解压之类的操作加上进度条，并且操作未完成前无法进行下一步操作，然后拦截对正在运行的文件的操作
我没有编程基础，不清楚这些东西的难度，如果对您造成困扰实在抱歉

**复现步骤**
文件尚未压缩完就下载，不关服压缩地图文件之类的

**Comment by Suwings** [comment]
新版本会升级Linux下的解压缩方案，敬请期待。

**Comment by unitwk** [comment]
此问题应该已经得到解决：https://github.com/MCSManager/MCSManager/releases/tag/v9.5.0
