### ISSUE TITLE
[Feature Request]终端窗口上下滑动锁定

### ISSUE THREAD

**Issue by lightumcc** [MCSManager/MCSManager#641]
**面板版本**
9.4.4

**想法/建议**
在电脑版浏览器中，若整个浏览器窗口无法完全显示垂直内容时，当我鼠标选中终端窗口时，上下滑动希望可以只限制在终端内，而不是整个网页上下滑动，方便服务器管理员查看最近的记录，或在终端窗口内添加一个一键返回底部的按钮

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
60

**Comment by huangsijun17** [comment]
目测是BUG，我前些天在终端中选中文本，按 Ctrl + C 想复制出来，结果吧终端暂停了。

**Comment by CCBlueX666** [comment]
但是我在选中xterm后，向下滑动，是网页下滑而不是终端下滑
