### ISSUE TITLE
[Feature Request] 建议增加运行LiteLoaderBDS环境镜像

### ISSUE THREAD

**Issue by hhaipaap** [MCSManager/MCSManager#643]
**面板版本**
9.4.4

**想法/建议**
建议在 镜像与容器=>环境镜像管理=>新建镜像 里增加 创建 LiteLoaderBDS 环境镜像（ https://www.minebbs.com/liteloader/ ）

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
40

**Comment by huangsijun17** [comment]
我去仔细看了一下LiteLoaderBDS 的 [Docker 镜像](https://hub.docker.com/r/shrbox/liteloaderbds)，该镜像为**服务端镜像**，而非**环境镜像**。MCSManager暂不支持直接运行服务端镜像。
