### ISSUE TITLE
[Feature Request] 面板端与守护进程连接中断后自动重连

### ISSUE THREAD

**Issue by Puqns67** [MCSManager/MCSManager#645]
**面板版本**
Web 9.4.4, Daemon 1.5.4

**想法/建议**
* 具体情况
我本人的情况是 Web 端运行在国外，Daemon 端运行在国内，常常因为网络问题断开连接，实际上是完全可以连的上的，要做到一个连接一直保持太难了，普通用户登录显示维护中实在是有点难受，还需要管理员账户上线手动重连

* 具体实现思维
在 Web 端与 Daemon 端的网络链接因网络问题而断开时自动重连，如多次重连后还是连不上则暂停尝试，如果管理员或 *非管理员* 账户登陆时 Web 端还因网络问题未链接至 Daemon 端，再次尝试重连

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
30 (感觉大部分人的两个远程服务端都是运行在同一台机器上，不会受到网络因素的影响)

**Comment by nkxingxh** [comment]
自动重连确实会更方便，现在香港的机器一天断几次

**Comment by Suwings** [comment]
可能线路不是很好，不过新版本已经新增了自动重连机制了。
