### ISSUE TITLE
[Feature Request] 希望可以更新一下这些问题

### ISSUE THREAD

**Issue by Baikele** [MCSManager/MCSManager#647]
**面板版本**
9.4.4

**想法/建议**

支持全版本MC
因为我尝试开一个1.6.4的服务器，在控制台发送消息，发送不出去，然后关闭服务器，提示一直在关闭中
这个问题，不止MC
我开7日杀的时候也是，提示在关闭中，然后关不掉
**您认为这个想法/建议在每100人中会有多少人遇到/使用**
20左右

**Comment by itzdrli** [comment]
> 

全版本MC？mcsm说白了就是个主要支持mc的java程序面板，甚至能跑其他java项目，至于你说的消息发送不出去，没理解你的意思，可能是你的网络问题；
关于服务器关闭不了，你可以试试在设置中修改关闭命令，比如将关闭命令设置成`^C`等等
