### ISSUE TITLE
使用MCSM自带的文件上传功能上传的sh脚本无法访问

### ISSUE THREAD

**Issue by cainiaoyizhou** [MCSManager/MCSManager#650]
![image](https://user-images.githubusercontent.com/103909046/169192352-0a8a0f47-aea1-481c-9ef5-4934b8e6015b.png)
提示权限不足

**Comment by Suwings** [comment]
用 root 权限运行面板。

**Comment by cainiaoyizhou** [comment]
已使用root（难道面板不检查权限吗
![image](https://user-images.githubusercontent.com/103909046/169206313-d63c454d-eb4b-4830-8b3d-bb609f0075a1.png)

**Comment by cainiaoyizhou** [comment]
且在终端直接运行（root）也这样提示

**Comment by huangsijun17** [comment]
Linux权限管理相关问题，请自行使用`ls -l`等命令排查权限。
