### ISSUE TITLE
[Bug Report] MCSManager控制面板/实例文件管理/新建目录中的"确定"与"取消"按钮汉化不完全

### ISSUE THREAD

**Issue by Hi-awaBlack** [MCSManager/MCSManager#652]
**操作系统版本**
Web: Windows Server 2012 R2 Datacenter 6.3.9600
Daemon: CentOS 7.6 64bit
**面板版本**
Web: 9.4.4
Daemon: 1.5.4
**出现概率**
100%
**BUG 详情描述**
MCSManager控制面板/实例文件管理/新建目录中的"确定"与"取消"按钮汉化不完全。
![image](https://user-images.githubusercontent.com/63138378/169655203-29ea56f9-5049-4a9e-93be-15fb81d28299.png)
**复现步骤**
进入MCSManager控制面板，打开任意实例的文件管理，点击"新建目录"。

**Comment by huangsijun17** [comment]
重命名 也漏了汉化。

**Comment by Hi-awaBlack** [comment]
经查看 该问题已在 MCSManager 9.5.0 中修复

自行关闭 issue
