### ISSUE TITLE
[Bug Report] 通过运行wine运行服务端只显示winedbg日志

### ISSUE THREAD

**Issue by StarsDream00** [MCSManager/MCSManager#653]
**操作系统版本**
Fedora 36
**面板版本**
9.4.4+1.5.4

**出现概率**
100%

**BUG 详情描述**
通过wine运行服务端只有winedbg的日志

**复现步骤**
无

**Comment by Suwings** [comment]
这是什么需求？你应该可以直接运行 Linux 下的服务端吧。这个情况不能算BUG。

**Comment by StarsDream00** [comment]
BDS for Windows + LiteLoaderBDS

**Comment by Suwings** [comment]
Fedora 无法直接开 Bedrock 服务端吗？通过 wine 来启动的话，我也不清楚会发生什么，有点异常也是正常情况。
