### ISSUE TITLE
[Bug Report] 项目主页的手动安装脚本错误

### ISSUE THREAD

**Issue by SereinP1geon** [MCSManager/MCSManager#654]
第一次提issue，不太会，大佬见谅哈;w;
如题，安装脚本原文如下：

```
# 下载面板端（Web）程序
git clone https://github.com/MCSManager/MCSManager-Web-Production.git
# 重命名文件夹并进入
mv MCSManager-Web-Production web
cd web
# 安装依赖库
npm install --registry=https://registry.npm.taobao.org
```

**这里，是否应该重新cd /opt/mcsmanager/
然后再继续下一步操作?**

```
# 下载守护进程（Daemon）程序
git clone https://github.com/MCSManager/MCSManager-Daemon-Production.git

# 打开两个终端或两个 Screen 软件的终端窗口
# 先启动守护进程
cd /opt/mcsmanager/daemon
# 启动
node app.js

```
**根据本人测试，如果不如上操作的话，daemon进程应位于/opt/mcsmanager/web/daemon
而非/opt/mcsmanager/web**

**Comment by Suwings** [comment]
你是指哪个仓库？具体多少行？你这个是Readme上的代码还是一键安装脚本的。

安装脚本：https://github.com/MCSManager/Script/blob/master/setup.sh

**Comment by SereinP1geon** [comment]
readme中的Linux手动安装代码
![H~2Z31E}Ihttps://github.com/MCSManager/MCSManager/blob/master/README.md#%E5%9C%A8-linux-%E8%BF%90%E8%A1%8C中的Linux手动安装脚本，

NSQE}Y{OKN2L](https://user-images.githubusercontent.com/104287277/170687069-a0da4ea1-c486-4b57-8d8a-6ea43ffbeb7a.png)

21-24行之间应该有一个cd /opt/mcsmanager/ ...?

**Comment by huangsijun17** [comment]
> readme中的Linux手动安装代码 ![H~2Z31E}Ihttps://github.com/MCSManager/MCSManager/blob/master/README.md#%E5%9C%A8-linux-%E8%BF%90%E8%A1%8C中的Linux手动安装脚本，
> 
> NSQE}Y{OKN2L](https://user-images.githubusercontent.com/104287277/170687069-a0da4ea1-c486-4b57-8d8a-6ea43ffbeb7a.png)
> 
> 21-24行之间应该有一个cd /opt/mcsmanager/ ...?

是的。
