### ISSUE TITLE
[Feature Request] 网址添加一个最前端的目录

### ISSUE THREAD

**Issue by YipSzeho** [MCSManager/MCSManager#655]
**面板版本**
9.4.2

**想法/建议**
添加一个最前端的目录，现在的是`host/#/overview/` `host/#/css/`
可以的话希望变成`host/#/mcsm/overview` `host/#/mcsm/css`
这样反代就可以在域名的目录下访问面板

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
也许是我学艺不精，我现在是`https://domain/mcsm/` 来访问面板
但实现这种效果的nginx配置比较复杂，反代后还要设置write
要在`location \ `下添加规则`if ($document_uri ~* '/css|#|img|fonts|api|static|js/.*') {rewrite ^/(.*)$ /mcsm/$1 last;  }`
才能通过目录打开面板，但还是会遇到登陆后转跳回http://domain/ 的情况
或者有什么更好的配置nginx的方法吗？

附上现在的nginx配置
```
  server {
    listen 443 ssl http2;
    ssl_certificate /home/cert/cert.pem;
    ssl_certificate_key /home/cert/key.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    if ($document_uri ~* '/css|#|img|fonts|api|static|js/.*') {rewrite ^/(.*)$ /mcsm/$1 last;  }

    location /mcsm/ {
      proxy_pass http://mcsm/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Port $server_port;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
  }
```

**Comment by bddjr** [comment]
你这样不如搞三级域名稳定，例如 mcsm.domain.com

**Comment by YipSzeho** [comment]
嘛之前白嫖DDNS的域名所以没法这样搞，后来买了域名就方便了(

**Comment by huangsijun17** [comment]
> 嘛之前白嫖DDNS的域名所以没法这样搞，后来买了域名就方便了(

前端现在已经支持反代到非根目录了。后端还不行。主要是握手/通讯那块要大改。
