### ISSUE TITLE
希望可以针对国外的vps的安装进行优化

### ISSUE THREAD

**Issue by SungHerobrine97** [MCSManager/MCSManager#657]
我用的是EUServ的vps机子（只有ipv6），我是在修改dns之后安装MCSManager的，但是在npmmirror上下载时直接没网速了，之后我又在nodejs上下载最新版本的node（16.15.1）反而高速，希望可以对国外的vps机子提供node依赖的备用安装方案。

**Comment by huangsijun17** [comment]
现在的安装脚本等是针对中国大陆优化的。您可以去看一下脚本里面都地址，将gitee改成github，npmmirror.com改成npmjs.com。

**Comment by SungHerobrine97** [comment]
谢谢
