### ISSUE TITLE
翻譯問題

### ISSUE THREAD

**Issue by hankwu0501** [MCSManager/MCSManager#659]
如果我想翻譯這個面板要翻譯哪些檔案

**Comment by huangsijun17** [comment]
系列项目无I18n设计，无独立的语言文件，而且可能难以实现I18n。可能需要依次翻译所有文件。

**Comment by huangsijun17** [comment]
另外，安装脚本、教程都是为了适配中国大陆而优化的，可能需要修改其中的镜像地址。

**Comment by Suwings** [comment]
确实如此，缺如爱卿所言。

**Comment by cracky5322** [comment]
> 系列项目无I18n设计，无独立的语言文件，而且可能难以实现I18n。可能需要依次翻译所有文件。

目前我已經有粗略的翻譯版本，可以由貴團隊開繁體中文的分支，繁體中文與簡體中文與簡體中文可以使用分支的方式，也算另類的多語言，繁體中文的部分之後再由使用者義務性的翻譯後統一由貴團隊發布更新版本，不知貴團隊覺得如何?
