### ISSUE TITLE
[Bug Report] ReadME.md 文件中出错

### ISSUE THREAD

**Issue by huangyuID** [MCSManager/MCSManager#661]
**操作系统版本**
---
**面板版本**
---

**出现概率**
---

**BUG 详情描述**
在“搭建开发环境”中，“守护进程（Daemon）”部分的代码块第一行出现问题
(问题处原文开始)
**https://github.com/MCSManager/Daemon.git**
cd Daemon
npm install
npm run start
#运行后请在控制面板端连接本守护进程
#默认运行在 24444 端口
(问题处原文结束)
修改建议：加粗部分在最前方应放置“git clone ”
**复现步骤**
打开 https://github.com/MCSManager/MCSManager 后即复现

**Comment by huangsijun17** [comment]
请直接提交Pull requests。

**Comment by huangyuID** [comment]
> 请直接提交Pull requests。

好的

**Comment by huangsijun17** [comment]
https://github.com/MCSManager/MCSManager/pull/668
