### ISSUE TITLE
[Feature Request] 一键上传日志以便于分享

### ISSUE THREAD

**Issue by huangsijun17** [MCSManager/MCSManager#662]
**面板版本**
N.A.

**想法/建议**
在日志界面可以一键上传日志文件到类似于[Ubuntu Pastebin](https://paste.ubuntu.com/)、[paste.ee](http://paste.ee)的网站，以便于分享日志给他人来排查问题。

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
60%~80%

**Comment by Mr-Ao-Dragon** [comment]
> **面板版本**
> N.A.
> 
> **想法/建议**
> 在日志界面可以一键上传日志文件到类似于[Ubuntu Pastebin](https://paste.ubuntu.com/)、[paste.ee](http://paste.ee)的网站，以便于分享日志给他人来排查问题。
> 
> **您认为这个想法/建议在每100人中会有多少人遇到/使用**
> 60%~80%

我推荐一个[网站](https://susepaste.org)，还不错

**Comment by huangsijun17** [comment]
![AI~3W_3VMM%~VLY`}K6 @SG](https://user-images.githubusercontent.com/31504595/185865710-580ca959-a697-4719-b0bc-ea395d7a32ed.png)
