### ISSUE TITLE
[Feature Request] 优化文件管理交互逻辑

### ISSUE THREAD

**Issue by jstar0** [MCSManager/MCSManager#664]
**面板版本**
9.4.5

**想法/建议**
1. 列文件时，提供“整页浏览全部文件”的选项；换页按钮不应只存在于顶部右侧，同样应在页面底端添加，方便翻页。
2. 文件管理上方，相对路径应以按钮的形式呈现，允许点击后跳转。

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
99

**Comment by Suwings** [comment]
就是因为有些程序某个文件夹里面会有上千上万的小文件导致页面崩溃才加入的分页功能，所以不应该再提供`整页浏览全部文件`的功能。

至于分页按钮底部也要摆放一个，这点我倒是挺认可。

其他的可以考虑，谢谢你的意见，如果可以也欢迎提交PR。

**Comment by huangsijun17** [comment]
希望可以带上刷新文件夹&文件排序。
