### ISSUE TITLE
[Bug Report] XXXXXXX

### ISSUE THREAD

**Issue by failin98fish** [MCSManager/MCSManager#665]
**操作系统版本**
arm64

**面板版本**
最新版本

**出现概率**
百分百

**BUG 详情描述**
node 版本正确 端口全部放行
![图片](https://user-images.githubusercontent.com/56397393/173268278-a6a5f3f4-9943-4806-b1cd-7c53cfb8b3f7.png)
![图片](https://user-images.githubusercontent.com/56397393/173268311-8834d9e7-393f-400c-9314-d7a1365dc279.png)
status全是active
但是浏览器访问不了23333端口

**复现步骤**

**Comment by Suwings** [comment]
检查防火墙，重启MCSM面板服务，systemctl restart mcsm-{web,daemon} ，或重启服务器。
