### ISSUE TITLE
[Feature Request] 重启整台机器

### ISSUE THREAD

**Issue by CCBlueX666** [MCSManager/MCSManager#666]
**面板版本**
9.4.5

**想法/建议**
建议在实例控制组处或数据监控栏右上角增加重启整台机器的按钮，这样可以省去链接SSH/服务器后台在点击重启从而清理数据库或其他缓存的步骤

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
80

**Comment by CCBlueX666** [comment]
如果可以的话，可以顺带在计划任务-任务动作/类型处增加重启整台机器的操作

**Comment by huangsijun17** [comment]
**技术上不可实现。**
不是每个用户都是用管理员/超级管理员来运行MCSManager的。作为一个业务服务程序，也不应该使用管理员/超级管理员来运行MCSManager。MCSManager的用户可能也应当无权直接重启电脑。更何况，MCSManager也是可以运行在Docker容器内，在容器里如何重启宿主？

**Comment by Suwings** [comment]
使用实例启动一个webshell，启动命令就是 bash。然后使用此终端代替 SSH 功能。

需要使用 root 权限。

**Comment by CCBlueX666** [comment]
明白了，谢谢两位大佬提醒

**Comment by Suwings** [comment]
> **技术上不可实现。** 不是每个用户都是用管理员/超级管理员来运行MCSManager的。作为一个业务服务程序，也不应该使用管理员/超级管理员来运行MCSManager。MCSManager的用户可能也应当无权直接重启电脑。更何况，MCSManager也是可以运行在Docker容器内，在容器里如何重启宿主？

我觉得有时候你想太多了。。。
