### ISSUE TITLE
升级后报错无法启动web端

### ISSUE THREAD

**Issue by stevened7246** [MCSManager/MCSManager#667]
**操作系统版本**
Ubuntu 20.04.4 LTS

**面板版本**
一键命令安装的
9.4.4

**出现概率**
更新到9.4.5出现

**BUG 详情描述**
gitpull后web端node报错找不到模塊
使用`npm install --registry=https://registry.npmmirror.com/`后成功启动

**复现步骤**
使用
```
systemctl stop mcsm-{web,daemon}
cd /opt/mcsmanager/web
git pull
cd /opt/mcsmanager/daemon
git pull
systemctl start mcsm-{web,daemon}
```
从9.4.4升级到9.4.5

**Comment by huangsijun17** [comment]
正常现象，新版本引用了新的库文件时，就需要进行安装。

**Comment by Suwings** [comment]
这个我发布更新的时候忘记说了，新增了依赖库，所以需要重新安装一下，正常。
