### ISSUE TITLE
[Bug Report] java路径问题导致面板无法启动服务器

### ISSUE THREAD

**Issue by oneoness** [MCSManager/MCSManager#669]
**操作系统版本**
Ubuntu 20 / Centos 7.6

**面板版本**
9.4.5

**BUG 详情描述**
面板默认的java路径是usr，并且没有提供修改功能和教程提示。当用户将java装在别的路径下时，ssh能正常启动服务器，而面板则找不到java环境

**复现步骤**
将java装在其他目录下就能复现

**Comment by huangsijun17** [comment]
试试看输入Java的完整路径。

**Comment by oneoness** [comment]
按XQZ所说，完整路径是没有问题的。不过希望开发者们能在教程中指出这个问题，或者在面板中添加修改路径的功能

**Comment by huangsijun17** [comment]
> 按XQZ所说，完整路径是没有问题的。不过希望开发者们能在教程中指出这个问题，或者在面板中添加修改路径的功能

应该是低版本的MCSM安装脚本在安装systemd服务时未继承系统的`$PATH变量`的问题。建议参考[这里](https://github.com/MCSManager/Script/commit/de1aac7f2eb551944864d8dbd7bea6938f489032)修改mcsm-web.service与mcsm-daemon.service文件。

**Comment by oneoness** [comment]
好的，我找到了这两个文件。目前我也推断出问题出在哪了。安装脚本应该是没有问题，确实继承下来了`$PATH`变量
下面我来描述一下这个“BUG”出现的原因：
1. 前两次我是先安装了面板，再安装JDK，所以面板没有可以继承的`$PATH`变量
2. 第三次我先安装了JDK，再安装面板，这时候打开如上所述的两个service文件，看到的是`$PATH`变量继承成功

所以安装脚本没有问题，这个BUG不属于系统本身的漏洞，而是用户行为上产生的漏洞。

---
我的建议是官方教程中提示一句：先安装JDK环境后再安装面板
当然如果面板本身能自动修复这个问题就更好了

**Comment by huangsijun17** [comment]
> 好的，我找到了这两个文件。目前我也推断出问题出在哪了。安装脚本应该是没有问题，确实继承下来了`$PATH`变量 下面我来描述一下这个“BUG”出现的原因：
> 
> 1. 前两次我是先安装了面板，再安装JDK，所以面板没有可以继承的`$PATH`变量
> 2. 第三次我先安装了JDK，再安装面板，这时候打开如上所述的两个service文件，看到的是`$PATH`变量继承成功
> 
> 所以安装脚本没有问题，这个BUG不属于系统本身的漏洞，而是用户行为上产生的漏洞。
> 
> 我的建议是官方教程中提示一句：先安装JDK环境后再安装面板 当然如果面板本身能自动修复这个问题就更好了

安装脚本前两天刚更新，修改了这个bug。我前面发的链接就是更新详情。

**Comment by oneoness** [comment]
但其实我是昨天安装的  23333

**Comment by Suwings** [comment]
> > 好的，我找到了这两个文件。目前我也推断出问题出在哪了。安装脚本应该是没有问题，确实继承下来了`$PATH`变量 下面我来描述一下这个“BUG”出现的原因：
> > 
> > 1. 前两次我是先安装了面板，再安装JDK，所以面板没有可以继承的`$PATH`变量
> > 2. 第三次我先安装了JDK，再安装面板，这时候打开如上所述的两个service文件，看到的是`$PATH`变量继承成功
> > 
> > 所以安装脚本没有问题，这个BUG不属于系统本身的漏洞，而是用户行为上产生的漏洞。
> > 我的建议是官方教程中提示一句：先安装JDK环境后再安装面板 当然如果面板本身能自动修复这个问题就更好了
> 
> 安装脚本前两天刚更新，修改了这个bug。我前面发的链接就是更新详情。

说实在的，我在 Ubuntu 上测试过，有没有这次 Commit 都是正常的，PATH 环境都存在。

Centos 的话，昨日有用户反馈依然找不到环境变量中的命令，比如java之类的，有空你可以测试一下，我最近没时间。

不过不管有没有修复，这次提交都不影响。

https://github.com/MCSManager/Script/commit/de1aac7f2eb551944864d8dbd7bea6938f489032
