### ISSUE TITLE
[Bug Report] safari浏览器无法上传文件

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#671]
**操作系统版本**
Windows Server 2019 Datacenter 10.0.17763
**面板版本**
9.4.5

**出现概率**
100%

**BUG 详情描述**
在文件管理页面单机“上传文件”按钮无反应

**复现步骤**

**Comment by huangsijun17** [comment]
safari浏览器？哪个系统？哪个版本？

**Comment by XiaoXiaoYang233** [comment]
> safari浏览器？哪个系统？哪个版本？

IOS系统，版本15.5

**Comment by huangsijun17** [comment]
已知BUG，成因未知。
https://github.com/MCSManager/MCSManager/issues/632
