### ISSUE TITLE
[Feature Request] 新增设置是否让用户第一次登录时候重置密码

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [MCSManager/MCSManager#673]
**面板版本**

9.4

**想法/建议**

在不判断密码复杂度的情况下强制要求重置密码过于武断，且密码重置判定偶发性不生效，即使重置了密码依然要求重置。

**您认为这个想法/建议在每100人中会有多少人遇到/使用**

80

**Comment by huangsijun17** [comment]
密码是双重加密存储的……而且未加密的密码不应当上传到服务器。直接重置为相同的密码即可。

**Comment by Suwings** [comment]
`即使重置了密码依然要求重置。`

这个是一个BUG，在 9.5 版本已修复。
