### ISSUE TITLE
[Bug Report] 控制臺輸入輸出亂碼

### ISSUE THREAD

**Issue by Kokored7214** [MCSManager/MCSManager#675]
**操作系统版本**
#136-Ubuntu SMP Fri Jun 10 13:40:48 UTC 2022 5.4.0-120-generic

**面板版本**
9.4.5

**出现概率**
100%

**BUG 详情描述**
![image](https://user-images.githubusercontent.com/67258143/175325700-688b7e68-a132-407d-9d55-b22d62dbfd47.png)
![image](https://user-images.githubusercontent.com/67258143/175325730-4d5e749b-1d63-4883-a15f-caa5f1fabe0b.png)

已將終端輸入和輸出編碼改為big5試過還是一樣
![image](https://user-images.githubusercontent.com/67258143/175326206-20c8d2de-65b4-475f-8cdd-84f49d7f17eb.png)

**Comment by huangsijun17** [comment]
是否使用了Docker？使用了的话，需要用UTF-8，并且加上这个JAVA启动参数：`-Dfile.encoding=UTF-8`

**Comment by Suwings** [comment]
> 是否使用了Docker？使用了的话，需要用UTF-8，并且加上这个JAVA启动参数：`-Dfile.encoding=UTF-8`

那这样面板输入输出编码配置那里是不是要改成 UTF8？

**Comment by huangsijun17** [comment]
> > 是否使用了Docker？使用了的话，需要用UTF-8，并且加上这个JAVA启动参数：`-Dfile.encoding=UTF-8`
> 
> 那这样面板输入输出编码配置那里是不是要改成 UTF8？

我就是这样解决中文显示&中文输入失败的问题的。
