### ISSUE TITLE
[Bug Report] 文件解压错误

### ISSUE THREAD

**Issue by hangsman** [MCSManager/MCSManager#676]
**操作系统版本**
centos 8
**面板版本**
9.4.5

**出现概率**
100%

**BUG 详情描述**
解压zip文件会出现大部分文件没有解压出来，再次解压时显示超过最大解压任务
![Snipaste_2022-06-25_18-18-56](https://user-images.githubusercontent.com/57695975/175769364-958c2fe8-cd22-4426-8b6c-4f114b12e5e9.png)

**复现步骤**
上传zip文件 解压文件夹

**Comment by Suwings** [comment]
已知情，正在修复。

**Comment by unitwk** [comment]
此问题应该已经得到解决：https://github.com/MCSManager/MCSManager/releases/tag/v9.5.0
