### ISSUE TITLE
[Bug Report] Bungeecord 服务端启动后不接收网页端控制台输入

### ISSUE THREAD

**Issue by wifi-left** [MCSManager/MCSManager#677]
**操作系统版本**
Windows Server 2019
**面板版本**
## 面板版本
9.4.2
## 对应守护进程版本
1.5.2

**出现概率**
100%

**BUG 详情描述**
使用 Bungeecord 端，网页端控制台输入命令后无反应（任何信息都没有），但能接收输出。
注：直接在系统上启动 cmd 输入` java -jar xx.jar` 启动的服务端，可以接收输入，并且有相关描述。

**复现步骤**
1. 下载 bungeecord 以及其依赖
2. 网页端配置使用 `java -jar bungeecord.jar` 启动
3. 网页端启动服务器
4. 网页端控制台无法接收输入

本人描述能力有限，看到更新日志里没有与此相关的内容，所以提交此问题。

**Comment by huangsijun17** [comment]
麻烦把bungeecord版本、JDK版本给一下。

**Comment by wifi-left** [comment]
> 引用到新

Bungeecord 版本：1644
下载：https://ci.md-5.net/job/BungeeCord/1644/
JDK版本：
```
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
```

**Comment by wifi-left** [comment]
> 试一下这样的启动命令：
> 
> `java -Djline.terminal=jline.UnsupportedTerminal -jar bungeecord.jar`

谢谢，解决了
