### ISSUE TITLE
[Bug Report] BDS-1.19版本在面板运行执行中文指令乱码

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#679]
**操作系统版本**
Windows Server 2019 Datacenter 10.0.17763
**面板版本**
9.4.5

**出现概率**
100%

**BUG 详情描述**
在"Windows 10 专业版 21H2"以及"windows server 2019"上面运行1.19的BDS，只要是在面板下运行，中文命令全部会乱码。
不管是加载LL，还是设置代码页，或者是注入DLL设置代码页，设置面板输入流编码为UTF-8、GBK、GB2312、UTF-16均无效
现在已经给mojang提issues，估计一时半会解决不了。（估计不会解决）
如果直接在cmd里面打开1.19的BDS，那么就没有这个问题，mojang的这个BUG只针对面板。

参考：https://www.minebbs.com/resources/base64.4244/

**复现步骤**
1.运行1.19以上版本的BDS
2.在面板控制台输入say 测试
3.查看客户端反馈

https://s1.328888.xyz/2022/07/03/LidE.jpg

**Comment by Suwings** [comment]
> 设置面板输入流编码为UTF-8、GBK、GB2312、UTF-16均无效

乱码不一定时输入流的问题，大部分时输出流编码问题，你两个选项是否都有设置成 gbk 或者输入是 utf8 输出是 gbk 之类的？
可以尝试一下。

**Comment by XiaoXiaoYang233** [comment]
> > 设置面板输入流编码为UTF-8、GBK、GB2312、UTF-16均无效
> 
> 乱码不一定时输入流的问题，大部分时输出流编码问题，你两个选项是否都有设置成 gbk 或者输入是 utf8 输出是 gbk 之类的？ 可以尝试一下。

1.18的时候设置utf-8是完全正常的，1.19由于mojang改了编码所以会乱码，但是在cmd运行就没这问题，各种编码都试了

**Comment by huangsijun17** [comment]
> 1.18的时候设置utf-8是完全正常的，1.19由于mojang改了编码所以会乱码，但是在cmd运行就没这问题，各种编码都试了
 
1.19默认开启了高级控制台的关系，请在MCDR的config.yml里找到 `advanced_console: true` 并修改为 `advanced_console: false`

参见：
https://docs.mcsmanager.com/#/tutorial/mcdr
https://github.com/MCSManager/MCSManager/issues/588#issuecomment-1173364504

**Comment by XiaoXiaoYang233** [comment]
> config.yml

bds没有吧，我整个端都搜索了一遍没找到

**Comment by Suwings** [comment]
> > 1.18的时候设置utf-8是完全正常的，1.19由于mojang改了编码所以会乱码，但是在cmd运行就没这问题，各种编码都试了
> 
> 1.19默认开启了高级控制台的关系，请在MCDR的config.yml里找到 `advanced_console: true` 并修改为 `advanced_console: false`
> 
> 参见： https://docs.mcsmanager.com/#/tutorial/mcdr [#588 (comment)](https://github.com/MCSManager/MCSManager/issues/588#issuecomment-1173364504)

人家说的是 BDS，你给他发 MCDR 的配置做什么？

**Comment by huangsijun17** [comment]
> > > 1.18的时候设置utf-8是完全正常的，1.19由于mojang改了编码所以会乱码，但是在cmd运行就没这问题，各种编码都试了
> > 
> > 
> > 1.19默认开启了高级控制台的关系，请在MCDR的config.yml里找到 `advanced_console: true` 并修改为 `advanced_console: false`
> > 参见： https://docs.mcsmanager.com/#/tutorial/mcdr [#588 (comment)](https://github.com/MCSManager/MCSManager/issues/588#issuecomment-1173364504)
> 
> 人家说的是 BDS，你给他发 MCDR 的配置做什么？

看错了。

**Comment by Suwings** [comment]
@XiaoXiaoYang233 不执行 `say 你好` 这种命令，而是只是来自服务器自主的发出中文的信息的情况下，依然会乱码吗？

比如服务器里面的某位玩家说了中文，显示在面板终端的文本依然乱码？可以尝试更改面板的输出流（不是输入流）编码来进行尝试。

如果还是没用，那我也不清楚这是为何。

**Comment by Suwings** [comment]
我看了你在 Minebbs 写的内容，你说在 cmd 中的中文是正常的，我认为就算现在无法解决这个乱码问题，在我们的新项目研发成功之后，这个问题应该也会一起解决。

新项目，感兴趣可以给个 star：https://github.com/MCSManager/pty

**Comment by XiaoXiaoYang233** [comment]
> @XiaoXiaoYang233 不执行 `say 你好` 这种命令，而是只是来自服务器自主的发出中文的信息的情况下，依然会乱码吗？
> 
> 比如服务器里面的某位玩家说了中文，显示在面板终端的文本依然乱码？可以尝试更改面板的输出流（不是输入流）编码来进行尝试。
> 
> 如果还是没用，那我也不清楚这是为何。

不会

**Comment by XiaoXiaoYang233** [comment]
> @XiaoXiaoYang233 不执行 `say 你好` 这种命令，而是只是来自服务器自主的发出中文的信息的情况下，依然会乱码吗？
> 
> 比如服务器里面的某位玩家说了中文，显示在面板终端的文本依然乱码？可以尝试更改面板的输出流（不是输入流）编码来进行尝试。
> 
> 如果还是没用，那我也不清楚这是为何。

只有输入才会，这导致我使用面板封禁玩家填写封禁原因乱码

**Comment by XiaoXiaoYang233** [comment]
> 我看了你在 Minebbs 写的内容，你说在 cmd 中的中文是正常的，我认为就算现在无法解决这个乱码问题，在我们的新项目研发成功之后，这个问题应该也会一起解决。
> 
> 新项目，感兴趣可以给个 star：https://github.com/MCSManager/pty

好的，已给

**Comment by lss233** [comment]
设置面板输入流编码的问题可能和 MCSManager/Daemon#25 有关，之前使用的时候发现修改输出编码就可以，但是输出的内容就乱码了。
