### ISSUE TITLE
[Bug Report] openssl版本不同报错

### ISSUE THREAD

**Issue by cym31153** [MCSManager/MCSManager#680]
**操作系统版本**
Ubuntu 22.04 LTS
或者是15-Ubuntu SMP Fri Jun 10 12:18:08 UTC 2022 5.15.0-1011-oracle

**面板版本**9.4.5

**出现概率**高

**BUG 详情描述**
Ubuntu 22.04默认openssl版本是3.0，导致无法启动实例
直接运行会提示./bedrock_server: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**复现步骤**
按照https://docs.mcsmanager.com/#/tutorial/ubuntu_bds安装，提示
![image](https://user-images.githubusercontent.com/63576755/177094812-104bc5f3-7282-4d24-a399-d0039c959152.png)
在shell中运行，提示./bedrock_server: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

大佬，能在面板中集成一个自动安装openssl1.1的功能吗

**Comment by cym31153** [comment]
https://askubuntu.com/questions/1408702/minecraft-bedrock-dedicated-server-libssl-library-error
我从这里看到的，是真的吗

**Comment by Suwings** [comment]
最新的代码已经修复这个问题，但是还没有发布，下个版本发布之后就会修复这个问题，如果你现在想要解决这个问题，可以前往构建Docker镜像的时候自定义里面的 Dockerfile 内容。

内容如下：

```
FROM ubuntu:18.04
ENV TZ=Asia/Shanghai
RUN mkdir -p /workspace
RUN apt -y update && apt -y install openssl && DEBIAN_FRONTEND="noninteractive" apt -y install tzdata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
WORKDIR /workspace
```
