### ISSUE TITLE
[Bug Report] XXXXXXX

### ISSUE THREAD

**Issue by SuYueQiuLiang** [MCSManager/MCSManager#681]
**操作系统版本**
ubantu 20
**面板版本**
1.3.0升级到1.5.5后

**出现概率**
100%？

**BUG 详情描述**
无法正常启动，手动用node app.js启动后报错缺少依赖axios，手动npm install axios后可以正常启动

**复现步骤**
一键安装脚本安装1.3.0后升级到1.5.5

**Comment by Suwings** [comment]
这个确实需要手动执行一次 npm install，下次更新新增依赖库的时候，我会额外说明这种情况。
