### ISSUE TITLE
[Bug Report] 文件解压错误

### ISSUE THREAD

**Issue by cym31153** [MCSManager/MCSManager#682]
**操作系统版本**Ubuntu22.04

**面板版本**9.4.5

**出现概率**未知

**BUG 详情描述**
大佬们，为什么我按照步骤操作但是解压出来的文件不对
![image](https://user-images.githubusercontent.com/63576755/177732371-f619919c-f14f-47e4-b81e-41b5ab0ee98e.png)
这个是正常部署的样子
![image](https://user-images.githubusercontent.com/63576755/177732454-a25c9d86-a727-4dae-92b9-1af60e1adcb0.png)
文件也是正常的

但是我部署出来却是这样
![image](https://user-images.githubusercontent.com/63576755/177732597-6b2f5053-6b0c-4689-bda3-a65067668a9f.png)

刚刚装面板的时候是正常的，然后我就是安装了一个unzip和openssl1.1，就无法正常解压文件了
有没有大佬知道是为什么

**复现步骤**
刚刚装面板的时候部署是正常的
然后（由于openssl版本不同）报错，我不知道为什么，我就安装官方的步骤做，发现unzip没有安装，就安装了unzip
然后了解到openssl版本不同的问题，就装了一个openssl
就无法正常解压文件了
有没有大佬知道是为什么

**Comment by cym31153** [comment]
但是手动用unzip解压是可以的
可能是面板的bug？

**Comment by cym31153** [comment]
大佬们，现在面板都无法访问了，怎么办

**Comment by cym31153** [comment]
这。。。
这个项目不会要占用很多资源吧
是不是我运行的实例太多了

**Comment by huangsijun17** [comment]
1. 运行出现问题，不一定是BUG，请不要滥用BUG面板。
2. 解压需要时间，请等待前一个任务完成后再行解压。
3. Issues不是聊天平台，Issues支持编辑，请不要滥用Issue。
4. 一般运行问题可以添加QQ群询问，[【MCSManager 面板用户群】](https://jq.qq.com/?_wv=1027&k=ElInwSpC)。
