### ISSUE TITLE
[Bug] 自动关服，服务器运行10小时左右自动关服

### ISSUE THREAD

**Issue by wykwey** [MCSManager/MCSManager#683]
**操作系统版本**
centos 7

面板版本
9.4.4
守护进程版本
1.5.4

**出现概率**
极大

**BUG 详情描述**
在服务器运行大约十小时左右，会出现服务器自动关闭
无报错，无现象
已经排除BT面板干扰（据隔壁大佬说宝塔影响）
**复现步骤**
长时间运行服务器

**Comment by Suwings** [comment]
面板从没有人报告这种情况，在代码中也不应该出现这种情况。

建议从其他因素开始考虑，比如内存不足？MC服插件之类的。

**Comment by wykwey** [comment]
> 面板从没有人报告这种情况，在代码中也不应该出现这种情况。
> 
> 建议从其他因素开始考虑，比如内存不足？MC服插件之类的。
内存我想Linux系统配置1g是够的，服务器配置3g但是基本没人玩（哭）也应该是够的

**Comment by wykwey** [comment]
更正四点左右关机

**Comment by wykwey** [comment]
> 面板从没有人报告这种情况，在代码中也不应该出现这种情况。
> 
> 建议从其他因素开始考虑，比如内存不足？MC服插件之类的。

晚上四点准时关服，但是创建的第二个服务器没有这种情况

**Comment by Suwings** [comment]
应该不是面板的问题，我想不到什么原因

**Comment by nkxingxh** [comment]
进程直接就结束了？

**Comment by wykwey** [comment]
> 进程直接就结束了？

每次就像输入关服指令一样

**Comment by wykwey** [comment]
> 建议排除：
> 
> 1. MC插件的自动重启（自动关闭+启动脚本实现重启）。
> 2. 第三方程序使用MCSM的API重启实例。

最有可能的是cmi插件和服务器自己（不过好像都没这个功能）
服务器仅运行mcsm

**Comment by wykwey** [comment]
服务器自己的问题

**Comment by ApartTUSITU** [comment]
e，每一个人说在点子上，我觉得是有人搞恶作剧给实例加了一个计划任务
