### ISSUE TITLE
[Bug Report] 终端信息最下面被挡了一行

### ISSUE THREAD

**Issue by zeruns** [MCSManager/MCSManager#689]
**操作系统版本**
centos7
**面板版本**
9.5

**出现概率**
100%

**BUG 详情描述**
终端显示的信息最下面那被一条东西挡住了一行，如下图所示

![imagebf1ce7cf455b86e5.png](https://tc.zeruns.tech/images/2022/07/19/imagebf1ce7cf455b86e5.png)

**Comment by Suwings** [comment]
左侧的【实例设置】里面有个终端高度设置，更改那个高度解决这个问题
