### ISSUE TITLE
[Bug Report] 禁封用户bug

### ISSUE THREAD

**Issue by SteveCodeFox** [MCSManager/MCSManager#691]
**操作系统版本**
Windows10 21H2
**面板版本**
9.5.0

**出现概率**
百分百

**BUG 详情描述**
永久显示
网页无法正确运作
无法获取身份数据，网页所有功能将全部不可用，请立刻刷新网页或重新登录

**复现步骤**
复现视频
https://8766.lanzouv.com/iVsXD08668ze 密码:1234

**Comment by unitwk** [comment]
谢谢你的视频提供！我已经清楚原因，原因是使用禁封帐号登录之后，服务器已经记住你的浏览器是这个封禁账号，此时你的重复登录是无效的，所以你就一直无法进入面板。

解决方案：清除浏览器Cookie或重启面板。

我们将在下个版本解决这个BUG。

**Comment by ZSXB2468** [comment]
好家伙，害得我直接重启面板了🤣

**Comment by unitwk** [comment]
开发版本已修复此问题，待 9.6.0 发布之后，即可看见效果。
