### ISSUE TITLE
[Bug Report] iOS无法使用文件上传功能

### ISSUE THREAD

**Issue by engsr6982** [MCSManager/MCSManager#692]
**操作系统版本**
Windows Server 2012 R2 Datacenter 6.3.9600
**面板版本**
9.4和9.5

**出现概率**
100%

**BUG 详情描述**
两台设备系统分别为iOS13.6和iOS14.2
测试了Safari浏览器、Chrome浏览器、Edge浏览器、Gear浏览器 文件上传功能均无反应
MCSManager9.4和9.5都不可用，之前可以

**Comment by unitwk** [comment]
确认存在，原因暂时不清楚。已加入迭代线，日后将修复。谢谢你的反馈！

**Comment by engsr6982** [comment]
> 确认将存在，因为您今天已经加入！线，之后。恢复回复
Safari浏览器文件下载无反应，Chrome浏览器点下载是在线预览
系统iOS13.6    文件是服务端日志（.csv格式）
系统环境和上面一样

**Comment by engsr6982** [comment]
实际测试后，下载功能好像也不行，7z压缩包大小386Mb，Safari无反应，Chrome秒下载，但文件只有69字节，zip同样

**Comment by unitwk** [comment]
> 实际测试后，下载功能好像也不行，7z压缩包大小386Mb，Safari无反应，Chrome秒下载，但文件只有69字节，zip同样

是 iphone 的chrome吧？

**Comment by engsr6982** [comment]
是的

**Comment by unitwk** [comment]
开发版本已修复此问题，待 9.6.0 发布之后，即可看见效果。
