### ISSUE TITLE
[Bug Report] 执行指令时玩家名称颜色显示错误

### ISSUE THREAD

**Issue by lightumcc** [MCSManager/MCSManager#694]
**操作系统版本**
#1 SMP Debian 4.19.208-1 (2021-09-29) 4.19.0-18-amd64
**面板版本**
9.5.0

**出现概率**
80%

**BUG 详情描述**
执行指令的时候，出现名字颜色显示错误
<img width="448" alt="image" src="https://user-images.githubusercontent.com/60721270/180712324-5b1d978a-7921-48d8-9bde-d88ae8057af6.png">

**复现步骤**
在游戏内输入任何一个指令

**Comment by lightumcc** [comment]
我不确定是否是我的名字使面板出现了故障

**Comment by unitwk** [comment]
关闭前端自带的颜色渲染，在【实例设置】，【颜色渲染】选项界面。

**Comment by unitwk** [comment]
这种前端颜色渲染机制有一定的错误率，这个暂时无法避免，以后可寻找代替方案。

**Comment by lightumcc** [comment]
感谢您的回复，已解决
