### ISSUE TITLE
[Bug Report] 直接在仿真终端内输入的指令不会进入命令历史

### ISSUE THREAD

**Issue by lightumcc** [MCSManager/MCSManager#695]
**操作系统版本**
#1 SMP Debian 4.19.208-1 (2021-09-29) 4.19.0-18-amd64
**面板版本**
9.5.0

**出现概率**
100%

**BUG 详情描述**
直接在仿真终端内输入的指令不会进入命令历史
<img width="865" alt="image" src="https://user-images.githubusercontent.com/60721270/180712746-e4de8ed1-15ef-49ce-a80d-812e52f3c293.png">
<img width="246" alt="image" src="https://user-images.githubusercontent.com/60721270/180712771-3a7ea65c-f486-428f-a854-26ccc7dc19f7.png">

**复现步骤**
在命令栏和仿真终端内分别输入命令，检查命令历史

**Comment by unitwk** [comment]
好的，这确实是一个BUG，下版本修复或尝试使用其他代替方案。

**Comment by lightumcc** [comment]
感谢您的回复

**Comment by nkxingxh** [comment]
感觉这个比较难判断吧，比如用户在仿真终端中使用vim

**Comment by unitwk** [comment]
> 感觉这个比较难判断吧，比如用户在仿真终端中使用vim，那会不会把用户编辑的某一行内容识别为命令

会，如果做那就是基于回车来做命令结尾。

**Comment by unitwk** [comment]
原本计划修复，修复过程中发现成本较高，主要是要排除掉 tab ，退格，换行等按键的过滤操作，还有快捷键。

所以仿真终端你还是按上下方向键来查看历史吧，大部分程序应该都支持这个功能。

底下的命令历史以后可以考虑换个别的东西显示。
