### ISSUE TITLE
[Feature Request] 建议增加FTP服务器管理器

### ISSUE THREAD

**Issue by zeruns** [MCSManager/MCSManager#697]
**想法/建议**
建议增加FTP服务器管理器，在创建用户时可以同步创建一个FTP账号，并且分配实例给用户时这个实例的目录权限也给到这个FTP账号，方便用户通过FTP来管理服务端的文件。

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
60

**Comment by 123485k** [comment]
+1，确实需要这个功能

**Comment by KagurazakaNyaa** [comment]
我记得ftp服务器在早期版本是有的，后来因为安全问题不再使用了

**Comment by huangsijun17** [comment]
FTP的安全性、确定性等等都太差了在MCSM8中删除的功能，不予考虑。

**Comment by unitwk** [comment]
已经2022年了，就不要再说FTP这种东西了，用户为了上传文件还去下载一个客户端的时代，应该早就不存在的。

**Comment by cainiaoyizhou** [comment]
如果需要可以同时安装小皮面板
