### ISSUE TITLE
[Feature Request] 是否可以将集成终端用xterm.js+node-pty实现

### ISSUE THREAD

**Issue by 123485k** [MCSManager/MCSManager#698]
**想法/建议**
使用xterm.js+node-pty实现集成终端，可以基于页面动态调整终端大小，现在仿真终端模式在手机上的表现不佳，无法动态调整造成了很大的麻烦

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
30

**Comment by 123485k** [comment]
这套组合被用于vscode的集成终端，以及多个web-shell项目。

**Comment by unitwk** [comment]
**Pty-node 构建所需依赖：**

Linux/Ubuntu
sudo apt install -y make python build-essential
The following are also needed:

Node.JS 10+
macOS
Xcode is needed to compile the sources, this can be installed from the App Store.

Windows
npm install requires some tools to be present in the system like Python and C++ compiler. Windows users can easily install them by running the following command in PowerShell as administrator. For more information see https://github.com/felixrieseberg/windows-build-tools:

npm install --global --production windows-build-tools
The following are also needed:

[Windows SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk) - only the "Desktop C++ Apps" components are needed to be installed
Node.JS 10+


**MCSM9.6.0 现有Pty方案依赖：**

0 个

**Comment by unitwk** [comment]
> 可以基于页面动态调整终端大小，现在仿真终端模式在手机上的表现不佳，无法动态调整造成了很大的麻烦

使用了 Node-pty 也无法避免这个情况。你想象一个3个人访问同一个实例的时候，高度和宽度是无法动态决定的，因为这三个人中有可能是平板，有可能是手机，有可能是电脑，那么你应该用谁的宽度作为标准宽度？

现有的 Pty 程序并不是不支持动态调整大小，而是无法解决一对多的情况。

**Comment by 123485k** [comment]
> > 可以基于页面动态调整终端大小，现在仿真终端模式在手机上的表现不佳，无法动态调整造成了很大的麻烦
> 
> 使用了 Node-pty 也无法避免这个情况。你想象一个3个人访问同一个实例的时候，高度和宽度是无法动态决定的，因为这三个人中有可能是平板，有可能是手机，有可能是电脑，那么你应该用谁的宽度作为标准宽度？
> 
> 现有的 Pty 程序并不是不支持动态调整大小，而是无法解决一对多的情况。

可以学习tmux，再多个终端访问的时候取最小的尺寸宽度

**Comment by 123485k** [comment]
就像这样，两个终端同时访问tmux会话时且大小不同，tmux会将会话调整为最小的终端大小
![IMG_20220727_115730](https://user-images.githubusercontent.com/45510011/181157907-fa9a039c-3b25-4f9a-9556-921b41f8b051.jpg)
![Screenshot_2022-07-27-11-57-20-885_org connectbot](https://user-images.githubusercontent.com/45510011/181157998-a600abfd-3010-4842-acc5-3f40abd939cb.jpg)

**Comment by 123485k** [comment]
是我对需求描述不准确了，我重开一个issue说的更清楚吧
