### ISSUE TITLE
[Bug Report] 1.5.4无法正常更新

### ISSUE THREAD

**Issue by cainiaoyizhou** [MCSManager/MCSManager#699]
**操作系统版本**
ubuntu20.04
**面板版本**
1.5.4更新到1.6.0

**出现概率**
100%

**BUG 详情描述**
输入git pull后无法启动面板，
具体报错：
![image](https://user-images.githubusercontent.com/103909046/181160209-a183d88a-1233-4d53-bd67-0696220adba2.png)

已尝试npm install 无果

**复现步骤**
在1.5.4版本在web和daemon文件夹下输入git pull更新面板

###### 注：我已手动备份数据后重装面板成功

**Comment by unitwk** [comment]
理论上应该就是执行 npm install 即可。你这个错误很明显是缺少依赖库，既然你已经解决了，可能只是偶尔事件，

**Comment by cainiaoyizhou** [comment]
但是我反复用快照试了6次，都是这个情况，npm后相同报错
