### ISSUE TITLE
[Feature Request] 仿真终端自动调整以及添加虚拟按键

### ISSUE THREAD

**Issue by 123485k** [MCSManager/MCSManager#700]
**面板版本**
9.5.0

**想法/建议**
1.仿真终端是否可以根据页面情况自动调整，在多人以不同尺寸访问终端的时候pty大小以最小的为准（参考tmux/screen的处理方式)
2.添加诸如tab ctrl alt esc 上下左右等键盘虚拟按键，方便移动设备使用仿真终端

**您认为这个想法/建议在每100人中会有多少人遇到/使用**

**Comment by unitwk** [comment]
第二点 `添加诸如tab ctrl alt esc 上下左右等键盘虚拟按键，方便移动设备使用仿真终端` 可以考虑。

第一点 取最小窗口最为终端高宽，程序设计较为复杂和并且还需要特殊处理，固定高宽直接且开发简单，而且也兼容手机端和PC端，就不考虑其他方案了。

**Comment by 123485k** [comment]
自己尝试实现动态终端大小的时候发现pty重构了，没有动态调整大小的功能了，悲伤

**Comment by unitwk** [comment]
原本就不打算做那么复杂，最简单的方案有时候都是是最好的～

**Comment by zijiren233** [comment]
您可以继续使用旧版本pty，但旧版本已不在维护
