### ISSUE TITLE
[Bug Report] 强制关闭无法终止java进程(TEST)

### ISSUE THREAD

**Issue by srlss123** [MCSManager/MCSManager#701]
**操作系统版本**
CentOS 7.9.2009 x86_64(Py3.7.9)
**面板版本**
前端 1.6.0
后端 1.6.0

**出现概率**
一直

**BUG 详情描述**
当你使用 “强制终止进程” 面板端显示已经关闭实例，但后台top中可以看到java进程并未结束。
面板中点击启动后，会提示端口占用，这个时候只能使用kill来杀死。

**复现步骤**
1.打开服务端
2.使用强制终止
3.java进程还在

**Comment by unitwk** [comment]
开发版本已修复此问题，待 9.6.0 发布之后，即可看见效果。
