### ISSUE TITLE
[Bug Report] 启用仿真终端后无法通过设置的^c关闭实例

### ISSUE THREAD

**Issue by nkxingxh** [MCSManager/MCSManager#702]
**操作系统版本**
Rocky 8.5 (Green Obsidian) x86_64

**面板版本**
9.5.0

**守护进程版本**
1.6.0

**出现概率**
100%

**BUG 详情描述**
通用控制台程序，启用仿真终端，将关闭命令设置为 ^c ，无法使用 **关闭实例** 按钮关闭。只能在终端内按 Ctrl+C

**复现步骤**
同上

**Comment by unitwk** [comment]
这不算bug，只是尚未支持。
