### ISSUE TITLE
[Bug Report] 面板中实例部分日期格式不正确

### ISSUE THREAD

**Issue by Hi-awaBlack** [MCSManager/MCSManager#703]
**操作系统版本**
Linux CentOS 7.6.1810 (Core)
**面板版本**
Linux CentOS 7.6.1810 (Core)
**出现概率**
100%
**BUG 详情描述**
面板实例中启动时间/创建日期/最后启动的日期格式均为 mm/dd/yyyy，与到期时间的 yyyy/mm/dd 不符，影响美观（恼
![image](https://user-images.githubusercontent.com/63138378/181728027-4fd75fb9-9c5c-4272-8fb2-6e84a2500198.png)

**复现步骤**
控制面板 / 应用实例 / 任意一个实例 / 详细信息

**Comment by unitwk** [comment]
好的，确认问题存在，下两个迭代应该会修复。

**Comment by unitwk** [comment]
开发版本已修复此问题，待 9.6.0 发布之后，即可看见效果。
