### ISSUE TITLE
[Feature Request] 允许编辑已有的计划任务

### ISSUE THREAD

**Issue by lightumcc** [MCSManager/MCSManager#706]
**面板版本**
9.5.0

**想法/建议**
如题，因为我有时候需要更改一些已有的任务来适应服务器当前的情况。虽然重新开一个任务花不了多少时间，但是我认为如果只需要修改一个时间或因错误设置的一个命令，有一个修改按钮会更好

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
50

**Comment by unitwk** [comment]
定时任务一旦启动，就无法重设时间，这才是不支持编辑根本原因。

只能支持删除和新增，就算使用编辑功能也是这两个功能的结合实现，没有必要。

**Comment by lightumcc** [comment]
好的明白了
