### ISSUE TITLE
[Bug Report] 不能在github codespaces中顺利使用

### ISSUE THREAD

**Issue by F-Unction** [MCSManager/MCSManager#707]
**操作系统版本**
`#91~18.04.1-Ubuntu SMP Thu Jun 23 20:33:05 UTC 2022 5.4.0-1086-azure`

**面板版本**
`9.4.5`

**出现概率**
`100%`

**BUG 详情描述**
使用github codespaces作为守护进程服务器时 进入实例控制台将会无法连接并得到提示:
>浏览器无法连接到 wss://username-codespace-codespaceid-webport.githubpreview.dev:daemonport
>
>可能是您未开放守护进程的端口导致，或是使用了内网地址的缘故

**复现步骤**
虽然这样有点不道德 但是本人试图用github codespaces开服务器

使用网页版github codespaces的Port Forward功能映射面板端口 会得到url:`https://username-codespace-codespaceid-webport.githubpreview.dev/`

这个url可以正常打开并进入面板

守护进程的地址直接填写`localhost` 提示可以正常连接 但是不能进入实例控制台 提示如上

提示下还有三个可能的解决方案 但是看那个url格式 我觉得好像没法做到

**Comment by unitwk** [comment]
可能不支持吧，或者不支持 Websocket，具体你自己试试吧。

**Comment by F-Unction** [comment]
确实是不支持ws 我在想有没有什么方法把那个ws链接换成codespace的链接




------------------ 原始邮件 ------------------
From: Unitwk ***@***.***&gt;
发送时间: 08/06/2022, 09:32
To: MCSManager/MCSManager ***@***.***&gt;
抄送: 类C语言是一家 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Reply:[MCSManager/MCSManager] [Bug Report] 不能在github codespaces中顺利使用 (Issue #707)





 
可能不支持吧，或者不支持 Websocket，具体你自己试试吧。
