### ISSUE TITLE
[Feature Request] service配置文件自动生成

### ISSUE THREAD

**Issue by F-Unction** [MCSManager/MCSManager#708]
**面板版本**
`9.4.5`

**想法/建议**
linux安装脚本自动识别该系统使用service还是systemctl 并自动生成对应的配置文件

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
10+

**Comment by huangsijun17** [comment]
我在重写安装脚本，可以区别是init.d还是systemd管理服务。但似乎并不能生成init.d的配置文件。（貌似要自己写deamon等等）
咕咕咕~
