### ISSUE TITLE
[Bug Report] Rust 遊戲伺服器 無法顯示並且無法輸入中文項目

### ISSUE THREAD

**Issue by TW527E** [MCSManager/MCSManager#709]
**操作系统版本**
Windows 10 Pro 10.0.19044
**面板版本**
9.5.0

**出现概率**
100%

**BUG 详情描述**
Rust 遊戲伺服器 無法顯示並且無法輸入中文項目

**复现步骤**
使用仿真終端，編碼選擇 UTF8
所有出現中文的地方通通變為亂碼

**Comment by unitwk** [comment]
下版本会优化这个编码错误的情况，谢谢反馈。

你可以尝试关闭仿真终端试试。

**Comment by zijiren233** [comment]
经过测试发现使用原始启生方式输入中文同样会导致乱码
可能是rust服务器控制台本身不支持中文输入

**Comment by TW527E** [comment]
(話說無法顯示是指 無法顯示中文項目qwq

**Comment by zijiren233** [comment]
> (話說無法顯示是指 無法顯示中文項目qwq

使用cmd或者双击启动可以正常显示吗，能否提供仿真终端和原生启动的差异截图

**Comment by TW527E** [comment]
此為 仿真終端，暫時無法提供其他的狀態，因為有人在伺服器裡面遊玩
![image](https://user-images.githubusercontent.com/37478187/184469792-ccf61669-275a-4ce0-b052-e021263b9d84.png)

**Comment by zijiren233** [comment]
> 此為 仿真終端，暫時無法提供其他的狀態，因為有人在伺服器裡面遊玩 ![image](https://user-images.githubusercontent.com/37478187/184469792-ccf61669-275a-4ce0-b052-e021263b9d84.png)

我测试是使用的bat脚本调用cmd启动的，发现真正的终端中文也是乱码，而cmd却没有乱码。也有可能我测试平台是win11的缘故
尝试一下设置编码为GBK能否暂时解决

**Comment by zijiren233** [comment]
![image](https://user-images.githubusercontent.com/84728412/184470130-dd5b878e-5029-465e-82e2-e26356ee0b9c.png)
这是我测试时候的截图

**Comment by TW527E** [comment]
所以? 我要試試看用 cmd 來調用伺服器?

**Comment by zijiren233** [comment]
編碼選擇 GBK 试试

**Comment by TW527E** [comment]
GBK 試過了 但是依舊亂碼

**Comment by zijiren233** [comment]
服务器是 big5? 试试big5编码

**Comment by TW527E** [comment]
(都試過了 沒有用

**Comment by zijiren233** [comment]
你可以暂时使用脚本启动服务器解决问题：
在bat文件中第一句写入 chcp 65001
此为设置cmd的编码为UTF8

**Comment by TW527E** [comment]
謝謝 不久後我去試試

**Comment by TW527E** [comment]
谢谢 正常了
![image](https://user-images.githubusercontent.com/37478187/184473680-18206fba-e6b7-4a4d-91a3-fc821e548955.png)

**Comment by unitwk** [comment]
既然已有解决方案，下个版本会对接新版的仿真终端，优化此问题。

**Comment by unitwk** [comment]
开发版本已优化此问题，待 9.6.0 发布之后，即可看见效果。

**Comment by TW527E** [comment]
感謝w
