### ISSUE TITLE
[Bug Report] ARK 生存進化 遊戲伺服器 開啟伺服器時 在伺服器桌面 彈出伺服器窗口 且MCSM無法捕捉終端內容

### ISSUE THREAD

**Issue by TW527E** [MCSManager/MCSManager#710]
**操作系统版本**
Windows 10 Pro 10.0.19044

**面板版本**
9.5.0
 
**出现概率**
100%

**BUG 详情描述**
ARK 生存進化 遊戲伺服器 開啟伺服器時 在伺服器桌面 彈出伺服器窗口 且MCSM無法捕捉終端內容

**复现步骤**
使用仿真終端，在MCSM開啟實例，將在伺服器端桌面彈出伺服器窗口

**Comment by unitwk** [comment]
ARK 生存进化那个窗口不是纯粹的控制台程序，它似乎不是由 cmd.exe 驱动，有点类似于自己写了一个像终端的 Windows 桌面窗口，MCSM一直以来都无法捕捉，这个无法支持。
