### ISSUE TITLE
[Feature Request] 計畫任務

### ISSUE THREAD

**Issue by TW527E** [MCSManager/MCSManager#711]
**面板版本**
9.5.0

**想法/建议**
在 計畫任務 單項規則 多指令 以順序執行 
在 計畫任務 裡面的 任务动作/类型 新增 更新實例 讓每天重啟伺服器時都能自動更新

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
50

**Comment by unitwk** [comment]
谢谢你的意见，我们会考虑的。
