### ISSUE TITLE
[Feature Reques建议给每个实例加一个“记事本”功能

### ISSUE THREAD

**Issue by huangsijun17** [MCSManager/MCSManager#714]
**面板版本**
N.A.

**想法/建议**
我建议给每个实例加一个“记事本”功能，方便手动记录一点东西，管理之间交流等等。

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
80%+

**Comment by unitwk** [comment]
你还是用系统自带的记事本吧。。。

**Comment by unitwk** [comment]
或者用微软的 TODO，这个不是面板的范畴。

**Comment by huangsijun17** [comment]
> 或者用微软的 TODO，这个不是面板的范畴。

这不是拿来记录todo……
内容可能是对于端的详细描述，某些情况的对应方法。记事本的关键是便于多人协作、租赁商留言给腐竹等。
比如在Bungeecord核心那里写加子服的插件清单/设置方法等。在关服回档时，说明进度。等等等等

**Comment by unitwk** [comment]
那你还是找个记事本记吧，或者表格....

**Comment by KagurazakaNyaa** [comment]
> 

直接在服务器文件管理里面写个`README.md`不就好了
