### ISSUE TITLE
[Bug Report] mcsm-daemon.service缺失User条目

### ISSUE THREAD

**Issue by astro-angelfish** [MCSManager/MCSManager#715]
**操作系统版本**
**Operation System Version**
```
Linux kinomccn 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
**面板版本**
**Panel version**
面板v9.5.0
Panel v9.5.0
守护进程v1.9.0
Daemon v1.9.0
**出现概率**
**Probability**
100%

**BUG 详情描述**
**Detailed bug description**
service文件缺失User条目，所有服务端以及面板后端都是以root用户运行，不符合最低权限原则
service file is missing of `user` key. All the server and the daemon is running under the root user. Which is against the lowest permission rule.
如果遇到蠕虫类插件或安全漏洞，将影响整个服务器
If there is a backdoor plugin or any security vulnerability, it would affect the whole server.

**复现步骤**
**Steps to replication**
1. 安装mcsmanager
1. Install MCSManager
2. 启动任意服务器
2. Start any minecraft server
3. 执行`ps aux`指令
3. Perform `ps aux` command in terminal
4. 所有服务端进程都是以root用户运行的
4. You'll found that all the processes of server is running under root.

**Comment by huangsijun17** [comment]
上古问题了，而且你必须**先**手动修改目录的**文件归属权**。

**Comment by unitwk** [comment]
因为不是每个人都拥有Linux的操作知识，为了解决很多人遇到的各种权限问题，有时候使用 root 权限执行程序，是最快速方便的方法。

你说的安全隐患，只要配合上 Docker 就不会有问题，MCSManager 兼容 Docker。

但是这毕竟是治标不治本的方法，后续可以计划增加 MCSM 自定用户。

**Comment by huangsijun17** [comment]
> 因为不是每个人都拥有Linux的操作知识，为了解决很多人遇到的各种权限问题，有时候使用 root 权限执行程序，是最快速方便的方法。
> 
> 你说的安全隐患，只要配合上 Docker 就不会有问题，MCSManager 兼容 Docker。
> 
> 但是这毕竟是治标不治本的方法，后续可以计划增加 MCSM 自定用户。

容器中运行的进程同样具有访问主机资源的权限(docker 默认并没有对用户进行隔离)，当然一般情况下容器技术会把容器中进程的可见资源封锁在容器中。但是通过我们演示的对数据卷中文件的操作可以看出，一旦容器中的进程有机会访问到宿主机的资源，它的权限和宿主机上用户的权限是一样的。以root启动Docker，安全性也是不足的。
