### ISSUE TITLE
[Bug Report] 命令助手默认附加参数错误

### ISSUE THREAD

**Issue by pa733** [MCSManager/MCSManager#717]
**操作系统版本**
N/A
jdk 17

**面板版本**
latest - 9.5.0

**出现概率**
1

**BUG 详情描述**
命令助手的java“附加参数”中Duser.language和Duser.country参数的值写反了

**复现步骤**
在控制面板-新增实例中打开命令助手
![image](https://user-images.githubusercontent.com/67588574/185130327-12ea38bb-f4ab-416a-9ad5-3d61753fdaac.png)
![image](https://user-images.githubusercontent.com/67588574/185132769-76c9221e-9e48-49e3-a2be-9d180c2a6fbc.png)

**修改建议**
将该处改为：`-Dfile.encoding=UTF-8 -Duser.language=zh -Duser.country=CN`
~~要不是我找不到怎么改，我这会已经交pr了~~

**Comment by huangsijun17** [comment]
https://github.com/MCSManager/UI/blob/c5b754e6947bb903d21e172a0adffcdb043b795c/src/components/CommandAssist.vue#L186

前端的代码，肯定在前端仓库里啊。去改吧。

**Comment by unitwk** [comment]
已合并。谢谢你的贡献
