### ISSUE TITLE
[Feature Request] 给MC实例增加Socks5代理

### ISSUE THREAD

**Issue by Illusionika** [MCSManager/MCSManager#718]
**面板版本**
9.5

**想法/建议**
近期由于众所周知的原因,墙高了.导致mojang、spigot等国外网站难以连上。

而MC本体、插件等都要连接这些网站获取角色数据、插件更新信息等。因为连不上所以疯狂报错，甚至有一些插件甚至会卡主主线程。让我苦不堪言(TMD获取更新获取不到会卡主线程你信？)

正好手上有个自己架的Socks5,试着用 -DsocksProxyHost= -DsocksProxyPort= -Djava.net.socks.username=-Djava.net.socks.password=
这个参数在MC本体上直接接挂,但是失败了.

所以想问问面板上能不能做一个代理功能 

**您认为这个想法/建议在每100人中会有多少人遇到/使用**
国内这些盗版骗氪服是用不到的,但是我这种正版公益服完全依赖这些国外插件简直苦不堪言

**Comment by unitwk** [comment]
你说的是Minecraft客户端的正版信息获取吧？服务器端虽然也有正版获取相关逻辑，不过你说这个代理功能已经超出的管理面板的职责，且此功能需要一定的长期维护费用，收益并不高。

**Comment by Illusionika** [comment]
> 你说的是Minecraft客户端的正版信息获取吧？服务器端虽然也有正版获取相关逻辑，不过你说这个代理功能已经超出的管理面板的职责，且此功能需要一定的长期维护费用，收益并不高。

我的想法是类似火狐扩展的FoxyProxy, 代理站点和要代理目标网址让用户自己填,本身只提供个功能

也想不出什么好的办法,直接用JVM参数不支持用户密码,跑额外的代理程序又太烦了

这个月开始墙高的离谱,MC本身要去mojang,插件要去spigotmc和dev.bukkit,甚至下载libraries的repo.maven.apache.org都连不上了

**Comment by unitwk** [comment]
理解你的想法，但是这个的确不应该属于面板所应该提供的功能，而且开发成本也较高。

这个还是交给专门的代理程序吧来做吧。

**Comment by Illusionika** [comment]
厄厄厄
