### ISSUE TITLE
[Bug Report] 使用面板启动通用控制台程序出现的问题

### ISSUE THREAD

**Issue by Crystal-Moling** [MCSManager/MCSManager#719]
**操作系统版本**
CentOS 7

**面板版本**
9.5.0 - web
1.6.0 - daemon

**BUG 详情描述**
我预想使用面板来启动 SakuraFrp,于是我上传文件(frpc_linux_amd64)并使用命令助手生成了启动命令,但启动后会出现如下错误:
![屏幕截图 2022-08-23 173703](https://user-images.githubusercontent.com/80235192/186129031-f629a6ea-d6ec-4c3f-bd13-5404ec41ec5c.jpg)
需要将高级实例设置中的启动命令修改为 ./frpc_linux_amd64 才能够正常启动

(不确定其他程序是否也会这样,但既然出现了还是提一下)

**Comment by unitwk** [comment]
使用 ./frpc_linux_amd64 命令启动是 Linux 下的正常情况，这不是BUG。
