### ISSUE TITLE
[Bug Report] 面板无法向docker发送终端命令

### ISSUE THREAD

**Issue by Enix-123** [MCSManager/MCSManager#720]
**操作系统版本**
windows 10 Home edition 21H2
docker desktop v4.11.1/wsl2
**面板版本**
9.5.0

**出现概率**
100%

**BUG 详情描述**
在使用docker for windows创建实例运行后无法使用终端发送任何命令（仿真终端无法输入/输入框发送无法执行）
但服务器正常运行
不使用docker则正常
怀疑docker启动时没有用-it

**Comment by unitwk** [comment]
请问下你启动的程序是什么程序？

**Comment by unitwk** [comment]
可能还不能完全支持Docker For Windows 吧。
