### ISSUE TITLE
[Bug Report] Web面板内守护进程无法访问，但直接访问后端地址正常

### ISSUE THREAD

**Issue by MCSeekeri** [MCSManager/MCSManager#721]
**操作系统版本**
Ubuntu 22.04.01
**面板版本**
9.6.0
守护进程版本为2.0.0
**出现概率**
100%
**BUG 详情描述**
当访问穿透出来的守护进程地址时，会提示守护进程离线。浏览器控制台可以看到一个500报错
![image](https://user-images.githubusercontent.com/20928094/187215000-ed15ae54-6be5-4485-80dd-fef5e27cc719.png)
访问之后报错为无法找到请求头

**复现步骤**
在Ubuntu 22.04.1 上安装MCSM。

已经确定是从Github拉取的最新版。nodejs环境正常，守护进程访问正常，内网穿透正常。
也许重新安装可以解决问题，但是我数据备份有点麻烦。

如果需要更多信息我可以提供

**Comment by unitwk** [comment]
500错误的信息就只有“无法找到请求头 x-requested-with: xmlhttprequest”吗？没有其他的了？

应该是穿透导致的情况，我这边不好复现，有空看下

**Comment by MCSeekeri** [comment]
> 500错误的信息就只有“无法找到请求头 x-requested-with: xmlhttprequest”吗？没有其他的了？
> 
> 应该是穿透导致的情况，我这边不好复现，有空看下

我换了一家内网穿透，Argo Tunnel，问题依旧。
精确来讲，在Web端控制台中报错是500，打开对应链接后报错是403
完整的报错是：
`{"status":403,"data":"[Forbidden] 无法找到请求头 x-requested-with: xmlhttprequest","time":1661825725247}`

**Comment by unitwk** [comment]
`打开对应链接后报错是403`这个是正常情况。

麻烦请具体描述 `在Web端控制台中报错是500` 这个情况，给出500的错误信息。


另外，如果没有使用穿透的话，应该是正常访问吧？

**Comment by MCSeekeri** [comment]
![image](https://user-images.githubusercontent.com/20928094/187334736-4377f3a7-a262-48e5-9c85-e06aca8d0522.png)
![image](https://user-images.githubusercontent.com/20928094/187334801-d59fb7bf-0b2d-438e-80d8-5b455caaa467.png)
嗯……大概这样？
不使用穿透的确是正常的……但是换了两家穿透问题依旧就很奇怪……

**Comment by unitwk** [comment]
可以看出你的Web端是开启了HTTPS的，那么你的守护进程（默认24444端口）也是需要开启HTTPS的。

你必须两个程序均可公网正常访问才可以正常运作。

参考：https://docs.mcsmanager.com/#/tutorial/reverse_proxy+ssl

**Comment by MCSeekeri** [comment]
> 可以看出你的Web端是开启了HTTPS的，那么你的守护进程（默认24444端口）也是需要开启HTTPS的。
> 
> 你必须两个程序均可公网正常访问才可以正常运作。
> 
> 参考：https://docs.mcsmanager.com/#/tutorial/reverse_proxy+ssl

![image](https://user-images.githubusercontent.com/20928094/187335811-97ba159d-620e-4474-b309-5c0a6f0807b1.png)
嗯哼…………

**Comment by MCSeekeri** [comment]
仔细检查了下，有件事让我很在意。
理论上应该是浏览器同时访问Web和守护进程，但是看起来即使是选择守护进程时连接的还是Web的地址。
也就是说，Web"代理"了一部分流量，奇怪……我没装nginx或是类似的东西啊……

**Comment by MCSeekeri** [comment]
我这里又出现了这个情况。
真诡异……
