### ISSUE TITLE
版本升级后是不是仿真终端的依赖忘记改了

### ISSUE THREAD

**Issue by Shanwer** [MCSManager/MCSManager#723]
![image](https://user-images.githubusercontent.com/16631550/187879627-48a0dc82-fdc7-460f-a97b-17252856cfb0.png)
如图，刚刚更新了9.6.0，仿真终端启用不了，应该是lib忘改了吧，而且release忘记加win的包了（）

**Comment by unitwk** [comment]
http://oss.duzuii.com/MCSManager

**Comment by unitwk** [comment]
更新了
