### ISSUE TITLE
mcsm对我的服务器文件重拳出击这档子事

### ISSUE THREAD

**Issue by FURONGsun** [MCSManager/MCSManager#725]
# 希望MCSManger的开发组重视这个问题
我们的服务器团队在进行了4个月的重新开发之后，服务器开始正式走上正轨，为了让普通的管理也可以方便的管理群组，我们配置了很久之前就配置好的mcsm面板，进入面板，我首先删除了之前的所有旧实例，然后开始配置新的服务器，突然我发现我的目录全部不见了.
首先我开始排查mount目录挂载情况，再经过了一系列的排查之后，我回忆到了最后一个操作，我删除了一个实例，并且这个实例的文件夹路径与我的服务器新开发的路径重合，均为/home/furong/TEP
我怀着半信半疑的态度重新测试了这个操作，事实证明mcsm会自动删除我的实例，以及对应的目录
可是mcsm既没有在文档中做任何相关说明，在进行操作时也仅仅只是提示：你将删除这个实例
首先，mcsm做完一个进程监控软件，真的有删除路径的必要吗
在我使用过的一切进程监控软件中，你删除了监控项目，也是提示你需要手动清除对应文件夹下目录
从不会出现类似与mcsm的问题
退而求其次的说，即使一定要删除路径，以方便某些对linux不熟悉的人使用，为何不增加一个删除选项：删除路径，并且反复确认这个操作呢？
我很清楚这次灾难的造成是我个人对于mcsm的进程监控的文件操作相关机制不明确导致的，但是我仍然希望mcsm开发团队可以解决这个问题

# 我仍然保留我的气愤
#### 我们在这一个开发项目上面倾注了非常多的心血，我使用mcsm的时间长达1年以上，并且对mcsm的操作都比较的信任，但是这次出现了如此严重的恶性问题，我不对mcsm以后的使用报有任何希望
# 如果我的反馈给mcsm开发组的人带来了不好的情绪，我对此表示歉意，但是我想说的是，我仍然非常气愤

**Comment by FURONGsun** [comment]
或许我的反馈没有遵守应有的反馈流程，但是我现在非常愤怒，请谅解

**Comment by ZSXB2468** [comment]
好像曾经有人提过：
https://github.com/MCSManager/MCSManager/issues/712

**Comment by FURONGsun** [comment]
好的，谢谢你，我现在裂开了，我不知道该如何和我的开发组伙伴解释这个问题，因为在我使用的上一个大版本之前，mcsm并不存在删除目录这个问题

**Comment by ZSXB2468** [comment]
你可以尝试使用文件恢复软件，越快应该能恢复更多

**Comment by FURONGsun** [comment]
感谢你的建议，我已经在尝试对数据进行恢复了，但是我并不熟练

**Comment by ZSXB2468** [comment]
你可以看看这个视频
https://www.bilibili.com/video/BV1gg411F7rp

**Comment by ZSXB2468** [comment]
你可以看看这个视频
https://www.bilibili.com/video/BV1gg411F7rp

**Comment by FURONGsun** [comment]
我已经将磁盘卸载并且以只读方式挂载了，在这中间我造成了几mb的数据覆盖，希望这不会影响到关键内容

**Comment by ZSXB2468** [comment]
加油💪🏼

**Comment by unitwk** [comment]
＞ 我很清楚这次灾难的造成是我个人对于mcsm的进程监控的文件操作相关机制不明确导致的，但是我仍然希望mcsm开发团队可以解决这个问题

误操作确实在所难免，mcsmanager面板也有责任，下个版本将新增删除文件时，有明确警告提示，并且附带5秒内禁止按确定按钮的措施，以防止更多人误操作。

另外，删除实例有两种方式，一个是移除实例，另外一个是删除实例。前者不会删除文件，后者删除文件。
