### ISSUE TITLE
希望添加计划任务复制和编辑功能

### ISSUE THREAD

**Issue by lovemercer** [MCSManager/MCSManager#726]
1:计划任务改错了，只能删除重新添加，希望能编辑

2:当有大量的计划任务创建时，同样需要在其他实列添加对应功能的计划任务，需要一个一个填写，很麻烦，希望添加拷贝计划任务功能

3:我自己去文件夹里改计划任务，刷新并没有添加进去，同样的uid命名和内容更改对应uid，但是在对应实列并没有出现更改后的计划任务，是不是在添加计划任务时候，还声明了什么，能告知一下吗，这样我就可以在TaskConfig文件夹内快速复制自己需要的任务了

**Comment by unitwk** [comment]
目前要做的事情还很多，暂时不考虑优化您所说的这些功能点。

谢谢你的反馈。

**Comment by bddjr** [comment]
（考古）这是好的建议，但关帖速度挺快
