### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by Enderman-Teleporting** [MCSManager/MCSManager#727]
服务器提供商使用的是该项目,在尝试切换了所有的可能编码后,中文依旧输出乱码

**Comment by Enderman-Teleporting** [comment]
我比较忙,应该不会很快回复,我大概一星期来看一次

**Comment by Enderman-Teleporting** [comment]
我在Java启动指令中添加过-Dfile.encoding=utf-8但对控制台并没有用

**Comment by Enderman-Teleporting** [comment]
请问我应该让提供商怎么操作

**Comment by zijiren233** [comment]
mcsmanager v9.5中仿真终端存在部分程序恒定乱码的问题。已在v9.6中修复，或关闭仿真终端并设置编码
