### ISSUE TITLE
NGINX怎么配置二级目录网站?

### ISSUE THREAD

**Issue by Illusionika** [MCSManager/MCSManager#728]
我想把MCSM的控制面板的网站写下域名的二级目录下面

就像 http://主域名/mcsm/  这样来访问网站,但是写完之后打不开网站.一片白

搜issues看到了别人也问过相同的问题,他是直接在server下面写了一条 if ($document_uri ~* '/css|#|img|fonts|api|static|js/.*') {rewrite ^/(.*)$ /mcsm/$1 last; }有效果 ,但是我域名下面有好几个二级目录的网站, 这样写了的话其他网站的css就嗝屁了.不能这么弄
别人的issues[https://github.com/MCSManager/MCSManager/issues/655](url)

写在location /mcsm/ 下面也没效果,请问我该怎么弄?

**Comment by unitwk** [comment]
我没有试过这种场景如何配置，具体还请参考 Nginx 文档来进行尝试吧。

**Comment by bddjr** [comment]
你这样不如搞三级域名稳定，例如 mcsm.domain.com

（考古）
