### ISSUE TITLE
一些BUG

### ISSUE THREAD

**Issue by Illusionika** [MCSManager/MCSManager#730]
刚用一键脚本新装的9.6.0

以第一问题:
网站用nginx反代后无法获得登录用户的真实IP,logs全是127.0.0.1
官方教程上的

>proxy_set_header Host localhost;
 proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header REMOTE-HOST $remote_addr;

已经写了,在外网端口有一层负载均衡,而别的网站能正常获取真实IP

第二个问题:
计划任务里周期任务 星期1到7全勾上,但是实际缺只有2~7 周一没写到配置里,只有2,3,4,5,7,6,注意是2,3,4,5,7,6 不是2,3,4,5,6,7 ,7和6也反了过来

**Comment by unitwk** [comment]
计划任务相关问题下个版本将会优化
