### ISSUE TITLE
[Feature request] Suggest officially provided docker images

### ISSUE THREAD

**Issue by a-wing** [MCSManager/MCSManager#731]
Although has [`Dockerfile` documentation](https://github.com/MCSManager/Documentation/blob/main/tutorial/docker-compose.md#%E7%BC%96%E5%86%99%E4%B8%A4%E4%B8%AA-dockerfile) 

Maybe officially provided docker images will be better

Use github action build every tag https://github.com/docker/build-push-action

Storage at [ghcr.io](ghcr.io) or docker hub

**Comment by unitwk** [comment]
The main focus of our current work is not this. We will consider it later when we have time.

Thank you for your suggestion.

**Comment by LiamSho** [comment]
I have created repo to check MCSM version and build docker image automatically use GitHub Actions.

https://github.com/LiamSho/mcsmanager-image

Hope to be a reference

**Comment by a-wing** [comment]
> I have created repo to check MCSM version and build docker image automatically use GitHub Actions.
> 
> https://github.com/LiamSho/mcsmanager-image

Why not use [docker-build-push](https://github.com/docker/build-push-action) ?
