### ISSUE TITLE
[Bug report]Docker的中文输出异常

### ISSUE THREAD

**Issue by luluxiaoyu** [MCSManager/MCSManager#734]
**Version**
9.60
**System**
windows server2022
**Node Version**
整合版自带node

Windows Docker的中文输出异常  
无论utf8还是gbk的编码 中文都变成了问号输出

**Comment by unitwk** [comment]
开启仿真终端试试

**Comment by luluxiaoyu** [comment]
> 开启仿真终端试试

本来就是开着的 刚试下关掉 也是一样的情况

**Comment by huangsijun17** [comment]
在Docker里运行的什么？如果是JAVA程序，需要添加JAVA参数`-Dfile.encoding=UTF-8`

**Comment by MoeCinnamo** [comment]
看下編碼，以及鏡像是否僅有openjdk+版本號字樣，而不是前面有面板域名的(例如MCSM字樣)

**Comment by Gingmzmzx** [comment]
感谢大佬，更换镜像和添加了-Dfile.encoding=UTF-8之后解决了
