### ISSUE TITLE
请问下 api 密钥在哪里获取了

### ISSUE THREAD

**Issue by graytoowolf** [MCSManager/MCSManager#735]
我用后台访问密钥提示密钥错误。
请问这个东西在哪里能获取到了

apikey: String; // API 密钥

**Comment by stevened7246** [comment]
> 我用后台访问密钥提示密钥错误。 请问这个东西在哪里能获取到了
> 
> apikey: String; // API 密钥

修改用户文件后重启

**Comment by unitwk** [comment]
个人资料界面就有
