### ISSUE TITLE
Release笔记内更新wiki无法访问

### ISSUE THREAD

**Issue by lightumcc** [MCSManager/MCSManager#737]
如题，建议将连接更换为 https://docs.mcsmanager.com/#/tutorial/update_mcsm
现在点release链接进去状况如下图
<img width="1639" alt="image" src="https://user-images.githubusercontent.com/60721270/190657724-1fc4ad6c-75ce-4567-b75a-626f64076844.png">

**Comment by unitwk** [comment]
Thanks, we will fix this in next version.
