### ISSUE TITLE
关于文档说明的改进建议

### ISSUE THREAD

**Issue by Raven-L** [MCSManager/MCSManager#738]
1. 关于数据目录的说明，原文是直接说明data/目录下，但实际是在程序下面，即/opt/mcsmanager/web(或daemon）下，这容易造成误导。最好进行说明。
2. 同样的，一键安装脚本也最好进行对应的说明。或者增加迁移备份数据的功能。

**Comment by unitwk** [comment]
`data/` 和 `/data/` 是完全两种不同的意思，data/ 代表是相对路径，不是从跟目录算起，这个相对路径自然就是你的安装程序路径作为相对路径。

不过你说的可能确实容易造成误解，以后会慢慢改进的。
