### ISSUE TITLE
[Feature request] 語言增加: 增加 繁體中文 (正體中文)

### ISSUE THREAD

**Issue by TW527E** [MCSManager/MCSManager#739]
雖然這個語言並不是必要的，畢竟已經有簡體中文了，但是有繁體中文對於繁體使用者會好非常多，希望可以增加。

**Comment by unitwk** [comment]
语言文件太多会影响后期开发速度，比如新增一行字我便需要新增三种语言，繁体中文和简体中文拥有基本的可读性，暂时先这样吧~

**Comment by MoeCinnamo** [comment]
我認為先開發英文版，然後再自行上傳語言翻譯包作為翻譯會更好些。

**Comment by huangsijun17** [comment]
> 我認為先開發英文版，然後再自行上傳語言翻譯包作為翻譯會更好些。

我之前就建议将语言文件剥离到独立的项目。

**Comment by Mr-Ao-Dragon** [comment]
加一，我建议学mojang把语言交给社区

**Comment by huangsijun17** [comment]
另外，给一个参考案例：
[MultiMC/Launcher](https://github.com/MultiMC/Launcher)的语言文件就在[MultiMC/Translations](https://github.com/MultiMC/Translations)仓库，日常使用[crowdin](https://translate.multimc.org/)提交。
