### ISSUE TITLE
报错无法获取镜像信息，请确保您已正确安装Docker环境

### ISSUE THREAD

**Issue by MoeCinnamo** [MCSManager/MCSManager#741]
**Version**
9.6.0

**System**
Linux Debian 10

**Node Version**
16.17.0

**Problem**
已经成功安装docker，通过systemctl也可以看到docker在正常运行，但是在面板的环境镜像页面则会报错：

无法获取镜像信息，请确保您已正确安装Docker环境

**Comment by unitwk** [comment]
面板使用 Root 权限运行再进行尝试，顺便输入 docker ps 等命令查看 docker 是否正确运行。

**Comment by huangsijun17** [comment]
或者创建docker用户组，并将MCSM的业务用户加入该组。

**Comment by MoeCinnamo** [comment]
> 面板使用 Root 权限运行再进行尝试，顺便输入 docker ps 等命令查看 docker 是否正确运行。

正確運行的，但是可能和我沒用root用戶而是通過www(普通)用戶運行的面板有關。

**Comment by huangsijun17** [comment]
> > 面板使用 Root 权限运行再进行尝试，顺便输入 docker ps 等命令查看 docker 是否正确运行。
> 
> 正確運行的，但是可能和我沒用root用戶而是通過www(普通)用戶運行的面板有關。

www用户必须在docker用户组，或使用sudo，才能使用docker功能。这是docker的限制……
MCSM不支持使用sudo提权运行docker，所以必须将其加入docker用户组才能运行docker。

**Comment by MoeCinnamo** [comment]
问题已经解决，使用www用户是不行的，添加docker用户组比较麻烦，修改守护进程运行用户为root即可。
