### ISSUE TITLE
面板報錯因長時間未驗證身份而斷開

### ISSUE THREAD

**Issue by MoeCinnamo** [MCSManager/MCSManager#743]
**Version**
9.6.0

**System**
Linux Debian 10

**Node Version**
v16.17.0

**Problem**
面板連接守護進程速度緩慢，守護進程報錯會話因長時間未驗證身份而斷開連結
面板則報錯遠程節點已斷開
一般來說，從早晨8點開啟，下午2點連結成功，但是這時間也太長了，也並不穩定。
用域名連結就會出現這樣，多個獨立ip不配置https以及ws://的情況下不會出現這樣的問題。

**Comment by MoeCinnamo** [comment]
還有就是通過域名連結，不配置https的情況下也會出現這種問題。

**Comment by huangsijun17** [comment]
能否在装面板的主机上直接HTTP(S)访问一下后端的主机端口？如果是CLI，使用curl访问即可。看一下能不能获得正确的返回信息。

**Comment by unitwk** [comment]
> 能否在装面板的主机上直接HTTP(S)访问一下后端的主机端口？如果是CLI，使用curl访问即可。看一下能不能获得正确的返回信息。

他說的後端主機端口的意思是，用瀏覽器直接訪問守護進程，看看連接不上的時候能不能訪問到。

**Comment by MoeCinnamo** [comment]
> 能否在装面板的主机上直接HTTP(S)访问一下后端的主机端口？如果是CLI，使用curl访问即可。看一下能不能获得正确的返回信息。

可以的

**Comment by MoeCinnamo** [comment]
> > 能否在装面板的主机上直接HTTP(S)访问一下后端的主机端口？如果是CLI，使用curl访问即可。看一下能不能获得正确的返回信息。
> 
> 他說的後端主機端口的意思是，用瀏覽器直接訪問守護進程，看看連接不上的時候能不能訪問到。

用浏览器直接访问可以显示在线
使用主机curl也可以正常显示状态
只有面板链接速度奇慢(用域名)，用ip就不影响。

**Comment by Shuazijun** [comment]
域名访问慢请检查下你的域名dns服务器跟你的延迟（国内访问最好买阿里或腾讯底下的，dns延迟低）  
间歇性断开授权是SSL默认有Session时间限制，一般为10分钟（宝塔）  
还有就是hsts这个https严格模式，检查这个参数时间，一般为一年。  
Nginx反向代理也有timeout项。  
`ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    add_header Strict-Transport-Security "max-age=31536000";`
反向代理  
`proxy_connect_timeout 30s;
        proxy_read_timeout 86400s;
        proxy_send_timeout 30s;`

**Comment by MoeCinnamo** [comment]
> 域名访问慢请检查下你的域名dns服务器跟你的延迟（国内访问最好买阿里或腾讯底下的，dns延迟低） 间歇性断开授权是SSL默认有Session时间限制，一般为10分钟（宝塔） 还有就是hsts这个https严格模式，检查这个参数时间，一般为一年。 Nginx反向代理也有timeout项
> 
> `ssl_session_cache shared:SSL:10m;` `ssl_session_timeout 10m;` `add_header Strict-Transport-Security "max-age=31536000";` `proxy_connect_timeout 30s;` `proxy_read_timeout 86400s;` `proxy_send_timeout 30s;`

本來就是騰訊的dnspod，ssl的時間限制調成多少最好呢？nginx的timeout項則是120秒。

**Comment by MoeCinnamo** [comment]
沒有回我的嗎？我這個問題真的沒法解決嗎？

**Comment by MoeCinnamo** [comment]
我關掉了ssl和https，通過ws連接，發現是同樣的問題。但是現在完全無法正常使用，因為有固定公網ip的服務器內存不夠，內存夠的沒有固定的公網ip(有公網ip，但是變來變去的，只能用域名連接)，所以現在根本不能正常使用。

**Comment by Shuazijun** [comment]
自测ddns域名长时间挂机是会授权超时，但是刷新下页面就好了

**Comment by MoeCinnamo** [comment]
> 自测ddns域名长时间挂机是会授权超时，但是刷新下页面就好了

大哥，我強制刷新了很多次頁面的唉

**Comment by MoeCinnamo** [comment]
甚至我還重啟了很多次面板，也根本沒有解決問題。

**Comment by MoeCinnamo** [comment]
而且也完全不可能需要等待4個小時才能連上

**Comment by MoeCinnamo** [comment]
這是報錯信息：

面板端：
![746DA0D2-34A6-464E-AE6F-EE35018C4361](https://user-images.githubusercontent.com/101342651/193300259-5d7a6e04-c117-40cc-92e9-a05819f4f3b8.jpeg)

守護進程端：
![B64C2101-A4DE-4EE2-8FC0-E6BCA6E6039F](https://user-images.githubusercontent.com/101342651/193300322-54374fd2-1c8a-41b6-999a-5ca5a0d6a3a6.jpeg)

**Comment by zijiren233** [comment]
是否开启了cdn，大部分cdn是不支持ws长连接的
或者使用了反向代理且设置了tcp连接超时时间太短
也有可能会是网关的限制

**Comment by MoeCinnamo** [comment]
> 是否开启了cdn，大部分cdn是不支持ws长连接的
> 或者使用了反向代理且设置了tcp连接超时时间太短
> 也有可能会是网关的限制

開啟了cdn，玉桂雲加速自營的cdn，但是守護進程沒有用cdn。也沒有反向代理tcp超時時間太短，守護進程我根本沒反向代理。自家公網也不知道有沒有網關限制。

**Comment by MoeCinnamo** [comment]
面板120秒超時，cdn也是這樣，nginx做的cdn我也不明白能不能開ws長連接。但是守護進程沒有反向代理。

**Comment by MoeCinnamo** [comment]
意思就是，只有面板開啟了cdn，守護進程並沒有使用cdn，況且tcp超時時間也並不短，自己家有公網網關限制可以忽略不計。

**Comment by MoeCinnamo** [comment]
算了，我還是開ssl，雖然慢了點，首次連接要4個小時，應該和ddns有關，加上面板對域名作為守護進程的兼容性並不好。

**Comment by zijiren233** [comment]
当面板端开启了https，那么后端必须使用wss

**Comment by MoeCinnamo** [comment]
> 当面板端开启了https，那么后端必须使用wss

是的，前后端都关闭了https也无法连接，都打开也不行

**Comment by MoeCinnamo** [comment]
用域名就连不上

**Comment by bddjr** [comment]
为什么路径后面有个/localhost

**Comment by bddjr** [comment]
> 为什么路径后面有个/localhost

日志本来就这样，那没事了。我这是`/Remote Host`

**Comment by bddjr** [comment]
或许可以通过修改DNS，减少访问等待时间？

域名访问特别慢，但如果IP没事的话，我能想到的就是这个了。
（如果你家支持IPv6，那么你家的电脑通常会访问IPv6的DNS获取解析，请修改IPv6的DNS服务器地址。如果你家只有IPv4，那么请修改IPv4的DNS服务器地址）

**Comment by bddjr** [comment]
从日志上看，似乎在使用内网访问。内网在路由器安全的情况下不需要HTTPS。
（内网真的有必要通过域名访问吗？这个问题或许可以关掉了）
