### ISSUE TITLE
[文件上传] 支持多选文件上传

### ISSUE THREAD

**Issue by engsr6982** [MCSManager/MCSManager#744]
上传3、4个小文件时，在上传选择文件时提供多选文件上传

场景：插件配置文件，10kb不到，3个文件单独上传要反复操作3次，文件不大压缩在上传还需要解压移动

所以能否除单个上传外提供多选文件上传

**Comment by MoeCinnamo** [comment]
這確實能夠更方便。

**Comment by Mr-Ao-Dragon** [comment]
同意，这个确实比较刚需
