### ISSUE TITLE
Safari浏览器无法下载文件

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#745]
**MCSManager Version**
9.6.0
**System Info/Version**
Windows Server 2019 Datacenter 10.0.17763
**Node Version**
v14.15.1
**Step**
iphone/safari浏览器使用文件管理功能无法下载文件

**Comment by MoeCinnamo** [comment]
我這裡測試沒有這個問題，有可能和我是用的iOS 16有關。

**Comment by huangsijun17** [comment]
请更新到最新版本后尝试。

**Comment by engsr6982** [comment]
> 请更新到最新版本后尝试。

此BUG我在之前提交过，当时回复我9.6版本已修复
我测试了一下，iOS13.6不可用 iOS14.2不可用  iOS15.7不可用
此BUG涵盖多个系统版本
序号#692，链接https://github.com/MCSManager/MCSManager/issues/692

**Comment by MoeCinnamo** [comment]
> > 请更新到最新版本后尝试。
> 
> 此BUG我在之前提交过，当时回复我9.6版本已修复 当时提交的是上传问题，后面我回复了下载问题但没有新提交issus 我测试了一下，iOS13.6不可用 iOS14.2不可用 iOS15.7不可用 此BUG涵盖多个系统版本 序号#692，链接#692

目前16以上系統都可用，其它版本系統把防止跨站跟蹤和阻止彈出式窗口關閉應該就沒問題了。
