### ISSUE TITLE
爱发电赞助主页背景问题

### ISSUE THREAD

**Issue by zkitefly** [MCSManager/MCSManager#746]
![image](https://user-images.githubusercontent.com/64117916/193379310-c8bc1f45-7bab-4995-b19b-ce02c50e4527.png)

官网与爱发电赞助主页背景不一致

**Comment by zkitefly** [comment]
或许不换也可以（

我也不知道我为啥要提这个issue

**Comment by MoeCinnamo** [comment]
> 或许不换也可以（
> 
> 我也不知道我为啥要提这个issue

並且還被認成了bug。
