### ISSUE TITLE
在更新/安装实例 处运行自定义更新程序后，无法对程序输入

### ISSUE THREAD

**Issue by cngege** [MCSManager/MCSManager#747]
**MCSManager Version**
9.5.0
**System Info/Version**
Win10 X64
**Node Version**
v14.15.1
**Step**
.RT,
后台两个node的控制台窗口没有异常提示
另外我测试了一下 ，不是我程序的问题，我另写了个bat也不能输入
```cmd
@echo off&setlocal enabledelayedexpansion
@chcp 65001
echo 你好
set /p input=请输入:
echo 你输入的是:
echo %input%
pause
```
![图片](https://user-images.githubusercontent.com/28597788/193394268-e3165a1c-fa2d-40ea-a959-665066b8bfc3.png)

**Comment by unitwk** [comment]
不支持输入，未来也不会支持，没办法。

**Comment by cngege** [comment]
> 

可惜
