### ISSUE TITLE
运行Spigot服务端后无法删除libraries文件夹

### ISSUE THREAD

**Issue by Dongyanmio** [MCSManager/MCSManager#749]
**MCSManager Version：未知**

**System Info/Version：看日志得出应该是Windows Server 2019**

**Node Version：未知**

**Step：运行spigot服务端后无法删除其产生的文件夹**

**Comment by nz-lin** [comment]
？正在被使用的文件无法删除

**Comment by nz-lin** [comment]
结束掉Java进程后再尝试删除
taskkill -im java.exe -f

**Comment by nz-lin** [comment]
> **监控软件版本：未知**
> 
> **系统信息/版本：看日志得出应该是Windows Server 2019**
> 
> **节点版本：未知**
> 
> **Step：运行spigot服务端后无法删除其产生的文件夹**

结束掉Java进程后再尝试删除
taskkill -im java.exe -f

**Comment by Dongyanmio** [comment]
> 

关闭容器后依旧无法删除（我并不是服务器所有者，只是使用者）

**Comment by unitwk** [comment]
此问题应该与MCSManager面板无关，请自行检查权限，文件占用等问题。
