### ISSUE TITLE
需要一些从MCSM 9.0更新的帮助

### ISSUE THREAD

**Issue by playasmegumin** [MCSManager/MCSManager#751]
近日在考虑将原先的 MCSM 9.0 更新到最新版本。9.0 和 9.x 的目录结构差别过大，应该是不能通过文档里的方式更新了，所以想问问除了`/opt/MCSManager/server/server_core/`中的目录外还有哪些比较重要的配置文件需要备份？

**Comment by unitwk** [comment]
`/opt/MCSManager/server/server_core/` 这个目录是 8.X 版本，升级到 9.X 才是结构差异较大。

目前来看，如果你只想保存服务器数据，那就是备份这个目录即可。用户目录在 /users
