### ISSUE TITLE
添加对 Velocity 服务端的支持

### ISSUE THREAD

**Issue by MSDNicrosoft** [MCSManager/MCSManager#752]
~主要是我在写日志的序列化（解析），想根据实例类型来用相应的 formatter(s)~

如果可以，添加如下功能：
- 实例类型
	- 添加 `MC Velocity` 类型
- 特定配置支持
	| 文件名 | 路径 | 简述 |
	| - | - | - |
	| `velocity.toml` | 服务端核心文件同目录下 | 服务端配置文件（详见 [官方文档](https://docs.papermc.io/velocity/configuration)）  |
	| `forwarding.secret` | 服务端核心文件同目录下 | 转发的通信密钥（详见 `velocity.toml` 的注释或[官方文档](https://docs.papermc.io/velocity/configuration#root-section)） |

附加信息：
- Velocity 官网：<https://velocitypowered.com/>

**Comment by unitwk** [comment]
你可以提交 PR 来实现这个配置文件的兼容，具体参考：https://github.com/MCSManager/MCSManager/issues/626

**Comment by WhitePaper233** [comment]
[添加了 Velocity 反代服务端的支持 #77](https://github.com/MCSManager/UI/pull/77)
支持了velocity.toml的支持，forwarding.secret因为不是键值对形式不好添加

**Comment by WhitePaper233** [comment]
> [添加了 Velocity 反代服务端的支持 #77](https://github.com/MCSManager/UI/pull/77) 支持了velocity.toml的支持，forwarding.secret因为不是键值对形式不好添加

而且其实forwarding.secret只是个秘钥文件（并且velocity自己会生成），讲道理也不应该作为一个配置文件去处理
