### ISSUE TITLE
[Bug Report] 计划任务周期创建问题

### ISSUE THREAD

**Issue by 3154311518** [MCSManager/MCSManager#754]
MCSManager版本 9.6
操作系统Windows 2019

BUG1
我选择类型 周期时间性任务 来创建任务
选择时间 周一 到 周日 全选择了 创建后它只显示
触发时间为 2,3,4,5,6,7周期 没有周一的
![BUG1](https://user-images.githubusercontent.com/46740577/197291592-b3fc0136-7e02-467f-b9b4-b2c2c3c84b13.png)

BUG2
如果没有选择周期 计划任务无法删除 并且显示错误
Error: TypeError: Cannot read property 'cancel' of null
![BUG2](https://user-images.githubusercontent.com/46740577/197291735-51255337-0c00-460c-aed4-b9e9ab45ccfc.png)

BUG3
任务创建好后 在创建新的任务 执行次数会变成1
![BUG3](https://user-images.githubusercontent.com/46740577/197292057-76ea748d-eadd-48a0-8dec-b37cc3fb7ae9.png)

给个小建议
如果创建多个周期时间性任务 选择触发时间(指的是选择周期) 一个个点太累了
希望可以添加一键全选

**Comment by unitwk** [comment]
感谢反馈，下版本我们将修复这个问题

**Comment by unitwk** [comment]
9.7.1 应该已经修复这个BUG，如果还有问题欢迎再反馈。

**Comment by mcmohen** [comment]
> 9.7.1 应该已经修复这个BUG，如果还有问题欢迎再反馈。

![image](https://user-images.githubusercontent.com/53630942/224523612-f7265c80-2bab-47ce-883a-c66cf291aa0c.png)
同样的问题，已经更新9.8.0但还是无法删除错误的计划任务
