### ISSUE TITLE
[Feature Request]增加对MCDReforge下服务端配置文件特定选项的支持

### ISSUE THREAD

**Issue by LinkTechTips** [MCSManager/MCSManager#755]
RT 建议增加MCDR/server文件夹下如server.properties等配置文件特定选项的支持

**Comment by PangXitong** [comment]
macOS运行的Minecraft Java可以吗？我在官网没有找到有关macOS安装的链接。

**Comment by LinkTechTips** [comment]
> macOS运行的Minecraft Java可以吗？我在官网没有找到有关macOS安装的链接。

不是很懂你的意思 你是要在macOS下运行MCDR吗？

**Comment by PangXitong** [comment]
> > macOS运行的Minecraft Java可以吗？我在官网没有找到有关macOS安装的链接。
> 
> 
> 
> 不是很懂你的意思 你是要在macOS下运行MCSM/MCDR吗？

是的，我想在macOS运行MCSM/MCDR。

**Comment by LinkTechTips** [comment]
> > > macOS运行的Minecraft Java可以吗？我在官网没有找到有关macOS安装的链接。
> > 
> > 
> > 不是很懂你的意思 你是要在macOS下运行MCSM/MCDR吗？
> 
> 是的，我想在macOS运行MCSM/MCDR。

首先这个issue是一个**Feature Request** 你可以单独在[MCSManager](https://github.com/MCSManager/MCSManager)或者[MCDReforged](https://github.com/Fallen-Breath/MCDReforged)下单独开一个issue来征询此问题 其次你可能需要在你的MacOS上安装python以及java来运行MCSM/MCDR

**Comment by unitwk** [comment]
感觉改改几行配置应该就能适配，具体不太清楚

**Comment by huangsijun17** [comment]
> 感觉改改几行配置应该就能适配，具体不太清楚

我记得上个大版本有Mac的用户，按照Linux的安装方法安装成功了。

**Comment by LinkTechTips** [comment]
> > 感觉改改几行配置应该就能适配，具体不太清楚
> 
> 我记得上个大版本有Mac的用户，按照Linux的安装方法安装成功了。

是这样的 macOS 基于称为 Darwin 的开源 BSD Unix 内核 但个人感觉不太应该在feature request下面问无关的问题（

**Comment by WhitePaper233** [comment]
> 感觉改改几行配置应该就能适配，具体不太清楚

这个需求其实不好实现（就目前而言），MCDR默认将服务端放在其目录下的server目录中，但这个目录是可以自定义的，也就意味着MCDR的server.properties等文件的相对路径其实不固定，就目前而言想要完美支持这个功能其实还真没那么简单。想要实现就必须让daemon去读取mcdr配置文件中服务端的路径再传给前端
