### ISSUE TITLE
玩家数乱码

### ISSUE THREAD

**Issue by TaylorEevee** [MCSManager/MCSManager#756]
**MCSManager Version**
2.0
**System Info/Version**
centos8
**Node Version**
14.19.1
**Step**
服务器安装了cmi使用了其中的motd修改功能，有添加十六进制颜色，然后终端显示玩家数就乱码了
![Screenshot_20221029-092114](https://user-images.githubusercontent.com/75898916/198770192-798df148-ae44-48a0-920e-3101ae080b97.jpg)

**Comment by unitwk** [comment]
这种可能确实不支持，支持新的解析工作量太多，没有办法。

**Comment by TaylorEevee** [comment]
> 这种可能确实不支持，支持新的解析工作量太多，没有办法。

我看了一下，cmi在设置motd后写入到server.properties的motd一行，
§x§f§0§c§f§6§c遥§x§e§3§c§5§6§b远§x§d§7§b§b§6§a的§x§c§a§b§1§6§9树§x§b§e§a§7§6§8屋§x§b§f§a§a§6§f: §x§c§1§a§c§7§7三§x§c§2§a§f§7§e周§x§d§1§b§f§9§0目§x§e§0§c§f§a§3开§x§f§0§d§f§b§7放§x§f§f§e§f§c§a！§x§e§6§5§3§0§0Forge §x§a§7§b§3§a§11.18.2 §x§0§0§8§8§b§3科技 §x§0§0§e§6§7§7休闲 §x§b§3§a§1§0§0冒险
这是我motd一行的内容

**Comment by unitwk** [comment]
这个目前无法支持，以后看需要人数再决定是否开发此功能，谢谢你的建议。
