### ISSUE TITLE
在wls2-docker中启动的实例无法在控制台发送命令

### ISSUE THREAD

**Issue by xzrui** [MCSManager/MCSManager#757]
**MCSManager Version**
9.6.0
**System Info/Version**
宿主机（MCSM直接安装于此）：Windows_NT win32 Windows 10 Pro 10.0.22000
容器：System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.2+8-86) Host: Linux 5.10.16.3-microsoft-standard-WSL2 (amd64)
**Node Version**
v14.15.1
**Step**
使用如上所示的windows系统安装wls2Linux子系统，安装docker-desktop，然后启动容器，
在MCSM网页端管理页面输入回车没有反应。包括控制台左侧点击关闭/重启实例亦无反应，预设命令无法发送到容器，必须点强制终止实例才能关闭它。
已尝试更换换行符类型为windows或linux，这不起作用。
另，使用此MCSM连接另一个纯ubantu系统建立的MCSM守护进程节点，在此网页端是可以正常发送命令到此纯ubantu远程节点的。（此ubantu系统亦使用了docker）

**Comment by unitwk** [comment]
是否启用了仿真终端？

https://docs.mcsmanager.com/#/tutorial/pty 

参考这里来配置，并启用。如果依然无效，那可能MCSM对Windows的Docker并不是很好的支持。

**Comment by xzrui** [comment]
> 是否启用了仿真终端？
> 
> https://docs.mcsmanager.com/#/tutorial/pty
> 
> 参考这里来配置，并启用。如果依然无效，那可能MCSM对Windows的Docker并不是很好的支持。

是的，我尝试过启用仿真终端，但这仍然无效。
这应当的确是MCSM对Windows的docker兼容不佳，
希望MCSM的下一个版本能够尝试对它进行兼容，
愿MCSM越来越好！

**Comment by unitwk** [comment]
这个目前无法支持，以后看需要人数再决定是否开发此功能，谢谢你的建议。

**Comment by zx2587232768** [comment]
这个问题确实比较困扰，如果能解决的话会好很多

**Comment by zzydd** [comment]
可以利用RCON来输入命令，操作步骤如下：
1：修改配置文件
enable-rcon >true
rcon.port >自定义端口(默认25575)
rcon.password>自定义密码

2：关闭实例

3：实例面板>Steam Rcon 协议>启用 Rcon 协议>输入你之前设置的信息(端口、密码)

4：实例面板>应用实例设置>容器化>开放端口-编辑>新增配置>保存

5：重启实例，输入命令验证是否成功

这个方法我实测有效，我现在用Docker的实例用的都是这个方法

**Comment by LokmenoWer** [comment]
这个问题到了2024年还没修 令人感叹

**Comment by huangsijun17** [comment]
> 这个问题到了2024年还没修 令人感叹

MCSM本来就不支持Windows下的Docker……
