### ISSUE TITLE
识别压缩包内服务端的正确位置，或者服务端位置不对时进行文字提醒

### ISSUE THREAD

**Issue by ChrisKimZHT** [MCSManager/MCSManager#764]
我在 b 站做了使用 MCSM 的 Minecaraft 开服视频，有很多新手碰到问题就是，压缩包内多了一层文件夹，上传后面板找不到启动脚本对应的 jarfile，具体报错为：`Unable to access jarfile xxx.jar`. 

我认为这是一个可以优化的点，可以在解压时识别压缩包是否多了一层，也可以在出现该报错时，添加文字提醒如：请检查服务端是否在压缩包根目录。这样也能够降低面板使用门槛，减少新手的疑惑。

**Comment by unitwk** [comment]
这个确实是一个让小白误操作的地方，但是文字提醒应该不太可能（因为解压过程中用户可以关闭或者离开网页），我认为更多的还是当识别到包了一层文件夹时，自动的将你这个文件夹里面的文件全部放到上一层来，这个倒是可以实现。

后期看情况实现吧，最近工期比较满，感谢你的反馈。

另外您的 B 站开服视频可否提供一下，给你一个一键三连。

**Comment by ChrisKimZHT** [comment]
> 这个确实是一个让小白误操作的地方，但是文字提醒应该不太可能（因为解压过程中用户可以关闭或者离开网页），我认为更多的还是当识别到包了一层文件夹时，自动的将你这个文件夹里面的文件全部放到上一层来，这个倒是可以实现。
> 
> 后期看情况实现吧，最近工期比较满，感谢你的反馈。
> 
> 另外您的 B 站开服视频可否提供一下，给你一个一键三连。

[bilibili video](https://www.bilibili.com/video/BV1pa411G7zy)
