### ISSUE TITLE
下载文件无法获取password

### ISSUE THREAD

**Issue by molanp** [MCSManager/MCSManager#765]
请求参数（GET）是完全正确的
然而无论如何就是无法获取password（如图1）
![IMG_20221121_082434](https://user-images.githubusercontent.com/104612722/202935143-fbd48f5a-2b47-451f-86c2-8c8de9b34a10.jpg)
重新看了下请求格式，没发现错误（图2）
![Screenshot_2022_1121_082419](https://user-images.githubusercontent.com/104612722/202935176-8623656a-ad94-4aa8-9279-92e974985dcb.png)

但是把请求链接最后的file_name改为upload_dir来请求上传时却可以正常获取password，这说明问题出在最后的file_name（如图三）
![IMG_20221121_082533](https://user-images.githubusercontent.com/104612722/202935261-e1854556-0bbe-4c9d-9252-ce4c565560d0.png)

我又怀疑是文件名称等不对，可是这个文件在我请求的uuid的实例的根目录中（如图四）
![Screenshot_2022_1121_082628](https://user-images.githubusercontent.com/104612722/202935341-f2373655-380b-42e5-b783-523430803e03.png)
我的请求方式到底有没有错？还是说这是一个bug？

**Comment by unitwk** [comment]
应该是文档错误，将 `/api/files/upload` 地址更改为 `/api/files/download` 再进行尝试。

**Comment by molanp** [comment]
解决了，的确是文档错误，改成download就可以了

**Comment by unitwk** [comment]
文档错误已修复。
