### ISSUE TITLE
获取用户信息api错误

### ISSUE THREAD

**Issue by molanp** [MCSManager/MCSManager#771]
![Screenshot_2022_1202_100357](https://user-images.githubusercontent.com/104612722/205198296-f9ddb20b-0f26-4146-8269-a563951ad63f.png)
请求时发现无论参数是什么，返回结果都是404。
![Screenshot_2022_1202_100654](https://user-images.githubusercontent.com/104612722/205198375-d48fbc16-32f4-4bf8-bb4f-e9a2846500f1.png)
因为如果进入了错误的目录，也会返回404，所以怀疑是不是文档有问题，如果是，请修改正确的api地址，谢谢

**Comment by unitwk** [comment]
面板自己也会使用本接口：
![image](https://user-images.githubusercontent.com/18360009/205431531-e2f2b751-e683-4361-8250-2f756540705b.png)
![image](https://user-images.githubusercontent.com/18360009/205431541-529d7e98-c205-4444-a2bd-a0468711e342.png)

对应的代码：https://github.com/MCSManager/MCSManager/blob/master/src/app/routers/protected/low_level_user_router.ts#L35

如果报 404 应该是你自身的问题。

**Comment by molanp** [comment]
看报错是用到了cookie？
[所用到的文档页面(https://docs.mcsmanager.com/#/panel/info)
![屏幕截图 2022-12-04 080103](https://user-images.githubusercontent.com/104612722/205467387-5c7777fa-fb64-4f05-a0a8-26cb099d001f.png)

**Comment by unitwk** [comment]
> Cookie
API 接口不需要任何 Cookie，只需要一个 apikey。

> 面板在服务器上，是用ip远程请求的，会不会造成影响？

不会

如果有反向代理请关闭，或者查看有无其他程序影响URL导致重写，否则错误代码不可能是 404。
