### ISSUE TITLE
实例控制台发送命令后总是多显示一个空行

### ISSUE THREAD

**Issue by RealChitose** [MCSManager/MCSManager#772]
**MCSManager Version**

9.7.0

**System Info/Version**

Windows 10 Pro 10.0.19045

**Node Version**

v18.12.1

**Step**

1. 使用`CatServer-1.16.5-6d6b2d34-server.jar`；

2. 发送任意命令：

[![2022-12-04-100647.png](https://i.postimg.cc/hPvgrqtr/2022-12-04-100647.png)](https://postimg.cc/bd7KyWbD)

**Comment by unitwk** [comment]
控制台左侧，终端设置，在对话框右侧有一个命令换行符，选择 \n 即可。

**Comment by RealChitose** [comment]
谢谢！
