### ISSUE TITLE
[CentOS] 在外部挂载磁盘中创建实例时不会自动创建目录

### ISSUE THREAD

**Issue by luyurun** [MCSManager/MCSManager#773]
**MCSManager Version**
9.7.1
**System Info/Version**
CentOS 7 (#1 SMP Tue Nov 8 15:48:59 UTC 2022 3.10.0-1160.80.1.el7.x86_64)
**Node Version**
v14.19.1
**Step**

案例：

CentOS7中 面板安装至`/opt/mcsm/`
挂载外部硬盘(`/dev/sdb`的1号分区`/dev/sdb1`)至`/data/`
创建目录并给777权限`/data/mscm`
创建实例时将工作目录指向`/data/mcsm/test`
创建完成后无法上传文件/创建目录

若手动创建目录`/data/mcsm/test`并给777权限
面板实例中后续上传文件开服创建文件夹一切没有问题

在以上案例中 面板网页显示`进程权限用户：root`

本人Linux半初见 请给位大大多多指教 非常感谢帮助

**Comment by huangsijun17** [comment]
能否说一下您的这块磁盘的文件系统格式？

**Comment by luyurun** [comment]
> 能否说一下您的这块磁盘的文件系统格式？

`/dev/sdb1`分区格式是`ext4`

**Comment by unitwk** [comment]
自定义服务器路径原本就不会自动创建目录，因为那个是用来指定已存在目录的。

**Comment by luyurun** [comment]
> 自定义服务器路径原本就不会自动创建目录，因为那个是用来指定已存在目录的。

在一键上传服务器创建实例的时候工作目录的设定是不是仅限以下情况
1. 自动生成工作目录（指向daemon目录下）
2. 将工作目录指向一个已经存在的目录

**Comment by unitwk** [comment]
> > 自定义服务器路径原本就不会自动创建目录，因为那个是用来指定已存在目录的。
> 
> 在一键上传服务器创建实例的时候工作目录的设定是不是仅限以下情况
> 
> 1. 自动生成工作目录（指向daemon目录下）
> 2. 将工作目录指向一个已经存在的目录

对，不过在 9.7.1 版本已经新增一个配置项目支持自定义默认安装位置，在 daemon/data/config/ 中

**Comment by luyurun** [comment]
> > > 自定义服务器路径原本就不会自动创建目录，因为那个是用来指定已存在目录的。
> > 
> > 
> > 在一键上传服务器创建实例的时候工作目录的设定是不是仅限以下情况
> > 
> > 1. 自动生成工作目录（指向daemon目录下）
> > 2. 将工作目录指向一个已经存在的目录
> 
> 对，不过在 9.7.1 版本已经新增一个配置项目支持自定义默认安装位置，在 daemon/data/config/ 中

了解了 我到时候重新设置一下配置文件看看能不能自动将新实例创建至外部存储。
非常感谢耐心解答

CLOSED
