### ISSUE TITLE
mcsmanager.com 的文档无法访问

### ISSUE THREAD

**Issue by xby020** [MCSManager/MCSManager#774]
**MCSManager Version**

**System Info/Version**

**Node Version**

**Step**
- https://docs.mcsmanager.com/ 的服务器貌似挂了

**Comment by unitwk** [comment]
可能是 CF 被墙，请稍等一会或挂梯子进行访问。

**Comment by xby020** [comment]
> 可能是 CF 被墙，请稍等一会或挂梯子进行访问。

额，你可以正常访问吗，我这边看到的是 cf 连不上 host

**Comment by unitwk** [comment]
已修复
