### ISSUE TITLE
面板端时间与本地时间不一致

### ISSUE THREAD

**Issue by PHEmberz** [MCSManager/MCSManager#776]
![屏幕截图 2022-12-07 121848](https://user-images.githubusercontent.com/90391015/206087307-eade2fff-b38b-4c7b-8f4d-c689522ea885.png)
如何把面板时间和本地时间进行同步呢

**Comment by huangsijun17** [comment]
面板端的时间是该服务器的时间。由于服务器的时间和计算机时间偏差可能会造成某些功能错误、MC日志时间错误等，故显示时间以供调试。如果想更改这一时间，请直接更改该**服务器主机的时间和时区设置**。

**Comment by bddjr** [comment]
“面板端时间”显示的是`国际标准时间`，只要Minecraft的日志里的时间没问题，就代表你的操作系统时区设置没问题。

**Comment by bddjr** [comment]
（这个问题或许可以关闭了？又或者官方打个`BUG`标签，以后修一下时区没适配的BUG）

**Comment by huangsijun17** [comment]
> （这个问题或许可以关闭了？又或者官方打个`BUG`标签，以后修一下时区没适配的BUG）

时区是参照服务器设置的。你总不能不允许服务器和用户在不同地区使用不同时区吧。

**Comment by Bluemangoo** [comment]
> > （这个问题或许可以关闭了？又或者官方打个`BUG`标签，以后修一下时区没适配的BUG）
> 
> 时区是参照服务器设置的。你总不能不允许服务器和用户在不同地区使用不同时区吧。

那应该传timestamp而不是string。

**Comment by bddjr** [comment]
> > （这个问题或许可以关闭了？又或者官方打个`BUG`标签，以后修一下时区没适配的BUG）
> 
> 时区是参照服务器设置的。你总不能不允许服务器和用户在不同地区使用不同时区吧。

但是服务器时区设置是北京时间，MC的日志记录时间也是北京时间。说明这是MCSM程序的问题，不是时区设置问题。

**Comment by Bluemangoo** [comment]
![image](https://user-images.githubusercontent.com/63218454/230747619-3e681f66-ecd8-4d07-b602-5f6a2ab6359d.png)

**Comment by Bluemangoo** [comment]
确实有问题，好修的。

**Comment by Bluemangoo** [comment]
改完了，等待审查合并。

**Comment by Bluemangoo** [comment]
已完成，可以关闭了。

**Comment by bddjr** [comment]
你的修复方式如果没记录服务器时区，就是有问题的。
最简单的方法是：
```js
(new Date).toString()
```
中文终端输出：
```js
'Fri Jun 09 2023 21:33:46 GMT+0800 (中国标准时间)'
```
英文终端输出：
```js
'Fri Jun 09 2023 21:31:32 GMT+0800 (China Standard Time)'
```
实测nodev14.19.1也有效。

**Comment by Bluemangoo** [comment]
我也没能成功复现。我的做法是到客户端处理。

**Comment by Bluemangoo** [comment]
本来就不要服务端的。我要服务端时区干什么。

**Comment by bddjr** [comment]
toLocaleString也没问题啊，MCSManager为什么这么怪的

![image](https://github.com/MCSManager/MCSManager/assets/109646559/da172f17-642a-49b2-8614-8d5aada5a455)

**Comment by bddjr** [comment]
破案了，英文模式运行MCSManager整的
![image](https://github.com/MCSManager/MCSManager/assets/109646559/09e0855c-4e89-4b04-9584-7832a0f710a2)

**Comment by bddjr** [comment]
？？？这也没问题啊PM

所以这个问题根本不存在？

**Comment by Bluemangoo** [comment]
谁叫你toString的。你看看那个UI塞得下吗。

**Comment by bddjr** [comment]
9.6.0

![image](https://github.com/MCSManager/MCSManager/assets/109646559/f9b3e9ee-edcb-4bb1-a823-e995c3775cd3)

**Comment by Bluemangoo** [comment]
手机。

**Comment by bddjr** [comment]
自动换行：你好

![image](https://github.com/MCSManager/MCSManager/assets/109646559/4fc468b0-c47c-404d-ad56-be9d678012d0)

**Comment by bddjr** [comment]
> ？？？这也没问题啊PM
> 
> 所以这个问题根本不存在？

所以这个issue描述的问题可能就不存在，改成时间戳反而造成了新的bug，就是不按照服务器的时区显示服务器的时间

但或许 toLocaleString 改为 toString 的话，会明确服务器时区，让人更好判断到底有没有问题。

**Comment by Bluemangoo** [comment]
连个时间都要换两行没意义啊。而且那些信息没用啊。

**Comment by Bluemangoo** [comment]
不是，你要知道服务器时区干什么。

**Comment by bddjr** [comment]
Minecraft的日志记录就是按照系统设置的时区来的，别忘了这是MineCraftServerManagerPanel

**Comment by bddjr** [comment]
如果明确时区的话，可以让人知道是服务器的时区设置有问题，而不是以为你面板有问题

**Comment by Bluemangoo** [comment]
服务器时区有问题？我服务器真在US怎么办？正常国内服务器怎么会时区出错？这已经超出MCSM的作用范围了。

**Comment by huangsijun17** [comment]
我就提一嘴，如果服务器的时间和本机的时间不一致，可能导致火狐浏览器的HTTPS验证不通过而无法访问。

**Comment by Bluemangoo** [comment]
时区不一致时间是一致的。比对时间戳的。

（突然发现为什么火狐会掉https

**Comment by bddjr** [comment]
客户端与服务器的时间戳（GMT）误差不超过24小时应该不会有事（之前测出来的）
