### ISSUE TITLE
[Docker] Docker配置翻译问题及400报错

### ISSUE THREAD

**Issue by luyurun** [MCSManager/MCSManager#777]
**MCSManager Version**
9.7.1
**System Info/Version**
CentOS 7 (https://github.com/MCSManager/MCSManager/pull/1 SMP Tue Nov 8 15:48:59 UTC 2022 3.10.0-1160.80.1.el7.x86_64)
**Node Version**
v14.19.1
**Step**

在删除Docker镜像时，弹出的提示框选项两个都为确定（貌似是翻译问题

还有一个问题是删除镜像文件时会删除失败然后弹出以下错误

`Error: Error: (HTTP code 400) unexpected - invalid reference format`

**Comment by unitwk** [comment]
这个暂时还无法解决，主要原因是容器名字不存在，而删除的API接口参数是以名字为ID的，以后再寻找其他方案。

**Comment by huangsijun17** [comment]
> 

尽量不要通过HTTP错误码代表API的错误结果。API调用正确后，什么都放在200的回包里好。
HTTP返回错误，只应该是HTTP的错误。例如这样的返回相当滑稽：
```
{error:null, 
error_description:null, 
message: "最高教育经历只能存在一个", 
path:null, 
status:"500", 
timestamp:null}
```
况且返回404、500之类，还可能被替换为自定义页面。
