### ISSUE TITLE
求问Linux下如何设置实例工作目录的绝对路径

### ISSUE THREAD

**Issue by CleMooling** [MCSManager/MCSManager#779]
如题，Windows下可以直接写C:\…，实例在Linux系统下要怎么写？

**Comment by ChrisKimZHT** [comment]
Linux 系统直接从根目录下开始写（Linux 没有盘符这个概念），在命令行输入 `pwd` 可以查询当前的工作目录。

例如：`/opt/mcsmanager/daemon/data/InstanceData/xxxxxxx`

P.s. GitHub issue 非提问论坛，不建议在此提问。

**Comment by CleMooling** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
