### ISSUE TITLE
WinSer下Docker运行实例无法发送指令

### ISSUE THREAD

**Issue by Geek-Xiaochen** [MCSManager/MCSManager#780]
**9.7.1**

**WinSer2022 21H2 / Docker 4.15.0**

**默认附加的**

**使用目前最新版本面板与守护进程，配置无论基岩还是Java版本的，都能正常启动，但是无法输入命令，配置了仿真终端和回车符也是一样，这个在最初安装时似乎没有遇到问题**

**Comment by Geek-Xiaochen** [comment]
![Snipaste_2022-12-17_00-27-11](https://user-images.githubusercontent.com/63461126/208144130-ced9e239-fa5e-4e4d-914a-ff558dd61730.png)

**Comment by Geek-Xiaochen** [comment]
可以正常开启无法正常关闭及发送指令
无论是仿真终端还是输入框

**Comment by Mr-Ao-Dragon** [comment]
不建议使用windows作为docker承载，因为docker desktop还相当不完善。

**Comment by huangsijun17** [comment]
Linux Docker兼容为实验性功能，Windows Docker兼容不属于MCSM的功能。个别用户声称他们成功了，但我们都没复现过。
