### ISSUE TITLE
web面板请求404

### ISSUE THREAD

**Issue by king-bcolor** [MCSManager/MCSManager#781]
**MCSManager Version**
9.7.1

**System Info/Version**
Ubuntu 22.04 长期支持版

**Node Version**
14.19.1

**Step**
1.一键安装命令安装，正常显示安装完成界面，访问web面板，显示拒绝访问
2.跟着教程都试了一遍，之后web面板出现404错误
3.卸载重装之后仍然404
4.在此之前已经手动部署开启了一个MC服务器

**Comment by unitwk** [comment]
检查你是否有反向代理，或者是其他可以重写地址的服务面板自身不可能出现404的错误，如果是500的话，还可以理解为是面板的错误。

404的话，极有可能是前端的文件没有找到检查你的/opt/mcsmanager/web/public这个文件夹，检查权限是否正确设置。

**Comment by king-bcolor** [comment]
> Thank you，已解决
