### ISSUE TITLE
能不能在mcsmdaemon接管服务器的情况下显示桌面控制台？

### ISSUE THREAD

**Issue by Duck15** [MCSManager/MCSManager#782]
mcsm运行实例时能不能创建一个桌面控制台？（保留源控制台样式/特性(尽量)
方便在windows主机上用 窗口 控制台管理后台
而不是再开一个浏览器localhost访问（个人感觉显得多此一举
还有能不能可以加一个对于windows的捕获控制台窗口功能（保留源控制台（？可以参考conemu

(这提问是不是有点太过强求了w)

**Comment by unitwk** [comment]
是过强求了。

**Comment by huangsijun17** [comment]
您可以使用API写一个。
