### ISSUE TITLE
面板更新后linux系统下仿真终端无法使用

### ISSUE THREAD

**Issue by cainiaoyizhou** [MCSManager/MCSManager#783]
**系统：**
（腾讯云镜像）ubuntu20.04
**面板版本：**
从9.6全新安装到9.7之后把data文件夹拷回去（为什么我每次git pull之后daemon都会挂）
**node版本：**
14.19.1

更新后蹦极端反复重启，两个purpur端直接摆烂
然后把仿真终端关了就正常了

但windows server2022这边更新后一切正常

**Comment by unitwk** [comment]
听你的描述，看起来已经修复了，只是说需要重启而已。

**Comment by cainiaoyizhou** [comment]
必须关仿真终端，否则启动不了

**Comment by cainiaoyizhou** [comment]
linux在9.6是可以开仿真终端的，9.7就不行了

**Comment by unitwk** [comment]
> linux在9.6是可以开仿真终端的，9.7就不行了

删除 /opt/mcsmanager/daemon/lib/pty_linux_x64(或其他含有pty的文件)，重启daemon服务自动下载新版 pty 程序。

**Comment by cainiaoyizhou** [comment]
![图片](https://user-images.githubusercontent.com/103909046/208885115-98b8c3fc-9026-4b8f-b9f9-9af58a3bb637.png)
依然不行

**Comment by unitwk** [comment]
尝试对 pty 程序进行 chmod 777 权限更正，如果依然还不行，那我也不清楚是为何，就目前信息无法判断出问题所在。

**Comment by cainiaoyizhou** [comment]
已经是777了...另外只有mc不行，bash和frp都正常...
另外我还装了个xp面板，就这个：https://www.xp.cn/

**Comment by Renpengy2002** [comment]
删除/opt/mcsmanager文件夹
重新使用一键脚本安装
`wget -qO- https://gitee.com/mcsmanager/script/raw/master/setup.sh | bash`
然后添加已有服务器，添加启动命令，最后启动实例即可。

**Comment by cainiaoyizhou** [comment]
> 删除/opt/mcsmanager文件夹 重新使用一键脚本安装 `wget -qO- https://gitee.com/mcsmanager/script/raw/master/setup.sh | bash` 然后添加已有服务器，添加启动命令，最后启动实例即可。

我更新到9.7就这样更新的，再来一次？

**Comment by unitwk** [comment]
> 已经是777了...另外只有mc不行，bash和frp都正常...

根据你的这个描述，可能已经跟面板没有什么关系了，把你的命令写绝对路径。

比如 java -jar xxx.jar

改写成： /bin/xxx/zzz/java -jar xxx.jar

**Comment by cainiaoyizhou** [comment]
> > 已经是777了...另外只有mc不行，bash和frp都正常...
> 
> 根据你的这个描述，可能已经跟面板没有什么关系了，把你的命令写绝对路径。
> 
> 比如 java -jar xxx.jar
> 
> java-jar xxx.jar
> 
> 改写成： /bin/xxx/zzz/java -jar xxx.jar

感谢帮助，问题已解决

###### 但这是为什么啊啊啊

**Comment by huangsijun17** [comment]
> > > 已经是777了...另外只有mc不行，bash和frp都正常...
> > 
> > 
> > 根据你的这个描述，可能已经跟面板没有什么关系了，把你的命令写绝对路径。
> > 比如 java -jar xxx.jar
> > java-jar xxx.jar
> > 改写成： /bin/xxx/zzz/java -jar xxx.jar
> 
> 感谢帮助，问题已解决
> 
> ###### 但这是为什么啊啊啊

环境变量的$PATH没传到node.js里。检查systemd服务配置。

**Comment by zijiren233** [comment]
暂时没有很好的解决办法，`/etc/systemd/system/mcsm-daemon.service` 文件里PATH加上java的环境变量可以暂时解决

**Comment by cainiaoyizhou** [comment]
> > > > 已经是777了...另外只有mc不行，bash和frp都正常...
> > > 
> > > 
> > > 根据你的这个描述，可能已经跟面板没有什么关系了，把你的命令写绝对路径。
> > > 比如 java -jar xxx.jar
> > > java-jar xxx.jar
> > > 改写成： /bin/xxx/zzz/java -jar xxx.jar
> > 
> > 
> > 感谢帮助，问题已解决
> > ###### 但这是为什么啊啊啊
> 
> 环境变量的$PATH没传到node.js里。检查systemd服务配置。



> 暂时没有很好的解决办法，`/etc/systemd/system/mcsm-daemon.service` 文件里PATH加上java的环境变量可以暂时解决

然而我从头到尾没有使用过path环境变量啊，为了同时在同一系统上部署1.8.8和1.19.3的同时方便迁移整个服务端，我使用的是相对路径，JAVA直接放在服务端文件夹里，每个服务端单独一个java，后来把java路径改成绝对路径就好了，这和path有什么关系

**Comment by huangsijun17** [comment]
> > > > > 已经是777了...另外只有mc不行，bash和frp都正常...
> > > > 
> > > > 
> > > > 根据你的这个描述，可能已经跟面板没有什么关系了，把你的命令写绝对路径。
> > > > 比如 java -jar xxx.jar
> > > > java-jar xxx.jar
> > > > 改写成： /bin/xxx/zzz/java -jar xxx.jar
> > > 
> > > 
> > > 感谢帮助，问题已解决
> > > ###### 但这是为什么啊啊啊
> > 
> > 
> > 环境变量的$PATH没传到node.js里。检查systemd服务配置。
> 
> > 暂时没有很好的解决办法，`/etc/systemd/system/mcsm-daemon.service` 文件里PATH加上java的环境变量可以暂时解决
> 
> 然而我从头到尾没有使用过path环境变量啊，为了同时在同一系统上部署1.8.8和1.19.3的同时方便迁移整个服务端，我使用的是相对路径，JAVA直接放在服务端文件夹里，每个服务端单独一个java，后来把java路径改成绝对路径就好了，这和path有什么关系

`$PATH`的用处你可以理解为输入命令时免于路径。

**Comment by zijiren233** [comment]
> > > > > 已经是777了...另外只有mc不行，bash和frp都正常...
> > > > 
> > > > 
> > > > 根据你的这个描述，可能已经跟面板没有什么关系了，把你的命令写绝对路径。
> > > > 比如 java -jar xxx.jar
> > > > java-jar xxx.jar
> > > > 改写成： /bin/xxx/zzz/java -jar xxx.jar
> > > 
> > > 
> > > 感谢帮助，问题已解决
> > > ###### 但这是为什么啊啊啊
> > 
> > 
> > 环境变量的$PATH没传到node.js里。检查systemd服务配置。
> 
> > 暂时没有很好的解决办法，`/etc/systemd/system/mcsm-daemon.service` 文件里PATH加上java的环境变量可以暂时解决
> 
> 然而我从头到尾没有使用过path环境变量啊，为了同时在同一系统上部署1.8.8和1.19.3的同时方便迁移整个服务端，我使用的是相对路径，JAVA直接放在服务端文件夹里，每个服务端单独一个java，后来把java路径改成绝对路径就好了，这和path有什么关系

更新仿真终端即可 `https://github.com/MCSManager/pty/releases/tag/v1.3.6` 并且 chmod +x
或等待mcsm下一个版本更新
