### ISSUE TITLE
在控制台新增返回上次查看的文件夹按钮

### ISSUE THREAD

**Issue by cainiaoyizhou** [MCSManager/MCSManager#784]
可以方便重启服务端后打开配置文件

比如：
我加了个插件
点击“回到控制台”并重启服务端
这时候我要去改配置文件
我改好了，“回到控制台”，“重启实例”
这时候我看了游戏效果，觉得不对
我又要去改那个配置文件，就要再找到那个文件夹，但是在几十个插件的服务器里找文件真的很难受
这个按钮可以用来快速返回我刚刚编辑的文件所在的文件夹

**------------------------------------------------------------------------------------------------------------------------**
还有一个建议：
不要把如何获取api密钥这个问题放wiki的常见问题里...我找了整整4个小时......
（个人意见，在别的地方也放一下）

###### 自带的深色模式好刺眼睛啊

**Comment by unitwk** [comment]
> 自带的深色模式好刺眼睛啊

哪里刺眼睛了？能否加几个截图说明一下。

>不要把如何获取api密钥这个问题放wiki的常见问题里...我找了整整4个小时......

后续会在文档中明显处显示

> 这个按钮可以用来快速返回我刚刚编辑的文件所在的文件夹

可以考虑新增一个文件编辑历史，点击快速跳转，但是时间忙没时间，如果你感兴趣开发欢迎提交pr代码。

**Comment by cainiaoyizhou** [comment]
>哪里刺眼睛了？能否加几个截图说明一下。

![图片](https://user-images.githubusercontent.com/103909046/208883217-4d9228c7-bd4f-4120-b7c3-198ce8353d68.png)
控制台白色文字部分亮度太高，黑暗环境下达不到应有效果，可以适当降低亮度，否则没啥用
