### ISSUE TITLE
实例启动失败

### ISSUE THREAD

**Issue by rayleigh57** [MCSManager/MCSManager#789]
[MCSMANAGER] [ERROR] 检测到实例进程/容器启动失败（PID 为空），其可能的原因是：
1. 实例启动命令编写错误，请前往实例设置界面检查启动命令与参数。
2. 系统主机环境不正确或缺少环境，如 Java 环境等。

这是什么原因，求助

**Comment by unitwk** [comment]
<img width="692" alt="image" src="https://user-images.githubusercontent.com/18360009/209805277-eda75a82-b8bb-4f57-88e2-f8c5ceb760c5.png">

它不是已经告诉你了吗？
