### ISSUE TITLE
压缩包无法正常解压

### ISSUE THREAD

**Issue by ChrisKimZHT** [MCSManager/MCSManager#791]
**MCSManager Version**
v9.7.1
**System Info/Version**
Ubuntu 20.04
**Node Version**
v14.19.1
**Step**
上传 .zip 压缩包创建实例，面板无法正确解压，进入文件管理发现实例目录只有一个未解压的 .zip 文件。尝试在文件管理内手动解压也没有反应。

在 Windows 内解压、在系统内直接用 unzip 解压同一个压缩包均不会出现错误，可以排除压缩包的问题。

（该问题由看我的教程的观众提出，好像是近一个月内经常有观众反馈这个问题。如果有需要更多信息，我可以问下有问题的人，看能不能借用他们的服务器收集下信息）

**Comment by ChrisKimZHT** [comment]
有一位观众给出的线索，不知道有没有帮助。

![私信对话](https://user-images.githubusercontent.com/49368462/210176061-737782ff-a615-4969-84a3-33bc07cc8404.png)

**Comment by unitwk** [comment]
新版本已经修复此问题，谢谢你的反馈。
