### ISSUE TITLE
Linux下安装问题

### ISSUE THREAD

**Issue by LGY07** [MCSManager/MCSManager#793]
# Node
如果系统的node版本符合要求，希望不要强制安装node，如果一定要安装也不要链接到/usr/bin/
# 打包
可以发行bash自解压包吗，有的时候需要在离线的环境使用（（（

**Comment by unitwk** [comment]
<img width="526" alt="image" src="https://user-images.githubusercontent.com/18360009/210477350-ea9df57f-6f2f-4769-acdd-6c4725d1d888.png">

根据上图所示，在你的系统还未安装 Node 时才会连接到 /bin，如果以有 node 版本，安装脚本会自己放一份node版本且不污染任何系统环境，这是兼容性最佳的方法。

参考：https://github.com/MCSManager/Script/blob/master/setup.sh

**Comment by LGY07** [comment]
> <img alt="image" width="526" src="https://user-images.githubusercontent.com/18360009/210477350-ea9df57f-6f2f-4769-acdd-6c4725d1d888.png">
> 
> 根据上图所示，在你的系统还未安装 Node 时才会连接到 /bin，如果以有 node 版本，安装脚本会自己放一份node版本且不污染任何系统环境，这是兼容性最佳的方法。
> 
> 参考：https://github.com/MCSManager/Script/blob/master/setup.sh

谢谢你，昨天没仔细看脚本
