### ISSUE TITLE
WSS and HTTPS

### ISSUE THREAD

**Issue by alexjabka** [MCSManager/MCSManager#801]
Hello, I noticed this application doesn't like https.
Is there any way to make it work with wss and https so it connects to daemon properly ?

It only works with ws and http. When I connect to the panel via https and go to Applications it shows daemon wss connection error. Setting daemon address like this wss://address in the interface makes daemon status go offline, setting daemon address like this ws://address makes daemon go online but then it doesn't want to connect when you go to Applications.

**Comment by unitwk** [comment]
Are you using Nginx reverse proxy?

You need to enable both Web and Daemon to support ssl, and use the public IP to connect to it in Daemons management (for example: wss://43.123.123.123:23333).

**Comment by eyhc1** [comment]
if i directly connect to the Daemon on the browser with link like https://43.123.123.123:8082 (image below) it does gets connected:
![dm](https://github.com/MCSManager/MCSManager/assets/53346129/aa1c49e6-9afd-452e-9dee-4126bce5faef)
but if i put it in the panel like wss://43.123.123.123 with the port 8082, it does not connect, even though the panels is also in https:
![panel](https://github.com/MCSManager/MCSManager/assets/53346129/061577dd-64e5-4ecd-a05e-03057bf4a1a6)
