### ISSUE TITLE
通用frpc联机

### ISSUE THREAD

**Issue by 66Leo66** [MCSManager/MCSManager#802]
希望能提供一个通用的frpc的管理，允许通过提供frpc.ini配置文件启动frp客户端（而不是依赖openfrp的服务）

**Comment by unitwk** [comment]
依赖于openfrp是为了更方便新手用户使用，实现家庭网络快速联机，通用的frp管理会提高使用门槛，这与此功能的初衷不一致，会导致目标用户群体更变。

**Comment by LingkongSky** [comment]
其实要复用mcs和frp的话，只需要在启动命令那里多加一条frpc的命令就行

**Comment by BingYanchi** [comment]
> 其实要复用mcs和frp的话，只需要在启动命令那里多加一条frpc的命令就行

我也觉得这未必会是个好事。但如果你非想做，你可以再开一个控制台实例，也不是什么太费事的事情

**Comment by Bluemangoo** [comment]
能附加的话会方便一些，当然我现在就是用的新开实例的办法。之后把实例分组做掉会好办很多。
