### ISSUE TITLE
[BUG] 文件管理即使不保存直接回到文件列表也会更改文件的修改时间

### ISSUE THREAD

**Issue by Glucy-2** [MCSManager/MCSManager#803]
**MCSManager Version**
Web:`9.7.1`,Daemon:`3.1.0`
**System Info/Version**
Debain(Linux) 11
**Node Version**
`16.17.0`
**Step**
1. 使用面板中的文件管理打开任意文件
2. 点击`回到文件列表`按钮并确认
3. 发现文件修改时间发生变化（如果打开文件后关闭网页不会使文件修改时间变化）

**Comment by Glucy-2** [comment]
`9.8.0`/`3.3.0`版本此问题仍然存在

**Comment by unitwk** [comment]
> `9.8.0`/`3.3.0`版本此问题仍然存在

我们尝试复现了此问题，确实存在这个BUG，暂时不清楚原因，可能的猜测是读取文件数据时导致文件时间发生了改变。

不过看起来并不会有什么太大的实际影响，所以暂时没有打算修复此问题的计划。

谢谢你的反馈。
