### ISSUE TITLE
希望能够增加隐藏实例按钮

### ISSUE THREAD

**Issue by cainiaoyizhou** [MCSManager/MCSManager#804]
> **_这个功能我觉得很好用，但是可能受众不是很多，所以优先级可以适当降低_**

实例隐藏后不出现在简单视图中，也不在这里算入计数
![图片](https://user-images.githubusercontent.com/103909046/212326672-3c9de311-2391-4da6-8260-a75cc874d204.png)
###### ↑不计入这个地方可以让强迫症极度舒适↑

这个功能可以让各位使用mcsm管理一些奇怪的不用经常打开的看东西的用户
（如：![图片](https://user-images.githubusercontent.com/103909046/212327228-3b3e5e35-fd14-4804-9020-2c31366b03b3.png)）
更快的找到他们的mc服务器

###### 该死的我居然觉得批量视图比简单视图简单得多

**Comment by huangsijun17** [comment]
附议。

**Comment by mcjuzi666** [comment]
同意，希望更新此内容
