### ISSUE TITLE
以Administrator身份访问文件管理时，弹出Error: Error: 无法访问路径

### ISSUE THREAD

**Issue by Skely0528** [MCSManager/MCSManager#805]
**MCSManager Version 9.7.1**

**Windows 11 Pro 22H2**

**Node Version v18.12.1**

**文件管理**
![Error](https://user-images.githubusercontent.com/86063544/212817072-942d1e5c-45b6-4ad5-9c87-056753d82cec.png)

**Comment by unitwk** [comment]
估计你应该是自动填写了你的新实例工作目录，请前往目的地手动创建文件夹。

**Comment by yxsj245** [comment]
简单来说 目录设置不对 不存在呗
