### ISSUE TITLE
控制台在中文输入法状态按下回车后会直接发送

### ISSUE THREAD

**Issue by QuarkPixel** [MCSManager/MCSManager#806]
**MCSManager Version**
VM-16-16-centos
**System Info/Version**
#1 SMP Tue Jun 28 15:37:28 UTC 2022 3.10.0-1160.71.1.el7.x86_64
**Node Version**
v14.19.1
**Step**
控制台在中文输入法状态按下回车后会直接发送

https://user-images.githubusercontent.com/65812149/213251871-ad2830cc-7732-46ed-94b1-193391ed89b6.mov

**Comment by Rabbit0w0** [comment]
网页端无法检测你是什么输入法

**Comment by huangsijun17** [comment]
> 网页端无法检测你是什么输入法

这是网页响应了输入给输入法的回车。很常见的bug。
