### ISSUE TITLE
[Bug] 端口映射环境中Web与Daemon连接不正常

### ISSUE THREAD

**Issue by Glucy-2** [MCSManager/MCSManager#807]
**MCSManager Version**
Web9.7.2/Daemon3.2.0
**System Info/Version**
Windows Server 2019
**Node Version**
(自带)
**Step**
1. 在某个VPS服务商处购买了一个Windows VPS
2. 安装MCSM-Web和MCSM-Daemon
3. 在服务商处添加端口映射
4. 出现问题

补充信息：
1. 服务商的端口映射不会返回真实IP地址，如使用IP为200.100.100.100的计算机访问Web，日志中显示的地址是192.168.1.254
2. 如果Web在连接Daemon时使用映射的地址则会无法连接，在VPS上使用浏览器访问亦是如此，但是在公网无论是使用浏览器访问还是用Web连接都一切正常
3. 如果Web在连接Daemon时使用127.0.0.1，则显示能连接，但是几乎无法使用任何功能
4. 我不确定这是否是MCSM的bug，如果不是请close

**Comment by huangsijun17** [comment]
1. 服务商的端口映射不会返回真实IP地址的问题。请联系服务商。
2. 在Web上无法使用`[外网IP]:[端口]`连接是服务商的端口映射未开启IP回环。请联系服务商。
3. 建议在同一服务器上安装Web和Daemon时，使用`127.0.0.1`；在同一内网安装Web和Daemon时，使用内网地址。
4. 请详细描述_“几乎无法使用任何功能”_为何。

**Comment by Glucy-2** [comment]
在同一台机器上安装Web和Daemon室友127.0.0.1连接是没有问题的吗？
内置nodejs指的是mcsm官网提供的Windows包里的

**Comment by huangsijun17** [comment]
> 在同一台机器上安装Web和Daemon室友127.0.0.1连接是没有问题的吗？ 内置nodejs指的是mcsm官网提供的Windows包里的

`localhost`、`127.1`、`::1`任选一个就行了。

**Comment by Glucy-2** [comment]
好的谢谢，是我之前自以为是了
