### ISSUE TITLE
有计划为ARM设备（如树莓派）做适配吗？

### ISSUE THREAD

**Issue by AkarinLiu** [MCSManager/MCSManager#808]
我有一个闲置的树莓派，想用它开服，通过Cloudflare的Zero Trust进行内网穿透，但是我不知道MCSManage是否支持ARM架构。你们有计划为ARM设备做适配吗？

**Comment by KagurazakaNyaa** [comment]
理论上，这是一个nodejs的项目，那么在能够运行node的设备上应当都可以正常运行

**Comment by unitwk** [comment]
你用 Linux 安装一键安装脚本，应该是可以安装成功的，但是解压缩功能可能会有一点点问题。

**Comment by LingkongSky** [comment]
有依赖包和一键安装的需求可以找我
我曾经花半个月时间在树莓派4b上解决了1.1.6到1.17的所有依赖包和启动问题
相关依赖包文件：www.smallpipe.xyz
技术相关视频：https://www.bilibili.com/video/BV1eb4y1m7hF/
qq: 2504726488

**Comment by unitwk** [comment]
> 有依赖包和一键安装的需求可以找我 我曾经花半个月时间在树莓派4b上解决了1.1.6到1.17的所有依赖包和启动问题 相关依赖包文件：www.smallpipe.xyz 技术相关视频：https://www.bilibili.com/video/BV1eb4y1m7hF/ qq: 2504726488

非常不错的视频，三连已送，如果可以，更希望能推出一个配合MCSManager使用的小教程什么的！
