### ISSUE TITLE
使用VPN无法访问

### ISSUE THREAD

**Issue by iewnfod** [MCSManager/MCSManager#813]
因为我的服务器在新加坡，国内访问不开VPN会奇慢无比。
然而，当我开启VPN访问时，浏览器提示 `502 当前无法处理此请求`
<img width="614" alt="截屏2023-01-25 21 39 42" src="https://user-images.githubusercontent.com/108739262/214578377-870647b9-1ee4-4734-90b0-94f00f3ff0cb.png">
访问其他同ip端口都没有任何问题。

**Comment by unitwk** [comment]
我也经常开VPN访问面板，没有出现你所说的情况。

**Comment by iewnfod** [comment]
那要怎么办啊？有人遇到过这种情况吗？

**Comment by Glucy-2** [comment]
可能是你的服务商网络的原因，看看面板web端日志有没有访问记录

**Comment by yxsj245** [comment]
这个还真不是面板的问题亲 建议联系服务商

**Comment by alecctv** [comment]
我也遇到了，所以我让面板不走代理了

**Comment by bddjr** [comment]
（这个问题或许可以关闭了？）
