### ISSUE TITLE
官网 和 文档网站无法访问

### ISSUE THREAD

**Issue by jumingya** [MCSManager/MCSManager#814]
今天打开[MCSManager官网](https://mcsmanager.com)时，出现522错误，截图如下：
![image](https://user-images.githubusercontent.com/117981354/215313866-6f06e2f2-9b8c-497a-b5f9-0d1aefc49d79.png)
访问[Docs](https://docs.mcsmanager.com)时，同样出现522错误，截图如下：
![image](https://user-images.githubusercontent.com/117981354/215313855-c49270c9-49b9-4f34-ba57-310ff2050f37.png)

---

## 网络环境

使用 `梯子` 访问： 522 错误

使用我本地的武汉电信访问：522错误

## 浏览器

使用 Chrome 版本 109.0.5414.120（正式版本） （64 位）

**Comment by huangsijun17** [comment]
HTTPS跪了……

**Comment by unitwk** [comment]
已恢复

**Comment by huangsijun17** [comment]
> 已恢复

https还是打不开。你证书没上传？
