### ISSUE TITLE
使用dokcer部署，实例无法启动

### ISSUE THREAD

**Issue by 0AvA0** [MCSManager/MCSManager#815]
1.  报错内容
![image](https://user-images.githubusercontent.com/89952068/215417309-fa5f3fc3-3056-413e-9a6d-1b680bb90872.png)

2. 报错日志
![image](https://user-images.githubusercontent.com/89952068/215416889-630b635b-d1df-472a-af01-7062a32b926d.png)

3. 系统环境
![image](https://user-images.githubusercontent.com/89952068/215417692-56335910-ab7a-4f5d-975e-18669c656a6e.png)

4.docker-compose.yml配置
![image](https://user-images.githubusercontent.com/89952068/215418496-4f1d0115-f2c1-484a-b940-6122428842e2.png)
![image](https://user-images.githubusercontent.com/89952068/215418578-dc7de5b7-fdea-4937-a325-5f35ac07f8c8.png)

**Comment by 0AvA0** [comment]
注释掉的是9.7.1面板 远程节点2.0使用正常

**Comment by 0AvA0** [comment]
未截图内容默认未修改
![image](https://user-images.githubusercontent.com/89952068/215419835-22d0d9e2-ea01-4f59-be7e-e456bcbac15b.png)

**Comment by zijiren233** [comment]
![image](https://user-images.githubusercontent.com/84728412/215484029-e7a8e49e-f53c-4598-bf8d-5d51d1396966.png)
![image](https://user-images.githubusercontent.com/84728412/215484067-54d44c44-f03d-49ea-8e49-933a23070c3b.png)
目录不一致会导致无法启动容器，必须使用.env来设置相同的路径

**Comment by Funny-ppt** [comment]
> ![image](https://user-images.githubusercontent.com/84728412/215484029-e7a8e49e-f53c-4598-bf8d-5d51d1396966.png) ![image](https://user-images.githubusercontent.com/84728412/215484067-54d44c44-f03d-49ea-8e49-933a23070c3b.png) 目录不一致会导致无法启动容器，必须使用.env来设置相同的路径

在群辉部署，.env文件也设置了，一样后台只有409，reason undefined. 不管怎么说什么具体原因都没有实在是没法排查错误。。。

**Comment by zijiren233** [comment]
你不要改dockerfile和compose文件啊

**Comment by Funny-ppt** [comment]
> 你不要改dockerfile和compose文件啊 自己乱改启动不了...

我没有改dockerfile和compose文件。只改了env文件。

**Comment by unitwk** [comment]
一直以来都有各种各样的用户想添加自己的技术栈到mcsmanager中，比如给面板加入NGINX反代，加入ssl，又或者套入docker容器中。

但是我们一直都提倡最简单使用和安装方式，有些额外配置和软件，你可能根本不需要它。

你所反馈的问题虽然来自于官方文档，但这不是我们提倡的使用方式，请更换到原始启动方式，并且愉快的使用 mcsmanager 吧。
