### ISSUE TITLE
When will the work for English docs finish?

### ISSUE THREAD

**Issue by Ryuo1** [MCSManager/MCSManager#817]
I am thinking about learning Chinese just to read the docs :sob:

**Comment by ryu0q** [comment]
I just need to know how I can import my docker-compose Minecraft java server to MCSManager.

**Comment by unitwk** [comment]
I'm very sorry, writing English documents is a heavy workload, I don't have extra time to do this, because I still have some other daily tasks to be done.

You can use Google Translate to read the documentation first, and we will roll out the documentation in English as soon as possible.

**Comment by unitwk** [comment]
https://docs.mcsmanager.com/

80% of the translation work has been completed.

**Comment by ryu0q** [comment]
very very great

**Comment by ryu0q** [comment]
i should really start learning chinese
seems like a very cool language
