### ISSUE TITLE
openfrp 无法自动连接 显示下载失败

### ISSUE THREAD

**Issue by ghostzwc** [MCSManager/MCSManager#819]
**MCSManager Version** 9.7.2

**System Info/Version**Ubuntu 22.10 x86_64

**Node Version**node-v14.19.1-linux-x64

**Step**
[ERROR] 下载 FRP 应用程序失败，无法正常启动 FRP 内网映射程序。: Request failed with status code 404

**Comment by unitwk** [comment]
很抱歉回复较晚，此问题应该已经修复。
