### ISSUE TITLE
docker镜像环境启动实例失败

### ISSUE THREAD

**Issue by g-mero** [MCSManager/MCSManager#821]
**MCSManager Version**
9.7.2
**System Info/Version**
centos7.9

**Node Version**
14.9.1
**Step**
![image](https://user-images.githubusercontent.com/62990607/217311462-31610285-3918-4596-827f-2f61ef8d29ec.png)

![image](https://user-images.githubusercontent.com/62990607/217312167-5c2a3a9f-d666-4f52-866b-acc2aef5fc2d.png)

**Comment by unitwk** [comment]
看起来是挂载的目录权限不足，找到前往实例实际目录（即你第二张图没截图到的工作目录部分），执行 chmod 777 <路径>，再重启面板进行尝试即可。

**Comment by g-mero** [comment]
> 看起来是挂载的目录权限不足，找到前往实例实际目录（即你第二张图没截图到的工作目录部分），执行 chmod 777 <路径>，再重启面板进行尝试即可。

没用啊

**Comment by huangsijun17** [comment]
```
sudo chown $USER:$USER -R <路径>
sudo chmod -R 777 <路径>
```
试试看这个。

**Comment by g-mero** [comment]
> ```
> sudo chown $USER:$USER -R <路径>
> sudo chmod -R 777 <路径>
> ```
> 
> 试试看这个。

系统换ubuntu就一点问题没有了，离谱
