### ISSUE TITLE
浏览器无法连接到 ws://xxxxx

### ISSUE THREAD

**Issue by Steven-WZH** [MCSManager/MCSManager#822]
mcsm我是部署在vps上的，端口映射也做好了
vps上本地访问是没问题的，但在自己电脑上访问控制台就报错了
其他配置界面都是可以正常访问的，就是服务器的控制台访问不了
节点管理里面我填的是24444映射之后的公网地址，都显示正常
![image](https://user-images.githubusercontent.com/113268133/217693607-502b61c4-11c1-498a-8635-f46461d70e29.png)
![image](https://user-images.githubusercontent.com/113268133/217693672-ebb9b700-7d15-4ce7-a125-358c58b5b40a.png)
![image](https://user-images.githubusercontent.com/113268133/217693893-0194d5c5-1b00-4151-8c5b-24cd971bf125.png)

**Comment by Steven-WZH** [comment]
![image](https://user-images.githubusercontent.com/113268133/217694202-fac5f41a-228e-4160-9f8d-269c8b8644f3.png)
实例配置可以正常访问
![image](https://user-images.githubusercontent.com/113268133/217694789-05c9da62-fe2a-450d-9702-2f44866d07ed.png)
24444端口映射到公网也可以访问
![image](https://user-images.githubusercontent.com/113268133/217695209-0b233084-477b-49e7-802f-49dc8f00bd3a.png)
ws://xxxxxxx 无法访问

**Comment by unitwk** [comment]
根据你反馈的所有信息，我也没有发现任何异常之处，理论上只要浏览器&面板都能连接到你映射后的 `a.rainplay.cn:10257` 端口并确保正确转发到 24444 端口即可。

可能是你的映射对 TCP 连接支持不太友好？如果有反向代理则需要开通 Websocket 支持。

**Comment by bddjr** [comment]
这个问题描述得似乎并不是特别清楚。如果是防火墙层面的端口转发，应该不至于无法连接。

或许是因为端口不一致？Web面板程序使用24444端口连接守护节点，而浏览器这边却需要使用10257进行访问。如果按照你描述的问题的话。

如果不依靠Nginx，您或许应当在防火墙映射外部与内部一致的端口号（10257），然后手动更改守护节点监听的端口号（10257）并重启MCSM，再让Web面板程序通过10257端口连接守护进程。

**Comment by bddjr** [comment]
抱歉我没仔细看图，你直接将防火墙的内外端口号都改成10257，应该就行了

**Comment by bddjr** [comment]
但是这些图我真没看明白，感觉有点前后矛盾
也许是填错域名了？
你这个问题我不好解答，以上方法不行的话当我瞎说。

> ![image](https://user-images.githubusercontent.com/113268133/217693672-ebb9b700-7d15-4ce7-a125-358c58b5b40a.png)
> ![image](https://user-images.githubusercontent.com/113268133/217694789-05c9da62-fe2a-450d-9702-2f44866d07ed.png) 24444端口映射到公网也可以访问 ![image](https://user-images.githubusercontent.com/113268133/217695209-0b233084-477b-49e7-802f-49dc8f00bd3a.png) ws://xxxxxxx 无法访问

**Comment by Bluemangoo** [comment]
缺少足够的反馈信息，无法解答问题。

**Comment by bddjr** [comment]
你或许可以尝试在进入实例前，按F12打开DevTools，找到Network（中文名`网络`）并点进去，然后回到网页点实例的卡片进入实例终端，再来到DevTools里看看哪些地址报错
