### ISSUE TITLE
是否可以开发功能直接进行远程管理

### ISSUE THREAD

**Issue by Morgana0w0** [MCSManager/MCSManager#823]
我想是不是可以直接开发一个功能模块对某个没有安装面板的远程主机进行直接管理，这样可以让集中式管理变得比较轻松。让面板直接使用用户账号对远程服务器进行管理和开服（禁止使用root账号），这样对那些配置比较低的机器（例如1C2T，1G）友好一点省掉一个面板资源运行也会更流畅。虽然这样会有一定的风险。

**Comment by unitwk** [comment]
你是不是在寻找一种叫 SSH 可视化客户端的工具。

**Comment by KagurazakaNyaa** [comment]
也许你需要的是jumpserver

**Comment by huangsijun17** [comment]
宝塔面板？

发件人: ***@***.***>
发送时间: 2023年2月14日 13:47
收件人: ***@***.***>
抄送: ***@***.***>
主题: [MCSManager/MCSManager] 是否可以开发功能直接进行远程管理 (Issue #823)


我想是不是可以直接开发一个功能模块对某个没有安装面板的远程主机进行直接管理，这样可以让集中式管理变得比较轻松。让面板直接使用用户账号对远程服务器进行管理和开服（禁止使用root账号），这样对那些配置比较低的机器（例如1C2T，1G）友好一点省掉一个面板资源运行也会更流畅。虽然这样会有一定的风险。

―

**Comment by bddjr** [comment]
（这个帖子似乎没什么价值，是不是可以关掉了）

**Comment by Morgana0w0** [comment]
可我就是想让面板用SSH直接托管服务器啊。。。我还省事了不用写脚本啥的。

半岛的蒟蒻bddjr ***@***.***> 于 2023年4月8日周六 23:39写道：

**Comment by bddjr** [comment]
（现在谁还用1G内存的服啊，一般是2G起步好吧）
