### ISSUE TITLE
增加 “X-Forwarded-For” 与 “X-Real-IP” 的支持让反向代理更加安全

### ISSUE THREAD

**Issue by BingYanchi** [MCSManager/MCSManager#824]
我使用 Nginx 对面板端进行了反向代理。

最近朋友在直播中暴露了反向代理后的地址，观众在不需要密码的情况下登录了账号。后来我查看日志后，看到了所有请求的 ip 地址均指向 127.0.0.1。出现这种情况或许是面板端没有对 header 中 “X-Forwarded-For” 与 “X-Real-IP” 做处理。

希望能够加入这个功能，让面板端在使用反向代理时更加安全。

**Comment by unitwk** [comment]
提议很好，但是代码改动量可能会有点大，因为大部分获取ip的地方都是直接调用的 socket ip地址（即TCP连接的网络地址），目前没有精力去做这个事情。

**Comment by BingYanchi** [comment]
请耐心等待加载完毕...

**Comment by bddjr** [comment]
账号登录状态不是浏览器缓存的吗？

**Comment by unitwk** [comment]
> 账号登录状态不是浏览器缓存的吗？

浏览器和 Web 服务器都有缓存的，分别是 Cookie 和与之对应的 Session。

**Comment by bddjr** [comment]
或许实现起来可以在面板配置里加这个？（默认**禁止**，在本机配置反向代理后自己**手动开启**）
![image](https://user-images.githubusercontent.com/109646559/232183439-ed86d969-01ce-4a03-9d48-7303943bc012.png)
