### ISSUE TITLE
关于统一管理多个MCSM面板的一些易用性以及安全建议。

### ISSUE THREAD

**Issue by yzazzx2021** [MCSManager/MCSManager#825]
目前MCSM面板可以统一管理多个一模一样的面板，但是被管理的面板依旧可以被访问到，这点很不好，容易被注入，有一定的安全风险，可以参照无线网领域的AC+AP，即仅留一个网页访问端口，被管理的面板直接关闭网页访问端口，强制访问会显示404不存在错误，并且设置一个脚本，可以断开与管理者的面板的连接，并且重新启动网页访问端口，然后关于这个密码的问题，可以设置一个密码重置脚本，执行此之后会允许管理者重新设置管理面板上的账户密码，并且修改被管理面板上的账户密码。

**Comment by unitwk** [comment]
前往其他被管理的面板，执行 `systemctl stop mcsm-web` 即可关闭网页访问功能，只留最基本的远程控制功能。

或者，防火墙屏蔽 23333 端口即可。

**Comment by bddjr** [comment]
> 被管理的面板直接关闭网页访问端口，强制访问会显示404不存在错误，并且设置一个脚本，可以断开与管理者的面板的连接，并且重新启动网页访问端口，然后关于这个密码的问题，可以设置一个密码重置脚本，执行此之后会允许管理者重新设置管理面板上的账户密码，并且修改被管理面板上的账户密码。

这个应该可以自己编脚本，加上nginx实现 吧
