### ISSUE TITLE
Daemon访问端口支持自定义路径

### ISSUE THREAD

**Issue by rayfalling** [MCSManager/MCSManager#826]
希望可以通过Nginx反代不同的路径实现访问不同的端口，节省下有限的端口资源

**Comment by unitwk** [comment]
MCSManager 现有架构设计很难实现此需求，成本过高，没有必要。

**Comment by bddjr** [comment]
似乎可以通过检测路径开头是不是 `/socket.io/` 来区分两种代理流量？  
我没测试过，我不确定，你或许可以试试能不能连上。  
从浏览器的F12里看到浏览器访问守护进程的时候路径前面都是`/socket.io/`

**Comment by bddjr** [comment]
> 似乎可以通过检测路径开头是不是 `/socket.io/` 来区分两种代理流量？ 我没测试过，我不确定，你或许可以试试能不能连上。 从浏览器的F12里看到浏览器访问守护进程的时候路径前面都是`/socket.io/`

刚去浏览器看了下，是这样的。如果Web面板访问守护节点也这样，那么确实可以通过区分路径开头是不是`/socket.io/`来确定是否将流量代理到守护进程。我还没试过，对于我来说没必要这样

**Comment by bddjr** [comment]
总之这类东西可能还得自己研究，毕竟官方可能不会提供太多信息（

**Comment by huangsijun17** [comment]
现阶段暂不支持反代到子目录。

**Comment by bddjr** [comment]
实测可行

**Comment by bddjr** [comment]
> 现阶段暂不支持反代到子目录。

![image](https://user-images.githubusercontent.com/109646559/230537436-48d59129-e03f-4949-b586-d9604d616fce.png)

**Comment by bddjr** [comment]
后续我会为文档的那个PR加上这个教程

**Comment by huangsijun17** [comment]
> > 现阶段暂不支持反代到子目录。
> 
> ![image](https://user-images.githubusercontent.com/109646559/230537436-48d59129-e03f-4949-b586-d9604d616fce.png)

你试过吗？反代后失败的问题是页面的各处url都是`/`开头的绝对引用。要改成`./`开头的相对引用才行。

**Comment by bddjr** [comment]
> > > 现阶段暂不支持反代到子目录。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/109646559/230537436-48d59129-e03f-4949-b586-d9604d616fce.png)
> 
> 你试过吗？反代后失败的问题是页面的各处url都是`/`开头的绝对引用。要改成`./`开头的相对引用才行。

试过，成功，连接状态在线，浏览器连接实例终端成功

**Comment by bddjr** [comment]
我不明白你说的失败是怎么回事，location似乎没有相对引用，默认是匹配开头，~是匹配正则表达式，=是完全匹配，优先级从高到低是等号到正则到默认，默认的填路径相似度越高的越优先

> > > 现阶段暂不支持反代到子目录。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/109646559/230537436-48d59129-e03f-4949-b586-d9604d616fce.png)
> 
> 你试过吗？反代后失败的问题是页面的各处url都是`/`开头的绝对引用。要改成`./`开头的相对引用才行。

**Comment by huangsijun17** [comment]
> 我不明白你说的失败是怎么回事，location似乎没有相对引用，默认是匹配开头，~是匹配正则表达式，=是完全匹配，优先级从高到低是等号到正则到默认，默认的填路径相似度越高的越优先
> 
> > > > 现阶段暂不支持反代到子目录。
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/109646559/230537436-48d59129-e03f-4949-b586-d9604d616fce.png)
> > 
> > 
> > 你试过吗？反代后失败的问题是页面的各处url都是`/`开头的绝对引用。要改成`./`开头的相对引用才行。

例如 [index.html的79行](https://github.com/MCSManager/UI/blob/df6fae104e055a5acc37e47435e0494bc9325c7e/public/index.html#L79) 的 `src="/static/editor/ace.js"` 会去请求`example.com/static/editor/ace.js`，而反代到`example.com/mcsm/`后，需要改为请求`example.com/mcsm/static/editor/ace.js`。这需要修改index.html的源代码。把原来改成的`src="/static/editor/ace.js"`改成`src="./static/editor/ace.js"`。其他代码同理。除了各个html，一些js代码等里面也会涉及url地址，都要做相应处理来兼容反代到二级目录。

**Comment by Bluemangoo** [comment]
> 例如 [index.html的79行](https://github.com/MCSManager/UI/blob/df6fae104e055a5acc37e47435e0494bc9325c7e/public/index.html#L79) 的 `src="/static/editor/ace.js"` 会去请求`example.com/static/editor/ace.js`，而反代到`example.com/mcsm/`后，需要改为请求`example.com/mcsm/static/editor/ace.js`。这需要修改index.html的源代码。把原来改成的`src="/static/editor/ace.js"`改成`src="./static/editor/ace.js"`。其他代码同理。除了各个html，一些js代码等里面也会涉及url地址，都要做相应处理来兼容反代到二级目录。

bddjr 的意思应该是在nginx里面把所有`/socket.io/`开头的部分反代到daemon，剩下的原样代理到backend。

比如，`/socket.io/foo/`会到`localhost:24444/socket.io/foo`而`/foo/bar/`会到`localhost:23333/foo/bar/`。

不需要代码层面的其它修改。

**Comment by bddjr** [comment]
如果那个文档PR审核通过了，那这个issue是不是可以直接关掉了

**Comment by Bluemangoo** [comment]
> 如果那个文档PR审核通过了，那这个issue是不是可以直接关掉了
> 
> （附上解答该问题的文档链接）
> https://github.com/bddjr/Documentation/blob/pr-2-1/zh-cn/tutorial/https_proxy_merge_ports.md

pr还没过，不着急。

（这个commit信息，，，，，，，，一般都是说明这个commit做了什么更改的。你合并完之后那个前不着村后不着店的确实让人看不懂。

**Comment by bddjr** [comment]
> > 如果那个文档PR审核通过了，那这个issue是不是可以直接关掉了
> > （附上解答该问题的文档链接）
> > https://github.com/bddjr/Documentation/blob/pr-2-1/zh-cn/tutorial/https_proxy_merge_ports.md
> 
> pr还没过，不着急。
> 
> （这个commit信息，，，，，，，，一般都是说明这个commit做了什么更改的。你合并完之后那个前不着村后不着店的确实让人看不懂。

然后真的没过（悲）

**Comment by Bluemangoo** [comment]
你这个跟人家要的也不一样啊。

**Comment by huangsijun17** [comment]
> > 例如 [index.html的79行](https://github.com/MCSManager/UI/blob/df6fae104e055a5acc37e47435e0494bc9325c7e/public/index.html#L79) 的 `src="/static/editor/ace.js"` 会去请求`example.com/static/editor/ace.js`，而反代到`example.com/mcsm/`后，需要改为请求`example.com/mcsm/static/editor/ace.js`。这需要修改index.html的源代码。把原来改成的`src="/static/editor/ace.js"`改成`src="./static/editor/ace.js"`。其他代码同理。除了各个html，一些js代码等里面也会涉及url地址，都要做相应处理来兼容反代到二级目录。
> 
> bddjr 的意思应该是在nginx里面把所有`/socket.io/`开头的部分反代到daemon，剩下的原样代理到backend。
> 
> 比如，`/socket.io/foo/`会到`localhost:24444/socket.io/foo`而`/foo/bar/`会到`localhost:23333/foo/bar/`。
> 
> 不需要代码层面的其它修改。

需要的是反代web和daemon的根目录到二级目录。而非反代二级目录到二级目录。
如是，才能只使用一个外网端口。

**Comment by huangsijun17** [comment]
还有，前端不支持连接带有目录的后端端口号并不能插入到域名和目录之间。
除此以外，还有一系列的问题。你们测试过什么？就敢说可以用？
![image](https://user-images.githubusercontent.com/31504595/231189792-72bf6c2e-48aa-4bac-b043-8203f7b36ced.png)

**Comment by rayfalling** [comment]
路径不需要变，只是公用一个端口，我个人服务器上还有很多其他服务，如果面板需要使用两个以上的端口，会导致原本有限的端口数量不够使用
或者考虑这么一个使用场景，部分服务器提供商是使用端口映射的，分配给KVM机器可能就10-20个能使用端口，同时部署面板和其他服务，就有可能端口不够使用

**Comment by bddjr** [comment]
有的VPS甚至只给9个端口（我在用的）

**Comment by huangsijun17** [comment]
> 路径不需要变，只是公用一个端口，我个人服务器上还有很多其他服务，如果面板需要使用两个以上的端口，会导致原本有限的端口数量不够使用 或者考虑这么一个使用场景，部分服务器提供商是使用端口映射的，分配给KVM机器可能就10-20个能使用端口，同时部署面板和其他服务，就有可能端口不够使用

原有路径是根目录“/”，你不变路径，反代到的不还是根目录？

**Comment by bddjr** [comment]
你先别急
![image](https://user-images.githubusercontent.com/109646559/231352069-3a769342-9b82-411e-a0a9-91deddc6e34f.png)

**Comment by huangsijun17** [comment]
> 你先别急 ![image](https://user-images.githubusercontent.com/109646559/231352069-3a769342-9b82-411e-a0a9-91deddc6e34f.png)

最关键的不是这三个路径，而是ws(s)。另外，在根目录下，还有一个显示下文的页面，不能反代或许没问题：

> [MCSManager Daemon] Status: OK | reference: https://mcsmanager.com/

**Comment by bddjr** [comment]
这个根路径只是你自己直接访问的时候表明节点在线而已，Web面板程序、浏览器完全不需要节点的根路径识别状态以及进行交互。  

WSS通信是支持的，麻烦你按照我写的文章试一下  
https://q8p.cc/proxyformcsm/配置HTTPS反向代理且合并端口.md

**Comment by rayfalling** [comment]
> 这个根路径只是你自己直接访问的时候表明节点在线而已，Web面板程序、浏览器完全不需要节点的根路径识别状态以及进行交互。
> 
> WSS通信是支持的，麻烦你按照我写的文章试一下 [https://q8p.cc/proxyformcsm/配置HTTPS反向代理且合并端口.md](https://q8p.cc/proxyformcsm/%E9%85%8D%E7%BD%AEHTTPS%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86%E4%B8%94%E5%90%88%E5%B9%B6%E7%AB%AF%E5%8F%A3.md)

这个看了下基本是可行的，不过现在看起来官方还是不愿意支持反代到同一个端口
我觉得Nginx里面写很多location去匹配都不是问题，只要他们本身设计的时候没有出现两个面板路径重复就没问题
WSS本身就可以反向代理的时候upgrade，我Aria2还有Clash的面板都有WSS反代

**Comment by rayfalling** [comment]
这个问题到此为止吧

我后面自己写规则去代理了
原本是希望官方能够提供官方的写法或者提供合并端口的方案的

**Comment by bddjr** [comment]
官方不直接关掉已经很好了（

**Comment by bddjr** [comment]
其实从设计结构上，早就支持合并了，官方可能只是现在不太清楚自己之前写的啥东西（或者不想说这些）

**Comment by huangsijun17** [comment]
上一代的MCSM8就是前后端合一的。MCSM9特意把前后端分开，你又要双羽把他们拼一起？开倒车？
还有，说了那么多，你要是可以这样复用根目录来反代，倒是**把前端连接后端成功的截图**发出来啊。能路上后端的HTTP(s)有啥用？按照你的方法，只反代二级目录到二级目录，根目录的ws链接去哪里？我刚才试过，daemon都连不上。
![image](https://user-images.githubusercontent.com/31504595/231363727-612c8f48-4832-47f1-8f24-7a045b390d72.png)
还有，我在帮双羽去改程序里的各处代码，识图将UI和daemon可以反代到二级目录正常运行。UI已经本体已经改得差不多了，现在的问题在通信层面。

**Comment by bddjr** [comment]
你还是没理解我说的东西。

**Comment by bddjr** [comment]
> 上一代的MCSM8就是前后端合一的。MCSM9特意把前后端分开，你又要双羽把他们拼一起？开倒车？

首先我不知道你说的双羽是谁，其次通过反向代理合并后能正常使用的情况下，是否通过反向代理合并端口可以由使用者自己决定，MCSM官方开发者也就不用为此操心了。
我不明白你们站什么角度，但我作为普通的使用者，我认为作为使用者，通过反向代理合并端口，不影响自己使用，没什么问题。

**Comment by bddjr** [comment]
看起来你似乎正在使用`非本地回环地址`连接节点，如果你配置的是HTTPS，请试着在前面加上`wss://`。我在文中有说这点了。

**Comment by bddjr** [comment]
如果按照教程里的来，那么为什么我访问的时候不是MCSM登录页面？

你先别急，好好理解下我说的是什么

**Comment by huangsijun17** [comment]
> 如果按照教程里的来，那么为什么我访问的时候不是MCSM登录页面？
> 
> 你先别急，好好理解下我说的是什么

你是基于UI和deamon的二级目录不同，且deamon不使用根目录，所以将deamon的二级目录反代到UI的二级目录。
但我[一级目录](https://www.mengmeet.cn)都不是MCSM，我连都ui反代走了。
![image](https://user-images.githubusercontent.com/31504595/231381674-e558ac57-e1b1-454d-9d58-b9ca0f1875be.png)
****
PS：这个MCSM装在这里是我拿来测试用的，已经修改了部分源码，初步实现了可以反代到二级目录。

**Comment by huangsijun17** [comment]
> （瞎猜）快进到官方认为少数情况才会用到这样的反代，然后拒绝更改

我能说我在改源码吗？搞完直接接受PR就行。

**Comment by bddjr** [comment]
假如拒绝更改呢
（感谢你抽出时间写PR，但MCSM本身的设计较为复杂，这样搞得我审核成本较高，且这类需求很少，我没见过端口不够用的。）

**Comment by bddjr** [comment]
应该是不会接受的，因为双羽没明确接受更改，所以PR无效。

现在有个规则，就是程序PR需要issue讨论，官方接受了才能开PR，不接受的话开PR没有用

**Comment by huangsijun17** [comment]
> 应该是不会接受的，因为双羽没明确接受更改，所以PR无效。
> 
> 现在有个规则，就是程序PR需要issue讨论，官方接受了才能开PR，不接受的话开PR没有用

我只是改了web的几行，加了几个点，让web支持反代到路径下，算不上程序PR。只是云编译出了问题，某个依赖更新了openssl，导致不支持旧的哈希算法等等的问题。
至于deamon反代到路径下，那要改握手鉴权等等的代码设计，是一个程序PR。

**Comment by Bluemangoo** [comment]
May be resolved in #1187. Require tests and feedback [here (with guide)](https://github.com/MCSManager/MCSManager/pull/1187#issuecomment-2042212475).

可能在 #1187 中被解决。[这里](https://github.com/MCSManager/MCSManager/pull/1187#issuecomment-2042212475)要一点测试和反馈（含教程）。
