### ISSUE TITLE
Upnp自动端口映射支持

### ISSUE THREAD

**Issue by rayfalling** [MCSManager/MCSManager#827]
内网环境有公网Ip情况下希望能通过Upnp自动打通端口

**Comment by huangsijun17** [comment]
Upnp打通的端口，每次不一样。短期自动调用可以。但长期坐监听端口，还需要每次上报端口号。发短消息/邮件等告知管理员。自动映射固定端口就好，Upnp不是画蛇添足吗？

**Comment by rayfalling** [comment]
Upnp在内网环境下，存在提供Upnp服务但是没有管理权限的情况，如果能整合一下Upnp的设置会比较好，虽然也可以自己起UpnpClient

**Comment by huangsijun17** [comment]
> 在内网环境下，可能存在提供Upnp服务但是没有路由器管理权限的情况 如果能整合一下Upnp的设置会比较好 虽然也可以自己起UpnpClient

唯一的问题是，外网的端口是变动的。MCSManager的外网端口是给人连接用的，而不是程序直接调用。你重启iUpnp后端口就改一次。那么，MCSM是不是还要加一套自动上报端口号的机制？
