### ISSUE TITLE
关于实例内存限制问题

### ISSUE THREAD

**Issue by Doctor-Yin** [MCSManager/MCSManager#828]
**MCSManager Version 9.8**

**System Info/Version 3.3**
内存超出面板设置,在自动关闭实例时,有大概率会触发docker死机

**Comment by Doctor-Yin** [comment]
应该,还在测

**Comment by yxsj245** [comment]
我几百个用户都没有这个情况 是你docker安装的问题或者配置的问题吧

**Comment by huangsijun17** [comment]
超出哪个的设置？Java的还是Docker的？
MCSManager自身是没有内存限制功能的。内存限制由Java和Docker实现。MCSManager的内存设置都是对其启动参数的设置。

**Comment by Doctor-Yin** [comment]
> 超出哪个的设置？Java的还是Docker的？ MCSManager自身是没有内存限制功能的。内存限制由Java和Docker实现。MCSManager的内存设置都是对其启动参数的设置。
测了后,是到了docker内存限制,docker没完全杀死进程(卡死进程),也不知道是不是docker的问题,放开限制完全没问题

**Comment by huangsijun17** [comment]
> > 超出哪个的设置？Java的还是Docker的？ MCSManager自身是没有内存限制功能的。内存限制由Java和Docker实现。MCSManager的内存设置都是对其启动参数的设置。
> > 测了后,是到了docker内存限制,docker没完全杀死进程(卡死进程),也不知道是不是docker的问题,放开限制完全没问题

`docker内存限制`？Docker内的Java进程到达了容器的内存上限？您Java设置了多少，Docker有其1.5倍吗？

**Comment by unitwk** [comment]
没有继续的信息跟进，BUG 复现未能成功，信息不足。此 issue 关闭。
