### ISSUE TITLE
密钥不小心给我删了，能不能重新生成密钥，重装都生成不了

### ISSUE THREAD

**Issue by FDuiv** [MCSManager/MCSManager#830]

**Comment by unitwk** [comment]
你把所有节点删掉，然后执行命令 systemctl restart mcsm-{web,damon} 重启一次应该就行了

**Comment by FDuiv** [comment]
> 你把所有节点删掉，然后执行命令 systemctl restart mcsm-{web,damon} 重启一次应该就行了

我甚至重装过了，目前的办法是用这条命令查询
journalctl -u mcsm-daemon.service > tmp.txt
cat tmp.txt
