### ISSUE TITLE
增加一个配置可以彻底关闭9.8.0左边主菜单上的'命令终端'和'文件管理'按钮

### ISSUE THREAD

**Issue by Illusionika** [MCSManager/MCSManager#832]
卧槽,刚从9.7.1升上来

看到这2按钮玩意居然直接跳转 / 服务器根目录去了,被吓到了,只要万一有人手贱了或者被别人手贱了,后果不堪设想

我知道你有这个功能,你也可以有这个功能,但不要直接放在那边啊,太你妈的危险了啊,万一误操作或者面板被黑了 就直接寄了,面板可是root用户在跑啊

这终端点进去了还关不掉,一直挂个进程在那,点终止直接重开了 草

快出个选项能把这2个按钮去掉,或者直接写在config配置文件里一条关闭的配置

**Comment by huangsijun17** [comment]
面板被黑，直接先建一个实例，命令写`shell`，目录写`/`就行了。
MCSM8年代的方法了。

**Comment by Illusionika** [comment]
> 面板被黑，直接先建一个实例，命令写`shell`，目录写`/`就行了。 MCSM8年代的方法了。

对,他们现在直接把这个实列设置默认在了主界面上了.

如果说以前要弄这个,首先要知道能这么做,还要手动建个特殊实列这样的话.算危险度50%
现在尼玛呼你脸上,像开了嘲讽一样说来搞事啊.不管是被黑了.还是自己手贱了.还是给别的管理员手贱了.早晚出事.危险度直接拉满100%

**Comment by Illusionika** [comment]
你不是ssh终端 你不是宝塔面板 你不是docker desktop ,你只是一个mc面板啊 不要搞骚操作啊,理哪些小白无理取闹的需求干嘛.弄的又臃肿又危险

**Comment by huangsijun17** [comment]
> 你不是ssh终端 你不是宝塔面板 你不是docker desktop ,你只是一个mc面板啊 不要搞骚操作啊,理哪些小白无理取闹的需求干嘛.弄的又臃肿又危险

MC的本质就是一个Java程序。MC内置的shell见过没？直接可以修改根目录的那种。
这年头还拿Root跑MCSM的也是心大。我跑MCSM的用户连sudo权限都不给。

**Comment by Illusionika** [comment]
> > 你不是ssh终端 你不是宝塔面板 你不是docker desktop ,你只是一个mc面板啊 不要搞骚操作啊,理哪些小白无理取闹的需求干嘛.弄的又臃肿又危险
> 
> MC的本质就是一个Java程序。MC内置的shell见过没？直接可以修改根目录的那种。 这年头还拿Root跑MCSM的也是心大。我跑MCSM的用户连sudo权限都不给。

你是看不懂我说的话还是怎么的?你可以有 但是你妈的别放在主页这么招摇的位置直接放出来 懂了没?

**Comment by unitwk** [comment]
后续版本会改进这项功能
