### ISSUE TITLE
关闭实例后长时间服务端未关闭，能加一个自动强制终止实例的功能吗

### ISSUE THREAD

**Issue by KK1ve** [MCSManager/MCSManager#833]
有些整合包关闭服务端可能有bug，没法正常关闭，需要强制终止实例。

**Comment by unitwk** [comment]
那应该是你的关闭实例命令设置的不正确，理论上只要是任何符合输入输出模式标准的控制台程序，都将会接受到关闭命令以执行关闭流程。

**Comment by KK1ve** [comment]
![无标题](https://user-images.githubusercontent.com/52612498/222155513-308663eb-aded-4131-9292-e61dc30b6b6a.png)
![无标题1](https://user-images.githubusercontent.com/52612498/222155547-d46119c6-7a29-4a75-88fd-48cebb408087.png)
CTRL+C这个不算正常关闭吧，毕竟都没保存世界这个步骤。
有些整合包在启动的时候fml也会报错，然后进程就假死了，没法自动崩溃重启，这个有啥解决方法吗。

**Comment by huangsijun17** [comment]
> ![无标题](https://user-images.githubusercontent.com/52612498/222155513-308663eb-aded-4131-9292-e61dc30b6b6a.png) ![无标题1](https://user-images.githubusercontent.com/52612498/222155547-d46119c6-7a29-4a75-88fd-48cebb408087.png) CTRL+C这个不算正常关闭吧，毕竟都没保存世界这个步骤。 有些整合包在启动的时候fml也会报错，然后进程就假死了，没法自动崩溃重启，这个有啥解决方法吗。

CTRL+C只是为了兼容部分较为特殊的程序。例如开泰拉瑞亚服务器等。部分服务器程序原生就是使用CTRL+C关服的。
另外，您现在开服跑的什么命令？

**Comment by KK1ve** [comment]
启动命令是:"D:\MCSManager_v9.7.2_win_x64\mcsmanager\daemon\lib\jdk11\bin\java.exe" -javaagent:YggdrasilOfficialProxy-2.3.0-paperclip.jar -Xmx16G -Xms16G -Dfile.encoding=UTF-8 -Duser.language=zh -Duser.country=CN -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar forge-1.15.2-31.2.57.jar nogui
平台是:windows11，用的MC整合包为Craft to Exile [Dissonance]，你可以看到上面第一张图我使用stop命令后长达10分钟未正常关闭，不能否认一些服务端存在关闭问题的观点。

**Comment by unitwk** [comment]
关服命令设置为 `stop` ，`end` 或 `exit` 都无效吗？我没有开过 forge 服务器，但是我认为这些设置应该是有效的。

**Comment by KK1ve** [comment]
只有stop能关闭。还有假如一个服务端在启动的时候发生了FML崩溃，进程进入假死状态，有什么自动化的重启方案吗。

**Comment by huangsijun17** [comment]
> > 只有stop能关闭。还有假如一个服务端在启动的时候发生了FML崩溃，进程进入假死状态，有什么自动化的重启方案吗。
> 
> 现在没什么针对mcsmapi的插件和mod，比较无奈

关服时大多数插件、MOD都退出了。

**Comment by bddjr** [comment]
我也觉得这个功能应该加入。  
有的时候不知道为什么，MC服务端所有东西都退出了，进程还在，有的时候又没这个情况。  

如果这个功能要加入，或许可以默认设置为5分钟未关闭自动终止程序
