### ISSUE TITLE
如果可以的话请求获取指定行数的outputlog

### ISSUE THREAD

**Issue by wkea** [MCSManager/MCSManager#834]
/api/protected_instance/outputlog
能获取256k的信息 
但是这对获取某些指令的反馈太多了
建议可以设置以行数为基准 
比如获取 最后100行log
params = {
    "uuid": "xxxxxxxxxxxx",
    "remote_uuid": "xxxxxxx",
    "apikey": "xxxxxxxxx"
    "lastlines": "100"
}

**Comment by wkea** [comment]
当然以上都是建议，而且是可以通过分割来做 ，但是 256kb在某些情况下重复执行 占用带宽会比较大  而且获取一次outputlog通常不止256k （也许是我代码的问题）以下是我的代码

`
import requests

url = "http://192.168.5.186:xxx/api/protected_instance/outputlog"
params = {
    "uuid": "xxx",
    "remote_uuid": "xxx",
    "apikey": "xxx"
}

response = requests.get(url, params=params)
if response.ok:
    data = response.json()
    with open('output.txt', 'w', encoding='utf-8') as f:
        print(data, file=f)
else:
    with open('output.txt', 'w', encoding='utf-8') as f:
        print(f"请求失败，HTTP状态码：{response.status_code}", file=f)
`
分割后我得到了大概5000多行的log

**Comment by huangsijun17** [comment]
> 你使用 API 请求后，自己手动以 \n 分割，然后取最后 100 项，不就已经实现了这项功能吗？何必需要我来为此支持昵？

看起来像是api请求给出的数据过大，超出本地处理程序处理能力，亦或者超出传输能力的问题。

**Comment by unitwk** [comment]
根据代码可得，现在的临时日志储存已经更变成 512KB 了。

https://github.com/MCSManager/Daemon/blob/master/src/routers/instance_event_router.ts#LL9C15-L9C15

**Comment by Bluemangoo** [comment]
此Issue问题已经解决，可以close了。
