### ISSUE TITLE
`强制终止实例`并不会杀死MCDR的子进程

### ISSUE THREAD

**Issue by Glucy-2** [MCSManager/MCSManager#835]
跟 #591 是重复的，但是问题没有解决
**MCSManager Version**
`9.8.0`/`3.3.0`
**System Info/Version**
Debian 11
**Node Version**
16.17.0
**Step**
1. 开启一个使用MCDR的Minecraft服务端
2. 在Minecraft服务端卡死的情况下强制终止实例
3. 再次开启实例
4. 报错：
```py
[Server] [17:42:13] [main/ERROR]: Failed to start the minecraft server
[Server] net.minecraft.class_5125$class_5126: /path/to/server/./world/session.lock: already locked (possibly by other Minecraft instance?)
```
可见Minecraft存档仍然被锁定，这说明Minecraft服务端进程没有被杀死，通过htop等工具查看确实如此，也就是说杀死实例时MCDR进程被杀死而它的Minecraft服务端子进程没有。这种情况出现时如果用户不是管理员（没有终端控制权）那么将始终不能正常重开实例，希望能解决，谢谢。

**Comment by unitwk** [comment]
可能对 MCDR 的支持并不是很美好，暂且先只能这样，没有多余的精力修复它。
