### ISSUE TITLE
能否考虑添加"本地节点"功能

### ISSUE THREAD

**Issue by ApliNi** [MCSManager/MCSManager#837]
```
使客户端可以通过面板端连接守护进程, 而不是直接连接守护进程. 
适合管理单台主机或内网的多台主机, 而不需要开放许多端口到外网. 


或许可以: 
- 解决 HTTPS 部署复杂, 以及使部署面板更简单
- 在节点无法开放端口的情况下, 使用 内网穿透/虚拟局域网 等方式与面板端通讯
- 如果使用内网穿透等方式开放面板, 可以减少隧道使用, 以及优化面板服到节点的连接(直接连接而非通过内网穿透连接)
- 防止通过网络扫描找到节点服务器
- 解决因客户端网络问题而连接不上远程节点


如果可以作为新增节点中的一个选项, 那么不会影响现有的分布式功能. 


一个使改动最小化的想法: 
- 连接"本地节点"时使用面板端的IP和端口, 面板端直接将这些流量转发给目标节点
```

**Comment by unitwk** [comment]
这个想法我们曾经也思考过，这主要是对于只有一台机器的用户使用会非常方便。

但是目前的设计可能不太能够支持这种由面板转发流量的情况，实现起来较为复杂。

**Comment by Bluemangoo** [comment]
其实目前上游frp还没有解决websocket协议的转发问题（虽然有pr但是被close了）。

就算支持了面板端转发也不一定可以一条隧道解决因为有俩协议。代码量也很大。最终效果可能不如在面板端搭一个frps。

**Comment by ApliNi** [comment]
> 其实目前上游frp还没有解决websocket协议的转发问题（虽然有pr但是被close了）。
> 
> 就算支持了面板端转发也不一定可以一条隧道解决因为有俩协议。代码量也很大。最终效果可能不如在面板端搭一个frps。

我正用着FRP转发websocket数据, FRP使用https协议, 本地用nginx反向代理websocket服务器, 整个网站和websocket使用一条隧道

**Comment by Bluemangoo** [comment]
> > 其实目前上游frp还没有解决websocket协议的转发问题（虽然有pr但是被close了）。
> > 就算支持了面板端转发也不一定可以一条隧道解决因为有俩协议。代码量也很大。最终效果可能不如在面板端搭一个frps。
> 
> 我正用着FRP转发websocket数据, FRP使用https协议, 本地用nginx反向代理websocket服务器, 整个网站和websocket使用一条隧道

frp的http可以转发ws，但是https转发wss我死活连不上。看上游的issue应该是不行。

上游frp issue [2119](https://github.com/fatedier/frp/issues/2119), [2194](https://github.com/fatedier/frp/issues/2194)

**Comment by huangsijun17** [comment]
> > > 其实目前上游frp还没有解决websocket协议的转发问题（虽然有pr但是被close了）。
> > > 就算支持了面板端转发也不一定可以一条隧道解决因为有俩协议。代码量也很大。最终效果可能不如在面板端搭一个frps。
> > 
> > 
> > 我正用着FRP转发websocket数据, FRP使用https协议, 本地用nginx反向代理websocket服务器, 整个网站和websocket使用一条隧道
> 
> frp的http可以转发ws，但是https转发wss我死活连不上。看上游的issue应该是不行。
> 
> 上游frp issue [2119](https://github.com/fatedier/frp/issues/2119), [2194](https://github.com/fatedier/frp/issues/2194)

我不使用frp，但我见过不少使用frp的，他们都成功转发wss了。
