### ISSUE TITLE
文字显示错误

### ISSUE THREAD

**Issue by schalldemz** [MCSManager/MCSManager#838]
**MCSManager Version**
ver. 9.8.0
**System Info/Version**
Debian 11
**Node Version**
ver. 14.19.1

初始化界面 "Manage My Command line" 下面用的是 progr*e*m 而不是 program
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/46231785/222939793-590e362c-f323-4b5d-9a79-52cc177fc2f5.png">

**Comment by huangsijun17** [comment]
您可以直接PR。

**Comment by unitwk** [comment]
https://github.com/MCSManager/UI/commit/df6fae104e055a5acc37e47435e0494bc9325c7e

已修正。
