### ISSUE TITLE
多实例的端口问题

### ISSUE THREAD

**Issue by Never2333** [MCSManager/MCSManager#839]
致开发团队：

在运行多个 Minecraft 服务端实例时，只有一个服务端可被远端连接。

本机上（局域网 IP 为 10.13.14.13）运行了 A, B, C 三个 Minecraft 服务端实例，A的 server-port 设置为 25565，B的为 25065，C的为25265，且各自的 query.port 也已设置为与 server-port 一致，rcon.port 是在 server-port 的原有基础上+10。路由器的端口转发也已设置好，对应各自的 server-port （IPv4-tcp, udp 来自 所有主机 位于 wan 通过 所有路由 IP 在 端口 25565 → IP 10.13.14.13, 端口 25565 位于 lan）。宽带有公网 IP，已绑定 DDNS 域名，本机 ufw 防火墙已关闭。

现在的问题是仅有编号 A 的 Minecraft 服务端实例可在公网连接（a.example.com:25565），B与C仅可在局域网下连接（10.13.14.13:xxxxx）。

系统：Ubuntu 22.04 LTS；面板版本：9.8.0；对应远程节点版本：3.3.0；Node 版本：v14.19.1。未开启 Ubuntu Pro。

还请多多指教。

**Comment by unitwk** [comment]
为何关闭，已经解决了吗？原因是什么？

**Comment by Never2333** [comment]
> 为何关闭，已经解决了吗？原因是什么？

系 pve 自身问题，与本项目无关。

**Comment by Shapaper233** [comment]
> > 为何关闭，已经解决了吗？原因是什么？
> 
> 系 pve 自身问题，与本项目无关。

我也遇到了类似问题，能提供下您的解决方案吗
