### ISSUE TITLE
增加更多的权限管理

### ISSUE THREAD

**Issue by YangHaoNing-CN** [MCSManager/MCSManager#842]
或许可以增加更多的用户权限管理，这样可以提高服务器整体安全性
类似
- 是否可以创建实例
- 是否可以控制他人权利
- 拥有自己 / 他人创造的实例高级管理权限
- 可创建的实例类型

**Comment by unitwk** [comment]
对于 MCSManager 这种管理游戏服务器面板目前的开发计划与规模而言，开发这个功能的成本与其收益是不对等的，因此没有必要且暂时没有开发这类功能的想法。

不过这个可以作为一个 idea 暂且保存下来，感谢你的意见反馈，期待你的更多反馈意见～
