### ISSUE TITLE
增加实例备份功能

### ISSUE THREAD

**Issue by YangHaoNing-CN** [MCSManager/MCSManager#843]
可以增加实例备份功能，能够较为方便的备份文件

**Comment by unitwk** [comment]
对于 MCSManager 这种管理游戏服务器面板目前的开发计划与规模而言，开发这个功能的成本与其收益是不对等的，因此没有必要且暂时没有开发这类功能的想法。

你可以通过 MC 插件来实现你的需求。

**Comment by Bluemangoo** [comment]
你可以试着新建一个实例写命令行备份。

**Comment by KagurazakaNyaa** [comment]
备份应当由服务器插件或mod实现，这样才能防止备份的数据正在被写入导致的错误

**Comment by YangHaoNing-temp** [comment]
> 备份应当由服务器插件或mod实现，这样才能防止备份的数据正在被写入导致的错误

是的，但是可以添加服务器关闭时备份一次数据之类的功能

**Comment by Mr-Ao-Dragon** [comment]
提议：增加一些触发备份运行的手段，如：计划任务追加系统指令（默认管理员可用）
