### ISSUE TITLE
进程启动方式切换后docker的 资源限制 和 可用端口 依然存在

### ISSUE THREAD

**Issue by YangHaoNing-CN** [MCSManager/MCSManager#844]
**9.7.2**

**Ubuntu 20.04.5 LTS x86_64**

**v14.19.1**

**
   将进程启动方式设置为 虚拟化容器
   启动游戏
   进程启动方式切换为 默认类型
  
![image](https://user-images.githubusercontent.com/83169812/224487815-3f6e5efa-3cac-48d3-acdd-7fd74eb03c95.png)

**

**Comment by unitwk** [comment]
重启实例，刷新网页，是否正常？

**Comment by YangHaoNing-temp** [comment]
不正常
