### ISSUE TITLE
当使用文本编辑器编辑带有双引号的文本时光标会错位

### ISSUE THREAD

**Issue by jswnlinyu** [MCSManager/MCSManager#847]
**MCSManager Version**
9.8.0
**System Info/Version**
Windows Server 2022 Datacenter 10.0.20348
**Node Version**
v18.12.1
**Step**
编辑js文件时，发现当光标处于""号后时，出现位置在应该出现字符前一个位置

**Comment by LazyCreeper** [comment]
没能复现你的问题，我在Chrome`111.0.5563.147`和Edge`111.0.1661.62`上测试一切正常。
[![pp45oi4.png](https://s1.ax1x.com/2023/04/04/pp45oi4.png)](https://imgse.com/i/pp45oi4)
