### ISSUE TITLE
增加WebDAV功能

### ISSUE THREAD

**Issue by MeTerminator** [MCSManager/MCSManager#848]
如题，给MCSM增加一个WebDAV功能。
可以将多个实例的文件挂载到本地，
每个实例有一个挂载入口，可以访问该实例下的所有文件；
每个用户也有一个挂载入口，可以访问该用户拥有的实例的所有文件；
全局文件管理也可以有一个挂载入口，给每个超级管理员一个挂载点。

**Comment by unitwk** [comment]
对于 MCSManager 这种管理游戏服务器面板目前的开发计划与规模而言，开发这个功能的成本与其收益是不对等的，因此没有必要且暂时没有开发这类功能的想法。

不过这个可以作为一个 idea 暂且保存下来，感谢你的意见反馈，期待你的更多反馈意见～
