### ISSUE TITLE
實例資源使用量查看

### ISSUE THREAD

**Issue by IceBrick01** [MCSManager/MCSManager#852]
顯示實例中的 CPU、Ram 和存儲使用情況，以了解實例的資源使用情況。

**Comment by huangsijun17** [comment]
非Docker示例时，无法监控各示例的CPU与内存占用。

**Comment by IceBrick01** [comment]
如果是 Docker Instance 就顯示？

**Comment by huangsijun17** [comment]
> 如果是 Docker Instance 就顯示？

该功能并没有实现。只是使用Docker启动，才有实现的可能性。

**Comment by unitwk** [comment]
對於 MCSManager 這種管理遊戲服務器面板目前的開發計劃與規模而言，開發這個功能的成本與其收益是不對等的，因此沒有必要且暫時沒有開發這類功能的想法。

不過這個可以作為一個 idea 暫且保存下來，感謝你的意見反饋，期待你的更多反饋意見～

**Comment by yxsj245** [comment]
還是錢的問題，如果真的需要可以轉翼龍
