### ISSUE TITLE
能否查看到控制台执行过的命令记录

### ISSUE THREAD

**Issue by flowerinsnowdh** [MCSManager/MCSManager#855]
您好！如果我想查看一个用户在控制台中执行过的命令，是否有该功能？

**Comment by unitwk** [comment]
你是想查看你的普通用户在控制台执行的命令吗？这个可能涉及到用户的隐私，不支持此功能。

如果你是想看见自己输入过的命令，关闭「终端设置」-「仿真终端」功能即可。

**Comment by flowerinsnowdh** [comment]
> 你是想查看你的普通用户在控制台执行的命令吗？这个可能涉及到用户的隐私，不支持此功能。
> 
> 如果你是想看见自己输入过的命令，关闭「终端设置」-「仿真终端」功能即可。

可是我是管理员呀w，别人万一执行什么坏东西怎么办

**Comment by unitwk** [comment]
采用 Docker 技术来保护你的系统。

请转移到 Linux 系统安装你的 MCSManager 面板，并在实例配置底部启用「虚拟化容器」技术。

**Comment by flowerinsnowdh** [comment]
有人会给自己上权限之类的，或者能不能禁用命令呐

**Comment by KagurazakaNyaa** [comment]
> 有人会给自己上权限之类的，或者能不能禁用命令呐

如果只是玩家，那么你没有必要为他们分配面板权限。
如果是管理员，那么他们是应当可以访问控制台的，否则如何管理服务器？
