### ISSUE TITLE
405: Method Not Allowed

### ISSUE THREAD

**Issue by SISUBEN** [MCSManager/MCSManager#856]
405
![image](https://user-images.githubusercontent.com/100661067/227906635-ddde030e-b62f-4ccb-9f9b-5713397fc3af.png)

**Comment by unitwk** [comment]
此错误并非来自 MCSManager 面板，请检查你的防火墙，反向代理，或前往官方网站重新下载尝试。

无其他可参考的任何有价值信息，此 issue 将被忽略。
