### ISSUE TITLE
建议节点wss协议后台连接支持关闭证书安全性校验

### ISSUE THREAD

**Issue by bddjr** [MCSManager/MCSManager#857]
如题（这里是指从面板后台程序连接daemon节点时，关闭证书安全校验），
这样可以使自签证书能直接正常连接wss协议节点，减少布置后台面板https的工作量（虽然安全性可能降低，但起码比裸连安全）。
继#837 ，但实现方式可能不同

**Comment by unitwk** [comment]
没有明白你说的「证书安全性校验」是指什么，这个行为应该是由浏览器来决定的，由浏览器来审核你所连接的SSL网站的证书是否正确。

另外你说的「对于使用者的一种可行的方法」我也没有看明白你的意思，你的理论依据是什么？

**Comment by bddjr** [comment]
一个节点的CPU占用、实例数量、各个实例的名称，是由`面板代发`，而非浏览器直接发送请求。
而由`面板代发`访问节点，遇到不信任的证书会直接报错，而`不能`选择无视证书继续访问。
但`浏览器`可以，当访问一个证书无效的网站时，会提示不安全，此时`只需要`点高级选项，继续访问。
系统的curl也可以，只需要加一个参数，就能忽略证书有效性，直接建立https连接。
那么既然如此，面板代发的时候，或许也可以考虑`忽略证书是否有效`，直接建立https连接。
***
下面那个是我偶然发现的，我也不知道为什么那个方法仍然能让面板与daemon稳定建立连接。但如果尝试更新地址就失效了，即便改回原来的连接地址。

**Comment by Bluemangoo** [comment]
提出一个设想：直接访问deamon端点击忽略，然后再试。

浏览器会把证书状态缓存。之前我捣鼓证书的时候就出现过有些浏览器报错有些正常，后来排查发现清了缓存都报错（笑）

**Comment by bddjr** [comment]
> 提出一个设想：直接访问deamon端点击忽略，然后再试。
> 
> 浏览器会把证书状态缓存。之前我捣鼓证书的时候就出现过有些浏览器报错有些正常，后来排查发现清了缓存都报错（笑）

我这边edge只需要在面板继续访问，edge在面板页面内直接请求访问daemon的时候自动忽略证书问题。

**Comment by bddjr** [comment]
该帖子所描述的实现方式，与那个帖子不同。

那个帖子是让面板后台转发daemon的ws流量，从而让浏览器能正常使用wss连接。
而我这个帖子描述的实现方案是，让面板后台连接daemon时，忽略证书有效性，直接建立wss连接，从而能在面板能使用wss正常连接节点的情况下，浏览器也能正常使用wss连接。

**Comment by bddjr** [comment]
因此，该帖子所描述的问题，是在使用自签证书的情况下，不是浏览器连不了wss，而是面板后台连不了wss，因此面板会显示节点离线。因此也导致浏览器也无法通过面板，点击访问实例。

**Comment by bddjr** [comment]
Error: The remote daemon is not available. Try reconnecting to the remote daemon or check the configuration

```
2023-03-30T12:20:08.751 INFO [HTTP] PUT: http://localhost/api/service/remote_service?uuid=f04efccf30b0400a8cdc0acb9366fff8&token=88ddb2217bde4ba28206b8b772021ea41680149294866
2023-03-30T12:20:08.751 INFO [HTTP] IP: ::ffff:127.0.0.1 USER: bddjrmcsm UUID: c904d9b448fe453492f3af8a8d3946e7
2023-03-30T12:20:08.797 INFO [HTTP] GET: http://localhost/api/service/link_remote_service?uuid=f04efccf30b0400a8cdc0acb9366fff8&token=88ddb2217bde4ba28206b8b772021ea41680149294866
2023-03-30T12:20:08.798 INFO [HTTP] IP: ::ffff:127.0.0.1 USER: bddjrmcsm UUID: c904d9b448fe453492f3af8a8d3946e7
2023-03-30T12:20:08.799 INFO 用户发起重复连接请求，现进行重置连接配置:[f04efccf30b0400a8cdc0acb9366fff8] [wss://localhost:15455/Remote Host]
2023-03-30T12:20:08.800 INFO 主动断开远程节点 [f04efccf30b0400a8cdc0acb9366fff8] [wss://localhost:15455] 
2023-03-30T12:20:08.800 INFO 正在尝试连接远程节点:[f04efccf30b0400a8cdc0acb9366fff8] [wss://localhost:15455/Remote Host]
```

**Comment by bddjr** [comment]
此时如果弄回ws，还是不行。我想不明白之前说的那个nginx方法为何实测有效。

```
2023-03-30T12:27:27.111 INFO [HTTP] PUT: http://localhost/api/service/remote_service?uuid=f04efccf30b0400a8cdc0acb9366fff8&token=88ddb2217bde4ba28206b8b772021ea41680149294866
2023-03-30T12:27:27.112 INFO [HTTP] IP: ::ffff:127.0.0.1 USER: bddjrmcsm UUID: c904d9b448fe453492f3af8a8d3946e7
2023-03-30T12:27:27.162 INFO [HTTP] GET: http://localhost/api/service/link_remote_service?uuid=f04efccf30b0400a8cdc0acb9366fff8&token=88ddb2217bde4ba28206b8b772021ea41680149294866
2023-03-30T12:27:27.163 INFO [HTTP] IP: ::ffff:127.0.0.1 USER: bddjrmcsm UUID: c904d9b448fe453492f3af8a8d3946e7
2023-03-30T12:27:27.164 INFO 用户发起重复连接请求，现进行重置连接配置:[f04efccf30b0400a8cdc0acb9366fff8] [ws://localhost:15455/Remote Host]
2023-03-30T12:27:27.164 INFO 主动断开远程节点 [f04efccf30b0400a8cdc0acb9366fff8] [localhost:15455] 
2023-03-30T12:27:27.164 INFO 正在尝试连接远程节点:[f04efccf30b0400a8cdc0acb9366fff8] [ws://localhost:15455/Remote Host]

```

**Comment by bddjr** [comment]
> 目前我摸索出一种对于使用者（不是开发者修改面板程序）来说可行的方法：
> 
> （使用此方法不要将节点加`wss://`协议头！！！） nginx的daemon代理先不监听ssl（需重启nginx），让面板后台程序连接， 成功后，再监听ssl（需重启nginx）。 此时后台程序连接正常，浏览器也能正常使用wss协议连接节点的各个实例的wss协议。

再次实测，仍然有效。节点状态显示在线，浏览器wss直连成功。
或许是因为没重新建立连接，所以不会报错？

**Comment by bddjr** [comment]
> 提出一个设想：直接访问deamon端点击忽略，然后再试。
> 
> 浏览器会把证书状态缓存。之前我捣鼓证书的时候就出现过有些浏览器报错有些正常，后来排查发现清了缓存都报错（笑）

或许是可以像这样，改成直接让浏览器访问节点获取状态，来解决上述的那种问题。
在节点设置里加个选项，让使用者可以决定让面板还是浏览器来获取节点在线状态。

**Comment by bddjr** [comment]
但是一旦在面板点连接，该配置内容就会消失

**Comment by unitwk** [comment]
> rejectUnauthorized

也许这个参数能做到这一点，后续版本我可以将这个参数加入到 socket 默认配置中去。

**Comment by Bluemangoo** [comment]
如果只是出于私人目的需要此功能，我建议您自己下载源码、修改并编译打包使用。

对于此项目，我不建议将此功能默认开启，否则会对安全性产生影响，如中间人攻击。应该只允许对单独守护进程启用，并且在连接到无法验证的守护进程时候在控制台警告用户。

另外，不建议在生产环境关闭验证。

**Comment by bddjr** [comment]
多数情况下，节点是填`localhost`的。或许可以默认不验证`localhost`的ssl证书是否有效。

**Comment by huangsijun17** [comment]
> 多数情况下，节点是填`localhost`的。或许可以默认不验证`localhost`的ssl证书是否有效。

证书是反代时添加的，localhost都不应该使用https的端口。

**Comment by Bluemangoo** [comment]
可以安装自己的根证书。

**Comment by huangsijun17** [comment]
> > 目前我摸索出一种对于使用者（不是开发者修改面板程序）来说可行的方法：
> > （使用此方法不要将节点加`wss://`协议头！！！） nginx的daemon代理先不监听ssl（需重启nginx），让面板后台程序连接， 成功后，再监听ssl（需重启nginx）。 此时后台程序连接正常，浏览器也能正常使用wss协议连接节点的各个实例的wss协议。
> 
> ### 连接`localhost`节点已经不需要上面这个方法了。
> 在nginx中，先监听`127.0.0.1`的http端口，再监听用于公网访问的https端口。（两者监听的IP不一样，不会发生冲突）
> 
> 以下`用于Daemon的代理配置`示范仅适用于`web`与`Daemon`都在`同一个服务器`且使用`IPv4`的场景，填在`http{}`里。 `<>`这俩符号需要按里面描述的内容进行填写（填写时别带这俩符号！）
> 
> ```nginx
>     server {
>         # Daemon 端localhost访问端口
>         listen 127.0.0.1:<代理后的端口>; #！！！注意<>！！！
>         # 可以通过多个listen监听多个地址与端口。
> 
>         server_name localhost;
> 
>         location / {
>             proxy_pass http://localhost:<Daemon进程真正监听的端口号>; #！！！注意<>！！！
>             proxy_set_header Host localhost;
>             proxy_set_header X-Real-IP $remote_addr;
>             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>             proxy_set_header REMOTE-HOST $remote_addr;
>             proxy_set_header Upgrade $http_upgrade;
>             proxy_set_header Connection "upgrade";
>             add_header X-Cache $upstream_cache_status;
>             add_header Cache-Control no-store;
>             expires 12h;
>         }
>     }
>     server {
>         # Daemon 端公网访问端口
>         listen <代理后的端口> ssl; #！！！注意<>！！！
>         # 可以通过多个listen监听多个地址与端口。
> 
>         server_name <你访问时使用的域名> <也可以通过空格分割，填写多个域名>; #！！！注意<>！！！
>         deny 127.0.0.1; #这个可有可无，主要是debug的时候为了确保localhost真的不是访问这个。
> 
>         # 在示范内容之前已经填了ssl证书相关配置，因此这里并没有ssl配置。您也可以在此处单独配置ssl。
> 
>         # 这块只是在公网尝试使用http访问、https访问根路径、返回404时，直接切断连接。
>         # 这段代码可有可无，有也不会影响一般情况下的访问。
>         error_page 404 =200 /;
>         error_page 497 =200 /;
>         location =/ {
>             return 444;
>         }
>         #================
> 
>         location / {
>             proxy_intercept_errors on; #捕捉到错误状态码时，让nginx决定返回的错误页面。
>             proxy_pass http://localhost:<Daemon进程真正监听的端口号>; #！！！注意<>！！！
>             proxy_set_header Host localhost;
>             proxy_set_header X-Real-IP $remote_addr;
>             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>             proxy_set_header REMOTE-HOST $remote_addr;
>             proxy_set_header Upgrade $http_upgrade;
>             proxy_set_header Connection "upgrade";
>             add_header X-Cache $upstream_cache_status;
>             add_header Cache-Control no-store;
>             expires 12h;
>         }
>     }
> ```
> 
> 不需要安装nginx插件，不需要stream模块。 然后`localhost`直接`ws`协议访问就行了，公网通过浏览器访问终端会自动使用`wss`协议。 （以上代码段展示使用github的nginx风格效果，部分配置参考MCSManager官方文档）
> 
> 也就是说，我上面描述这个问题对于我来说已经有稳定的解决方案。
> 
> ### 但由于这是个`建议`的帖子，我不主动关闭。

同机安装本应如此。本机内连接就不应当使用HTTPS/WSS。
而MCSM是支持分布式部署的。连接其他设备的Daemon服务，即使是局域网内，依然有可能存在路由器入侵、ARP诈骗等中间人攻击。局域网连接使用HTTPS也是必要的。

**Comment by bddjr** [comment]
我之前不太会搞，MCSM官方文档的“配置HTTPS”就那点内容（

**Comment by bddjr** [comment]
目前考虑修改中文文档的“配置HTTPS”，并提交PR

**Comment by Bluemangoo** [comment]
不建议在生产环境使用。

**Comment by Mooling0602** [comment]
自签名证书使用双向验证时面板应该是无法连接到daemon节点的：

![Image](https://github.com/user-attachments/assets/552c35b3-143a-428c-bd75-9532121edb75)

![Image](https://github.com/user-attachments/assets/e8dd8b45-73f7-4b65-a574-399b47eafa80)

目前有两种理论上可行的方案：
1. MCSManager面板支持选择客户端证书（p12 / crt, key）
> 感觉基本不可能（逃

2. 反代服务器对于来自Web节点的IP，不验证客户端证书
> 我用的caddy，如果有人找到方法了可以踢下我谢谢

@yumao233

**Comment by bddjr** [comment]
你另外给个域名用来绕过客户端证书验证的，然后那个域名只允许白名单内的IP建立连接

**Comment by Mooling0602** [comment]
> 你另外给个域名用来绕过客户端证书验证的，然后那个域名只允许白名单内的IP建立连接

**Comment by bddjr** [comment]
我想了想好像不行，服务器与客户端是使用同一个域名连接，这种情况下好像没什么办法

**Comment by bddjr** [comment]
我不知道新版mcsm是否支持后端与前端使用不同地址连接，如果不支持，这个问题好像无解

**Comment by Mooling0602** [comment]
> 我想了想好像不行，服务器与客户端是使用同一个域名连接，这种情况下好像没什么办法

改hosts配置？

**Comment by Mooling0602** [comment]
> 我不知道新版mcsm是否支持后端与前端使用不同地址连接，如果不支持，这个问题好像无解

应该是不支持的

**Comment by bddjr** [comment]
果然不出所料，我对这项目不抱希望了

**Comment by bddjr** [comment]
我还是研究怎么自己写一个吧

**Comment by bddjr** [comment]
没想到这么长时间过去了还有人翻这个issue，我当初提这个issue是因为不知道nginx可以针对本地回环地址（127.0.0.1）使用HTTP明文连接，那时候官方文档没写这段，后来故意移除这段，我真不知道某些人脑子怎么想的。

文档里的 `使用HTTPS` 有个漏洞没修，cookie没添加secure关键字，这会导致浏览器意外降级到HTTP时 **明文发送了cookie** 。
这个漏洞后来在我写的文档里修复了，但是不知道有多少人知道。  
https://proxyformcsm.bddjr.com/
```nginx
# 仅允许客户端使用HTTPS发送Cookie
proxy_cookie_flags ~ secure;
```
这个bug也可以由前端修复，只需在请求时包含前端的 `self.isSecureContext` 布尔值，后端判断该值为 `true` 时，返回的cookie带有`secure`关键字即可。

MCSManager直到现在都没有公开历史上处理过的漏洞，也不能在github里直接点击绿色按钮提交漏洞，我真不知道某些人是不是觉得自己写的代码一坨，心虚了不敢公开，还是说对自己写的东西有迷之自信，觉得自己不会错。

我近期还发现了两个有关鉴权的漏洞。
