### ISSUE TITLE
关于运行实例问题

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [MCSManager/MCSManager#858]
最近使用mcsm管理我的python项目，发现运行实例时都是以root用户运行，导致需要重新安装依赖，非常麻烦。请问如何指定mcsm以某个普通用户运行实例？
系统版本：ubuntu22.04LTS

**Comment by huangsijun17** [comment]
您MCSM是如何运行的？MCSM不支持以指定用户运行实例，除非你自己加个sudo -u的命令。

**Comment by YuYue-Amatsuki** [comment]
> 您MCSM是如何运行的？MCSM不支持以指定用户运行实例，除非你自己加个sudo -u的命令。

感谢，已解决
