### ISSUE TITLE
怎麼用nginx proxy manager設定反向代理？

### ISSUE THREAD

**Issue by naruko-hstk** [MCSManager/MCSManager#860]
如標題

**Comment by bddjr** [comment]
如果只需要http，请参考 https://docs.mcsmanager.com/#/zh-cn/tutorial/simple_reverse_proxy

**Comment by nanami1227** [comment]
我有https的需求

**Comment by bddjr** [comment]
我这边提交了个文档，官方还在审，你或许可以参考下
https://github.com/MCSManager/Documentation/blob/a19f533b9e595daaeb5ffa029c5d3d23731da345/zh-cn/tutorial/reverse_proxy%2Bssl.md

**Comment by bddjr** [comment]
最新文档  
https://github.com/bddjr/Documentation/blob/pr-2-1/zh-cn/tutorial/reverse_proxy%2Bssl.md

**Comment by bddjr** [comment]
https://q8p.cc/proxyformcsm/配置HTTPS反向代理.md
