### ISSUE TITLE
增加功能：1-当docker镜像不存在的时候主动拉取、2-根据实例的需求的java版本智能推荐镜像、3-启用不保留容器功能选项

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [MCSManager/MCSManager#862]
#### 功能动机
实战时，发现docker相关功能不够完善

#### 功能目标
- 增强体验一致性
- 减少操作步骤
- 减少存储占用

#### 个人推荐docker镜像
[zulu jre](https://hub.docker.com/r/azul/zulu-openjdk-distroless)
无暂停gc，更好的性能，符合兼容标准，简直是MinecraftServer命中注定的runtime

**Comment by huangsijun17** [comment]
1. MCSM未提供任何官方镜像。一切Docker镜像都是使用Dockerfiles本地生成。
2. 实例无Java版本选择，MC版本和Java版本非密切相关。服务端亦未提供版本检测接口，且主动运行来监测版本可能存在其他问题。
3. MCSM的Docker功能默认且只能不保留容器。MCSM未提供以容器形式开服，将服务端文件保存在Docker容器内的功能。

**Comment by Mr-Ao-Dragon** [comment]
> 1. MCSM未提供任何官方镜像。一切Docker镜像都是使用Dockerfiles本地生成。
> 2. 实例无Java版本选择，MC版本和Java版本非密切相关。服务端亦未提供版本检测接口，且主动运行来监测版本可能存在其他问题。
> 3. MCSM的Docker功能默认且只能不保留容器。MCSM未提供以容器形式开服，将服务端文件保存在Docker容器内的功能。

好的，填入镜像地址:tag 自动拉取不算官方推荐，应该能做

**Comment by Mr-Ao-Dragon** [comment]
> 1. MCSM未提供任何官方镜像。一切Docker镜像都是使用Dockerfiles本地生成。
> 2. 实例无Java版本选择，MC版本和Java版本非密切相关。服务端亦未提供版本检测接口，且主动运行来监测版本可能存在其他问题。
> 3. MCSM的Docker功能默认且只能不保留容器。MCSM未提供以容器形式开服，将服务端文件保存在Docker容器内的功能。

直接拉取填入的镜像地址还是可以考虑的

**Comment by huangsijun17** [comment]
> > 1. MCSM未提供任何官方镜像。一切Docker镜像都是使用Dockerfiles本地生成。
> > 2. 实例无Java版本选择，MC版本和Java版本非密切相关。服务端亦未提供版本检测接口，且主动运行来监测版本可能存在其他问题。
> > 3. MCSM的Docker功能默认且只能不保留容器。MCSM未提供以容器形式开服，将服务端文件保存在Docker容器内的功能。
> 
> 好的，填入镜像地址:tag 自动拉取不算官方推荐，应该能做

MCSM中运行Minecraft的Docker镜像有一定的特性，例如需要指定运行目录，建议修改时区等等。所以还是建议使用DockerFiles拉取 镜像地址:tag 下载后修改生成专用镜像。

**Comment by Mr-Ao-Dragon** [comment]
> > > 1. MCSM未提供任何官方镜像。一切Docker镜像都是使用Dockerfiles本地生成。
> > > 2. 实例无Java版本选择，MC版本和Java版本非密切相关。服务端亦未提供版本检测接口，且主动运行来监测版本可能存在其他问题。
> > > 3. MCSM的Docker功能默认且只能不保留容器。MCSM未提供以容器形式开服，将服务端文件保存在Docker容器内的功能。
> > 
> > 好的，填入镜像地址:tag 自动拉取不算官方推荐，应该能做
> 
> MCSM中运行Minecraft的Docker镜像有一定的特性，例如需要指定运行目录，建议修改时区等等。所以还是建议使用DockerFiles拉取 镜像地址:tag 下载后修改生成专用镜像。

好的
