### ISSUE TITLE
希望能控制安装脚本的细节

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [MCSManager/MCSManager#863]
如
- 利用参数选择安装哪端
- 是否检测环境
- 决定安装的位置等

**Comment by unitwk** [comment]
过多的细节控制只会让程序复杂化，由程序直接替用户的选择，实现整个过程无人操作自动完成正是我编写安装脚本的初衷，此设计原则不可违背。

如果某个用户想自定义安装位置，自定义安装环境，那么它就应该手动安装，并且承受所需的学习成本：

https://github.com/MCSManager/MCSManager#linux

**Comment by Mr-Ao-Dragon** [comment]
明白了
