### ISSUE TITLE
关于在ro只读文件系统下的mcsm数据保存问题

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [MCSManager/MCSManager#864]
尽管可能没必要，但我在此类文件系统下部署mcsm确实很麻烦，需要使用软连接或网络挂载等手段，是否考虑可选的网络数据存储？

**Comment by huangsijun17** [comment]
设计之初就没有考虑过ro文件系统。如果要支持，修改范围可能较大。而且ro文件系统这个需求比例不大吧。

**Comment by Bluemangoo** [comment]
可以试试改一个出来，我可以把面板中心丢到vercel去（虎狼之词）。

**Comment by Bluemangoo** [comment]
p.s. 你开玩笑的吗一口气开五六个issue。

**Comment by Mr-Ao-Dragon** [comment]
> p.s. 你开玩笑的吗一口气开五六个issue。

这段时间累积的
