### ISSUE TITLE
添加功能：一次性创建多个同类实例

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [MCSManager/MCSManager#865]
如题，现在操作的时候，需要每次退回上级菜单，希望能给一个新建并继续添加的按钮。
以及希望能在新建实例时，一级菜单能给出默认折叠的高级参数填写功能。

**Comment by unitwk** [comment]
你可以使用现有版本的预设开服功能，自定义自己的开发预设包，实现点击两三下即可完成一个标准配置模板的实例搭建。

**Comment by unitwk** [comment]
> > 你可以使用现有版本的预设开服功能，自定义自己的开发预设包，实现点击两三下即可完成一个标准配置模板的实例搭建。
> 
> 好，第二项是否考虑？

`一级菜单能给出默认折叠的高级参数填写功能。` 这一部分没有明白，哪里被折叠了？能给个截图吗？

**Comment by Mr-Ao-Dragon** [comment]
> > > 你可以使用现有版本的预设开服功能，自定义自己的开发预设包，实现点击两三下即可完成一个标准配置模板的实例搭建。
> > 
> > 好，第二项是否考虑？
> 
> `一级菜单能给出默认折叠的高级参数填写功能。` 这一部分没有明白，哪里被折叠了？能给个截图吗？

新建实例，开始填写参数的菜单

**Comment by Mr-Ao-Dragon** [comment]
> > > 你可以使用现有版本的预设开服功能，自定义自己的开发预设包，实现点击两三下即可完成一个标准配置模板的实例搭建。
> > 
> > 
> > 好，第二项是否考虑？
> 
> `一级菜单能给出默认折叠的高级参数填写功能。` 这一部分没有明白，哪里被折叠了？能给个截图吗？

是我表述不清楚，我想在创建时能直接填写图2的所有信息
![image](https://github.com/MCSManager/MCSManager/assets/67987607/cd80e867-898d-4ebc-80c1-a9725293033f)
![image](https://github.com/MCSManager/MCSManager/assets/67987607/8557079b-5478-4a04-b373-998f63dd45e5)

**Comment by unitwk** [comment]
> > > > 你可以使用现有版本的预设开服功能，自定义自己的开发预设包，实现点击两三下即可完成一个标准配置模板的实例搭建。
> > > 
> > > 
> > > 好，第二项是否考虑？
> > 
> > 
> > `一级菜单能给出默认折叠的高级参数填写功能。` 这一部分没有明白，哪里被折叠了？能给个截图吗？
> 
> 是我表述不清楚，我想在创建时能直接填写图2的所有信息 ![image](https://user-images.githubusercontent.com/67987607/242187222-cd80e867-898d-4ebc-80c1-a9725293033f.png) ![image](https://user-images.githubusercontent.com/67987607/242187476-8557079b-5478-4a04-b373-998f63dd45e5.png)

开发成本过高，为了一些小的偏好需求没有必要。
