### ISSUE TITLE
添加实例分组的前端功能

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [MCSManager/MCSManager#866]
如题，为实例分组后，能更清晰的了解bc群组的情况，同时也让Docker组网目标更清晰。

**Comment by unitwk** [comment]
想法不错。

**Comment by Bluemangoo** [comment]
然后再加个一口气启动整个分组所有实例的功能，，，

有点眼熟。这不是我之前想做的东西吗。

嘿嘿嘿，权限问题。

**Comment by unitwk** [comment]
我只是说想法不错，又没说一定会做。

**Comment by Bluemangoo** [comment]
给个权限问题的解决方案，我回头也能写吧，，

**Comment by Mr-Ao-Dragon** [comment]
> 给个权限问题的解决方案，我回头也能写吧，，

权限节点

**Comment by unitwk** [comment]
这个不难，只是我懒得写而已，没啥时间。
