### ISSUE TITLE
建议增加“刷新网页颜色渲染”的按钮

### ISSUE THREAD

**Issue by bddjr** [MCSManager/MCSManager#868]
开启“网页颜色渲染”后，有些时候会出现终端颜色渲染失败，如果能手动刷新颜色会更方便。（起码比不能刷新好）

**Comment by Bluemangoo** [comment]
F5（

**Comment by bddjr** [comment]
刷新网页没用，甚至原本好好的刷新后没颜色了

**Comment by Bluemangoo** [comment]
（其实我也会碰到这个问题

可以排下原因吗？

_p.s.今天怎么这么多issue，，，_
