### ISSUE TITLE
无法修改节点终端设置 | Cannot change terminal settings of node terminal

### ISSUE THREAD

**Issue by Bluemangoo** [MCSManager/MCSManager#870]
**MCSManager Version**: Panel 9.8.0;

**System Info/Version**: Windows 11 (Windows NT 10.0);

**Node Version**: v16.19.0

**Details**: 

### English

Cannot change terminal settings of node terminal, because it is always running (auto restart on stopping).

A way to fix it maybe allowing changing while terminal is running but apply them next time it starts.

The same as other instances. (Plus, only one fix is needed)

### 简体中文

无法修改节点终端的终端设置。

一种可行的办法是允许在运行时修改终端设置，但是在下一次启动实例时才应用它们。

其它实例也应该如此（当然只要改一处代码就行）。

![image](https://user-images.githubusercontent.com/63218454/232218697-8563475b-82a4-4bd9-bcf7-1931f4c91917.png)

**Comment by Bluemangoo** [comment]
我翻了下源码，只是限制了仿真终端pty设置的修改。

[Daemon/src/entity/instance/instance.ts:102](https://github.com/MCSManager/Daemon/blob/cfdf14eceb2daddd8348d767c6884a289c6cb9dd/src/entity/instance/instance.ts#L102)
```ts
if (this.status() != Instance.STATUS_STOP) throw new Error($t("instanceConf.cantModifyPtyModel"));
```

**Comment by Bluemangoo** [comment]
实测删除这条限制不会出现问题：

- on -> off: 仿真终端会直接失效（本次运行）；

- off -> on: 仿真终端不会启动（本次运行）。

**Comment by Bluemangoo** [comment]
如果认为的确可以删除这条限制我就提pr了。

**Comment by unitwk** [comment]
`off -> on: 仿真终端不会启动（本次运行）。`

你不是都试过了吗？从off到on不会生效，那么用户就算开启了这个设置也没有用。

那干脆还是弹窗告知一下用户，让用户知道必须关闭实例才能更改，这个会更好。

所以这个限制不必删除。

**Comment by Bluemangoo** [comment]
主要是这个实例无法关闭。

**Comment by Bluemangoo** [comment]
你可以试一下，节点终端这个实例会自动重启。

**Comment by Bluemangoo** [comment]
> `off -> on: 仿真终端不会启动（本次运行）。`
> 
> 你不是都试过了吗？从off到on不会生效，那么用户就算开启了这个设置也没有用。
> 
> 那干脆还是弹窗告知一下用户，让用户知道必须关闭实例才能更改，这个会更好。
> 
> 所以这个限制不必删除。

这是指本次运行不会生效，重启实例后就会生效了。

**Comment by bddjr** [comment]
MCSManager通常用于开Minecraft服，而Minecraft服的配置文件 server.properties 也是需要重启生效，所以我觉得Bluemangoo这样做没什么问题。

**Comment by Bluemangoo** [comment]
> MCSManager通常用于开Minecraft服，而Minecraft服的配置文件 server.properties 也是需要重启生效，所以我觉得Bluemangoo这样做没什么问题。

不一样的。

**Comment by bddjr** [comment]
命令终端为什么不支持全屏（恼）  
而且打开会自动输入奇怪的字符，自建bash实例可没这种情况  

![image](https://user-images.githubusercontent.com/109646559/232484866-b4bc940c-2677-4de5-b596-5cc0e5cdabe3.png)

**Comment by huangsijun17** [comment]
> > MCSManager通常用于开Minecraft服，而Minecraft服的配置文件 server.properties 也是需要重启生效，所以我觉得Bluemangoo这样做没什么问题。
> 
> 不一样的。

MCSM的很多配置没做预读取。不重启修改配置需要把预读取加上，还会因此增加内存消耗。

**Comment by huangsijun17** [comment]
> 命令终端为什么不支持全屏（恼） 而且打开会自动输入奇怪的字符，自建bash实例可没这种情况
> 
> ![image](https://user-images.githubusercontent.com/109646559/232484866-b4bc940c-2677-4de5-b596-5cc0e5cdabe3.png)

单独开issues，写清楚环境、运行的什么程序，有误docker等等。

**Comment by Bluemangoo** [comment]
> > > MCSManager通常用于开Minecraft服，而Minecraft服的配置文件 server.properties 也是需要重启生效，所以我觉得Bluemangoo这样做没什么问题。
> > 
> > 
> > 不一样的。
> 
> MCSM的很多配置没做预读取。不重启修改配置需要把预读取加上，还会因此增加内存消耗。

都用nodejs了就别考虑这点内存问题了吧。

另外，如果有人能找出修改节点终端ptr配置的方法这个issue就能关了。

**Comment by Bluemangoo** [comment]
（踢一脚maintainer @unitwk

**Comment by unitwk** [comment]
> （踢一脚maintainer @unitwk

我不是很早就已经回复并且表达了结果吗？

> off -> on: 仿真终端不会启动（本次运行）。
> 你不是都试过了吗？从off到on不会生效，那么用户就算开启了这个设置也没有用。
> 那干脆还是弹窗告知一下用户，让用户知道必须关闭实例才能更改，这个会更好。
> 所以这个限制不必删除。

没有必要支持中途修改 pty，因为你修改了也不会生效，必须要重启。

那么你反正要关闭一次实例程序，那么在关闭时就可以修改 pty 了。

**Comment by bddjr** [comment]
命令终端怎么关

**Comment by Bluemangoo** [comment]
> > （踢一脚maintainer @unitwk 
> 
> 我不是很早就已经回复并且表达了结果吗？
> 
> > off -> on: 仿真终端不会启动（本次运行）。
> > 你不是都试过了吗？从off到on不会生效，那么用户就算开启了这个设置也没有用。
> > 那干脆还是弹窗告知一下用户，让用户知道必须关闭实例才能更改，这个会更好。
> > 所以这个限制不必删除。
> 
> 没有必要支持中途修改 pty，因为你修改了也不会生效，必须要重启。
> 
> 那么你反正要关闭一次实例程序，那么在关闭时就可以修改 pty 了。

你再看一眼我前面写的。


> 主要是这个实例无法关闭。


> 你可以试一下，节点终端这个实例会自动重启。


节点终端这个实例会自动重启，导致无法在关闭情况下修改pty设置（因为根本没有关闭状态。）

**Comment by bddjr** [comment]
（似乎有条评论自己删除了）

**Comment by unitwk** [comment]
> > > （踢一脚maintainer @unitwk
> > 
> > 
> > 我不是很早就已经回复并且表达了结果吗？
> > > off -> on: 仿真终端不会启动（本次运行）。
> > > 你不是都试过了吗？从off到on不会生效，那么用户就算开启了这个设置也没有用。
> > > 那干脆还是弹窗告知一下用户，让用户知道必须关闭实例才能更改，这个会更好。
> > > 所以这个限制不必删除。
> > 
> > 
> > 没有必要支持中途修改 pty，因为你修改了也不会生效，必须要重启。
> > 那么你反正要关闭一次实例程序，那么在关闭时就可以修改 pty 了。
> 
> 你再看一眼我前面写的。
> 
> > 主要是这个实例无法关闭。
> 
> > 你可以试一下，节点终端这个实例会自动重启。
> 
> 节点终端这个实例会自动重启，导致无法在关闭情况下修改pty设置（因为根本没有关闭状态。）

明白了，我已经尝试了一次。

除了 仿真终端 选项无法修改之外，其他选项均可正常操作，这个是符合预期的。

`仿真终端` 这个开关不需要管它， 如果不兼容的话会自动关闭，这个终端为了实现和 Shell 的同等效果，这个开关是一定要打开的。

你是出于什么原因想要关闭这个开关？

**Comment by bddjr** [comment]
假如调大字体，那么这个尺寸就不适合这个小屏幕了，此时需要调尺寸来适配这个字体大小。  
（字体大小为什么不是每个实例分开的啊）  
而且，命令终端不能全屏，这点就不是很认可了

**Comment by Bluemangoo** [comment]
实际上作为一个配置项应该让用户自己决定开关而不是无法调整。

**Comment by unitwk** [comment]
> 实际上作为一个配置项应该让用户自己决定开关而不是无法调整。

我理解你的意思，不过在运行时改变 `仿真终端` 设置可能会导致一些问题，因为命令的输入，内容的输出模式会在运行时就发生改变，但是实际上进程却不是 PTY 模式启动的进程（因为没有重启）。

所以只能这样了。

**Comment by Bluemangoo** [comment]
两种解决办法吧，要么允许这个实例关闭（不自动重启），要么修改pty设置后不应用先写到配置里面，我推荐两个都做吧。

如果有时间（最近两个礼拜应该没有）我可以自己改完交pr。

**Comment by unitwk** [comment]
不明白为什么你如此纠结这个 `仿真终端` 的开关，你如果不喜欢这一点可以自己 fork 一份用于自己的项目，不需要提交 PR，这个 PR 不会被接受。

如果用户将 `仿真终端` 关闭，那它也不叫 `命令终端` 了？连 vim,nano,top 等这些基础命令运行都会有问题。

**Comment by bddjr** [comment]
那假如还有一种可能，让用户可以关掉“命令终端”这个不必要的功能，这样甚至可以减少后台占用的进程

**Comment by unitwk** [comment]
> 那假如还有一种可能，让用户可以关掉“命令终端”这个不必要的功能，这样甚至可以减少后台占用的进程

最多省下 5～20MB 的内存占用，我想现在应该还是 2023 年。

这个功能只是让用户更方便的管理服务器，省去了一些面板无法处理的情况而需要登录 SSH 客户端的流程，这确实不是必备的功能。但如果这样说的话，那么分布式节点，Docker 镜像管理，多用户和数据监控等这些附加业务功能都是不必要的，因为只需要一个 Web Shell 就能开启和管理 MC 服务器。

**Comment by bddjr** [comment]
你对但使用者可以直接为节点创建bash实例比这好用

**Comment by Bluemangoo** [comment]
> 不明白为什么你如此纠结这个 `仿真终端` 的开关，你如果不喜欢这一点可以自己 fork 一份用于自己的项目，不需要提交 PR，这个 PR 不会被接受。
> 
> 如果用户将 `仿真终端` 关闭，那它也不叫 `命令终端` 了。在关闭仿真终端的情况下，连 vim,nano,top 等这些基础命令运行都会有问题。

也行吧。
