### ISSUE TITLE
当实例未关闭时 打开"高级实例设置"会一直加载

### ISSUE THREAD

**Issue by FallenCrystal** [MCSManager/MCSManager#874]
**MCSManager Version**
9.8.0

**System Info/Version**
Windows_NT win32 (Windows 10 Pro for Workstations 10.0.19045)

**Node Version**
v18.12.1

**Step**
创建并开启一个实例 然后点进`高级实例设置`会无限加载.
![image](https://user-images.githubusercontent.com/71176602/232798824-252cf5dc-16cf-478d-a3a4-cd4f89e1c80f.png)

> 此功能之前就可以在运行时点击并编辑其中的内容. 如果它现在不允许这么做 至少弹个提示吧..

**Comment by unitwk** [comment]
这个应该是一个BUG，设计上没有规定无限加载的情况。

有时间我再具体看看，谢谢你的反馈。

**Comment by bddjr** [comment]
linux表示没遇到

**Comment by FallenCrystal** [comment]
> linux表示没遇到

之前是没有的 是升级到9.8.0才有的问题

**Comment by bddjr** [comment]
我也是9.8.0，但CentOS，目前没遇到这问题

**Comment by FallenCrystal** [comment]
虽然不清楚是什么问题 但在我重新安装web服务之后解决
