### ISSUE TITLE
使用“实例特定配置”为低于1.20-pre1的MC版本直接修改motd会导致§乱码

### ISSUE THREAD

**Issue by bddjr** [MCSManager/MCSManager#875]
**MCSManager Version**
Web 9.8.0 Daemon 3.3.0
**System Info/Version**
CentOS 7
**Node Version**
6.14.6
**Step**
![image](https://user-images.githubusercontent.com/109646559/233055180-1920a6d0-154b-4d6a-8d02-3eb8d6142e6e.png)

原因：`§`字符没转码，不支持`\n`

***
2024年2月23日：  
我开免打扰了，这个项目怎么处理这个bug不关我事

**Comment by unitwk** [comment]
你这两个字符 `^A` 是什么字符？`§`保存之后错乱的字符吗？另外你这里似乎已经成功显示了不同的文字颜色？

**Comment by bddjr** [comment]
> 你这两个字符 `^A` 是什么字符？`§`保存之后错乱的字符吗？另外你这里似乎已经成功显示了不同的文字颜色？

我已经看了配置文件，`§`保存后就是`§`而不是`\u`开头的。这会导致Minecraft服务端将其转为奇怪的字符，图中的A就是。

**Comment by bddjr** [comment]
应当将所有不是ASCII里包含的字符都转为`\u`开头的。

**Comment by Bluemangoo** [comment]
> 应当将所有不是ASCII里包含的字符都转为`\u`开头的。

你怎么知道哪些要转码保存？直接保存是预期行为，其它编辑器也这样。

**Comment by unitwk** [comment]
> > 应当将所有不是ASCII里包含的字符都转为`\u`开头的。
> 
> 你怎么知道哪些要转码保存？直接保存是预期行为，其它编辑器也这样。

这一点你说的没错，这个BUG我没有办法修复，要修复只能做特殊处理，这会导致更多的问题（比如兼容更多 MC 服务端配置），这是一个无底洞。

你在保存配置文件时，可以尝试自己手动先转一下码，然后再粘贴到编辑器里面，再进行保存。

就好比 `VSCode` 工具，你不能指望它能自动帮你将 § 符号转成 \u 形式。

**Comment by bddjr** [comment]
你说得对，但基于您的理论可能产生了个新的问题，原文件我保存为\u开头的形式，被面板的“实例特定配置”读出来却显示为UTF8字符，而不是\u形式。

**Comment by unitwk** [comment]
好的，我已明白你的意思。

下个版本我会修复这个问题，在保存时会将内容转为  iso 8859-1 编码格式再进行保存，这个编码格式是 Java 程序认可的格式。

届时，所有非 ASCII 都会转成 \u 码，当然此功能只会在「实例特定配置」中的配置文件编辑生效，文本编辑器不包含此更新。

**Comment by bddjr** [comment]
好

**Comment by bddjr** [comment]
该bug在1.20-pre1已被mojang修复
https://bugs.mojang.com/browse/MC-2215

**Comment by unitwk** [comment]
> 该bug在1.20-pre1已被mojang修复 https://bugs.mojang.com/browse/MC-2215

那意味着我不需要管它了是吧，那就 close 吧。

**Comment by bddjr** [comment]
> > 该bug在1.20-pre1已被mojang修复 https://bugs.mojang.com/browse/MC-2215
> 
> 那意味着我不需要管它了是吧，那就 close 吧。

但MCSManager是一个面向全版本MC的管理面板

**Comment by huangsijun17** [comment]
> > > 该bug在1.20-pre1已被mojang修复 https://bugs.mojang.com/browse/MC-2215
> > 
> > 
> > 那意味着我不需要管它了是吧，那就 close 吧。
> 
> 但MCSManager是一个面向全版本MC的管理面板

能否先明确一下，这个MC的BUG覆盖的版本范围多大？如果只是几个测试版，或者非最终版的小版本，我不认为MCSM有必要为此去适配。

**Comment by bddjr** [comment]
![image](https://github.com/MCSManager/MCSManager/assets/109646559/7cb0275f-413e-4c1d-811d-85c5cf60fd9c)

**Comment by bddjr** [comment]
> > > > 该bug在1.20-pre1已被mojang修复 https://bugs.mojang.com/browse/MC-2215
> > > 
> > > 
> > > 那意味着我不需要管它了是吧，那就 close 吧。
> > 
> > 
> > 但MCSManager是一个面向全版本MC的管理面板
> 
> 能否先明确一下，这个MC的BUG覆盖的版本范围多大？如果只是几个测试版，或者非最终版的小版本，我不认为MCSM有必要为此去适配。

自己点开链接就能看到了，会列出mojang测试过的版本

**Comment by unitwk** [comment]
好的，有空我将继续修复这个问题。
