### ISSUE TITLE
关于开启discussion

### ISSUE THREAD

**Issue by Bluemangoo** [MCSManager/MCSManager#876]
希望可以开启项目的discussions。

可以在这里开对于新功能的投票（以决定优先性之类的）、让大家互帮互助之类的。

开启在settings - general - features - discussions(复选框)

**Comment by unitwk** [comment]
以前开过，没有什么太多作用，不开了

**Comment by Bluemangoo** [comment]
可以像pcl那边一样。那边的discussions还是挺活跃的。

**Comment by bddjr** [comment]
或许可以在面板UI里引流，例如在左侧插入 “为新功能投票” “问题反馈” “发送建议” 这类按钮

**Comment by unitwk** [comment]
> 或许可以在面板UI里引流，例如在左侧插入 “为新功能投票” “问题反馈” “发送建议” 这类按钮

这点可以考虑，下个版本看情况加入。

**Comment by Bluemangoo** [comment]
可以把打算做的功能和修复放在diacussions让大家投票哪个功能呼声最高。
