### ISSUE TITLE
终端未处理ANSI转义码"\033[2Km","\033[1Gm"

### ISSUE THREAD

**Issue by Bluemangoo** [MCSManager/MCSManager#877]
**MCSManager Version**: Panel 9.8.0;

**System Info/Version**: Windows 11 (Windows NT 10.0);

**Node Version**: v16.19.0

**Details**:

（在仿真终端情况下，普通情况下由于创建child_process使用了`stdio: "pipe"`并不会传递ANSI转义码）

终端未处理这两种ANSI转义码（已发现两种，可能还有更多）：

- "\033[2Km": 清除这行

- "\033[1Gm": 将光标移动到左侧

![image](https://user-images.githubusercontent.com/63218454/233757781-0a09f26d-b6bd-4610-982a-faea2b800331.png)

这是除了颜色外的ANSI转义码：

```
\33[0m 关闭所有属性 
\33[1m 设置高亮度 
\33[4m 下划线 
\33[5m 闪烁 
\33[7m 反显 
\33[8m 消隐 
\33[30m -- \33[37m 设置前景色 
\33[40m -- \33[47m 设置背景色 
\33[nA 光标上移n行 
\33[nB 光标下移n行 
\33[nC 光标右移n行 
\33[nD 光标左移n行 
\33[y;xH设置光标位置 
\33[2J 清屏 
\33[K 清除从光标到行尾的内容 
\33[s 保存光标位置 
\33[u 恢复光标位置 
\33[?25l 隐藏光标 
\33[?25h 显示光标

\x1b[2J\x1b[$;1H    $表示行位
```

**Comment by unitwk** [comment]
你是否开启了 `终端设置` -> `颜色渲染` 这个选项，如果开启，只需关闭即可。

然后确保你使用的是仿真终端模式，应该这些字符就全部正常了。

**Comment by Bluemangoo** [comment]
开了仿真，没开颜色，其它颜色渲染都正常，就这两个转义码有问题。

**Comment by Bluemangoo** [comment]
踢一下maintainer@unitwk 

开启仿真终端，关闭颜色渲染，问题仍然存在（本来就是这样的）。

如果你觉得是使用的问题你可以试试跑个yarn install或者之类的命令。我前面截图的那部分就是js的cli，ora的spinner。

**Comment by Bluemangoo** [comment]
踢一下maintainer @unitwk 

开启仿真终端，关闭颜色渲染，问题仍然存在（本来就是这样的）。

如果你觉得是使用的问题你可以试试跑个yarn install或者之类的命令。我前面截图的那部分就是js的cli，ora的spinner。

**Comment by unitwk** [comment]
好的，了解，不过我现在并不清楚是什么原因。
