### ISSUE TITLE
9.8.0"命令终端"关闭后反复自启

### ISSUE THREAD

**Issue by scattered-leaves** [MCSManager/MCSManager#881]
环境：win Server2022
版本：9.8.0
问题：“命令终端”中，点击“终止”按钮后反复自启动

**Comment by unitwk** [comment]
这个是故意设计成这样的，Web 终端被关闭后会自动重新启动一个新的终端供使用。

**Comment by Bluemangoo** [comment]
那个终止按钮应该改名叫重启，顺便挂个提示解释为什么没有终止。

**Comment by scattered-leaves** [comment]
但是没发修改终端参数了

**Comment by scattered-leaves** [comment]
不小心关闭了
但这样就不能修改终端参数了

**Comment by Bluemangoo** [comment]
> 不小心关闭了 但这样就不能修改终端设置了

看看这个issue。#870
