### ISSUE TITLE
rcon.password密码显示错误

### ISSUE THREAD

**Issue by WinterChocolates** [MCSManager/MCSManager#887]
**MCSManager Version** 9.8.0

**System Info/Version** ubuntu 22.04

**Node Version** v16.13.0

**Step**
RCON密码第一位是0就会显示不出来，在保存后重新进入server.properties配置文件，0不会显示
![image](https://github.com/MCSManager/MCSManager/assets/117161185/25ae232d-67f5-460d-833a-1be30cb551b5)
![image](https://github.com/MCSManager/MCSManager/assets/117161185/6bf87c2f-f3cd-4418-9012-31aa6bb222cf)

**Comment by huangsijun17** [comment]
隐式转换成了整数？

**Comment by Bluemangoo** [comment]
试试把密码用引号包裹。

**Comment by WinterChocolates** [comment]
密码栏也会显示引号

**Comment by Zhou-Shilin** [comment]
应该是MCSManager错误地将它看作整数而非字符串

**Comment by LazyCreeper** [comment]
这是因为在[此处](https://github.com/MCSManager/Daemon/blob/4a597b59f2674e36685720095cb3aacdb2321b39/src/entity/instance/process_config.ts#L37)MCSM会将.properties文件转换为JSON，JSON是不支持数字以0开头的
