### ISSUE TITLE
安装后没有出现提示,而且没有相关服务。

### ISSUE THREAD

**Issue by LiaoShuaiAcount** [MCSManager/MCSManager#888]
使用的命令是: wget -qO- https://gitee.com/mcsmanager/script/raw/master/setup_cn.sh | bash
启动服务的命令是: systemctl start mcsm-{daemon,web}.service
结果是: 
Failed to start mcsm-daemon.service: Unit mcsm-daemon.service not found.
Failed to start mcsm-web.service: Unit mcsm-web.service not found.

**Comment by LiaoShuaiAcount** [comment]
操作系统	
CentOS Stream 8 64bit

**Comment by LiaoShuaiAcount** [comment]
腾讯云服务器，所以是我哪里弄错了吗？

**Comment by unitwk** [comment]
重新安装再试试，如果依然无果，可以尝试手动安装，在 readme 上有写
