### ISSUE TITLE
在 Linux 桌面下，命令终端页面的仿真窗口终端大小显示不正确

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [MCSManager/MCSManager#892]
**MCSManager Version**
9.8.0

**System Info/Version**
Opensuse leap 15.4

**Node Version**
v14.19.1

**Step**
一键部署完成后，直接打开命令终端，使用一些长输出的命令，即可发现底下部分内容被遮挡，例如
~~~bash
journalctl -xeu mcsm-daemon
~~~

**Comment by unitwk** [comment]
是使用的手机访问的网页还是PC端？显示器是正常的笔记本大小吗？

如果方便可以上一张截图。

另外看下你的终端设置，把终端字体调小有助于修复。

**Comment by Mr-Ao-Dragon** [comment]
> 是使用的手机访问的网页还是PC端？显示器是正常的笔记本大小吗？
> 
> 如果方便可以上一张截图。
> 
> 另外看下你的终端设置，把终端字体调小有助于修复。

好的

**Comment by unitwk** [comment]
> > 是使用的手机访问的网页还是PC端？显示器是正常的笔记本大小吗？
> > 如果方便可以上一张截图。
> > 另外看下你的终端设置，把终端字体调小有助于修复。
> 
> 好的

不必回复「好的」这类词语，有空就上传一下，帮助我们分析问题。

**Comment by Mr-Ao-Dragon** [comment]
> > > 是使用的手机访问的网页还是PC端？显示器是正常的笔记本大小吗？
> > > 如果方便可以上一张截图。
> > > 另外看下你的终端设置，把终端字体调小有助于修复。
> > 
> > 
> > 好的
> 
> 不必回复「好的」这类词语，有空就上传一下，帮助我们分析问题。
![image](https://github.com/MCSManager/MCSManager/assets/67987607/356180d4-7b66-4b65-825a-08ddec092f2f)
抱歉，现在才回复，经过测试发现，microsoft-edge-beta会出现此问题

**Comment by huangsijun17** [comment]
> > > > 是使用的手机访问的网页还是PC端？显示器是正常的笔记本大小吗？
> > > > 如果方便可以上一张截图。
> > > > 另外看下你的终端设置，把终端字体调小有助于修复。
> > > 
> > > 
> > > 好的
> > 
> > 
> > 不必回复「好的」这类词语，有空就上传一下，帮助我们分析问题。
> > ![image](https://user-images.githubusercontent.com/67987607/242134480-356180d4-7b66-4b65-825a-08ddec092f2f.png)
> > 抱歉，现在才回复，经过测试发现，microsoft-edge-beta会出现此问题

看上去像是浏览器宽度过窄，模拟终端中内容超宽而在底部加入滚动条时，滚动条遮挡文字的问题。

**Comment by unitwk** [comment]
你这是什么操作系统？

**Comment by huangsijun17** [comment]
> 你这是什么操作系统？

[openSUSE](https://www.opensuse.org/)的[KDE Plasma桌面](https://kde.org/zh-cn/plasma-desktop/)，其他Linux的KDE我记得也是这样。

**Comment by Mr-Ao-Dragon** [comment]
> > > > > 是使用的手机访问的网页还是PC端？显示器是正常的笔记本大小吗？
> > > > > 如果方便可以上一张截图。
> > > > > 另外看下你的终端设置，把终端字体调小有助于修复。
> > > > 
> > > > 
> > > > 好的
> > > 
> > > 
> > > 不必回复「好的」这类词语，有空就上传一下，帮助我们分析问题。
> > > ![image](https://user-images.githubusercontent.com/67987607/242134480-356180d4-7b66-4b65-825a-08ddec092f2f.png)
> > > 抱歉，现在才回复，经过测试发现，microsoft-edge-beta会出现此问题
> 
> 看上去像是浏览器宽度过窄，模拟终端中内容超宽而在底部加入滚动条时，滚动条遮挡文字的问题。

感觉遮挡的不只是这一点点，似乎在滚动条存在时，px高度就无法正确对齐了

**Comment by unitwk** [comment]
可能是 Linux 下桌面浏览器的字体大小通病？你可以前往截图中右下角的「终端设置」按钮，里面有个字体设置，将字体调整到比现有字体更小的再试试，如果无效的话，说明浏览器无法支持更小的字体，这样的话我也不知道应该如何修复它。

**Comment by Mr-Ao-Dragon** [comment]
> 可能是 Linux 下桌面浏览器的字体大小通病？你可以前往截图中右下角的「终端设置」按钮，里面有个字体设置，将字体调整到比现有字体更小的再试试，如果无效的话，说明浏览器无法支持更小的字体，这样的话我也不知道应该如何修复它。

确实更小了，但遮挡更厉害了，要不增加折叠命令栏的功能？

**Comment by unitwk** [comment]
再看吧，兼容 Linux 桌面浏览器不是我的首要目标。

**Comment by Mr-Ao-Dragon** [comment]
> 再看吧，兼容 Linux 桌面浏览器不是我的首要目标。

好的，可折叠命令栏是否考虑？

**Comment by huangsijun17** [comment]
> > 再看吧，兼容 Linux 桌面浏览器不是我的首要目标。
> 
> 好的，可折叠命令栏是否考虑？

折叠也不会解决你这个问题。你这是浏览器里文本框textarea的样式显示兼容问题。

**Comment by Mr-Ao-Dragon** [comment]
> > > 再看吧，兼容 Linux 桌面浏览器不是我的首要目标。
> > 
> > 好的，可折叠命令栏是否考虑？
> 
> 折叠也不会解决你这个问题。你这是浏览器里文本框textarea的样式显示兼容问题。

好的，我会反馈给microsoft-edge
