### ISSUE TITLE
希望更新/安装实例功能可以支持从url下载的脚本

### ISSUE THREAD

**Issue by ea6d031** [MCSManager/MCSManager#894]
如题，我尝试了[这里面](https://cloud.tencent.com/developer/ask/sof/30896)的所有方法都没有成功…比如
`wget -qO- https://gitee.com/mcsmanager/script/raw/master/setup_cn.sh | bash`
会将脚本内容打印到控制台输出而不是执行…请问后续有支持打算吗？或者说是有其他方法？谢谢。
我知道可以先下载，我只是希望可以支持不用下载就能执行的功能…
哦对了，我还在使用mcsm 9.5.0。如果新版本支持那请原谅我没有试…
(私钥找不到了…我一直把mcsm当ssh/ftp客户端在用…没法更新)

**Comment by Bluemangoo** [comment]
bash $(wget -qO- https://gitee.com/mcsmanager/script/raw/master/setup_cn.sh)

**Comment by ea6d031** [comment]
> bash $(wget -qO- https://gitee.com/mcsmanager/script/raw/master/setup_cn.sh)

感谢开发者。但是执行后会报错
![image](https://github.com/MCSManager/MCSManager/assets/49561891/2b122415-c167-4139-8ccc-5422706ef474)
wget是已经安装了的。

**Comment by bddjr** [comment]
可以试着直接把命令写在一个sh文件里，然后运行这个sh文件（也就是再套一层sh）

**Comment by Bluemangoo** [comment]
@ea6d031 忘记加参数了。
```bash
/bin/bash -c "$(curl -fsSL https://gitee.com/mcsmanager/script/raw/master/setup_cn.sh)"
```

**Comment by Mr-Ao-Dragon** [comment]
现在还能上控制台的话就gen一个新的注入进去吧

**Comment by Bluemangoo** [comment]
给你个建议，可以新建一个终端叫bash。

**Comment by Bluemangoo** [comment]
@ea6d031 你是不是没加sudo？

**Comment by ea6d031** [comment]
mcsm不是默认root权限么？

**Comment by Bluemangoo** [comment]
?

**Comment by ea6d031** [comment]
![image](https://github.com/MCSManager/MCSManager/assets/49561891/c02a642a-85f4-44c6-b640-784a576aa757)
就这个

**Comment by ea6d031** [comment]
之前也是，它只认脚本的第一行，而且不认管道符或者&&啥的

**Comment by Bluemangoo** [comment]
不是，为什么要写在update里面啊。新建一个终端填bash。

而且/bin/是路径，直接写个bash就行。

**Comment by ea6d031** [comment]
> 啊，我正在写一篇..有点离经叛道的”教程“，为了使教程更简短，我希望可以将更新服务端的工作精简到一两行写完。我能想到的最佳的方案就是使用更新/安装实例功能执行我扔在gh的垃圾脚本，如果可以实现最好，不能实现我只好在教程里要求先下载脚本再上传再执行...总感觉这样不够优雅
是这样。脚本内容[在这里](https://github.moeyy.xyz/https://github.com/ea6d031/MCServer/raw/main/pur1.19.4.sh)

**Comment by ea6d031** [comment]
有的。我自己就有个这样的实例，被我当作ssh/ftp客户端用 (:

**Comment by Bluemangoo** [comment]
那你直接在这里面敲就行啊。

**Comment by ea6d031** [comment]
> > 啊，我正在写一篇..有点离经叛道的”教程“，为了使教程更简短，我希望可以将更新服务端的工作精简到一两行写完。我能想到的最佳的方案就是使用更新/安装实例功能执行我扔在gh的垃圾脚本，如果可以实现最好，不能实现我只好在教程里要求先下载脚本再上传再执行...总感觉这样不够优雅
> > 是这样。脚本内容[在这里](https://github.moeyy.xyz/https://github.com/ea6d031/MCServer/raw/main/pur1.19.4.sh)

特殊需求。我自己肯定有办法解决呀~

**Comment by Bluemangoo** [comment]
直接
```bash
bash -c "$(curl -fsSL https://gitee.com/mcsmanager/script/raw/master/setup_cn.sh)"
```

**Comment by ea6d031** [comment]
哥们！我需要使用更新/安装实例功能执行url上的脚本，不是真的要覆盖安装mcsm..
我想问的是有没有实现办法或者更新计划...😂

**Comment by Bluemangoo** [comment]
换链接就行，我只是举个例子。

**Comment by ea6d031** [comment]
还是不行。
![image](https://github.com/MCSManager/MCSManager/assets/49561891/96e1a204-a21c-483a-87bc-42b330881ace)
我下播了，明天再说。。

**Comment by Bluemangoo** [comment]
你到时候翻翻你bash在哪里吧。

**Comment by Bluemangoo** [comment]
```bash
whereis bash
```

**Comment by Bluemangoo** [comment]
哦我大概懂你什么意思了。

**Comment by Bluemangoo** [comment]
是你的bash不能解析下载的文件。

我的单行命令我直接在bash上面是能跑的。

**Comment by Bluemangoo** [comment]
你可以把你的脚本url发出来。

有可能是脚本问题。比如说可能要把文件头改成这样

```bash
#!/usr/bin/env bash
```

或者是文件开头的bom。

这样的情况挺常见的，你可以找找stackoverflow。这不是MCSManager的问题，这是你系统或脚本的问题。

**Comment by huangsijun17** [comment]
我就说一句，MCSManager是不计划提供远程下载服务端功能的。因为该功能会导致MCSM变成一个远程下载器，而非开服软件，容易被滥用。

**Comment by Bluemangoo** [comment]
@huangsijun17 你可能忘了quick install。

**Comment by huangsijun17** [comment]
> @huangsijun17 你可能忘了quick install。

MCSM外的独立程序，查、封方便很多。

**Comment by ea6d031** [comment]
脚本[在这里](https://github.moeyy.xyz/https://github.com/ea6d031/MCServer/raw/main/pur1.19.4.sh)
更改脚本内容后脚本依然无法被bash正确识别
![image](https://github.com/MCSManager/MCSManager/assets/49561891/6b824e4e-2e6a-42bf-9475-898af20822b8)

**Comment by Bluemangoo** [comment]
救不了你。自己查查是不是把系统玩坏了吧。

**Comment by ea6d031** [comment]
用终端没问题的。只有使用更新/安装实例功能有这个问题！

**Comment by ea6d031** [comment]
![image](https://github.com/MCSManager/MCSManager/assets/49561891/4f66422c-ec09-4282-a546-97fd3ef60095)
事这个(悲)

**Comment by Bluemangoo** [comment]
但是是bash报告找不到路径。

**Comment by huangsijun17** [comment]
盲猜一个，MCSM是通过systemd启动的，服务配置文件里没教程系统的环境变量，导致$PATH不全等，所以命令不正常。

**Comment by Bluemangoo** [comment]
@huangsijun17 直接/bin/bash也是出错的。你看看报错，mcsm启动了bash，只是bash不能解析sh脚本。

**Comment by huangsijun17** [comment]
> @huangsijun17 直接/bin/bash也是出错的。你看看报错，mcsm启动了bash，只是bash不能解析sh脚本。

bash也依靠各个环境变量来执行其他程序啊。

**Comment by bddjr** [comment]
我这在bash实例输入的 $PATH 只比自己在ssl后面多加了个 /usr/local/ssl/bin （其实系统本来就有了，这两个重复了但不影响），所以 $PATH 应该没问题

**Comment by huangsijun17** [comment]
> 我这在bash实例输入的 $PATH 只比自己在ssl后面多加了个 /usr/local/ssl/bin （其实系统本来就有了，这两个重复了但不影响），所以 $PATH 应该没问题

ssh和bash实例里都打一个`env`对比一下。

**Comment by bddjr** [comment]
> > 我这在bash实例输入的 $PATH 只比自己在ssl后面多加了个 /usr/local/ssl/bin （其实系统本来就有了，这两个重复了但不影响），所以 $PATH 应该没问题
> 
> ssh和bash实例里都打一个`env`对比一下。

两边都能打出来

**Comment by bddjr** [comment]
所以他的问题可能是没更新mcsm

**Comment by Bluemangoo** [comment]
可以自己做个东西运行。

**Comment by Bluemangoo** [comment]
c++，rust写一个还是很快的。

**Comment by bddjr** [comment]
私钥丢失可以建bash实例然后vim改ssh配置文件并重启sshd，再不行就找服务商解决

**Comment by Bluemangoo** [comment]
唉，你帮他吧。

**Comment by Bluemangoo** [comment]
rust的，eg `runbash https://github.moeyy.xyz/https://github.com/ea6d031/MCServer/raw/main/pur1.19.4.sh`
[runbash.zip](https://github.com/MCSManager/MCSManager/files/11635588/runbash.zip)

无所谓我会开摆。

大是因为里面有个完整的请求模块。

**Comment by huangsijun17** [comment]
> > > 我这在bash实例输入的 $PATH 只比自己在ssl后面多加了个 /usr/local/ssl/bin （其实系统本来就有了，这两个重复了但不影响），所以 $PATH 应该没问题
> > 
> > 
> > ssh和bash实例里都打一个`env`对比一下。
> 
> 两边都能打出来

对比一下两边的区别，看一下大不大。

**Comment by ea6d031** [comment]
哦，谢谢！那我改天试试，mcsm我也会试着更新的，麻烦了！
不得不说，mcsm开发者的态度真的很好…感谢你们！

**Comment by Bluemangoo** [comment]
嘿嘿。

虽然但是我们只是社区贡献者，开发者在那里摆烂睡大觉（）

这是开发者： unitwk

**Comment by ea6d031** [comment]
不好意思，我又来了:(
刚才我已经试着将MCSM更新到9.9，但是执行脚本依然会出错
![`8FIPBS%M%`XBVLBUX2( FG](https://github.com/MCSManager/MCSManager/assets/49561891/580a4c00-e8fa-46ae-967c-0d3a9282cf2b)
而您发的二进制文件应该也没法以url形式在更新/安装实例功能里执行吧？毕竟还需要给予执行权限...

**Comment by Bluemangoo** [comment]
chmod +x runbash

另外，你这是中文路径？

**Comment by unitwk** [comment]
> 嘿嘿。喜欢的话可以follow一下（不是
> 
> 虽然但是我们只是社区贡献者，开发者在那里摆烂睡大觉（）
> 
> 这是开发者： unitwk


> 开发者在那里摆烂睡大觉

这话我就不爱听了

**Comment by ea6d031** [comment]
> chmod +x runbash
> 
> 另外，你这是中文路径？

我想要实现不用下载就能执行的，给予执行权限需要下载了…
不是中文路径

**Comment by Bluemangoo** [comment]
那就帮不了你了。

但是你把这个配置到path里面就只要下载一次，剩下的时候只要执行就行。

下载的话用bash就能。上传也行吧。
