### ISSUE TITLE
Minecraft 1.19.2 console中文编码

### ISSUE THREAD

**Issue by caikun233** [MCSManager/MCSManager#900]
**MCSManager Version**
主进程9.9.0；守护进程3.4.0
**System Info/Version**
Windows Server 2022
**Node Version**
自带的不清楚
**Step**
在控制台中输入指令"say 你好（任意中文字符）“，守护进程实际上执行的是"say pppppppppp”。
我是没见过这种问题，输什么进去都是p，输多少个字符就有多少个p，控制台和游戏内输出的结果都是pppp。
但游戏内玩家说的话都正常。输入输出编码都是UTF-8，9.8.0版本是怎么调都乱码，升到9.9.0之后问题变成这样。
![屏幕截图 2023-06-04 203433](https://github.com/MCSManager/MCSManager/assets/69567735/8e22de64-dc03-452a-8c13-27bb61c68100)
![屏幕截图 2023-06-04 203545](https://github.com/MCSManager/MCSManager/assets/69567735/a33e0c39-5d32-4374-91c9-bf4b59f45f5f)

需要更多信息可以通过此issue联系。

**Comment by Bluemangoo** [comment]
低版本正常吗？

**Comment by caikun233** [comment]
我从9.6.0升上来，9.6.0是正常的，其他版本没试过，访问的浏览器是Firefox。另外问问我可以通过前置nginx来套用SSL吗？

**Comment by Bluemangoo** [comment]
我是指mc的低版本。

nginx是可以用的，我就在用。

**Comment by caikun233** [comment]
昨晚睡了，1.12.2会全都变成问号，数量也一样，并且我没有其他版本可以测试了。

**Comment by fred913** [comment]
输入GBK试试？

**Comment by fred913** [comment]
有没有开启仿真终端？

**Comment by caikun233** [comment]
仿真终端已经开启，输入输出从UTF-8到GB18030的所有排列组合全都试过，还是不行

**Comment by caikun233** [comment]
> 有没有开启仿真终端？

仿真终端已经开启，输入输出从UTF-8到GB18030的所有排列组合全都试过，还是不行

**Comment by huangsijun17** [comment]
> > 有没有开启仿真终端？
> 
> 仿真终端已经开启，输入输出从UTF-8到GB18030的所有排列组合全都试过，还是不行

确认几点，是否使用了Docker？MC的开服命令有没有指定UTF-8？

**Comment by caikun233** [comment]
> > > 有没有开启仿真终端？
> > 
> > 
> > 仿真终端已经开启，输入输出从UTF-8到GB18030的所有排列组合全都试过，还是不行
> 
> 确认几点，是否使用了Docker？MC的开服命令有没有指定UTF-8？

全都是Windows环境，没有使用Docker；开服命令没有指定编码

**Comment by huangsijun17** [comment]
> > > > 有没有开启仿真终端？
> > > 
> > > 
> > > 仿真终端已经开启，输入输出从UTF-8到GB18030的所有排列组合全都试过，还是不行
> > 
> > 
> > 确认几点，是否使用了Docker？MC的开服命令有没有指定UTF-8？
> 
> 全都是Windows环境，没有使用Docker；开服命令没有指定编码

试试看加一个UTF-8的Java启动参数：`-Dfile.encoding=UTF-8`

**Comment by caikun233** [comment]
> > > > > 有没有开启仿真终端？
> > > > 
> > > > 
> > > > 仿真终端已经开启，输入输出从UTF-8到GB18030的所有排列组合全都试过，还是不行
> > > 
> > > 
> > > 确认几点，是否使用了Docker？MC的开服命令有没有指定UTF-8？
> > 
> > 
> > 全都是Windows环境，没有使用Docker；开服命令没有指定编码
> 
> 试试看加一个UTF-8的Java启动参数：`-Dfile.encoding=UTF-8`

刚试了一下
![图片](https://github.com/MCSManager/MCSManager/assets/69567735/0f6782b7-e921-444e-a022-b7329a2d159c)
变这样了，游戏内看到的也一样

**Comment by huangsijun17** [comment]
> > > > > > 有没有开启仿真终端？
> > > > > 
> > > > > 
> > > > > 仿真终端已经开启，输入输出从UTF-8到GB18030的所有排列组合全都试过，还是不行
> > > > 
> > > > 
> > > > 确认几点，是否使用了Docker？MC的开服命令有没有指定UTF-8？
> > > 
> > > 
> > > 全都是Windows环境，没有使用Docker；开服命令没有指定编码
> > 
> > 
> > 试试看加一个UTF-8的Java启动参数：`-Dfile.encoding=UTF-8`
> 
> 刚试了一下 ![图片](https://user-images.githubusercontent.com/69567735/247395926-0f6782b7-e921-444e-a022-b7329a2d159c.png) 变这样了，游戏内看到的也一样

MCSM里的输入输出也是UTF-8吗？

**Comment by caikun233** [comment]
> > > > > > > 有没有开启仿真终端？
> > > > > > 
> > > > > > 
> > > > > > 仿真终端已经开启，输入输出从UTF-8到GB18030的所有排列组合全都试过，还是不行
> > > > > 
> > > > > 
> > > > > 确认几点，是否使用了Docker？MC的开服命令有没有指定UTF-8？
> > > > 
> > > > 
> > > > 全都是Windows环境，没有使用Docker；开服命令没有指定编码
> > > 
> > > 
> > > 试试看加一个UTF-8的Java启动参数：`-Dfile.encoding=UTF-8`
> > 
> > 
> > 刚试了一下 ![图片](https://user-images.githubusercontent.com/69567735/247395926-0f6782b7-e921-444e-a022-b7329a2d159c.png) 变这样了，游戏内看到的也一样
> 
> MCSM里的输入输出也是UTF-8吗？

是的

**Comment by huangsijun17** [comment]
另外，cmd下打一个`chcp`命令，看一下系统的默认编码。

**Comment by huangsijun17** [comment]
mcsm的终端最好也打印一下。

**Comment by caikun233** [comment]
> 另外，cmd下打一个`chcp`命令，看一下系统的默认编码。 mcsm的终端最好也打印一下。

C:\Users\Administrator>chcp
活动代码页: 936


say 你好
[14:29:38] [Server thread/INFO]: [Not Secure] [Server] ��
