### ISSUE TITLE
更换java版本后报错

### ISSUE THREAD

**Issue by pikachen-pick** [MCSManager/MCSManager#901]
问题原因如title所述

[MCSMANAGER] [ERROR] 检测到实例进程/容器启动失败（PID 为空），其可能的原因是：
1. 实例启动命令编写错误，请前往实例设置界面检查启动命令与参数。
2. 系统主机环境不正确或缺少环境，如 Java 环境等。

原生启动命令：
java -jar -Xmx300m server.jar

启动命令解析体:
程序：java
参数：["-jar","server.jar"]

请将此信息报告给管理员，技术人员或自行排查故障。

[MCSMANAGER] [Error] 实例启动失败，请检查启动命令，主机环境和配置文件等

**Comment by Bluemangoo** [comment]
java的事情来这里发什么。

**Comment by Bluemangoo** [comment]
-jar后面直接跟jar，不要在中间差参。
