### ISSUE TITLE
希望可以出一键卸载或者重装功能

### ISSUE THREAD

**Issue by zycn0910** [MCSManager/MCSManager#902]
希望可以出一键卸载或者重装功能，不然每次都回退服务器快照有点麻烦

**Comment by fred913** [comment]
能否具体讲下需求？为什么要重装mcsm，没有理解

**Comment by huangsijun17** [comment]
MCSM的安装可以分为几个部分：

- 基础环境nodejs的安装
- 前端项目的拉取
- 后端项目的拉取
- 服务的建立
- 项目配置

其中，基础环境nodejs是可以和别的项目复用的，不可能卸载。你如果想卸载MCSM，删除两个项目的文件夹并删除两个服务文件就可以了。

另外，安装脚本是默认覆盖安装的。
