### ISSUE TITLE
wss 无法连接，使用https无法连接实例，http就可以

### ISSUE THREAD

**Issue by wjqalan** [MCSManager/MCSManager#903]
**MCSManager Version**

**System Info/Version**

**Node Version**
![Screenshot_2023-06-14-20-42-11-243_com microsoft](https://github.com/MCSManager/MCSManager/assets/114663932/20dbd4b5-6faf-4aa3-9600-907ff061fc46)

*
![屏幕截图(18)](https://github.com/MCSManager/MCSManager/assets/114663932/96ef3568-1a36-4cb8-9d0e-8603fbf6a35f)
*Step**

**Comment by Bluemangoo** [comment]
你是不是frp转wss然后cf cdn上ssl的。

**Comment by wjqalan** [comment]
> 

没上ssl，websocket和https莫名其妙不和，本地连接有时加https都不行

**Comment by Bluemangoo** [comment]
本地没证书怎么加https，我内网一般都是Nginx域名解析内网ip，wildcard证书上ssl的。

frp公用机的话不需要cf的cdn。（使用cloudflare加速您的网站.jpg）

**Comment by wjqalan** [comment]
cf开灵活会自动赋予源服务器ssl证书

**Comment by wjqalan** [comment]
会变成部分不安全

**Comment by Bluemangoo** [comment]
不要套代理啊。把代理关了。如果frp服务器不是自己的是公用的，那一般都有防的，不需要考虑安全性，反而要考虑速度。
