### ISSUE TITLE
能出一个实例转移的功能吗？

### ISSUE THREAD

**Issue by yuchen1204** [MCSManager/MCSManager#907]
比如将实例A从节点1转移到节点2

**Comment by DanielToyama** [comment]
其实可以自己压缩然后复制，然后再使用已存在的文件夹创建实例就可以了

**Comment by Bluemangoo** [comment]
> 其实可以自己压缩然后复制，然后再使用已存在的文件夹创建实例就可以了

这不是一个很方便的方法，特别是需要转移大量实例的时候，重新填写命令行很烦。

建议支持导出备份(.tar)和导入。

**Comment by huangsijun17** [comment]
> > 其实可以自己压缩然后复制，然后再使用已存在的文件夹创建实例就可以了
> 
> 这不是一个很方便的方法，特别是需要转移大量实例的时候，重新填写命令行很烦。
> 
> 建议支持导出备份(.tar)和导入。

不建议附带实例打包的功能。只用导出配置即可。

**Comment by Alex6357** [comment]
附议，只需要保存配置即可，文件可以自己迁移。另外也可以出一个实例复制的功能。
