### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by BubaProgrammer** [MCSManager/MCSManager#908]
If you want, add backups to minecraft server, add allow to select path/disk

**Comment by huangsijun17** [comment]
This idea has been dismissed before. The main consideration is that the MC server may not support backup at runtime, which may result in bad backup files.
The backup recommendation for Minecraft is to use plugins or mods. Quite a few of them even support offsite backups.

**Comment by BubaProgrammer** [comment]
> This idea has been dismissed before. The main consideration is that the MC server may not support backup at runtime, which may result in bad backup files. The backup recommendation for Minecraft is to use plugins or mods. Quite a few of them even support offsite backups.

what about, making server backup when shutting down server?

**Comment by Bluemangoo** [comment]
you can write a bat/sh file to do that.

**Comment by BubaProgrammer** [comment]
> you can write a bat/sh file to do that.

i forgot i can do it, i will do sh script to backups
