### ISSUE TITLE
内存显示问题

### ISSUE THREAD

**Issue by PLOKMV** [MCSManager/MCSManager#912]
我的pi本地显示只用了50%多的内存
但是mcsmanager显示用了99%
性能没有完全被发挥导致运行mc很卡顿
云端输入的是1G，本地只是用了500多MB
云端写超过1G还会报错
怎么回事

**Comment by Bluemangoo** [comment]
1. 应该是本地显示问题。
2. 你Java是不是32位的。
3. 你要看已提交，那个才是真正内存占用。
4. 关mcsm什么事。

**Comment by huangsijun17** [comment]
> 1. 应该是本地显示问题。
> 2. 你Java是不是32位的。
> 3. 你要看已提交，那个才是真正内存占用。
> 4. 关mcsm什么事。

MCSM或许真有关系。MCSM的内存显示之前使用的是nodejs的原生API。在Windows和Linux下显示规则不同。一个包含系统预读取，一个不包含。

**Comment by unitwk** [comment]
> 我的pi本地显示只用了50%多的内存 但是mcsmanager显示用了99% 性能没有完全被发挥导致运行mc很卡顿 云端输入的是1G，本地只是用了500多MB 云端写超过1G还会报错 怎么回事

请告知你的系统类型和版本。

**Comment by PLOKMV** [comment]
Raspberry Pi Os Lite（64bit）
A port of Debian Bullseye with no desktop environment



在 2023-06-25 14:10:34，"unitwk" ***@***.***> 写道：

我的pi本地显示只用了50%多的内存 但是mcsmanager显示用了99% 性能没有完全被发挥导致运行mc很卡顿 云端输入的是1G，本地只是用了500多MB 云端写超过1G还会报错 怎么回事

请告知你的系统类型和版本。

**Comment by PLOKMV** [comment]
发错了 其他一样 是32位的



在 2023-06-25 14:10:34，"unitwk" ***@***.***> 写道：

我的pi本地显示只用了50%多的内存 但是mcsmanager显示用了99% 性能没有完全被发挥导致运行mc很卡顿 云端输入的是1G，本地只是用了500多MB 云端写超过1G还会报错 怎么回事

请告知你的系统类型和版本。

**Comment by huangsijun17** [comment]
> Raspberry Pi Os Lite（64bit） A port of Debian Bullseye with no desktop environment 在 2023-06-25 14:10:34，"unitwk" ***@***.***> 写道： 我的pi本地显示只用了50%多的内存 但是mcsmanager显示用了99% 性能没有完全被发挥导致运行mc很卡顿 云端输入的是1G，本地只是用了500多MB 云端写超过1G还会报错 怎么回事 请告知你的系统类型和版本。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

先换64位再试。32位Java最高支持1G虚拟机。

**Comment by PLOKMV** [comment]
本地检查过，没问题
Java是32位
已提交确实是900多，但是也也不能有500多的情况吧



在 2023-06-25 11:18:37，"huangsijun17" ***@***.***> 写道：

应该是本地显示问题。
你Java是不是32位的。
你要看已提交，那个才是真正内存占用。
关mcsm什么事。

MCSM或许真有关系。MCSM的内存显示之前使用的是nodejs的原生API。在Windows和Linux下显示规则不同。一个包含系统预读取，一个不包含。

**Comment by Bluemangoo** [comment]
已提交是真正内存占用，你看到的那个是有写入的部分。相差这么多很正常。如果你了解一下就会知道这是申请新内存空间时是否填入初始化数据的区别。
