### ISSUE TITLE
模拟控制台中文乱码

### ISSUE THREAD

**Issue by zhoo47** [MCSManager/MCSManager#913]
hi

我在使用网页模拟控制台时，中文会出现乱码的情况
![image](https://github.com/MCSManager/MCSManager/assets/106870412/68271a5e-61c0-463b-b733-39a860e302e7)
就像这样。

使用say输入中文时，游戏内能看见中文，但控制台还是乱码，改变控制台输入输出编码不起作用。
请问怎么能解决？

spigot，1.20.1

**Comment by Zhou-Shilin** [comment]
> hi
> 
> 我在使用网页模拟控制台时，中文会出现乱码的情况 ![image](https://user-images.githubusercontent.com/106870412/248551163-68271a5e-61c0-463b-b733-39a860e302e7.png) 就像这样。
> 
> 使用say输入中文时，游戏内能看见中文，但控制台还是乱码，改变控制台输入输出编码不起作用。 请问怎么能解决？
> 
> spigot，1.20.1

无法复现
![062B8048-498A-4CF4-9FEA-9D7A7DDD624D](https://github.com/MCSManager/MCSManager/assets/86581525/b387b626-c975-477a-b1d2-dab4ea8ebb63)

**Comment by huangsijun17** [comment]
操作系统？MCSM版本？Nodejs版本？控制台输入输出的编码方式？有无使用Docker？

**Comment by Deeam001** [comment]
也有类似情况，Windows11操作系统，打开方式为cmd，jdk版本是22，控制台编码已经调成了UTF-8

**Comment by Deeam001** [comment]
只不过是spigot 1.21
