### ISSUE TITLE
面板异常

### ISSUE THREAD

**Issue by StarsDream00** [MCSManager/MCSManager#914]
**MCSManager Version**
9.9.0+3.4.0
**System Info/Version**
WindowsNT 10.0.25379
**Node Version**
18.16.1
**Step**
无

主页一直加载，大部分功能无响应
![截屏2023-06-27 02 34 42](https://github.com/MCSManager/MCSManager/assets/100036558/87f5cf55-1fb2-4040-9074-e3a1bb93a48a)
![截屏2023-06-27 02 34 16](https://github.com/MCSManager/MCSManager/assets/100036558/5d768e55-1950-468d-93b2-86f0929fff98)

**Comment by unitwk** [comment]
重新安装面板，开放防火墙。

**Comment by StarsDream00** [comment]
> 重新安装面板，开放防火墙。

试过保留数据重新部署了，效果相同
防火墙是开的

**Comment by unitwk** [comment]
升级NodeJS运行时环境，可以升级到最新版，或者 v16.16.0 版本。你这个很有可能是NodeJS环境低于14的原因。

输入 `node -v` 即可查看你现在的 NodeJS 环境。

**Comment by StarsDream00** [comment]
> 升级NodeJS运行时环境，可以升级到最新版，或者 v16.16.0 版本。你这个很有可能是NodeJS环境低于14的原因。
> 
> 
> 
> 输入 `node -v` 即可查看你现在的 NodeJS 环境。

图里有写node版本（
我之前用的20，出了问题之后换成了18LTS但是没什么效果

**Comment by Bluemangoo** [comment]
要16:(

**Comment by StarsDream00** [comment]
> 要16:(

必须等于16吗

**Comment by StarsDream00** [comment]
补充一下，面板是正常使用过的，不知道哪天突然就这样了

**Comment by huangsijun17** [comment]
请问，能否直接在浏览器使用http协议访问后端？以及`./socket.io/`、`./upload/`、`./download/`这三个目录？

**Comment by StarsDream00** [comment]
> 请问，能否直接在浏览器使用http协议访问后端？以及`./socket.io/`、`./upload/`、`./download/`这三个目录？

请问您说的后端指的是？

**Comment by Bluemangoo** [comment]
18可能有些依赖会出错。

后端指daemon端24444.

**Comment by StarsDream00** [comment]
> 18可能有些依赖会出错。
> 
> 
> 
> 后端指daemon端24444.

守护进程可以访问

**Comment by Bluemangoo** [comment]
> 请问，能否直接在浏览器使用http协议访问后端？以及`./socket.io/`、`./upload/`、`./download/`这三个目录？

@huangsijun17 那个是daemon的，它的问题不在daemon在web。

**Comment by Bluemangoo** [comment]
@StarsDream00 你看看web后端有没有报错之类的，给个log/stdout截图？

**Comment by StarsDream00** [comment]
> @StarsDream00 你看看web后端有没有报错之类的，给个log/stdout截图？

两边的日志都没有错误，网页端只有http消息，守护程序只有会话消息

**Comment by Bluemangoo** [comment]
看看网页端请求。

**Comment by huangsijun17** [comment]
浏览器里有没有报错？包括JS和资源请求的。

**Comment by StarsDream00** [comment]
> 浏览器里有没有报错？包括JS和资源请求的。

Safari 17.0
```
[Error] TypeError: Attempting to define property on object that is not extensible. — chunk-vendors.66520c06.js:106:55463
	oi (chunk-vendors.66520c06.js:106:85850)
	ri (chunk-vendors.66520c06.js:106:85803)
	ti (chunk-vendors.66520c06.js:106:85334)
	Ei (chunk-vendors.66520c06.js:106:87045)
```
```
[Error] TypeError: Attempting to define property on object that is not extensible. — chunk-vendors.66520c06.js:16:7711
	oi (chunk-vendors.66520c06.js:106:85850)
	ri (chunk-vendors.66520c06.js:106:85803)
	（匿名函数） (chunk-vendors.66520c06.js:106:85459)
```
```
[Error] TypeError: null is not an object (evaluating 'i.emitsOptions') — chunk-vendors.66520c06.js:106:38898
	oi (chunk-vendors.66520c06.js:106:85850)
	ri (chunk-vendors.66520c06.js:106:85803)
	ti (chunk-vendors.66520c06.js:106:85334)
	Ei (chunk-vendors.66520c06.js:106:87045)
```

**Comment by Bluemangoo** [comment]
看一下web后端的stdout。

**Comment by Bluemangoo** [comment]
再看一下浏览器网络(Network)栏有没有502的请求。

**Comment by StarsDream00** [comment]
> 看一下web后端的stdout。

跑在系统底下看不着，但是日志正常

> 再看一下浏览器网络(Network)栏有没有502的请求。

没有

**Comment by Bluemangoo** [comment]
试试重装mcsm（把node_modules和app.js替换了就行

**Comment by StarsDream00** [comment]
> 试试重装mcsm（把node_modules和app.js替换了就行

重部署过了无效（上面说过了）

**Comment by StarsDream00** [comment]
又重新npm i了一遍，功能恢复正常了，但是监控还是一直在加载

**Comment by unitwk** [comment]
> 给web又重新npm i了一遍，功能恢复正常了，但是监控还是一直在加载，实例的玩家数量折线图也不显示了

有可能是 Daemon 所在机器的 Node 版本过低，可以检查一下，如果依然没有问题，那我也不清楚你为何会出现这种情况。

**Comment by StarsDream00** [comment]
> > 给web又重新npm i了一遍，功能恢复正常了，但是监控还是一直在加载，实例的玩家数量折线图也不显示了
> 
> 
> 
> 有可能是 Daemon 所在机器的 Node 版本过低，可以检查一下，如果依然没有问题，那我也不清楚你为何会出现这种情况。

两个都是一样的，我怀疑是npm包的问题🤔

**Comment by StarsDream00** [comment]
完了又寄了😭
