### ISSUE TITLE
环境变量支持

### ISSUE THREAD

**Issue by TomyJan** [MCSManager/MCSManager#916]
是否可以支持设置环境变量? 

我无法使用 MCSM 运行 .net 应用, 会报错 `The user's home directory could not be determined. Set the 'DOTNET_CLI_HOME' environment variable to specify the directory to use.`

尝试了很多歪门邪道都没解决, 最后只得用 supervisor 设置了环境变量 `environment=DOTNET_CLI_HOME=/root` 才跑起来
但是 supervisor 管理起来很不方便... 所以希望开发大大是否能够提供设置环境变量的功能, 或者运行 .net 项目的指引

**Comment by Bluemangoo** [comment]
往daemon项目根目录新建一个.env文件写入`environment=DOTNET_CLI_HOME=/root`试试。

**Comment by huangsijun17** [comment]
应该是systemd启动时没有继承一系列环境变量的设置。

**Comment by TomyJan** [comment]
> 往daemon项目根目录新建一个.env文件写入`environment=DOTNET_CLI_HOME=/root`试试。

还是没用==
