### ISSUE TITLE
I wrote some OpenRC scripts to run MCSManager as a service with OpenRC. Should I open a pull request?

### ISSUE THREAD

**Issue by DerVerruckteFuchs** [MCSManager/MCSManager#918]
I have adapted the [systemd service unit files](https://docs.mcsmanager.com/#/getting-started/linux-service) into OpenRC scripts to run on my server. I figured I may as well share them while I am at it. This enables MCSManager to be run as a service on OpenRC based Linux distributions like Alpine Linux. Alpine Linux is popular for containers like LXC and Docker. This could open up the possibility for making MCSManager deployable via Docker and _maybe_ a TurnKey LXC LinuX Container. I need to look a bit deeper at TurnKey before being completely certain of that.

I am testing this on Alpine Linux 3.18.2 (with nodejs 18.16.1), but it should run on any version that has a compatible version of nodejs. The oldest compatible version of Alpine Linux seems to be 3.13, as it ships with nodejs version 14.20.1 (the `README.md` specifies 14.17.6 or newer). Alpine Linux 3.12 is a bit too old, since it ships with nodejs version 12.22.12 (the `nodejs-current` package is only 14.5.0).

The daemon script gets saved at `/etc/init.d/mcsm-daemon`:
```
#!/sbin/openrc-run

name="MCSManager Daemon"
command="/usr/bin/node /opt/mcsmanager/daemon/app.js"
command_background="yes"
directory="/opt/mcsmanager/daemon"
pidfile="/var/run/mcsm-daemon.pid"
output_log="/var/log/mcsm/daemon.log"
error_log="/var/log/mcsm/daemon.err"
supervisor="supervise-daemon"

depend() {
	need net localmount
	use logger
	after firewall
}
```

The web script gets saved at `/etc/init.d/mcsm-web`:
```
#!/sbin/openrc-run

name="MCSManager Web"
command="/usr/bin/node /opt/mcsmanager/web/app.js"
command_background="yes"
directory="/opt/mcsmanager/web"
pidfile="/var/run/mcsm-web.pid"
output_log="/var/log/mcsm/web.log"
error_log="/var/log/mcsm/web.err"
supervisor="supervise-daemon"

depend() {
	need net localmount
	use logger
	after firewall
}
```

I can also open a pull request for updating the English documentation on how to use the OpenRC scripts, if it is desired. There are a few more small steps beyond just saving the above files into their respective directories.

**Comment by unitwk** [comment]
Of course, you can submit PR in this repository.

https://github.com/MCSManager/Documentation

You can create a new section based on this file:

https://github.com/MCSManager/Documentation/blob/main/_sidebar.md
