### ISSUE TITLE
我不知道这个到底算不算BUG、折腾几天问题依旧

### ISSUE THREAD

**Issue by LinKin-tech** [MCSManager/MCSManager#919]
**MCSManager Version**
MCSManager_v9.9.0_CN
**System Info/Version**
Windows Server 2019 Datacenter_x64
**Node Version**
v18.12.1
**Step**
面板控制端采用了宝塔面板的Nginx反向代理，反代关闭了缓存，域名通过了阿里云CDN加速，关闭了缓存，守护进程节点使用公网IP直连，未走Nginx反代，
浏览器访问面板端需要强制刷新页面。。可是获取不到远程守护节点数据，使用的是浏览器第一次访问到的页面，就算把后台面板端关闭CTRL+F5强制刷新也是可以正常访问到页面，但是获取不到数据，点击退出管理员显示成功退出，可是还是会回到控制面板首页，点了退出后在新建实例显示ERROR:[Forbidden]令牌(Token)验证失败，拒绝访问，证明浏览器是有退出的，可是页面缓存还在，使用IP直接打通端口方式时没有出现过这个BUG存在，不知道到底是哪里的问题。。

**Comment by Bluemangoo** [comment]
你看看daemon后台有没有验证消息。

**Comment by LinKin-tech** [comment]
> 你看看daemon后台有没有验证消息。

有验证。后台会报user undefined

**Comment by Bluemangoo** [comment]
截图。

**Comment by Bluemangoo** [comment]
可以试试拿源码跑。

**Comment by Bluemangoo** [comment]
> 可以试试拿源码跑。

在这两行中间加个

```typescript
console.log(`Debug: auth with key ${data}, should be ${globalConfiguration.config.key}`);
```

https://github.com/MCSManager/Daemon/blob/4a597b59f2674e36685720095cb3aacdb2321b39/src/routers/auth_router.ts#L45-L46

连接的时候看看输出对不对。

**Comment by Bluemangoo** [comment]
user undefined那是你看错控制台了，看daemon控制台不是web的。
