### ISSUE TITLE
控制面板断线

### ISSUE THREAD

**Issue by Skely0528** [MCSManager/MCSManager#922]
**MCSManager Version**
9.9.0

**System Info/Version**
Windows Server 2012 R2

**Node Version**
v18.12.1

**Daemon Version**
3.4.0

面板是刚装的 最新版本。用着Windows Server 2012 R2。
最近一直有以下的问题，有时会断线，如下面照片的问题。能知道有什么解决办法吗？

照片里涂红色的都是FQDN, xxx.xxxxxx.xxx 把它当作 abc.1234.com 就好了
通常连去面板都是用IP http://abc.1234.com:22222
Daemon是abc.1234.com 然后 22223

有时一开面板时，会一直像一下照片那样，持续30秒以上
![loading](https://github.com/MCSManager/MCSManager/assets/86063544/3b9e8f81-708d-4a70-9717-53da30704ddd)

过后，他就会像这样
![network error pls refresh](https://github.com/MCSManager/MCSManager/assets/86063544/27205c77-9f8f-4c6b-841a-8d22d43d259e)

偶尔也会突然这样
![network error](https://github.com/MCSManager/MCSManager/assets/86063544/c86536ff-0c25-4b57-beed-1d0c3aeeda66)

偶尔，按进去服务器的控制面板时，他就会这样持续加载
![持续加载](https://github.com/MCSManager/MCSManager/assets/86063544/8fa4a170-f9c1-4862-bf0d-cdbb3d1da239)

差不多30秒后，就像以下的图片了
![daemon  error](https://github.com/MCSManager/MCSManager/assets/86063544/a6b48a3c-d3e1-4dd9-9c78-c36394d3176c)

**Comment by Bluemangoo** [comment]
那是你自己网络问题。

**Comment by Skely0528** [comment]
是在port forwarding的地方出问题了吗？还是我尝试把panel和daemon的port再改成别的？之前也是用着MCSManager面板，可是是旧的版本，现在更新了后就这样了 之前不会有断线的问题  重启了路由器之类的都还是一样 大神有什么建议吗请问

**Comment by Skely0528** [comment]
我找到问题了，是控制面板没有在跑，好像卡着了那样。 请问一下，重启面板的话需要把全部minecraft服务器关闭吗？

**Comment by Bluemangoo** [comment]
是这样的。
