### ISSUE TITLE
实例-事件任务-自动重启失效 Auto Restart is not working

### ISSUE THREAD

**Issue by Zhou-Shilin** [MCSManager/MCSManager#923]
**MCSManager Version**
9.9.0
**System Info/Version**
Ubuntu Server 22.04.2 LTS
`82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023 5.15.0-75-generic`
**Node Version**
`v14.19.1`
**Step**
1. Start a new application (Minecraft Arclight 1.18.2)
2. Go to `Function Group -> Event Tasks`, enable `Auto Restart`
3. Waiting for your server to crash...
4. It won't auto restart.

**Comment by unitwk** [comment]
The automatic restart feature can only be triggered when it detects the Java process exiting. If the process enters a state of false death or freezes, it cannot be detected.

In summary, it cannot detect all crashes.

**Comment by Zhou-Shilin** [comment]
> The automatic restart feature can only be triggered when it detects the Java process exiting. If the process enters a state of false death or freezes, it cannot be detected.
> 
> In summary, it cannot detect all crashes.

Can MCSManager add a new option in the advanced configuration, "Determine if Auto Restart is required by console output", the default is no. When the user enables this option, it also needs to enter what input is detected on the console before auto restart is required, such as "Stopping Server".

**Comment by Zhou-Shilin** [comment]
> The automatic restart feature can only be triggered when it detects the Java process exiting. If the process enters a state of false death or freezes, it cannot be detected.
> 
> In summary, it cannot detect all crashes.

@unitwk But MCSManager **did** find that the instance was closed. There's a "Start" button.
![9D771C98-2237-461B-B559-94F9A94B3514](https://github.com/MCSManager/MCSManager/assets/86581525/69577472-8b65-4e9f-b7cc-68763f8b9da1)

**Comment by Zhou-Shilin** [comment]
@unitwk Won't fix? or?

**Comment by Zhou-Shilin** [comment]
@unitwk Hello? Maybe I should close it?

**Comment by unitwk** [comment]
Thanks for the feedback, based on your info this could be a bug but I'm not sure how to reproduce it.If I run into this problem, I'll fix it when I get a chance.
