### ISSUE TITLE
Cloudflare代理后无法连接节点

### ISSUE THREAD

**Issue by abwuge** [MCSManager/MCSManager#924]
**MCSManager Version**
9.9.0
**System Info/Version**
Windows Server 2022 Datacenter 10.0.20348
**Node Version**
v18.12.1
**Step**
1.IP通过Cloudflare绑定域名，并**开启**代理
![image](https://github.com/MCSManager/MCSManager/assets/81455573/83d5f921-2290-476c-95de-b726c3a9318e)
2.在Cloudflare的规则->Origin Rules中，添加访问域名自动重定向到23333端口
![image](https://github.com/MCSManager/MCSManager/assets/81455573/af70fbd9-3100-4f03-a7db-0837470b9d96)
3.访问域名，能正确访问到MCSManager web面板
![image](https://github.com/MCSManager/MCSManager/assets/81455573/96c9f99c-338d-4609-af42-6d8268c637d3)
4.在应用实例中选择任意一个节点（无论是公网ip直连、域名、localhost）的任意一个实例，均出现连接到远程节点错误。
-----
1.原使用Ubuntu服务器，仍有相同问题
2.浏览器直连错误界面显示的ip:port（去掉wss://）可以正常显示如下界面。
![image](https://github.com/MCSManager/MCSManager/assets/81455573/a86b781c-9bae-4ffc-8b1f-37b24eefd906)
3.一旦换为ip:23333或domin:port的访问形式后，不出现上述问题。
-----
不知道是因为Cloudflare代理的原因还是Cloudflare端口转发的原因。但我希望MCSManager可以解决这个问题。

**Comment by Zhou-Shilin** [comment]
![44704C18-1B0E-4CA1-B30B-DE63D3B2839B](https://github.com/MCSManager/MCSManager/assets/86581525/fb1d64e7-4ea8-475f-8dd6-e137e7525a29)
Try to fill in your domain name here

**Comment by bddjr** [comment]
~~为啥要用cloudflare减速器代理前端啊~~

你这个情况可能是因为你的节点地址的配置有问题，你是打算让节点流量直连 还是走cloudflare

**Comment by WitheredWinter** [comment]
只要不使用HTTPS协议就行，如果访问web面板使用的是HTTPS（尤其是CF的免费证书），则连接实例时会使用wss；如果访问web面板使用的是HTTP，则连接实例时会使用ws。建议你使用HTTP。如果开启了CF的SSL加密，关掉。
![image](https://github.com/MCSManager/MCSManager/assets/123742753/240c5969-bc46-4705-9656-4df6086b15dc)

**Comment by bddjr** [comment]
居然有人回答一个很无厘头的问题😂

我建议直接选择不用cloudflare

**Comment by abwuge** [comment]
> ~为啥要用cloudflare减速器代理前端啊~
> 
> 你这个情况可能是因为你的节点地址的配置有问题，你是打算让节点流量直连 还是走cloudflare

为了使用它的端口转发功能，只是不想通过ip:port方式访问。

**Comment by abwuge** [comment]
> 只要不使用HTTPS协议就行，如果访问web面板使用的是HTTPS（尤其是CF的免费证书），则连接实例时会使用wss；如果访问web面板使用的是HTTP，则连接实例时会使用ws。建议你使用HTTP。如果开启了CF的SSL加密，关掉。 ![image](https://private-user-images.githubusercontent.com/123742753/301649373-240c5969-bc46-4705-9656-4df6086b15dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NjY4MzksIm5iZiI6MTcwNzQ2NjUzOSwicGF0aCI6Ii8xMjM3NDI3NTMvMzAxNjQ5MzczLTI0MGM1OTY5LWJjNDYtNDcwNS05NjU2LTRkZjYwODZiMTVkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQwODE1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2ZhNGJhMmE4YTM1ZjY0NjM5ZTQxNDc2YTM2YzU4ZDY0YWRiZmQxNmM0ZDdkYTdlNTNkZmUwM2M3ZjE0MDU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fMMEjYRtMjAW5dMHQlUD6J_Gb9nLVvSknzdfx0B9rHw)

谢谢回复！

**Comment by bddjr** [comment]
您吉祥

> 为了使用它的端口转发功能，只是不想通过ip:port方式访问。

**Comment by abwuge** [comment]
> ![44704C18-1B0E-4CA1-B30B-DE63D3B2839B](https://private-user-images.githubusercontent.com/86581525/252531108-fb1d64e7-4ea8-475f-8dd6-e137e7525a29.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0Njc1NTUsIm5iZiI6MTcwNzQ2NzI1NSwicGF0aCI6Ii84NjU4MTUyNS8yNTI1MzExMDgtZmIxZDY0ZTctNGVhOC00NzVmLThkZDYtZTEzN2U3NTI1YTI5LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQwODI3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Mjk3NWNhM2Q4NmI1ZDRiNTBlMmEwOGY5NjAyZjI4MDM4Mjc3Mzg2M2UxMGRkM2I0N2U3MzBlMjBhNzE3YTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EE5D5Bk0uthm3N61datC2Drn43HbHAWfu5-ePY3yJNU) Try to fill in your domain name here. Note that the _web_ use port 23333 but application use port 24444, so don't use port 23333 here.

Thank you for your prompt reply. I’m sorry for replying late due to some reasons, but the method you suggested did not work for me. It prompted me “Browser cannot connect to wss://my.domain.here:24444”. But when I use the browser to visit my.domain.here:24444, it correctly returns "[MCSManager Daemon] Status: OK | reference: https://mcsmanager.com/". I tried the method provided by WitheredWinter and it worked. Thank you again for your help!
