### ISSUE TITLE
会突然未知关机

### ISSUE THREAD

**Issue by zsanf** [MCSManager/MCSManager#925]
**MCSManager Version**2

**System Info/Version**124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 5.4.0-110-generic

**Node Version**v14.19.1

**Step**
使用面板运行开服程序，一开始好好的，但不知为何到后来服务器在没有人操作的情况下被关闭了，日志里也没有任何信息。已经出现多次
![Screenshot_20230705_185739_com microsoft emmx](https://github.com/MCSManager/MCSManager/assets/98582299/4cf36b13-7b54-4b28-9a87-5dd06a5ee96a)

**Comment by zsanf** [comment]
搞错了面板端的版本为9.9.0

**Comment by huangsijun17** [comment]
自动关闭服务器？服务端？
自动关闭服务器和面板什么关系？

**Comment by huangsijun17** [comment]
> 搞错了面板端的版本为9.9.0

github的issues可以编辑。

**Comment by ApartTUSITU** [comment]
检查下你的服务器是否有问题

**Comment by unitwk** [comment]
大概率是内存不足，被系统强制杀死而成。
