### ISSUE TITLE
[Help Wanted]: Discussion on the necessity of `RedisStorage`

### ISSUE THREAD

**Issue by NaturalSelect** [MCSManager/MCSManager#927]
* For the production environment: redis is a volatile key value storage, misuse may cause users to lose data.
* For the debug environment: it is not as convenient and easy to debug as the memory data structure.

`RedisStorage` is in an awkward position, therefore, it is necessary to discuss the necessity of the feature.

**Comment by NaturalSelect** [comment]
Chinese version:
Title: 对`RedisStorage`必要性的讨论
Content:
* 对于生产环境： redis是一个易失性键值存储，误用可能导致用户丢失数据。
* 对于调试环境： 它不如内存数据结构方便和易于调试。

`RedisStorage`处在一个尴尬的位置上，因此有必要对这个功能的必要性进行讨论。

**Comment by NaturalSelect** [comment]
@unitwk Please give some feedbacks.

**Comment by unitwk** [comment]
没有明白你在说什么，Redis 支持已经在 MCSM 面板中，但是并不是推荐方式。

**Comment by NaturalSelect** [comment]
> 没有明白你在说什么，Redis 支持已经在 MCSM 面板中，但是并不是推荐方式。

Redis并不是为持久化数据设计的，它是一个缓存。
如果它正常关闭，用户将失去所有在Redis中保存的数据。所以我想让你重新考虑`RedisStorage`的必要性，考虑是否将它删除。
