### ISSUE TITLE
守护进程每隔一段时间无故被杀

### ISSUE THREAD

**Issue by ApartTUSITU** [MCSManager/MCSManager#929]
系统：Debian 11.8 x64
Node版本：v14.19.1
已安装软件：宝塔面板8.0

我服务器的守护进程不固定时间就被杀，不是系统问题，没有定时杀进程的任务，也没有人恶作剧，通常在内存占用马上满时被杀，sysytemctl看了一下时守护进程是被kill了，有人说宝塔会引起这问题，请问怎么解决？

**Comment by unitwk** [comment]
只能通过加内存的方式解决，内存不足系统会优先杀掉内存大户的程序以保证系统稳定性。

**Comment by bddjr** [comment]
把系统的OOM killer关掉

**Comment by mhc2910463910** [comment]
我执行npm start后显示unable to load configuration from local daemon ,please configure the daemon manually.面板访问不了。
