### ISSUE TITLE
players tab

### ISSUE THREAD

**Issue by BigDaddyKalash47** [MCSManager/MCSManager#930]
this is an amazing manager. ive been looking for something like this for years and ive finally found this. but there is only one feature missing and it is a players tab. Please add a tab where you can see and click on currently online players to quickly perform actions such as kick, ban, OP etc...

i have attached an example picture
![players](https://github.com/MCSManager/MCSManager/assets/98878011/0cda5096-0696-4ab6-bff0-32c348ef7ebc)
![main](https://github.com/MCSManager/MCSManager/assets/98878011/3b558f64-cf83-4c2c-b650-20b0dbee2ef7)

**Comment by unitwk** [comment]
Thanks for your feedback.
We don't have time to do these functions at present, and we can consider adding these functions in the future.

**Comment by Zhou-Shilin** [comment]
> this is an amazing manager. ive been looking for something like this for years and ive finally found this. but there is only one feature missing and it is a players tab. Please add a tab where you can see and click on currently online players to quickly perform actions such as kick, ban, OP etc...
> 
> i have attached an example picture ![players](https://user-images.githubusercontent.com/98878011/252146753-0cda5096-0696-4ab6-bff0-32c348ef7ebc.png) ![main](https://user-images.githubusercontent.com/98878011/252146754-3b558f64-cf83-4c2c-b650-20b0dbee2ef7.png)

You can use a plugin to do that. https://www.spigotmc.org/resources/playermanagementgui.91439/

**Comment by BigDaddyKalash47** [comment]
Plugins for Minecraft won’t work for me because I would need to be inside if the game to use.
There should be a gui like MC server soft, on this page 
![](https://mcsmanager.com/main.png)
it should be between operation and function OR under command history in my opinion.

**Comment by Zhou-Shilin** [comment]
> Plugins for Minecraft won’t work for me because I would need to be inside if the game to use. There should be a gui like MC server soft, on this page ![](https://camo.githubusercontent.com/0987ddffd7a2618dddb4603b5849e4beb914747e03567c54cdac84f29f87c3fc/68747470733a2f2f6d63736d616e616765722e636f6d2f6d61696e2e706e67) it should be between operation and function OR under command history in my opinion.

You can make a program with MCSManager API. If you want to use Python, [this one](https://github.com/Zhou-Shilin/BaimoMCSManager-API) may help you XD.

**Comment by BigDaddyKalash47** [comment]
> > Plugins for Minecraft won’t work for me because I would need to be inside if the game to use. There should be a gui like MC server soft, on this page ![](https://camo.githubusercontent.com/0987ddffd7a2618dddb4603b5849e4beb914747e03567c54cdac84f29f87c3fc/68747470733a2f2f6d63736d616e616765722e636f6d2f6d61696e2e706e67) it should be between operation and function OR under command history in my opinion.
> 
> You can make a program with [MCSManager API](https://docs.mcsmanager.com/#/zh-cn/apis/readme). If you want to use Python, [this one](https://github.com/Zhou-Shilin/BaimoMCSManager-API) may help you XD.

Unfortunately I dropped out of the programming course due to getting headaches when looking at code (it’s when looking at screens) for too long 😭

**Comment by BigDaddyKalash47** [comment]
> > Plugins for Minecraft won’t work for me because I would need to be inside if the game to use. There should be a gui like MC server soft, on this page ![](https://camo.githubusercontent.com/0987ddffd7a2618dddb4603b5849e4beb914747e03567c54cdac84f29f87c3fc/68747470733a2f2f6d63736d616e616765722e636f6d2f6d61696e2e706e67) it should be between operation and function OR under command history in my opinion.
> 
> You can make a program with [MCSManager API](https://docs.mcsmanager.com/#/zh-cn/apis/readme). If you want to use Python, [this one](https://github.com/Zhou-Shilin/BaimoMCSManager-API) may help you XD.

Also would it be possible to do what I need using the api? Adding a players tab to were I mentioned previously?

**Comment by Zhou-Shilin** [comment]
> > > Plugins for Minecraft won’t work for me because I would need to be inside if the game to use. There should be a gui like MC server soft, on this page ![](https://camo.githubusercontent.com/0987ddffd7a2618dddb4603b5849e4beb914747e03567c54cdac84f29f87c3fc/68747470733a2f2f6d63736d616e616765722e636f6d2f6d61696e2e706e67) it should be between operation and function OR under command history in my opinion.
> > 
> > 
> > You can make a program with [MCSManager API](https://docs.mcsmanager.com/#/zh-cn/apis/readme). If you want to use Python, [this one](https://github.com/Zhou-Shilin/BaimoMCSManager-API) may help you XD.
> 
> Also would it be possible to do what I need using the api? Adding a players tab to were I mentioned previously?

Player Tab can be done using Minecraft Rcon.

**Comment by Zhou-Shilin** [comment]
#972 (Plugin support)
