### ISSUE TITLE
[Major] 成功检测到实例关闭但是没有自动重启

### ISSUE THREAD

**Issue by Zhou-Shilin** [MCSManager/MCSManager#932]
**MCSManager Version**
9.9.0
**System Info/Version**
`#82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023 5.15.0-75-generic`
**Node Version**
v14.19.1
**Step**
1. 启动一个Minecraft Java版服务器并打开事件任务中的自动重启
2. 等待为了服务器崩溃
3. 状态显示“已关闭”但是没有自动重启
![777D8F3F-139F-43BD-AD78-04797C7EB083](https://github.com/MCSManager/MCSManager/assets/86581525/8b6c008f-a79d-4b01-9ec2-f04dee036b80)

**特别注意：MSCManager成功检测到了实例的关闭**

另注：如果你也遇到了同样的问题，并且情况紧急，可以尝试我的[这个项目](https://github.com/Zhou-Shilin/MCSMAR)作为*临时的*解决方案。

**Comment by Zhou-Shilin** [comment]
![53B4C73A-701F-4091-A631-651E80FBF10D](https://github.com/MCSManager/MCSManager/assets/86581525/15794995-606a-4a67-9da6-7a2fbcf519bc)
![E7E5C3D2-6CBF-49EF-8F88-B7B8AFA28179](https://github.com/MCSManager/MCSManager/assets/86581525/fda882cd-dfac-43db-9212-2586e9f62916)

**Comment by Bluemangoo** [comment]
崩溃了的确不会自动重启。

**Comment by Zhou-Shilin** [comment]
@unitwk 这个问题应该很好修复？毕竟MCSManager正常检测到了实例已经关闭了。当用户点击Stop按钮之后，临时记录60秒。面板一旦检测到实例关闭，看看是否之前在60内按下过Stop按钮，若无则自动重启。

**Comment by Zhou-Shilin** [comment]
> > @unitwk 这个问题应该很好修复？毕竟MCSManager正常检测到了实例已经关闭了。当用户点击Stop按钮之后，临时记录60秒。面板一旦检测到实例关闭，看看是否之前在60内按下过Stop按钮，若无则自动重启。
> 
> 60s内必须关闭？我不可以设置关闭服务端时备份地图吗？还是说大型整合包关闭也必须在60s内完成？

那就120秒？240秒？这个数值都可以调的，有必要抠字眼吗？

**Comment by unitwk** [comment]
你们不需要在意多少秒，用户点击Stop按钮之后应该本来就不会自动重启。这个逻辑做在 MCSM 里面是存在的，难道这个逻辑不生效吗？ @Zhou-Shilin 

这里的代码很明显的解释了如果满足忽略条件就不执行自动重启。

https://github.com/MCSManager/Daemon/blob/4a597b59f2674e36685720095cb3aacdb2321b39/src/entity/instance/instance.ts#L223C37-L223C37

这里是当用户按下「停止实例（Stop）」按钮时进行的更改。
https://github.com/MCSManager/Daemon/blob/4a597b59f2674e36685720095cb3aacdb2321b39/src/entity/commands/stop.ts#L14

**Comment by Zhou-Shilin** [comment]
> 你们不需要在意多少秒，用户点击Stop按钮之后应该本来就不会自动重启。这个逻辑做在 MCSM 里面是存在的，难道这个逻辑不生效吗？ @Zhou-Shilin
> 
> 这里的代码很明显的解释了如果满足忽略条件就不执行自动重启。
> 
> https://github.com/MCSManager/Daemon/blob/4a597b59f2674e36685720095cb3aacdb2321b39/src/entity/instance/instance.ts#L223C37-L223C37
> 
> 这里是当用户按下「停止实例（Stop）」按钮时进行的更改。 https://github.com/MCSManager/Daemon/blob/4a597b59f2674e36685720095cb3aacdb2321b39/src/entity/commands/stop.ts#L14

现在的问题是，用户没有按下Stop但是实例也不会自动重启

**Comment by Zhou-Shilin** [comment]
如果你也遇到了同样的问题，并且情况紧急，可以尝试我的[这个项目](https://github.com/Zhou-Shilin/MCSMAR)作为*临时的*解决方案。

**Comment by huangsijun17** [comment]
> > > @unitwk 这个问题应该很好修复？毕竟MCSManager正常检测到了实例已经关闭了。当用户点击Stop按钮之后，临时记录60秒。面板一旦检测到实例关闭，看看是否之前在60内按下过Stop按钮，若无则自动重启。
> > 
> > 
> > 60s内必须关闭？我不可以设置关闭服务端时备份地图吗？还是说大型整合包关闭也必须在60s内完成？
> 
> 那就120秒？240秒？放在高级设置里让用户根据实例关闭速度调整也是一个临时的解决方案。有必要抠字眼吗？

1. 加一个选项，一系列的参数，复杂度上去太多了。
2. MC整合包无法正常关闭本就是整合有问题。该处理的的为何无法关闭，而不是强行将其关闭。
3. 真要加守护进程，也应该是使用`Server List Ping`来制作一个电子狗。

**Comment by Zhou-Shilin** [comment]
@unitwk 1周过去了，这个问题进展如何？

**Comment by Zhou-Shilin** [comment]
> 加一个选项，一系列的参数，复杂度上去太多了。
@huangsijun17 很显然，我们需要先解决能不能用的问题，再去解决好不好用的问题。
我们需要先解决吃得饱饭的问题，再去解决饭好不好吃的问题。

**Comment by bddjr** [comment]
我之前发现的是，如果实例是以勾选的“自动启动”的方式被启动，则“自动重启”不生效，只有手动开启实例才生效。不知道现在的版本还是不是这样。
