### ISSUE TITLE
指定页面无法唤起键盘

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#934]
**MCSManager Version**
9.9.0
**System Info/Version**
Windows Server 2022 Datacenter 10.0.20348
**Node Version**
v18.12.1
**Step**
侧边栏/高级功能/用户管理/用户列表/根据名称搜索的搜索框无法唤起键盘，除非点击后切换至后台然后返回
使用的浏览器为Safari

**Comment by Zhou-Shilin** [comment]
> **MCSManager Version** 9.9.0 **System Info/Version** Windows Server 2022 Datacenter 10.0.20348 **Node Version** v18.12.1 **Step** 侧边栏/高级功能/用户管理/用户列表/根据名称搜索的搜索框无法唤起键盘，除非点击后切换至后台然后返回 使用的浏览器为Safari

使用Chrome浏览器，iOS 16.2 Developer Beta 2，首次点击唤起失败，再次点击即可唤起
