### ISSUE TITLE
小页面下快速开始排版错误

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#935]
MCSManager Version
9.9.0
System Info/Version
Windows Server 2022 Datacenter 10.0.20348
Node Version
v18.12.1
Step
![IMG_3747](https://github.com/MCSManager/MCSManager/assets/99535761/125bf52c-de48-4136-adf5-ca658bfae9bc)

**Comment by Bluemangoo** [comment]
这不算排版错误吧。

**Comment by XiaoXiaoYang233** [comment]
> 这不算排版错误吧。

电脑跟手机的对比一下，跟9.8对比一下，查看历史安装任务跑上面了

**Comment by Bluemangoo** [comment]
行吧这个好改，顺序换一下就行。

**Comment by unitwk** [comment]
这个排版就是这样设计的，没有必要改变，以后有机会重构一下前端。
