### ISSUE TITLE
不显示无法访问的驱动器

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#936]
![IMG_3748](https://github.com/MCSManager/MCSManager/assets/99535761/b7dad34f-ccff-48c0-9850-3bccfd06e000)
![IMG_3751](https://github.com/MCSManager/MCSManager/assets/99535761/cb15749c-058b-45a4-8b03-ce0d978e10cd)

**Comment by unitwk** [comment]
好的，后续会改进，但也可能不会修复，这个影响不大。
