### ISSUE TITLE
文件管理小页面下长文件名辨识度低

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#937]
![IMG_3753](https://github.com/MCSManager/MCSManager/assets/99535761/1d2337c9-4c10-44ad-9aad-3c7bf9f2beda)
个人感觉折叠起来辨识度低而且比较乱，9.8的时候挺好的

**Comment by unitwk** [comment]
已记录，后续我们会逐渐优化这个问题。
