### ISSUE TITLE
小页面下文件管理“操作”排版错误

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#938]
MCSManager Version
9.9.0
System Info/Version
Windows Server 2022 Datacenter 10.0.20348
Node Version
v18.12.1
Step
![IMG_3754](https://github.com/MCSManager/MCSManager/assets/99535761/031ecc31-a975-41bf-8f34-fb273945f410)

**Comment by unitwk** [comment]
已记录，后续我们会逐渐优化这个问题。
