### ISSUE TITLE
拔出驱动器后文件管理仍有访问驱动器的按钮

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#939]
MCSManager Version
9.9.0
System Info/Version
Windows Server 2022 Datacenter 10.0.20348
Node Version
v18.12.1
Step
拔出驱动器后文件管理仍有访问驱动器的按钮，除非重启守护进程

**Comment by unitwk** [comment]
那此时如何继续点击「驱动器」的按钮，会发生什么事情？得出什么错误？

**Comment by XiaoXiaoYang233** [comment]
> 那此时如何继续点击「驱动器」的按钮，会发生什么事情？得出什么错误？https://github.com/MCSManager/MCSManager/issues/936
见此
