### ISSUE TITLE
完善基岩版server.properties的提示

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#941]
enable-lan-visibility
Listen and respond to clients that are looking for servers on the LAN. This will cause the server
to bind to the default ports (19132, 19133) even when `server-port` and `server-portv6`
have non-default values. Consider turning this off if LAN discovery is not desirable, or when
running multiple servers on the same host may lead to port conflicts.
Allowed values: "true" or "false"

compression-algorithm
Determines the compression algorithm to use for networking
Allowed values: "zlib", "snappy"

player-movement-action-direction-threshold
The amount that the player's attack direction and look direction can differ.
Allowed values: Any value in the range of [0, 1] where 1 means that the
direction of the players view and the direction the player is attacking
must match exactly and a value of 0 means that the two directions can
differ by up to and including 90 degrees.

chat-restriction
Allowed values: "None", "Dropped", "Disabled"
This represents the level of restriction applied to the chat for each player that joins the server.
"None" is the default and represents regular free chat.
"Dropped" means the chat messages are dropped and never sent to any client. Players receive a message to let them know the feature is disabled.
"Disabled" means that unless the player is an operator, the chat UI does not even appear. No information is displayed to the player.

disable-player-interaction
If true, the server will inform clients that they should ignore other players when interacting with the world. This is not server authoritative.

client-side-chunk-generation-enabled
If true, the server will inform clients that they have the ability to generate visual level chunks outside of player interaction distances.

block-network-ids-are-hashes
If true, the server will send hashed block network ID's instead of id's that start from 0 and go up.  These id's are stable and won't change regardless of other block changes.

disable-persona
Internal Use Only

disable-custom-skins
If true, disable players customized skins that were customized outside of the Minecraft store assets or in game assets.  This is used to disable possibly offensive custom skins players make.

server-build-radius-ratio
Allowed values: "Disabled" or any value in range [0.0, 1.0]
If "Disabled" the server will dynamically calculate how much of the player's view it will generate, assigning the rest to the client to build.
Otherwise from the overridden ratio tell the server how much of the player's view to generate, disregarding client hardware capability.
Only valid if client-side-chunk-generation-enabled is enabled

—————————————————————

enable-lan-visibility
开启或关闭局域网发现功能。如果开启，服务器将绑定到默认端口（19132，19133），即使`server-port`和`server-portv6`
设置了非默认值。如果不希望局域网内其他客户端发现服务器，或者在同一主机上运行多个服务器可能导致端口冲突，可以考虑关闭此功能。
允许的值："true" 或 "false"

compression-algorithm
确定用于网络传输的压缩算法
允许的值："zlib"，"snappy"

player-movement-action-direction-threshold
玩家的攻击方向和视线方向可以有多大的差异。
允许的值：[0, 1] 范围内的任意值，其中 1 表示玩家的视线方向和攻击方向必须完全一致，而 0 表示两个方向可以相差最多 90 度。

chat-restriction
允许的值："None"，"Dropped"，"Disabled"
这表示对每个加入服务器的玩家应用的聊天限制级别。
"None" 是默认值，表示正常的自由聊天。
"Dropped" 表示聊天消息被丢弃，不会发送给任何客户端。玩家会收到一条消息，告知他们此功能已被禁用。
"Disabled" 表示除非玩家是管理员，否则聊天界面甚至不会出现。也不会向玩家显示任何信息。

disable-player-interaction
如果为 true，服务器将通知客户端在与世界交互时忽略其他玩家。这不是服务器权威性的。

client-side-chunk-generation-enabled
如果为 true，服务器将通知客户端它们有能力在玩家交互距离之外生成视觉层面的区块。

block-network-ids-are-hashes
如果为 true，服务器将发送哈希化的区块网络 ID，而不是从 0 开始递增的 ID。这些 ID 是稳定的，不会因为其他区块的变化而改变。

disable-persona
仅供内部使用

disable-custom-skins
如果为 true，禁用玩家自定义皮肤，这些皮肤是在 Minecraft 商店资源或游戏内资源之外自定义的。这是用来禁止可能冒犯性的玩家自制皮肤的。

server-build-radius-ratio
允许的值："Disabled" 或 [0.0, 1.0] 范围内的任意值
如果为 "Disabled"，服务器将动态计算生成多少玩家视野范围内的区块，剩余部分交由客户端生成。
否则根据覆盖比率告诉服务器生成多少玩家视野范围内的区块，忽略客户端硬件能力。
只有当 client-side-chunk-generation-enabled 开启时才有效

未在server.properties中提及但存在且没有加提示的
language=en_US
服务端语言设置

以上内容均为面板未添加的提示

**Comment by unitwk** [comment]
你可以给 UI 仓库添加代码：https://github.com/MCSManager/UI/blob/master/src/components/mc_process_config/bds_server.properties.vue

另外，你的排版很难看，下次注意一下。

**Comment by XiaoXiaoYang233** [comment]
> 你可以给 UI 仓库添加代码：https://github.com/MCSManager/UI/blob/master/src/components/mc_process_config/bds_server.properties.vue
> 
> 另外，你的排版很难看，下次注意一下。

我也不想，我都改了好几次，甚至纯文本粘贴都自动搞成这样

**Comment by XiaoXiaoYang233** [comment]
> 你可以给 UI 仓库添加代码：https://github.com/MCSManager/UI/blob/master/src/components/mc_process_config/bds_server.properties.vue
> 
> 另外，你的排版很难看，下次注意一下。

好的，我整理一下

**Comment by huangsijun17** [comment]
> > 你可以给 UI 仓库添加代码：https://github.com/MCSManager/UI/blob/master/src/components/mc_process_config/bds_server.properties.vue
> > 另外，你的排版很难看，下次注意一下。
> 
> 好的，我整理一下，有什么需要注意的吗？

你发的，我都看不清。

**Comment by XiaoXiaoYang233** [comment]
> > > 你可以给 UI 仓库添加代码：https://github.com/MCSManager/UI/blob/master/src/components/mc_process_config/bds_server.properties.vue
> > > 另外，你的排版很难看，下次注意一下。
> > 
> > 
> > 好的，我整理一下，有什么需要注意的吗？
> 
> 你发的，我都看不清。

已修改，去掉了#号注释

**Comment by huangsijun17** [comment]
明显拙劣的机翻。各种语序的倒置。
