### ISSUE TITLE
添加不同主机上的 Daemon 自动化添加到 Web 的方法

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [MCSManager/MCSManager#943]
如题，这对自动化部署，高可用将非常有用，建议添加。

**Comment by Bluemangoo** [comment]
web连daemon，你怎么反过来了。

**Comment by Mr-Ao-Dragon** [comment]
> web连daemon，你怎么反过来了。

为了自动化，由于key是daemon持有，所以反向连接是最合适的，
比如：小型mc云可以预装MCSM，直接向用户索要面板API信息，这样用户就不用去手动部署，而是直接等待节点自动添加到自己的面板。（只是一个应用场景的可能假设！不代表任何实施或设计！）

**Comment by Bluemangoo** [comment]
那么配置更为麻烦。比如，你怎么把web的url和key告诉daemon？

**Comment by Mr-Ao-Dragon** [comment]
> 那么配置更为麻烦。比如，你怎么把web的url和key告诉daemon？

可以考虑直接添加api,在用户在面板段确认后即可直接加入。
在直接添加api里可以考虑一个来源的机密字段，让用户设置某来源可以免确认添加，这样就能将mcsm作为虚拟机的模板，无需用户关心其具体细节。

**Comment by Bluemangoo** [comment]
你写配置吗？

**Comment by Bluemangoo** [comment]
现在哪有云服务商干这种事的。

**Comment by Mr-Ao-Dragon** [comment]
是的，我打算把mcsm的自动部署搞定，就差这个环节了

**Comment by Bluemangoo** [comment]
反正我不建议。

**Comment by Mr-Ao-Dragon** [comment]
或者考虑一个外置的配置生成器？通过自动化脚本调用后直接返回生成的配置对

**Comment by unitwk** [comment]
理论上就不可能，至少要在 Web 配置一次的，不可能自动化。

**Comment by Mr-Ao-Dragon** [comment]
> 或者考虑一个外置的配置生成器？通过自动化脚本调用后直接返回生成的配置对

这样免去了暴露问题，也间接解决了自动化init

**Comment by Bluemangoo** [comment]
反正你肯定要在web端操作的，还不如web连daemon。

或者你可以考虑自己写一个脚本，调用web端的api解决问题。这个不是mcsm该做的事情。

**Comment by Mr-Ao-Dragon** [comment]
> 反正你肯定要在web端操作的，还不如web连daemon。
> 
> 或者你可以考虑自己写一个脚本，调用web端的api解决问题。这个不是mcsm该做的事情。

好的。

**Comment by Mr-Ao-Dragon** [comment]
> > > 或者考虑一个外置的配置生成器？通过自动化脚本调用后直接返回生成的配置对
> > 
> > 考虑一下？ 这样免去了暴露问题，也间接解决了自动化init
> 
> 理解了。
> 
> 这样做确实可以实现安装完后自动化部署与连接。是一个很不错的 idea。
> 
> 以后有空的话，我加一个吧。
> 
> 具体的形式类似于这样：在面板上新增一个页面，提供一个 Daemon 一键脚本生成的功能，用户在其他 Linux 安装完后，就主动去连接 Web 并根据安装脚本附带的密钥自动配置完成。
> 
对的，建议API一并提供
