### ISSUE TITLE
如何在退出命令中确定yes

### ISSUE THREAD

**Issue by DanielToyama** [MCSManager/MCSManager#945]
使用mcsm管理一些纯控制台程序时，使用^C会要求按下y确认，我查阅了文档和搜索了相关办法，使用”echo y | ^c”，^c\r\ny\r\n等方法都无效

**Comment by Bluemangoo** [comment]
包含^C无效是因为mcsm的代码中判断如果是"^c"就发送终止信号，否则向程序stdin输入。

**Comment by Bluemangoo** [comment]
只要发送的不只有"^c"都不会发送终止信号。

**Comment by DanielToyama** [comment]
> 只要发送的不只有"^c"都不会发送终止信号。

那么请问应当如何解决呢

**Comment by Bluemangoo** [comment]
我不到啊你问双羽。

**Comment by Bluemangoo** [comment]
哦，可以改，但是有点麻烦。

把^c识别出来然后在相应位置发终止信号就行。

@unitwk 你看看。

**Comment by DanielToyama** [comment]
> 哦，可以改，但是有点麻烦。
> 
> 把^c识别出来然后在相应位置发终止信号就行。
> 
> @unitwk 你看看。

非常感谢

**Comment by Bluemangoo** [comment]
pr合并会自动close的其实。
