### ISSUE TITLE
Typo in the decompress section on the web UI

### ISSUE THREAD

**Issue by forestlxrd** [MCSManager/MCSManager#946]
![image](https://github.com/MCSManager/MCSManager/assets/69772120/a868c0c5-bc41-4b1a-881e-2de709e52622)

**Comment by Bluemangoo** [comment]
enter?

**Comment by Mr-Ao-Dragon** [comment]
> ![image](https://github.com/MCSManager/MCSManager/assets/69772120/a868c0c5-bc41-4b1a-881e-2de709e52622)

type temp and confirm, then move file to you need path.

**Comment by unitwk** [comment]
https://github.com/MCSManager/UI/pull/107
