### ISSUE TITLE
[Minor] API中含有多处拼写错误、不合理的数据类型

### ISSUE THREAD

**Issue by Zhou-Shilin** [MCSManager/MCSManager#947]
**MCSManager Version**
9.9.0
**System Info/Version**
Ubuntu Server
**Node Version**
v14.19.1
**Content**
![搜狗截图20230721072520](https://github.com/MCSManager/MCSManager/assets/86581525/78ee88f1-b8a5-42b4-b504-3352abcffab4)
Download 拼成了 Donwload
![搜狗截图20230721072658](https://github.com/MCSManager/MCSManager/assets/86581525/ee019e06-0ef1-4e9d-bc05-e4f8f6eef6b3)
dataPort为int，httpPort却为str
位置：`/api/overview/setting`

#946 也是拼写错误
希望开发者能在发布前至少扫一眼代码，尽量避免这类低级错误。

另外: #932 进展如何

**Comment by Bluemangoo** [comment]
你直接提pr改吧。
