### ISSUE TITLE
api接口url改为`/api/v1/example`，以增加兼容性

### ISSUE THREAD

**Issue by Zhou-Shilin** [MCSManager/MCSManager#948]
如题，当前的API的响应数据和请求体格式一旦发生改变（据接口文档，`极有可能会随着版本迭代而变化`），基于上一代API制作的程序将会失效。为保证兼容性，建议将现有的`panel.example.com/api/example`改为`panel.example.com/api/v1/example`。

另外: #932 进展如何

**Comment by unitwk** [comment]
现有代码架构应该不足以满足这种需求，抱歉。

**Comment by Zhou-Shilin** [comment]
Unplanned.

**Comment by Zhou-Shilin** [comment]
Unplanned.
