### ISSUE TITLE
[Minor] Function Group UI排版错误

### ISSUE THREAD

**Issue by Zhou-Shilin** [MCSManager/MCSManager#949]
**MCSManager Version**
9.9.0
**System Info/Version**
Ubuntu Server
**Node Version**
v14.19.1
**Content**
https://github.com/MCSManager/MCSManager/assets/86581525/da80a632-0381-41c8-a6bd-ab931aed3a1b
![搜狗截图20230721080211](https://github.com/MCSManager/MCSManager/assets/86581525/679e7be2-6101-43ca-af6c-b89664f723c9)

另外: #932 进展如何

**Comment by Bluemangoo** [comment]
窗口尺寸？

**Comment by Zhou-Shilin** [comment]
> 窗口尺寸？

> Content
https://github.com/MCSManager/MCSManager/assets/86581525/da80a632-0381-41c8-a6bd-ab931aed3a1b

@Bluemangoo 请观看视频

**Comment by Bluemangoo** [comment]
我觉得这个不算bug。

**Comment by Zhou-Shilin** [comment]
> 我觉得这个不算bug。

那请问算什么？Feature Request？？？？

**Comment by Bluemangoo** [comment]
很正常，不需要改。

**Comment by Zhou-Shilin** [comment]
> 很正常，不需要改。

抱歉，但我不认为这是正常的。事实上，mcsm中的其他很多页面都没有这个问题。

**Comment by unitwk** [comment]
确实是 BUG ，这个时候应该每个按钮单独占一行，下版本之前。
