### ISSUE TITLE
[Suggestion] 根据漏洞的严重级别决定修复优先级并通过GitHub Projects管理Issue计划

### ISSUE THREAD

**Issue by Zhou-Shilin** [MCSManager/MCSManager#951]
# 现状
目前MCSM的漏洞修复优先级，似乎是`哪个好修就先修哪个`。
比如同样是我提交的issue，#947（拼写错误，Minor次要）的回复速度居然比#932 （功能没有完全实现，Major一般）功能快的多。一周过去了，#932 毫无进展；#947 不到1个小时就修复了

# 建议
1. 修复优先级按照漏洞的严重级别决定修复的优先级；
2. 使用[GitHub Projects](https://github.com/MCSManager/MCSManager/projects)管理Issue修复计划：To do, In progress, Done.

## 例子
（优先级从高到低）
### Blocker 崩溃 (4)
崩溃
### Critical 严重 (3)
系统主要功能部分丧失、数据库保存调用错误、用户数据丢失，一级功能菜单不能使用但是不影响其他功能的测试。功能设计与需求严重不符，模块无法启动或调用，程序重启、自动退出，关联程序间调用冲突，安全问题、稳定性等。如：软件中数据保存后数据库中显示错误，用户所要求的功能缺失，程序接口错误，数值计算统计错误等
### Major 一般 (2)
功能没有完全实现但是不影响使用，功能菜单存在缺陷但不会影响系统稳定性。如：操作时间长、查询时间长、格式错误、边界条件错误，删除没有确认框、数据库表中字段过多等
### Minor 次要 (1)
界面、性能缺陷，建议类问题，不影响操作功能的执行，可以优化性能的方案等。如：错别字、界面格式不规范，页面显示重叠、不该显示的要隐藏，描述不清楚，提示语丢失，文字排列不整齐，光标位置不正确，用户体验感受不好，可以优化性能的方案等

**Comment by Bluemangoo** [comment]
谔谔，我不是maintainer。

**Comment by Bluemangoo** [comment]
双羽一个礼拜能不能给你答复都不一定。

**Comment by Zhou-Shilin** [comment]
> 谔谔，我不是maintainer。
> 
> 按我算回复速度纯属乱来。

可以看看#937 #938 都是last week发last week回复，#932 甚至都没说要修。

**Comment by Bluemangoo** [comment]
双羽在线时间随缘的。

**Comment by Bluemangoo** [comment]
我要是找到bug原因就给你修了吧。

**Comment by Zhou-Shilin** [comment]
> 双羽在线时间随缘的。

时间少就更应该把时间花在刀刃上，就更应该根据漏洞的严重级别决定优先级

**Comment by Bluemangoo** [comment]
他也只是单纯self-assigned而已。到现在也没修。

**Comment by Zhou-Shilin** [comment]
> 他也只是单纯self-assigned而已。到现在也没修。

#932 self-assigned都没有

**Comment by unitwk** [comment]
感谢你对 MCSManager 开发团队提出的改进意见，你对 MCSM 面板一直以来的关注我都看在眼里。

目前的分工是 Pty，UI 仓库都有两名成员管理，如果只是 UI 或 Pty 单方面出问题，他们应该可以修复，不需要我来。

但是涉及 UI，Daemon，Web 三端的 BUG 和优化等功能则目前只能是我来处理。

但是你应该知道，我在现实生活中还有本职工作要做，上班节奏是字节跳动式的节奏，没有多余的时间和精力。当初我还只是一名高中生/大学生，有充足的时间来维护和解决问题。但是目前，我不得不优先解决工作上的事情再来解决这里的事情。

那么从解决BUG到效率上来看，自然是哪个最好解决就先解决哪个，这句话是没有错误的。之所以有些 issue 我没有回复是因为我无法回复你，因为我没有时间去复现它，但我也不能瞎扯信息，可是也不能关掉忽略这个 BUG，所以希望你理解。


你提出的这个「优先级计划」，无法实现，因为这个只能是一种业余爱好，无法作为主力来推进。

**Comment by Zhou-Shilin** [comment]
> 那么从解决BUG到效率上来看，自然是哪个最好解决就先解决哪个，这句话是没有错误的。

小问题的复现当然比大问题所需的时间短，解决所需的总时间也当然会短很多。
时间少，就更应该讲究“效率”。

“从解决BUG的效率上来看”，这个所谓“效率”不应该是解决的问题个数的多少，而是解决的问题的严重性的大小。这好比以写的代码行数的多少来决定一个人的效率是错误的，正确的方式是以实现的功能的多少来决定。

**Comment by unitwk** [comment]
嗯嗯，各有各的观点，争论这些没有必要。

事实上就是我没有一个连续 4～5 个小时去复现+修复一个大BUG，但是有时间去解决一个几十分钟的 BUG。

等有时间这些大 BUG 我会一起修复的。

**Comment by Zhou-Shilin** [comment]
好的，谢谢回复！ (*^▽^*) 

我大致理解了你的意思，你的时间碎片化的。如此短的时间只能修复一些小Bug，修复优先级没什么太大用处。
