### ISSUE TITLE
特定配置只在中文有

### ISSUE THREAD

**Issue by Bluemangoo** [MCSManager/MCSManager#952]
用i18n解决翻译问题就好了，不必限制于中文。

![image](https://github.com/MCSManager/MCSManager/assets/63218454/a3a8c9c9-1a3f-4ccb-ba23-090cbe078ea4)

**Comment by Bluemangoo** [comment]
另外，英文下入口是隐藏的。

![image](https://github.com/MCSManager/MCSManager/assets/63218454/5b34ce3b-3e83-4169-87a7-29879acd1637)

**Comment by unitwk** [comment]
本来就是只给中国人用的，国外对于这种配置文件了解比较多，再加上有丰富的英文 WIKI 注释。

国内的话由于大部分资料是英语，所以给中国用户做一套这类辅助界面是很有用的。

当然，最重要的还是因为我还要去抄一份英语原文来对应各个中文。

**Comment by Bluemangoo** [comment]
你懒得做我自己做吧。

**Comment by unitwk** [comment]
如果你感兴趣，可以尝试一下。

首先， 你需要使用此项目（https://github.com/unitwk/zh-cn-i18n-converter）将那几个代码文件转成国际化代码文件，因为代码里面不能直接写中文的。

然后，你再根据转换后的所有配置与对应的中文，逐一按照 WIKI 内容复制进去，不接受机器翻译。

整体流程其实不复杂，最难的其实就是按照 WIKI 来写对应的英文解释。

**Comment by unitwk** [comment]
你需要开发的具体的代码文件在此：https://github.com/MCSManager/UI/tree/master/src/components/mc_process_config

**Comment by Bluemangoo** [comment]
我知道。

**Comment by Bluemangoo** [comment]
在做。

**Comment by Bluemangoo** [comment]
转完了，差翻译。

面向console编程（笑）

![image](https://github.com/MCSManager/MCSManager/assets/63218454/2d53b11c-d4e4-450e-a179-6fceb9b6f49c)

**Comment by unitwk** [comment]
其实，你用 VSCode 的 `Ctrl+D` 多光标功能选定多个特征符号，批量编辑也是一样的效果....

不过你这个也是一个很不错的算法，赞。
