### ISSUE TITLE
在浏览器宽度为900px时UI出现问题

### ISSUE THREAD

**Issue by xiantiao233** [MCSManager/MCSManager#953]
**MCSManager Version**
new

在浏览器宽度为900px时，左边的菜单栏消失，且不会出现打开菜单栏的按钮

**Comment by unitwk** [comment]
打开菜单栏的按钮在「导航栏」最左侧，有个 「三」字型的符号按钮，仔细找找看看。

**Comment by xiantiao233** [comment]
可以再看看吗
![image](https://github.com/MCSManager/MCSManager/assets/112249833/c9a2bd8f-c5d8-421e-ba3c-9bba5223412c)
![image](https://github.com/MCSManager/MCSManager/assets/112249833/6731494a-48eb-4b04-a237-b3faa289c2c3)
![image](https://github.com/MCSManager/MCSManager/assets/112249833/ca0e1b2a-ccad-48d4-9a72-aa4c55d4930d)

**Comment by unitwk** [comment]
哦哦，明白了，正好 900px 的时候按钮消失了，是 BUG。

感谢你的耐心解答。

**Comment by LazyCreeper** [comment]
已修复~
