### ISSUE TITLE
建议使用Service Workers将静态资源缓存到浏览器

### ISSUE THREAD

**Issue by YosakuraTohu** [MCSManager/MCSManager#955]
如题，主要是这样操作可以加快面板的首屏加载时间，第一次加载可能没什么变化，缓存之后基本上可以做到**秒开**

用这个的原因是因为我使用了CloudFlare保护了面板的源站，但是每次js和css资源的加载都会占据大部分的时间。

**Comment by YosakuraTohu** [comment]
我自己项目使用的是`workbox-webpack-plugin`这个插件，可以很轻松的配置，支持正则表达式，下面是我实际使用的一个实例
```ts
new GenerateSW({
    clientsClaim: true,
    skipWaiting: true,
    runtimeCaching: [
        {
            urlPattern: new RegExp("^https://fonts"),
            handler: "CacheFirst",
            options: {
                cacheName: "font-cache",
                cacheableResponse: {
                    statuses: [200]
                }
            }
        }
    ]
}),
```

**Comment by Bluemangoo** [comment]
![-5dfb6d9373e0b8f4.jpg](https://github.com/MCSManager/MCSManager/assets/63218454/721c0f76-ef2d-406a-88d5-4ef2e1e5421d)

**Comment by Bluemangoo** [comment]
不对啊静态资源是有缓存的。

**Comment by YosakuraTohu** [comment]
我的意思是，js和css都缓存到浏览器上

**Comment by Bluemangoo** [comment]
对啊。

**Comment by Bluemangoo** [comment]
我相信你能看得懂英文的。

**Comment by Bluemangoo** [comment]
你如果开着F12是默认不会走缓存的。

**Comment by YosakuraTohu** [comment]
> ![-5dfb6d9373e0b8f4.jpg](https://user-images.githubusercontent.com/63218454/255381645-721c0f76-ef2d-406a-88d5-4ef2e1e5421d.jpg)

正在用CF，就是首屏太慢了，即便是配置了缓存规则（除了/api全部缓存）

**Comment by Bluemangoo** [comment]
首屏怎么样都慢的。

**Comment by Bluemangoo** [comment]
你都走cf了如果isp不是移动基本上快不起来。

**Comment by YosakuraTohu** [comment]
service worker有个实用的功能，就是源站寄了都没问题（前提是浏览器有缓存）我网站就是这么配置的（虽然源服务器已经过期了）

**Comment by Bluemangoo** [comment]
但是你这个站源站寄了一定会出事。

**Comment by YosakuraTohu** [comment]
![Screenshot_20230723-215409_Firefox](https://github.com/MCSManager/MCSManager/assets/96331099/11a34f71-29c3-487a-b10a-51933c28d6e9)
https://blog.kinareyuki.link/
试试，你现在的话肯定是打不开这个的

**Comment by Bluemangoo** [comment]
我有考虑过魔改让它能在vercel上面跑。那样不用考虑源站问题。

**Comment by Bluemangoo** [comment]
你搞清楚mcsm所有功能都一定是要过api的。

**Comment by Bluemangoo** [comment]
没有api你什么都做不了。

**Comment by Bluemangoo** [comment]
源站寄了一定停摆的。

**Comment by YosakuraTohu** [comment]
手头上没电脑不好给你看F12是怎样的，不过的确可以加快速度。

**Comment by Bluemangoo** [comment]
和你博客不一样。

**Comment by YosakuraTohu** [comment]
> 源站寄了一定停摆的。

但是面板打开速度很慢啊……我的重点是这个

**Comment by YosakuraTohu** [comment]
api这个我倒是知道，没有肯定寄

**Comment by YosakuraTohu** [comment]
我自己fork一个去改一改吧

**Comment by Mr-Ao-Dragon** [comment]
> 我有考虑过魔改让它能在vercel上面跑。那样不用考虑源站问题。

UI能在上面跑就行，所以UI静态版部署秋梨膏

**Comment by Bluemangoo** [comment]
> > 我有考虑过魔改让它能在vercel上面跑。那样不用考虑源站问题。
> 
> UI能在上面跑就行，所以UI静态版部署秋梨膏

UI的部署很简单。但是我在想怎么样整个web全部部署上去。

你要单纯部署UI可以私我我教你。

**Comment by YosakuraTohu** [comment]
抱歉现在才看到回复，理论上来说，我是否可以通过修改静态文件的配置，添加跨域的header，来访问其它域的API呢？
比如我讲静态内容部署到cdn上，API直接访问主机。

**Comment by Bluemangoo** [comment]
可以，你自己改。

如何要UI部署Vercel的话看这个。https://blog.bluemangoo.net/blogs/mcsm-ui-on-vercel/

**Comment by YosakuraTohu** [comment]
嗯，谢谢！

**Comment by YosakuraTohu** [comment]
![IMG_4202](https://github.com/MCSManager/MCSManager/assets/96331099/d6fe4a99-c594-4cab-8102-8b7351e0dac3)
如图，用了Vercel反而还比CF慢，API没有走CF

**Comment by YosakuraTohu** [comment]
```diff
10,11c10,11
<             "source": "/:match*",
<             "destination": "$YOUR_WEB_URL/:match*"
---
>             "source": "/api/:match*",
>             "destination": "$YOUR_WEB_URL/api/:match*"
14,15c14,15
<             "source": "/:match*/",
<             "destination": "$YOUR_WEB_URL/:match*/"
---
>             "source": "/api/:match*/",
>             "destination": "$YOUR_WEB_URL/api/:match*/"
```
修改示例，如果按照你原来的配置，应该都会rewrite到源站

**Comment by Bluemangoo** [comment]
你好，这是我的配置。

![IMG_20230812_230103.jpg](https://github.com/MCSManager/MCSManager/assets/63218454/e8fa8f31-c35d-480c-b36a-746829279a15)

**Comment by Bluemangoo** [comment]
它现在是能正常工作的。我不知道是不是你那边开了什么防火墙之类的。我直接走vercel中间不过任何转发之类的。

**Comment by Bluemangoo** [comment]
你可以看看vercel的文档。rewrite默认先匹配本地文件再匹配设定项。
