### ISSUE TITLE
建议出一个插件更新系统

### ISSUE THREAD

**Issue by xLikeWATCHDOG** [MCSManager/MCSManager#956]
功能如下：
1.首先能检测各个服务器的插件列表。
2.获取用户的服务器列表。
3.上传N个新版插件，自动检测名字，和对应在服务器里的文件。
4.选择更新的服务器。
5.确定不存在插件时，是添加还是忽略。
6.重启服务器。

***非常急切的需要***

**Comment by unitwk** [comment]
第二点可以考虑，并且也正在计划实现。

其他的暂无此方面的计划。

**Comment by Zhou-Shilin** [comment]
应该有其他程序可以完成你的需求。
