### ISSUE TITLE
[网站问题] 能否让旧版网站引导用户到新版网站

### ISSUE THREAD

**Issue by xiantiao233** [MCSManager/MCSManager#961]
![336d2102636047235940d0f8b5434480](https://github.com/MCSManager/MCSManager/assets/112249833/dba091fa-3422-4fab-acdb-c412c32383bf)

![image](https://github.com/MCSManager/MCSManager/assets/112249833/159e7fd6-1eec-49b3-8f1b-f96bcf2dbca9)

[https://litenpanjun.github.io/MCSManager8/](旧版链接)

**Comment by Bluemangoo** [comment]
那个仓库achieve了。

**Comment by huangsijun17** [comment]
这是 @LitenPanJun 做的MCSM旧版本[MCSManager8](https://github.com/LitenPanJun/MCSManager8)的历史镜像。和MCSM仓库本身无关。MCSM和现有开发者、奉献者等都不可能也无法去干涉第三个的合法镜像。如果您希望继续使用MCSM8版本，您可以会有一系列的可能涉及安全或非安全的问题。请您自行解决。

**Comment by unitwk** [comment]
你截图的那个跟我没关系，我也无权要求别人删除仓库。
