### ISSUE TITLE
选中文字后按下CTRL+C，会将^C发送至服务器端导致其关闭

### ISSUE THREAD

**Issue by Lendwishes** [MCSManager/MCSManager#963]
**MCSManager Version**
9.9.0
**System Info/Version**
Windows Server 2019 Datacenter 10.0.17763
远程节点版本3.4.0
**Node Version**
v18.12.1
**Step**
--------------------步骤1--------------------
![image](https://github.com/MCSManager/MCSManager/assets/47055366/ec4732ac-06d0-4ff9-8f49-65d84c89ff4b)
在终端输入"luckperms editor"，并回车
--------------------步骤2--------------------
![image](https://github.com/MCSManager/MCSManager/assets/47055366/d7bfd958-38d3-42e1-9eed-b00dba02c9c0)
使用鼠标左键拖拽并选中文字
--------------------步骤3--------------------
按下CTRL+C
--------------------步骤4--------------------
![image](https://github.com/MCSManager/MCSManager/assets/47055366/d6dcb825-254a-44e1-a6de-b1a09ac6dd01)
服务器端接收到^C，开始关闭服务器
---------------------结束---------------------
从以上步骤可以发现，选中文字按下CTRL+C并未成功复制文字，而是将CTRL+C发送至服务器终端，终端接收到后开始关闭服务器。

**Comment by huangsijun17** [comment]
请使用模拟终端。

**Comment by Bluemangoo** [comment]
> 请使用模拟终端。

这就是仿真终端底下的问题。

**Comment by Bluemangoo** [comment]
你可以用右键复制，我也没有什么好的解决办法。

**Comment by unitwk** [comment]
这不算BUG，在Linux下你也不可能通过 Ctrl+C 来复制文本，仿真终端就是为了模拟完全真实的终端才被称之为「仿真终端」。

你可以在左侧的「终端设置」关闭「仿真终端」以解决问题。

**Comment by Lendwishes** [comment]
> 这不算BUG，在Linux下你也不可能通过 Ctrl+C 来复制文本，仿真终端就是为了模拟完全真实的终端才被称之为「仿真终端」。
> 
> 你可以在左侧的「终端设置」关闭「仿真终端」以解决问题。

你好。在关闭「仿真终端」后使用模拟终端很好的提议。但是它仍然存在问题。即使它一切看起来正常工作。选中文字后按下Ctrl+C取消高亮，没有导致服务器关闭。但是它并没有将文字正确地复制到剪贴板中。剪贴板仍然保持着复制之前的样子。
