### ISSUE TITLE
直接双击运行bat可以正常开启，在面板中无法开启

### ISSUE THREAD

**Issue by FFDVDGD** [MCSManager/MCSManager#964]
直接双击运行bat可以正常开启，在面板中无法开启，输出为”'mcdreforged' 不是内部或外部命令，也不是可运行的程序
或批处理文件。“。如图为实例配置
<img width="555" alt="image" src="https://github.com/MCSManager/MCSManager/assets/82321430/9eaffccc-8291-436d-9050-0bb3dcd9e223">

**Comment by unitwk** [comment]
你的bat前面那么长的路径写到工作目录这一栏中，然后启动命令只留一个 start.bat。

**Comment by FFDVDGD** [comment]
![image](https://github.com/MCSManager/MCSManager/assets/82321430/8c8361c3-fe14-4ae1-b3c4-b84a936a99c6)
bat原本就在工作目录下，双击也可以正常运行
![image](https://github.com/MCSManager/MCSManager/assets/82321430/55ca1fcc-65eb-4cff-9c67-fc1f2226747d)
改成这样还是输出”'mcdreforged' 不是内部或外部命令，也不是可运行的程序
或批处理文件。“

**Comment by Mr-Ao-Dragon** [comment]
建议直接使用mcreforged启动命令。
~~~powershell
python3 /m mcreforged
~~~

**Comment by huangsijun17** [comment]
bat贴一下，或者传上来给看一下。

**Comment by FFDVDGD** [comment]
> bat贴一下，或者传上来给看一下。

![image](https://github.com/MCSManager/MCSManager/assets/82321430/3bea0dc4-aba3-4b8b-b913-04e512572e6e)

**Comment by FFDVDGD** [comment]
解决了，把python装在programfiles目录就好了
