### ISSUE TITLE
Docker构建环境镜像后无法看到或使用

### ISSUE THREAD

**Issue by KJZH001** [MCSManager/MCSManager#965]
**MCSManager Version**
```
Node 版本
v14.19.1

面板版本
9.9.0

对应远程节点版本
3.4.0
```
**System Info/Version**
```
       _,met$$$$$gg.          sakura@McDebian 
    ,g$$$$$$$$$$$$$$$P.       --------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) x86_64 
 ,$$P'              `$$$.     Host: Virtual Machine Hyper-V UEFI Release v4.0 
',$$P       ,ggs.     `$$b:   Kernel: 5.10.0-18-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 3 hours, 45 mins 
 $$P      d$'     ,    $$P    Packages: 1886 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.1.4 
 $$;      Y$b._   _,d$P'      Theme: Adwaita [GTK3] 
 Y$$.    `.`"Y$$$$P"'         Icons: Adwaita [GTK3] 
 `$$b      "-.__              Terminal: /dev/pts/2 
  `Y$$                        CPU: Intel Xeon E5-2630 0 (2) @ 2.299GHz 
   `Y$$.                      Memory: 1302MiB / 3930MiB 
     `$$b.
       `Y$$b.                                         
          `"Y$b._                                     
```
**Node Version**
看上面

**Step**
和普通的创建镜像步骤没什么区别，下面直接放出bug描述

![%{Z 2KR3_K~ T_44(VZ%ABP](https://github.com/MCSManager/MCSManager/assets/29683578/67cc4f91-0e6b-42eb-bf4a-7ef0278c4f0d)
这张图里，可以确定面板提示环境镜像创建完毕，守护进程的日志也说明了这点

![G%PGOV7`{04X283OB0G%LX7](https://github.com/MCSManager/MCSManager/assets/29683578/0f099d51-5224-441a-b2c4-9b8de11c6262)
现在回到前面的页面，发现仍然提示找不到镜像，实列设置里也同样看不到

![image](https://github.com/MCSManager/MCSManager/assets/29683578/c24b1146-2991-4c8f-8cbf-f12461eb33df)

在shell中，使用docker的命令也查找不到创建的镜像
![RSNOP8_9`%2KA}UZWOKI7 V](https://github.com/MCSManager/MCSManager/assets/29683578/4c3ebc4e-8b40-40ba-9a00-c1b024af1d3c)

通过抓包发现
http://192.168.3.1:23333/manifest.json
此地址一直返回Failed to load resource: the server responded with a status of 404 (Not Found)

内容为
```
{"status":404,"data":"[404] Not Found","time":1691157538971}
```

对于这个请求（参数已经删去）
http://192.168.3.1:23333/api/protected_instance/outputlog?remote_uuid=***&uuid=***&token=***
返回了Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by huangsijun17** [comment]
Docker镜像构建完成但构建失败了而已。报错404，明显的网络问题。构建完成又不是成功。

**Comment by unitwk** [comment]
应该是失败了，mcsm点构建无法保证100%成功，你可以自己手动构建一个

**Comment by KJZH001** [comment]
> 应该是失败了，mcsm点构建无法保证100%成功，你可以自己手动构建一个

好的，那么我后续使用软路由代理后会去再尝试一下能不能成功构建，如果还是不行我就手动执行构建操作了

**Comment by KJZH001** [comment]
> Docker镜像构建完成但构建失败了而已。报错404，明显的网络问题。构建完成又不是成功。

我认同你的说法，构建完毕不等于成功

但是这里我认为需要改进，至少我没有从日志中看到任何关于失败的报错记录，第一次使用mcsm的docker管理的人也很难知道这里会出现这种问题

并且，我查阅过mcsm现有的文档，其中对于这部分几乎没有什么说明

**Comment by Bluemangoo** [comment]
网络问题可以改。问问双羽什么说法。

Example

```js
const proxy = require("node-global-proxy").default;

proxy.setConfig({
  http: "http://localhost:1080",
  https: "https://localhost:1080",
});
proxy.start();
```

**Comment by huangsijun17** [comment]
> 网络问题可以改。问问双羽什么说法。
> 
> Example
> 
> ```js
> const proxy = require("node-global-proxy").default;
> 
> proxy.setConfig({
>   http: "http://localhost:1080",
>   https: "https://localhost:1080",
> });
> proxy.start();
> ```

他是后端服务器连不上Docker镜像仓库。

**Comment by Bluemangoo** [comment]
对的。改daemon源码。web加个设置项或者写config里面。

**Comment by KJZH001** [comment]
> > 网络问题可以改。问问双羽什么说法。
> > Example
> > ```js
> > const proxy = require("node-global-proxy").default;
> > 
> > proxy.setConfig({
> >   http: "http://localhost:1080",
> >   https: "https://localhost:1080",
> > });
> > proxy.start();
> > ```
> 
> 他是后端服务器连不上Docker镜像仓库。

我后面用软路由做旁网关代理之后构建成功了

另外我感觉大多数人应该都还是一个面板对一个后端的情况居多吧，不会每个人都有很多服务器需要组群集的
