### ISSUE TITLE
Windows仿真终端PTY启动失败

### ISSUE THREAD

**Issue by yxsj245** [MCSManager/MCSManager#966]
**MCSManager Version**
web 3.4.0 daemo 9.9.0
**System Info/Version**
Windows server2022
**Node Version**
v18.12.1
**Step**
经过我本人测试，可能是CPU利用率高了就会导致PTY无法启动
![Cache_8cd4fd95433f319](https://github.com/MCSManager/MCSManager/assets/107445049/6a252f8e-5500-4fc1-ba48-067245cfe360)
报错是PTY启动失败而不是指令运行错误，此问题本人尝试手动双击启动PTY可以临时解决，但是时间旧了之后MCSM还是无法启动。如果关闭仿真终端会造成代码流无法输出但是指令可以正常执行，docker run 则无法启动 望修复

**Comment by NuoNuoYES** [comment]
me too

**Comment by NuoNuoYES** [comment]
me too
![QQ图片20230805111845](https://github.com/MCSManager/MCSManager/assets/137254153/1de94478-bc71-4436-98e5-
![QQ图片20230805111827](https://github.com/MCSManager/MCSManager/assets/137254153/fafec2fa-3fd7-4caf-bbbd-72ded5abcd2b)
89d8e5905278)
![QQ图片20230805111836](https://github.com/MCSManager/MCSManager/assets/137254153/dedb9083-6f26-4cfd-8b38-24b944173de8)
![QQ图片20230805111845](https://github.com/MCSManager/MCSManager/assets/137254153/78905ded-c065-4627-a0e1-94e925491eac)

**Comment by NuoNuoYES** [comment]
我也是

**Comment by unitwk** [comment]
mcsm面板运行时，采用系统管理员身份启动，再试试

**Comment by yxsj245** [comment]
这是后台报错信息 仍然不行
![image](https://github.com/MCSManager/MCSManager/assets/107445049/621b1116-b116-426a-b7ef-866bc0e04bcd)

**Comment by yxsj245** [comment]
> mcsm面板运行时，采用系统管理员身份启动，再试试

这是后台报错信息 仍然不行
![](https://user-images.githubusercontent.com/107445049/258568490-621b1116-b116-426a-b7ef-866bc0e04bcd.png)
