### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Im-CatDev** [MCSManager/MCSManager#969]
Can I configure the panel so that the game server is on another server and the panel is on another server?

I want to install web panel on www hosting, where i have only file access, is it possible?

**Comment by Zhou-Shilin** [comment]
The web panel and daemon can be in two different server.
But you can not run mcsmanager web service without console access.

**Comment by Bluemangoo** [comment]
if u have node installed, the work can be done so.

**Comment by Bluemangoo** [comment]
if not, u can download node and unpack to somewhere you can access. then write a sh file to start the web server with the node you downloaded. without super user permission it's unpossible to install as a service. maybe another startus managers like `gnome-tweaks`.

**Comment by Zhou-Shilin** [comment]
> if not, u can download node and unpack to somewhere you can access. then write a sh file to start the web server with the node you downloaded. without super user permission it's unpossible to install as a service. maybe another startus managers like `gnome-tweaks`.

He said he only has file access, how can execute sh file if he can't use the console?

**Comment by Bluemangoo** [comment]
if u only have dir path file access, the work might be impossible.

anyway, u can only put static files there and run web backend in another machine. nginx will help you👀
