### ISSUE TITLE
控制台输入命令后面自动加上^j符号

### ISSUE THREAD

**Issue by GanchengCat** [MCSManager/MCSManager#970]
在控制台输入命令会自动在命令后面加上^j
这种问题已经出现很多次了，并且只在Linux系统上出现
这造成很多命令无法执行
希望来个答复

**Comment by Zhou-Shilin** [comment]
_复现失败_
有的时候从网页上复制的命令会带换行符，比如[MCSManager官方文档](docs.mcsmanager.com)。自己手动输入命令会出现问题吗？使用的仿真终端还是底部输入框？

**Comment by GanchengCat** [comment]
我并不是复制命令在控制台输入，我是纯手写

**Comment by GanchengCat** [comment]
我并不是复制命令在控制台输入，我是纯手写

**Comment by Zhou-Shilin** [comment]
> 使用的仿真终端还是底部输入框？

@GanchengCat

**Comment by GanchengCat** [comment]
底部输入框

**Comment by Bluemangoo** [comment]
请提供截图。

**Comment by Zhou-Shilin** [comment]
录屏？截图？我这边正常的没问题

**Comment by GanchengCat** [comment]
问题已经解决了，更改那个终端设置里面的回车换行符，Linux t统默认的换行符不起效，换成WINDOWS用的回车换行符解决了

**Comment by Zhou-Shilin** [comment]
把issue close掉
