### ISSUE TITLE
快捷将文本文件发到https://pastes.dev/或者其他贴log的地方

### ISSUE THREAD

**Issue by postyizhan** [MCSManager/MCSManager#971]
希望右键菜单可以有一个按钮，可以把文本文件快速发到(https://pastes.dev/) 能直接发log.gz就更好了

我不知道这种文本编辑器怎么称呼，所以直接上个图吧
![3cc91fe602a2043cde372d3427c02b94](https://github.com/MCSManager/MCSManager/assets/97342038/c15bf8ba-c721-471b-af82-c352c2e07e91)
我想要一个带目录的文本编辑器(或许MCSM有只是我不知道怎么开?)

**Comment by huangsijun17** [comment]
已被否决：
https://github.com/MCSManager/MCSManager/issues/662
