### ISSUE TITLE
支持插件

### ISSUE THREAD

**Issue by Zhou-Shilin** [MCSManager/MCSManager#972]
如题，面板提供插件API、支持安装插件，很多其他的feature request都可以通过插件解决。

**Comment by Bluemangoo** [comment]
我觉得先支持用户自定义语言包为好。

**Comment by Zhou-Shilin** [comment]
自定义语言包…？，[语言文件](https://github.com/MCSManager/MCSManager/blob/b742d51965c13c0b33c0dd209d6de2dd10a35a63/src/app/i18n/language/en_us.json)添加一个custom.json再在设置里增加个选项就行了吧

**Comment by Zhou-Shilin** [comment]
插件更有用一点吧

**Comment by Bluemangoo** [comment]
你不能要求用户学会自己打包。都是开放api我觉得半斤八两吧。i18n也可以上crowdins。

**Comment by Zhou-Shilin** [comment]
> 你不能要求用户学会自己打包。都是开放api我觉得半斤八两吧。i18n也可以上crowdins。

现在皮肤安装也是这么干的。。。
都要优化
crowdin是好主意

**Comment by Zhou-Shilin** [comment]
功能未实现，应以wontfix/notplanned关闭
