### ISSUE TITLE
带有空格的命令无法在终端执行

### ISSUE THREAD

**Issue by KnightPeink** [MCSManager/MCSManager#974]
**MCSManager Version**
9.8.0

**System Info/Version**
#1 SMP Tue Jun 20 11:48:01 UTC 2023 3.10.0-1160.92.1.el7.x86_64

**Node Version**
v14.19.1

**Step**
在终端内输入例如jupyter notebook命令会提示：
仿真终端中转命令:
程序：/opt/mcsmanager/daemon/lib/pty_linux_x64
参数：["-dir","/home/jupyter","-cmd","[\"jupyter\",\"notebook\"]","-size","140,40","-color","-coder","UTF8"]
请将此信息报告给管理员，技术人员或自行排查故障。
如果您认为是面板仿真终端导致的问题，请在左侧终端设置中关闭“仿真终端”选项，我们将会采用原始输入输出流的方式监听程序。

关闭仿真终端后会提示：
启动命令解析体:
程序：jupyter
参数：["notebook"]
请将此信息报告给管理员，技术人员或自行排查故障。

**Comment by Bluemangoo** [comment]
不不不，我觉得是他二进制文件名字带空格。

**Comment by KnightPeink** [comment]
> 请使用双引号包含你带空格的命令 "jupyter notebook"，比如 “/opt/bin/jupyter notebook”

加了引号后依然报错，报错信息如下：
原生启动命令：
"jupyter notebook"
仿真终端中转命令:
程序：/opt/mcsmanager/daemon/lib/pty_linux_x64
参数：["-dir","/home/jupyter","-cmd","[\"jupyter notebook\"]","-size","140,40","-color","-coder","UTF8"]

关闭仿真终端后的报错：
原生启动命令：
"jupyter notebook"
启动命令解析体:
程序：jupyter notebook
参数：[]

还有一些别的命令有同样的问题，比如nb run等一些带有空格的命令

**Comment by Bluemangoo** [comment]
你好，不要用引号包裹，而是检查可执行文件是否在path当中。如果不在，请使用完整路径调用。如` “/opt/bin/jupyter” notebook` 。你报错的原因是找不到二进制文件。可能是环境变量只在.bashrc中添加导致mcsm无法拿到那部分环境变量。这里的不方便无法解决。或者你把环境变量修改到`/etc/environment`里面可能可以解决。
