### ISSUE TITLE
网页颜色渲染错误

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#978]
MCSManager Version
9.9.0
System Info/Version
Windows Server 2022 Datacenter 10.0.20348
Node Version
v18.12.1
Step
在实例管理页面刷新网页有概率无法渲染“网页颜色渲染”，症状为关闭“网页颜色渲染”症状
使用的浏览器为Safari

**Comment by unitwk** [comment]
仿真终端是否开启？在左侧有一个终端设置的按钮。

**Comment by Bluemangoo** [comment]
不建议使用网页颜色渲染，而是应该启动pty。

**Comment by XiaoXiaoYang233** [comment]
> 仿真终端是否开启？在左侧有一个终端设置的按钮。
> 
> 另外你启动的程序是什么程序，MC服务器？有无截图。

开启了仿真终端，如果后面有输出的话，颜色是会正常渲染的
截图如下：
