### ISSUE TITLE
实例控制台刷新后异常

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#979]
MCSManager Version
9.9.0
System Info/Version
Windows Server 2022 Datacenter 10.0.20348
Node Version
v18.12.1
Step
刷新网页后实例控制台展示的内容有概率滑动到顶部
使用的浏览器为Safari
可能不需要手动刷新，把浏览器切到后台过几秒再切到前台也会这样

**Comment by bddjr** [comment]
老特性了
