### ISSUE TITLE
增加实例启动优先级配置选项

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#980]
而不是通过排序决定谁先启动

**Comment by Bluemangoo** [comment]
？你把我死去的fork发扬光大就行了（不是

**Comment by huangsijun17** [comment]
> ？你把我死去的fork发扬光大就行了（不是
> 
> #796

加一个自启动演示？ESXI、PVE等软件启动虚拟机都是可以设置延时。
