### ISSUE TITLE
文件管理上传文件错误

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#981]
MCSManager Version
9.9.0
System Info/Version
Windows Server 2022 Datacenter 10.0.20348
Node Version
v18.12.1
Step
上传一个大文件，会在上传途中中断卡进度无法上传

**Comment by huangsijun17** [comment]
请补全客户端系统和浏览器版本。

**Comment by unitwk** [comment]
是否存在反向代理，Https等情况。

**Comment by XiaoXiaoYang233** [comment]
> 请补全客户端系统和浏览器版本。

win11
edge

**Comment by XiaoXiaoYang233** [comment]
> 是否存在反向代理，Https等情况。

没有

**Comment by XiaoXiaoYang233** [comment]
文件为2G左右的7zip压缩包

**Comment by huangsijun17** [comment]
能否在客户端长ping一下服务端？是否存在网络波动？

**Comment by XiaoXiaoYang233** [comment]
> 能否在客户端长ping一下服务端？是否存在网络波动？

感觉跟网络无关，每次都是卡20%

**Comment by XiaoXiaoYang233** [comment]
下载大文件也一样

**Comment by Skely0528** [comment]
请问有解决方法吗？我也遇到同样的问题。
