### ISSUE TITLE
最新版貌似改不了远程节点名称？

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#982]
我记得在之前的版本是可以直接在面板改的，我没找到还是我记错了（？）

**Comment by unitwk** [comment]
节点名字右边有一个编辑按钮，点击即可编辑。

**Comment by XiaoXiaoYang233** [comment]
![image](https://github.com/MCSManager/MCSManager/assets/99535761/7a2861c2-91d9-4248-bef0-43a49a287af1)

**Comment by unitwk** [comment]
<img width="906" alt="image" src="https://github.com/MCSManager/MCSManager/assets/18360009/1ad0cf04-8fda-40f7-9a16-a5f3f3540512">


如果你没有这个按钮，可能是碰巧你安装的是一个没有编辑功能的版本，可以升级一下。

**Comment by XiaoXiaoYang233** [comment]
> <img width="906" alt="image" src="https://github.com/MCSManager/MCSManager/assets/18360009/1ad0cf04-8fda-40f7-9a16-a5f3f3540512">
> 
> 
> 
> 
> 
> 如果你没有这个按钮，可能是碰巧你安装的是一个没有编辑功能的版本，可以升级一下。
> 
> 

好的
