### ISSUE TITLE
计划任务触发时间选择错误

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#984]
MCSManager Version
9.9.0
System Info/Version
Windows Server 2022 Datacenter 10.0.20348
Node Version
v18.12.1
Step
![image](https://github.com/MCSManager/MCSManager/assets/99535761/8099a9c6-1d03-43dc-ad7a-f2f0279aef6e)
如果其他项目例如这里我选择的“分”，快速滑动进行选择会导致其他（这里是“时”出现问题）选项出现问题

**Comment by huangsijun17** [comment]
请补充客户端的操作系统、浏览器名称和版本号。

**Comment by XiaoXiaoYang233** [comment]
> 请补充客户端的操作系统、浏览器名称和版本号。

ios 16.5.1
Safari
