### ISSUE TITLE
文件上传替换错误

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#985]
MCSManager Version
9.9.0
System Info/Version
Windows Server 2022 Datacenter 10.0.20348
Node Version
v18.12.1
Step
当上传并替换一个被占用的文件时，会在%temp%目录生成一个无法被删除的文件，除非关闭守护进程，否则无法删除（关闭守护进程后文件自己消失了）

**Comment by unitwk** [comment]
所以有什么问题吗？

**Comment by XiaoXiaoYang233** [comment]
> 所以有什么问题吗？

属于bug吧

**Comment by huangsijun17** [comment]
导致%temp%被占满？Linux下的%temp%是内存盘，但Win下是目录，需要手动/程序删除。确实可能会满。

**Comment by XiaoXiaoYang233** [comment]
> 导致%temp%被占满？Linux下的%temp%是内存盘，但Win下是目录，需要手动/程序删除。确实可能会满。

上传一个相同文件名的文件面板会进行替换，但如果将要被替换的文件被占用了，那么windows目录的%temp%文件夹会存在一个无法被删除的文件，想要修改权限进行删除也会被禁止，只能停止守护进程，虽然可以预防，但是确实是个bug

**Comment by XiaoXiaoYang233** [comment]
> > 导致%temp%被占满？Linux下的%temp%是内存盘，但Win下是目录，需要手动/程序删除。确实可能会满。
> 
> 上传一个相同文件名的文件面板会进行替换，但如果将要被替换的文件被占用了，那么windows目录的%temp%文件夹会存在一个无法被删除的文件，想要修改权限进行删除也会被禁止，只能停止守护进程，虽然可以预防，但是确实是个bug

而且面板的文件管理看不到那个异常的文件
