### ISSUE TITLE
剪切粘贴文件进行替换提示错误

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#987]
MCSManager Version
9.9.0
System Info/Version
Windows Server 2022 Datacenter 10.0.20348
Node Version
v18.12.1
Step
![image](https://github.com/MCSManager/MCSManager/assets/99535761/39db0cdb-b44e-4f20-9afe-eb90f93e3c63)

**Comment by unitwk** [comment]
文件粘贴不支持覆盖操作。
