### ISSUE TITLE
用户登录异常

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [MCSManager/MCSManager#988]
MCSManager Version
9.9.0
System Info/Version
Windows Server 2022 Datacenter 10.0.20348
Node Version
v18.12.1
Step
如果在登录后重新访问“地址:端口/#/login”这个地址，然后使用“其他账户”登录，那么并不是“其他账户”的账户，而是原本已经登录了的账户

**Comment by unitwk** [comment]
因为你已经登录过了，重复登录无效。

另外你为什么要去重新访问 /login 这个地址。

**Comment by XiaoXiaoYang233** [comment]
> 因为你已经登录过了，重复登录无效。
> 
> 
> 
> 另外你为什么要去重新访问 /login 这个地址。

之前收藏网页的时候是在登录页面收藏的，在登录的时候遇到了这个问题，所以反馈了
