### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by Pokethorix** [MCSManager/MCSManager#989]
![image](https://github.com/MCSManager/MCSManager/assets/65714920/8bf8593d-4669-4f17-8b54-2f9a7772960c)
feel free to use this logo as your own if you like.

**Comment by unitwk** [comment]
Thanks for your contribution, but I don't like this 3D style Logo.

The logo should not be changed casually, but I will save this picture, maybe it will be used in the future.

 Thanks.
