### ISSUE TITLE
打开面板卡在Loading界面

### ISSUE THREAD

**Issue by Alex-bug** [MCSManager/MCSManager#990]
![O0 @T {50)57H`~1L@ BM_6](https://github.com/MCSManager/MCSManager/assets/70711089/166b937f-f156-462e-ac3a-a0be97de9ead)

请问这种情况应该怎么操作
（PS：https://docs.mcsmanager.com/#/zh-cn/README 里的群炸了，可以更新一下）

**Comment by Bluemangoo** [comment]
网络问题，检查web端public文件夹底下文件是否完整，检查F12是否有报错。

**Comment by huangsijun17** [comment]
浏览器按F12打开开发者选项，选择网络标签，刷新页面，截图上传。
