### ISSUE TITLE
Ability to run additional programs

### ISSUE THREAD

**Issue by UrbanSide** [MCSManager/MCSManager#993]
Make it possible to select the launch of the main program.
And for example, upon successful launch, launch an additional one.
If it's rude like a system of triggers.

For example, the Conan Exiles server works fine for me through your software, but when I restart, I first need to run the server / mod update check, and when the check program is closed (steamcmd.exe), start the server itself.
And after starting the server, run my exe that throws a webhook into the discord.

**Comment by Bluemangoo** [comment]
try bat/cmd file\(Windows\) or sh file\(Unix\)

**Comment by UrbanSide** [comment]
This is of course yes, but I just thought it might be convenient for many, for example, to prescribe what trigger to expect in the console output to launch the subprogram.
