### ISSUE TITLE
申请支持MCDR

### ISSUE THREAD

**Issue by QAZ-Solitude** [MCSManager/MCSManager#999]
希望可以通过MCDR启动Server，在MCDR根文件夹下用bat文件打开，bat文件打开Server

**Comment by QAZ-Solitude** [comment]
这是我的mcdr启动文件:
@echo off
start cmd /c "cd D:\MCDR\MCDR && mcdreforged init && mcdreforged"
pause

**Comment by QAZ-Solitude** [comment]
这是我的mcdr启动文件
@echo off
start cmd /c "cd D:\MCDR\MCDR && mcdreforged init && mcdreforged"
pause

**Comment by QAZ-Solitude** [comment]
这是我的mcdr启动文件
 @echo off
 start cmd /c "cd D:\MCDR\MCDR && mcdreforged init && mcdreforged"
 pause

**Comment by huangsijun17** [comment]
为什么要`start cmd /c `去新开一个cmd来运行？

**Comment by unitwk** [comment]
start指令执行后，会启动新的进程，mcsm将无法再监控。

**Comment by bobandbrony** [comment]
> 把start换成call试试？

然后启动命令也得是call ***.bat（mcdr启动文件）
